/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 94

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_94_j` is the pc presentation of the
GAP group `SmallGroup(94, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_94_j`.
-/

namespace Smallgroups.GAP

def sg94_1_L1 : PCLayer := ⟨2, by decide, [0], [[46]]⟩
def sg94_1_L2 : PCLayer := ⟨47, by decide, [], []⟩

def smallGroup_94_1 : PCPres := ⟨[sg94_1_L1, sg94_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg94_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg94_1_L1 [sg94_1_L2]) := by decide
instance : Group (PCGroup smallGroup_94_1) :=
  CycExt.group (pcTowerLayerData sg94_1_L1 [sg94_1_L2])

theorem card_smallGroup_94_1 : Nat.card (PCGroup smallGroup_94_1) = 94 := by
  rw [card_PCGroup]; decide

def sg94_2_L1 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg94_2_L2 : PCLayer := ⟨47, by decide, [], []⟩

def smallGroup_94_2 : PCPres := ⟨[sg94_2_L1, sg94_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg94_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg94_2_L1 [sg94_2_L2]) := by decide
instance : Group (PCGroup smallGroup_94_2) :=
  CycExt.group (pcTowerLayerData sg94_2_L1 [sg94_2_L2])

theorem card_smallGroup_94_2 : Nat.card (PCGroup smallGroup_94_2) = 94 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
