/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 35

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_35_j` is the pc presentation of the
GAP group `SmallGroup(35, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_35_j`.
-/

namespace Smallgroups.GAP

def sg35_1_L1 : PCLayer := ⟨5, by decide, [0], [[1]]⟩
def sg35_1_L2 : PCLayer := ⟨7, by decide, [], []⟩

def smallGroup_35_1 : PCPres := ⟨[sg35_1_L1, sg35_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg35_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg35_1_L1 [sg35_1_L2]) := by decide
instance : Group (PCGroup smallGroup_35_1) :=
  CycExt.group (pcTowerLayerData sg35_1_L1 [sg35_1_L2])

theorem card_smallGroup_35_1 : Nat.card (PCGroup smallGroup_35_1) = 35 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
