/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 87

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_87_j` is the pc presentation of the
GAP group `SmallGroup(87, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_87_j`.
-/

namespace Smallgroups.GAP

def sg87_1_L1 : PCLayer := ⟨3, by decide, [0], [[1]]⟩
def sg87_1_L2 : PCLayer := ⟨29, by decide, [], []⟩

def smallGroup_87_1 : PCPres := ⟨[sg87_1_L1, sg87_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg87_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg87_1_L1 [sg87_1_L2]) := by decide
instance : Group (PCGroup smallGroup_87_1) :=
  CycExt.group (pcTowerLayerData sg87_1_L1 [sg87_1_L2])

theorem card_smallGroup_87_1 : Nat.card (PCGroup smallGroup_87_1) = 87 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
