/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

set_option maxRecDepth 100000
set_option linter.style.longLine false

/-!
# Imported pc presentations: order 32

Generated by `Scripts/translate_pc.py --chunk-size 16 32` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_32_j` is the pc presentation of the
GAP group `SmallGroup(32, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_32_j`.
-/

namespace Smallgroups.GAP

def sg32_1_L1 : PCLayer := ⟨2, by decide, [1, 0, 0, 0], [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_1_L2 : PCLayer := ⟨2, by decide, [1, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_1_L3 : PCLayer := ⟨2, by decide, [1, 0], [[1, 0], [0, 1]]⟩
def sg32_1_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_1_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_1 : PCPres := ⟨[sg32_1_L1, sg32_1_L2, sg32_1_L3, sg32_1_L4, sg32_1_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_1_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_1_L4 [sg32_1_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_1_L3 [sg32_1_L4, sg32_1_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_1_L2 [sg32_1_L3, sg32_1_L4, sg32_1_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_1_L1 [sg32_1_L2, sg32_1_L3, sg32_1_L4, sg32_1_L5]) := by decide
instance : Group (PCGroup smallGroup_32_1) :=
  CycExt.group (pcTowerLayerData sg32_1_L1 [sg32_1_L2, sg32_1_L3, sg32_1_L4, sg32_1_L5])

theorem card_smallGroup_32_1 : Nat.card (PCGroup smallGroup_32_1) = 32 := by
  rw [card_PCGroup]; decide

def sg32_2_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_2_L2 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_2_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_2_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_2_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_2 : PCPres := ⟨[sg32_2_L1, sg32_2_L2, sg32_2_L3, sg32_2_L4, sg32_2_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_2_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_2_L4 [sg32_2_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_2_L3 [sg32_2_L4, sg32_2_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_2_L2 [sg32_2_L3, sg32_2_L4, sg32_2_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_2_L1 [sg32_2_L2, sg32_2_L3, sg32_2_L4, sg32_2_L5]) := by decide
instance : Group (PCGroup smallGroup_32_2) :=
  CycExt.group (pcTowerLayerData sg32_2_L1 [sg32_2_L2, sg32_2_L3, sg32_2_L4, sg32_2_L5])

theorem card_smallGroup_32_2 : Nat.card (PCGroup smallGroup_32_2) = 32 := by
  rw [card_PCGroup]; decide

def sg32_3_L1 : PCLayer := ⟨2, by decide, [0, 1, 0, 0], [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_3_L2 : PCLayer := ⟨2, by decide, [0, 1, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_3_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_3_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_3_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_3 : PCPres := ⟨[sg32_3_L1, sg32_3_L2, sg32_3_L3, sg32_3_L4, sg32_3_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_3_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_3_L4 [sg32_3_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_3_L3 [sg32_3_L4, sg32_3_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_3_L2 [sg32_3_L3, sg32_3_L4, sg32_3_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_3_L1 [sg32_3_L2, sg32_3_L3, sg32_3_L4, sg32_3_L5]) := by decide
instance : Group (PCGroup smallGroup_32_3) :=
  CycExt.group (pcTowerLayerData sg32_3_L1 [sg32_3_L2, sg32_3_L3, sg32_3_L4, sg32_3_L5])

theorem card_smallGroup_32_3 : Nat.card (PCGroup smallGroup_32_3) = 32 := by
  rw [card_PCGroup]; decide

def sg32_4_L1 : PCLayer := ⟨2, by decide, [0, 1, 0, 0], [[1, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_4_L2 : PCLayer := ⟨2, by decide, [0, 1, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_4_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_4_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_4_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_4 : PCPres := ⟨[sg32_4_L1, sg32_4_L2, sg32_4_L3, sg32_4_L4, sg32_4_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_4_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_4_L4 [sg32_4_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_4_L3 [sg32_4_L4, sg32_4_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_4_L2 [sg32_4_L3, sg32_4_L4, sg32_4_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_4_L1 [sg32_4_L2, sg32_4_L3, sg32_4_L4, sg32_4_L5]) := by decide
instance : Group (PCGroup smallGroup_32_4) :=
  CycExt.group (pcTowerLayerData sg32_4_L1 [sg32_4_L2, sg32_4_L3, sg32_4_L4, sg32_4_L5])

theorem card_smallGroup_32_4 : Nat.card (PCGroup smallGroup_32_4) = 32 := by
  rw [card_PCGroup]; decide

def sg32_5_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_5_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_5_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_5_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_5_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_5 : PCPres := ⟨[sg32_5_L1, sg32_5_L2, sg32_5_L3, sg32_5_L4, sg32_5_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_5_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_5_L4 [sg32_5_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_5_L3 [sg32_5_L4, sg32_5_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_5_L2 [sg32_5_L3, sg32_5_L4, sg32_5_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_5_L1 [sg32_5_L2, sg32_5_L3, sg32_5_L4, sg32_5_L5]) := by decide
instance : Group (PCGroup smallGroup_32_5) :=
  CycExt.group (pcTowerLayerData sg32_5_L1 [sg32_5_L2, sg32_5_L3, sg32_5_L4, sg32_5_L5])

theorem card_smallGroup_32_5 : Nat.card (PCGroup smallGroup_32_5) = 32 := by
  rw [card_PCGroup]; decide

def sg32_6_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 1], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_6_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg32_6_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_6_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_6_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_6 : PCPres := ⟨[sg32_6_L1, sg32_6_L2, sg32_6_L3, sg32_6_L4, sg32_6_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_6_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_6_L4 [sg32_6_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_6_L3 [sg32_6_L4, sg32_6_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_6_L2 [sg32_6_L3, sg32_6_L4, sg32_6_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_6_L1 [sg32_6_L2, sg32_6_L3, sg32_6_L4, sg32_6_L5]) := by decide
instance : Group (PCGroup smallGroup_32_6) :=
  CycExt.group (pcTowerLayerData sg32_6_L1 [sg32_6_L2, sg32_6_L3, sg32_6_L4, sg32_6_L5])

theorem card_smallGroup_32_6 : Nat.card (PCGroup smallGroup_32_6) = 32 := by
  rw [card_PCGroup]; decide

def sg32_7_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 1], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_7_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg32_7_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_7_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_7_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_7 : PCPres := ⟨[sg32_7_L1, sg32_7_L2, sg32_7_L3, sg32_7_L4, sg32_7_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_7_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_7_L4 [sg32_7_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_7_L3 [sg32_7_L4, sg32_7_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_7_L2 [sg32_7_L3, sg32_7_L4, sg32_7_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_7_L1 [sg32_7_L2, sg32_7_L3, sg32_7_L4, sg32_7_L5]) := by decide
instance : Group (PCGroup smallGroup_32_7) :=
  CycExt.group (pcTowerLayerData sg32_7_L1 [sg32_7_L2, sg32_7_L3, sg32_7_L4, sg32_7_L5])

theorem card_smallGroup_32_7 : Nat.card (PCGroup smallGroup_32_7) = 32 := by
  rw [card_PCGroup]; decide

def sg32_8_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 1], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_8_L2 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg32_8_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_8_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_8_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_8 : PCPres := ⟨[sg32_8_L1, sg32_8_L2, sg32_8_L3, sg32_8_L4, sg32_8_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_8_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_8_L4 [sg32_8_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_8_L3 [sg32_8_L4, sg32_8_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_8_L2 [sg32_8_L3, sg32_8_L4, sg32_8_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_8_L1 [sg32_8_L2, sg32_8_L3, sg32_8_L4, sg32_8_L5]) := by decide
instance : Group (PCGroup smallGroup_32_8) :=
  CycExt.group (pcTowerLayerData sg32_8_L1 [sg32_8_L2, sg32_8_L3, sg32_8_L4, sg32_8_L5])

theorem card_smallGroup_32_8 : Nat.card (PCGroup smallGroup_32_8) = 32 := by
  rw [card_PCGroup]; decide

def sg32_9_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_9_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg32_9_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_9_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_9_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_9 : PCPres := ⟨[sg32_9_L1, sg32_9_L2, sg32_9_L3, sg32_9_L4, sg32_9_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_9_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_9_L4 [sg32_9_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_9_L3 [sg32_9_L4, sg32_9_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_9_L2 [sg32_9_L3, sg32_9_L4, sg32_9_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_9_L1 [sg32_9_L2, sg32_9_L3, sg32_9_L4, sg32_9_L5]) := by decide
instance : Group (PCGroup smallGroup_32_9) :=
  CycExt.group (pcTowerLayerData sg32_9_L1 [sg32_9_L2, sg32_9_L3, sg32_9_L4, sg32_9_L5])

theorem card_smallGroup_32_9 : Nat.card (PCGroup smallGroup_32_9) = 32 := by
  rw [card_PCGroup]; decide

def sg32_10_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_10_L2 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg32_10_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_10_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_10_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_10 : PCPres := ⟨[sg32_10_L1, sg32_10_L2, sg32_10_L3, sg32_10_L4, sg32_10_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_10_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_10_L4 [sg32_10_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_10_L3 [sg32_10_L4, sg32_10_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_10_L2 [sg32_10_L3, sg32_10_L4, sg32_10_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_10_L1 [sg32_10_L2, sg32_10_L3, sg32_10_L4, sg32_10_L5]) := by decide
instance : Group (PCGroup smallGroup_32_10) :=
  CycExt.group (pcTowerLayerData sg32_10_L1 [sg32_10_L2, sg32_10_L3, sg32_10_L4, sg32_10_L5])

theorem card_smallGroup_32_10 : Nat.card (PCGroup smallGroup_32_10) = 32 := by
  rw [card_PCGroup]; decide

def sg32_11_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_11_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg32_11_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_11_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_11_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_11 : PCPres := ⟨[sg32_11_L1, sg32_11_L2, sg32_11_L3, sg32_11_L4, sg32_11_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_11_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_11_L4 [sg32_11_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_11_L3 [sg32_11_L4, sg32_11_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_11_L2 [sg32_11_L3, sg32_11_L4, sg32_11_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_11_L1 [sg32_11_L2, sg32_11_L3, sg32_11_L4, sg32_11_L5]) := by decide
instance : Group (PCGroup smallGroup_32_11) :=
  CycExt.group (pcTowerLayerData sg32_11_L1 [sg32_11_L2, sg32_11_L3, sg32_11_L4, sg32_11_L5])

theorem card_smallGroup_32_11 : Nat.card (PCGroup smallGroup_32_11) = 32 := by
  rw [card_PCGroup]; decide

def sg32_12_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_12_L2 : PCLayer := ⟨2, by decide, [1, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_12_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_12_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_12_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_12 : PCPres := ⟨[sg32_12_L1, sg32_12_L2, sg32_12_L3, sg32_12_L4, sg32_12_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_12_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_12_L4 [sg32_12_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_12_L3 [sg32_12_L4, sg32_12_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_12_L2 [sg32_12_L3, sg32_12_L4, sg32_12_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_12_L1 [sg32_12_L2, sg32_12_L3, sg32_12_L4, sg32_12_L5]) := by decide
instance : Group (PCGroup smallGroup_32_12) :=
  CycExt.group (pcTowerLayerData sg32_12_L1 [sg32_12_L2, sg32_12_L3, sg32_12_L4, sg32_12_L5])

theorem card_smallGroup_32_12 : Nat.card (PCGroup smallGroup_32_12) = 32 := by
  rw [card_PCGroup]; decide

def sg32_13_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_13_L2 : PCLayer := ⟨2, by decide, [1, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_13_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_13_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_13_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_13 : PCPres := ⟨[sg32_13_L1, sg32_13_L2, sg32_13_L3, sg32_13_L4, sg32_13_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_13_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_13_L4 [sg32_13_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_13_L3 [sg32_13_L4, sg32_13_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_13_L2 [sg32_13_L3, sg32_13_L4, sg32_13_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_13_L1 [sg32_13_L2, sg32_13_L3, sg32_13_L4, sg32_13_L5]) := by decide
instance : Group (PCGroup smallGroup_32_13) :=
  CycExt.group (pcTowerLayerData sg32_13_L1 [sg32_13_L2, sg32_13_L3, sg32_13_L4, sg32_13_L5])

theorem card_smallGroup_32_13 : Nat.card (PCGroup smallGroup_32_13) = 32 := by
  rw [card_PCGroup]; decide

def sg32_14_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_14_L2 : PCLayer := ⟨2, by decide, [1, 0, 1], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_14_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_14_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_14_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_14 : PCPres := ⟨[sg32_14_L1, sg32_14_L2, sg32_14_L3, sg32_14_L4, sg32_14_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_14_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_14_L4 [sg32_14_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_14_L3 [sg32_14_L4, sg32_14_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_14_L2 [sg32_14_L3, sg32_14_L4, sg32_14_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_14_L1 [sg32_14_L2, sg32_14_L3, sg32_14_L4, sg32_14_L5]) := by decide
instance : Group (PCGroup smallGroup_32_14) :=
  CycExt.group (pcTowerLayerData sg32_14_L1 [sg32_14_L2, sg32_14_L3, sg32_14_L4, sg32_14_L5])

theorem card_smallGroup_32_14 : Nat.card (PCGroup smallGroup_32_14) = 32 := by
  rw [card_PCGroup]; decide

def sg32_15_L1 : PCLayer := ⟨2, by decide, [0, 0, 1, 0], [[1, 1, 0, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_15_L2 : PCLayer := ⟨2, by decide, [1, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_15_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_15_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_15_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_15 : PCPres := ⟨[sg32_15_L1, sg32_15_L2, sg32_15_L3, sg32_15_L4, sg32_15_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_15_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_15_L4 [sg32_15_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_15_L3 [sg32_15_L4, sg32_15_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_15_L2 [sg32_15_L3, sg32_15_L4, sg32_15_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_15_L1 [sg32_15_L2, sg32_15_L3, sg32_15_L4, sg32_15_L5]) := by decide
instance : Group (PCGroup smallGroup_32_15) :=
  CycExt.group (pcTowerLayerData sg32_15_L1 [sg32_15_L2, sg32_15_L3, sg32_15_L4, sg32_15_L5])

theorem card_smallGroup_32_15 : Nat.card (PCGroup smallGroup_32_15) = 32 := by
  rw [card_PCGroup]; decide

def sg32_16_L1 : PCLayer := ⟨2, by decide, [0, 1, 0, 0], [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_16_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_16_L3 : PCLayer := ⟨2, by decide, [1, 0], [[1, 0], [0, 1]]⟩
def sg32_16_L4 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg32_16_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_16 : PCPres := ⟨[sg32_16_L1, sg32_16_L2, sg32_16_L3, sg32_16_L4, sg32_16_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_16_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_16_L4 [sg32_16_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_16_L3 [sg32_16_L4, sg32_16_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_16_L2 [sg32_16_L3, sg32_16_L4, sg32_16_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_16_L1 [sg32_16_L2, sg32_16_L3, sg32_16_L4, sg32_16_L5]) := by decide
instance : Group (PCGroup smallGroup_32_16) :=
  CycExt.group (pcTowerLayerData sg32_16_L1 [sg32_16_L2, sg32_16_L3, sg32_16_L4, sg32_16_L5])

theorem card_smallGroup_32_16 : Nat.card (PCGroup smallGroup_32_16) = 32 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
