/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 22

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_22_j` is the pc presentation of the
GAP group `SmallGroup(22, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_22_j`.
-/

namespace Smallgroups.GAP

def sg22_1_L1 : PCLayer := ⟨2, by decide, [0], [[10]]⟩
def sg22_1_L2 : PCLayer := ⟨11, by decide, [], []⟩

def smallGroup_22_1 : PCPres := ⟨[sg22_1_L1, sg22_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg22_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg22_1_L1 [sg22_1_L2]) := by decide
instance : Group (PCGroup smallGroup_22_1) :=
  CycExt.group (pcTowerLayerData sg22_1_L1 [sg22_1_L2])

theorem card_smallGroup_22_1 : Nat.card (PCGroup smallGroup_22_1) = 22 := by
  rw [card_PCGroup]; decide

def sg22_2_L1 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg22_2_L2 : PCLayer := ⟨11, by decide, [], []⟩

def smallGroup_22_2 : PCPres := ⟨[sg22_2_L1, sg22_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg22_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg22_2_L1 [sg22_2_L2]) := by decide
instance : Group (PCGroup smallGroup_22_2) :=
  CycExt.group (pcTowerLayerData sg22_2_L1 [sg22_2_L2])

theorem card_smallGroup_22_2 : Nat.card (PCGroup smallGroup_22_2) = 22 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
