/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 46

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_46_j` is the pc presentation of the
GAP group `SmallGroup(46, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_46_j`.
-/

namespace Smallgroups.GAP

def sg46_1_L1 : PCLayer := ⟨2, by decide, [0], [[22]]⟩
def sg46_1_L2 : PCLayer := ⟨23, by decide, [], []⟩

def smallGroup_46_1 : PCPres := ⟨[sg46_1_L1, sg46_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg46_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg46_1_L1 [sg46_1_L2]) := by decide
instance : Group (PCGroup smallGroup_46_1) :=
  CycExt.group (pcTowerLayerData sg46_1_L1 [sg46_1_L2])

theorem card_smallGroup_46_1 : Nat.card (PCGroup smallGroup_46_1) = 46 := by
  rw [card_PCGroup]; decide

def sg46_2_L1 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg46_2_L2 : PCLayer := ⟨23, by decide, [], []⟩

def smallGroup_46_2 : PCPres := ⟨[sg46_2_L1, sg46_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg46_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg46_2_L1 [sg46_2_L2]) := by decide
instance : Group (PCGroup smallGroup_46_2) :=
  CycExt.group (pcTowerLayerData sg46_2_L1 [sg46_2_L2])

theorem card_smallGroup_46_2 : Nat.card (PCGroup smallGroup_46_2) = 46 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
