/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Imported.Order32Part01
import Smallgroups.GAP.Polycyclic.Imported.Order32Part02
import Smallgroups.GAP.Polycyclic.Imported.Order32Part03
import Smallgroups.GAP.Polycyclic.Imported.Order32Part04

/-!
# Imported pc presentations: order 32

Generated by `Scripts/translate_pc.py --chunk-size`; the imported chunks contain
all 51 GAP groups `SmallGroup(32, j)` in the consecutive range
`1 <= j <= 51`.
-/
