/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 16

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_16_j` is the pc presentation of the
GAP group `SmallGroup(16, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_16_j`.
-/

namespace Smallgroups.GAP

def sg16_1_L1 : PCLayer := ⟨2, by decide, [1, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_1_L2 : PCLayer := ⟨2, by decide, [1, 0], [[1, 0], [0, 1]]⟩
def sg16_1_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_1_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_1 : PCPres := ⟨[sg16_1_L1, sg16_1_L2, sg16_1_L3, sg16_1_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_1_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_1_L3 [sg16_1_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_1_L2 [sg16_1_L3, sg16_1_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_1_L1 [sg16_1_L2, sg16_1_L3, sg16_1_L4]) := by decide
instance : Group (PCGroup smallGroup_16_1) :=
  CycExt.group (pcTowerLayerData sg16_1_L1 [sg16_1_L2, sg16_1_L3, sg16_1_L4])

theorem card_smallGroup_16_1 : Nat.card (PCGroup smallGroup_16_1) = 16 := by
  rw [card_PCGroup]; decide

def sg16_2_L1 : PCLayer := ⟨2, by decide, [0, 1, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_2_L2 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg16_2_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_2_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_2 : PCPres := ⟨[sg16_2_L1, sg16_2_L2, sg16_2_L3, sg16_2_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_2_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_2_L3 [sg16_2_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_2_L2 [sg16_2_L3, sg16_2_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_2_L1 [sg16_2_L2, sg16_2_L3, sg16_2_L4]) := by decide
instance : Group (PCGroup smallGroup_16_2) :=
  CycExt.group (pcTowerLayerData sg16_2_L1 [sg16_2_L2, sg16_2_L3, sg16_2_L4])

theorem card_smallGroup_16_2 : Nat.card (PCGroup smallGroup_16_2) = 16 := by
  rw [card_PCGroup]; decide

def sg16_3_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 1, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_3_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_3_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_3_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_3 : PCPres := ⟨[sg16_3_L1, sg16_3_L2, sg16_3_L3, sg16_3_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_3_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_3_L3 [sg16_3_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_3_L2 [sg16_3_L3, sg16_3_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_3_L1 [sg16_3_L2, sg16_3_L3, sg16_3_L4]) := by decide
instance : Group (PCGroup smallGroup_16_3) :=
  CycExt.group (pcTowerLayerData sg16_3_L1 [sg16_3_L2, sg16_3_L3, sg16_3_L4])

theorem card_smallGroup_16_3 : Nat.card (PCGroup smallGroup_16_3) = 16 := by
  rw [card_PCGroup]; decide

def sg16_4_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 1, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_4_L2 : PCLayer := ⟨2, by decide, [1, 0], [[1, 0], [0, 1]]⟩
def sg16_4_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_4_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_4 : PCPres := ⟨[sg16_4_L1, sg16_4_L2, sg16_4_L3, sg16_4_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_4_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_4_L3 [sg16_4_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_4_L2 [sg16_4_L3, sg16_4_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_4_L1 [sg16_4_L2, sg16_4_L3, sg16_4_L4]) := by decide
instance : Group (PCGroup smallGroup_16_4) :=
  CycExt.group (pcTowerLayerData sg16_4_L1 [sg16_4_L2, sg16_4_L3, sg16_4_L4])

theorem card_smallGroup_16_4 : Nat.card (PCGroup smallGroup_16_4) = 16 := by
  rw [card_PCGroup]; decide

def sg16_5_L1 : PCLayer := ⟨2, by decide, [0, 1, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_5_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_5_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_5_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_5 : PCPres := ⟨[sg16_5_L1, sg16_5_L2, sg16_5_L3, sg16_5_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_5_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_5_L3 [sg16_5_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_5_L2 [sg16_5_L3, sg16_5_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_5_L1 [sg16_5_L2, sg16_5_L3, sg16_5_L4]) := by decide
instance : Group (PCGroup smallGroup_16_5) :=
  CycExt.group (pcTowerLayerData sg16_5_L1 [sg16_5_L2, sg16_5_L3, sg16_5_L4])

theorem card_smallGroup_16_5 : Nat.card (PCGroup smallGroup_16_5) = 16 := by
  rw [card_PCGroup]; decide

def sg16_6_L1 : PCLayer := ⟨2, by decide, [0, 1, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg16_6_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_6_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_6_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_6 : PCPres := ⟨[sg16_6_L1, sg16_6_L2, sg16_6_L3, sg16_6_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_6_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_6_L3 [sg16_6_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_6_L2 [sg16_6_L3, sg16_6_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_6_L1 [sg16_6_L2, sg16_6_L3, sg16_6_L4]) := by decide
instance : Group (PCGroup smallGroup_16_6) :=
  CycExt.group (pcTowerLayerData sg16_6_L1 [sg16_6_L2, sg16_6_L3, sg16_6_L4])

theorem card_smallGroup_16_6 : Nat.card (PCGroup smallGroup_16_6) = 16 := by
  rw [card_PCGroup]; decide

def sg16_7_L1 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 1, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg16_7_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 1], [0, 1]]⟩
def sg16_7_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_7_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_7 : PCPres := ⟨[sg16_7_L1, sg16_7_L2, sg16_7_L3, sg16_7_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_7_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_7_L3 [sg16_7_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_7_L2 [sg16_7_L3, sg16_7_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_7_L1 [sg16_7_L2, sg16_7_L3, sg16_7_L4]) := by decide
instance : Group (PCGroup smallGroup_16_7) :=
  CycExt.group (pcTowerLayerData sg16_7_L1 [sg16_7_L2, sg16_7_L3, sg16_7_L4])

theorem card_smallGroup_16_7 : Nat.card (PCGroup smallGroup_16_7) = 16 := by
  rw [card_PCGroup]; decide

def sg16_8_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 1, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg16_8_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 1], [0, 1]]⟩
def sg16_8_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_8_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_8 : PCPres := ⟨[sg16_8_L1, sg16_8_L2, sg16_8_L3, sg16_8_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_8_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_8_L3 [sg16_8_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_8_L2 [sg16_8_L3, sg16_8_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_8_L1 [sg16_8_L2, sg16_8_L3, sg16_8_L4]) := by decide
instance : Group (PCGroup smallGroup_16_8) :=
  CycExt.group (pcTowerLayerData sg16_8_L1 [sg16_8_L2, sg16_8_L3, sg16_8_L4])

theorem card_smallGroup_16_8 : Nat.card (PCGroup smallGroup_16_8) = 16 := by
  rw [card_PCGroup]; decide

def sg16_9_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 1, 0], [0, 1, 1], [0, 0, 1]]⟩
def sg16_9_L2 : PCLayer := ⟨2, by decide, [0, 1], [[1, 1], [0, 1]]⟩
def sg16_9_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_9_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_9 : PCPres := ⟨[sg16_9_L1, sg16_9_L2, sg16_9_L3, sg16_9_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_9_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_9_L3 [sg16_9_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_9_L2 [sg16_9_L3, sg16_9_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_9_L1 [sg16_9_L2, sg16_9_L3, sg16_9_L4]) := by decide
instance : Group (PCGroup smallGroup_16_9) :=
  CycExt.group (pcTowerLayerData sg16_9_L1 [sg16_9_L2, sg16_9_L3, sg16_9_L4])

theorem card_smallGroup_16_9 : Nat.card (PCGroup smallGroup_16_9) = 16 := by
  rw [card_PCGroup]; decide

def sg16_10_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_10_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_10_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_10_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_10 : PCPres := ⟨[sg16_10_L1, sg16_10_L2, sg16_10_L3, sg16_10_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_10_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_10_L3 [sg16_10_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_10_L2 [sg16_10_L3, sg16_10_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_10_L1 [sg16_10_L2, sg16_10_L3, sg16_10_L4]) := by decide
instance : Group (PCGroup smallGroup_16_10) :=
  CycExt.group (pcTowerLayerData sg16_10_L1 [sg16_10_L2, sg16_10_L3, sg16_10_L4])

theorem card_smallGroup_16_10 : Nat.card (PCGroup smallGroup_16_10) = 16 := by
  rw [card_PCGroup]; decide

def sg16_11_L1 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg16_11_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_11_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_11_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_11 : PCPres := ⟨[sg16_11_L1, sg16_11_L2, sg16_11_L3, sg16_11_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_11_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_11_L3 [sg16_11_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_11_L2 [sg16_11_L3, sg16_11_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_11_L1 [sg16_11_L2, sg16_11_L3, sg16_11_L4]) := by decide
instance : Group (PCGroup smallGroup_16_11) :=
  CycExt.group (pcTowerLayerData sg16_11_L1 [sg16_11_L2, sg16_11_L3, sg16_11_L4])

theorem card_smallGroup_16_11 : Nat.card (PCGroup smallGroup_16_11) = 16 := by
  rw [card_PCGroup]; decide

def sg16_12_L1 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg16_12_L2 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg16_12_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_12_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_12 : PCPres := ⟨[sg16_12_L1, sg16_12_L2, sg16_12_L3, sg16_12_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_12_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_12_L3 [sg16_12_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_12_L2 [sg16_12_L3, sg16_12_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_12_L1 [sg16_12_L2, sg16_12_L3, sg16_12_L4]) := by decide
instance : Group (PCGroup smallGroup_16_12) :=
  CycExt.group (pcTowerLayerData sg16_12_L1 [sg16_12_L2, sg16_12_L3, sg16_12_L4])

theorem card_smallGroup_16_12 : Nat.card (PCGroup smallGroup_16_12) = 16 := by
  rw [card_PCGroup]; decide

def sg16_13_L1 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg16_13_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_13_L3 : PCLayer := ⟨2, by decide, [1], [[1]]⟩
def sg16_13_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_13 : PCPres := ⟨[sg16_13_L1, sg16_13_L2, sg16_13_L3, sg16_13_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_13_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_13_L3 [sg16_13_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_13_L2 [sg16_13_L3, sg16_13_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_13_L1 [sg16_13_L2, sg16_13_L3, sg16_13_L4]) := by decide
instance : Group (PCGroup smallGroup_16_13) :=
  CycExt.group (pcTowerLayerData sg16_13_L1 [sg16_13_L2, sg16_13_L3, sg16_13_L4])

theorem card_smallGroup_16_13 : Nat.card (PCGroup smallGroup_16_13) = 16 := by
  rw [card_PCGroup]; decide

def sg16_14_L1 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg16_14_L2 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg16_14_L3 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg16_14_L4 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_16_14 : PCPres := ⟨[sg16_14_L1, sg16_14_L2, sg16_14_L3, sg16_14_L4]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_14_L4 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_14_L3 [sg16_14_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_14_L2 [sg16_14_L3, sg16_14_L4]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg16_14_L1 [sg16_14_L2, sg16_14_L3, sg16_14_L4]) := by decide
instance : Group (PCGroup smallGroup_16_14) :=
  CycExt.group (pcTowerLayerData sg16_14_L1 [sg16_14_L2, sg16_14_L3, sg16_14_L4])

theorem card_smallGroup_16_14 : Nat.card (PCGroup smallGroup_16_14) = 16 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
