/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 62

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_62_j` is the pc presentation of the
GAP group `SmallGroup(62, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_62_j`.
-/

namespace Smallgroups.GAP

def sg62_1_L1 : PCLayer := ⟨2, by decide, [0], [[30]]⟩
def sg62_1_L2 : PCLayer := ⟨31, by decide, [], []⟩

def smallGroup_62_1 : PCPres := ⟨[sg62_1_L1, sg62_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg62_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg62_1_L1 [sg62_1_L2]) := by decide
instance : Group (PCGroup smallGroup_62_1) :=
  CycExt.group (pcTowerLayerData sg62_1_L1 [sg62_1_L2])

theorem card_smallGroup_62_1 : Nat.card (PCGroup smallGroup_62_1) = 62 := by
  rw [card_PCGroup]; decide

def sg62_2_L1 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg62_2_L2 : PCLayer := ⟨31, by decide, [], []⟩

def smallGroup_62_2 : PCPres := ⟨[sg62_2_L1, sg62_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg62_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg62_2_L1 [sg62_2_L2]) := by decide
instance : Group (PCGroup smallGroup_62_2) :=
  CycExt.group (pcTowerLayerData sg62_2_L1 [sg62_2_L2])

theorem card_smallGroup_62_2 : Nat.card (PCGroup smallGroup_62_2) = 62 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
