/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

set_option maxRecDepth 100000
set_option linter.style.longLine false

/-!
# Imported pc presentations: order 32

Generated by `Scripts/translate_pc.py --chunk-size 16 32` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_32_j` is the pc presentation of the
GAP group `SmallGroup(32, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_32_j`.
-/

namespace Smallgroups.GAP

def sg32_49_L1 : PCLayer := ⟨2, by decide, [0, 0, 0, 0], [[1, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 1]]⟩
def sg32_49_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg32_49_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_49_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_49_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_49 : PCPres := ⟨[sg32_49_L1, sg32_49_L2, sg32_49_L3, sg32_49_L4, sg32_49_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_49_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_49_L4 [sg32_49_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_49_L3 [sg32_49_L4, sg32_49_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_49_L2 [sg32_49_L3, sg32_49_L4, sg32_49_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_49_L1 [sg32_49_L2, sg32_49_L3, sg32_49_L4, sg32_49_L5]) := by decide
instance : Group (PCGroup smallGroup_32_49) :=
  CycExt.group (pcTowerLayerData sg32_49_L1 [sg32_49_L2, sg32_49_L3, sg32_49_L4, sg32_49_L5])

theorem card_smallGroup_32_49 : Nat.card (PCGroup smallGroup_32_49) = 32 := by
  rw [card_PCGroup]; decide

def sg32_50_L1 : PCLayer := ⟨2, by decide, [0, 0, 0, 0], [[1, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 1]]⟩
def sg32_50_L2 : PCLayer := ⟨2, by decide, [0, 0, 1], [[1, 0, 1], [0, 1, 0], [0, 0, 1]]⟩
def sg32_50_L3 : PCLayer := ⟨2, by decide, [0, 1], [[1, 0], [0, 1]]⟩
def sg32_50_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_50_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_50 : PCPres := ⟨[sg32_50_L1, sg32_50_L2, sg32_50_L3, sg32_50_L4, sg32_50_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_50_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_50_L4 [sg32_50_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_50_L3 [sg32_50_L4, sg32_50_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_50_L2 [sg32_50_L3, sg32_50_L4, sg32_50_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_50_L1 [sg32_50_L2, sg32_50_L3, sg32_50_L4, sg32_50_L5]) := by decide
instance : Group (PCGroup smallGroup_32_50) :=
  CycExt.group (pcTowerLayerData sg32_50_L1 [sg32_50_L2, sg32_50_L3, sg32_50_L4, sg32_50_L5])

theorem card_smallGroup_32_50 : Nat.card (PCGroup smallGroup_32_50) = 32 := by
  rw [card_PCGroup]; decide

def sg32_51_L1 : PCLayer := ⟨2, by decide, [0, 0, 0, 0], [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]⟩
def sg32_51_L2 : PCLayer := ⟨2, by decide, [0, 0, 0], [[1, 0, 0], [0, 1, 0], [0, 0, 1]]⟩
def sg32_51_L3 : PCLayer := ⟨2, by decide, [0, 0], [[1, 0], [0, 1]]⟩
def sg32_51_L4 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg32_51_L5 : PCLayer := ⟨2, by decide, [], []⟩

def smallGroup_32_51 : PCPres := ⟨[sg32_51_L1, sg32_51_L2, sg32_51_L3, sg32_51_L4, sg32_51_L5]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_51_L5 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_51_L4 [sg32_51_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_51_L3 [sg32_51_L4, sg32_51_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_51_L2 [sg32_51_L3, sg32_51_L4, sg32_51_L5]) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg32_51_L1 [sg32_51_L2, sg32_51_L3, sg32_51_L4, sg32_51_L5]) := by decide
instance : Group (PCGroup smallGroup_32_51) :=
  CycExt.group (pcTowerLayerData sg32_51_L1 [sg32_51_L2, sg32_51_L3, sg32_51_L4, sg32_51_L5])

theorem card_smallGroup_32_51 : Nat.card (PCGroup smallGroup_32_51) = 32 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
