/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 33

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_33_j` is the pc presentation of the
GAP group `SmallGroup(33, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_33_j`.
-/

namespace Smallgroups.GAP

def sg33_1_L1 : PCLayer := ⟨3, by decide, [0], [[1]]⟩
def sg33_1_L2 : PCLayer := ⟨11, by decide, [], []⟩

def smallGroup_33_1 : PCPres := ⟨[sg33_1_L1, sg33_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg33_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg33_1_L1 [sg33_1_L2]) := by decide
instance : Group (PCGroup smallGroup_33_1) :=
  CycExt.group (pcTowerLayerData sg33_1_L1 [sg33_1_L2])

theorem card_smallGroup_33_1 : Nat.card (PCGroup smallGroup_33_1) = 33 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
