/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 74

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_74_j` is the pc presentation of the
GAP group `SmallGroup(74, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_74_j`.
-/

namespace Smallgroups.GAP

def sg74_1_L1 : PCLayer := ⟨2, by decide, [0], [[36]]⟩
def sg74_1_L2 : PCLayer := ⟨37, by decide, [], []⟩

def smallGroup_74_1 : PCPres := ⟨[sg74_1_L1, sg74_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg74_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg74_1_L1 [sg74_1_L2]) := by decide
instance : Group (PCGroup smallGroup_74_1) :=
  CycExt.group (pcTowerLayerData sg74_1_L1 [sg74_1_L2])

theorem card_smallGroup_74_1 : Nat.card (PCGroup smallGroup_74_1) = 74 := by
  rw [card_PCGroup]; decide

def sg74_2_L1 : PCLayer := ⟨2, by decide, [0], [[1]]⟩
def sg74_2_L2 : PCLayer := ⟨37, by decide, [], []⟩

def smallGroup_74_2 : PCPres := ⟨[sg74_2_L1, sg74_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg74_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg74_2_L1 [sg74_2_L2]) := by decide
instance : Group (PCGroup smallGroup_74_2) :=
  CycExt.group (pcTowerLayerData sg74_2_L1 [sg74_2_L2])

theorem card_smallGroup_74_2 : Nat.card (PCGroup smallGroup_74_2) = 74 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
