/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Basic

/-!
# Imported pc presentations: order 55

Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library
(do not edit by hand).  `smallGroup_55_j` is the pc presentation of the
GAP group `SmallGroup(55, j)`; layers are given outermost generator first.

Each group carries: per-layer consistency instances (`by decide`), the
`Group` instance on `PCGroup`, and the order check `card_smallGroup_55_j`.
-/

namespace Smallgroups.GAP

def sg55_1_L1 : PCLayer := ⟨5, by decide, [0], [[3]]⟩
def sg55_1_L2 : PCLayer := ⟨11, by decide, [], []⟩

def smallGroup_55_1 : PCPres := ⟨[sg55_1_L1, sg55_1_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg55_1_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg55_1_L1 [sg55_1_L2]) := by decide
instance : Group (PCGroup smallGroup_55_1) :=
  CycExt.group (pcTowerLayerData sg55_1_L1 [sg55_1_L2])

theorem card_smallGroup_55_1 : Nat.card (PCGroup smallGroup_55_1) = 55 := by
  rw [card_PCGroup]; decide

def sg55_2_L1 : PCLayer := ⟨5, by decide, [0], [[1]]⟩
def sg55_2_L2 : PCLayer := ⟨11, by decide, [], []⟩

def smallGroup_55_2 : PCPres := ⟨[sg55_2_L1, sg55_2_L2]⟩
instance : CycExtData.Consistent
    (pcTowerLayerData sg55_2_L2 []) := by decide
instance : CycExtData.Consistent
    (pcTowerLayerData sg55_2_L1 [sg55_2_L2]) := by decide
instance : Group (PCGroup smallGroup_55_2) :=
  CycExt.group (pcTowerLayerData sg55_2_L1 [sg55_2_L2])

theorem card_smallGroup_55_2 : Nat.card (PCGroup smallGroup_55_2) = 55 := by
  rw [card_PCGroup]; decide

end Smallgroups.GAP
