/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order16_Wild
import Smallgroups.UsefulTheorems.PGroupGeneration

/-!
# Order 32: common reduction theorem and shared helper lemmas

`order32_central_reduction` reduces the classification of groups of order `32` to
central `C₂`-extensions of the 14 known order-`16` representatives. The remaining
lemmas in this file (`sq_eq_one_zpow_cases` through `four_commuting_gens_iso`) are
generic combinatorial tools reused across several of the per-parent descendant files.
-/

namespace Smallgroups.UsefulTheorems

/-- Every group of order 32 is a central `C₂`-extension of one of the 14 known groups of
order 16: it is isomorphic to `CocycleGroup f hf` for some normalized 2-cocycle `f` valued
in `ZMod 2` over `order16_wild_reps i`. -/
theorem order32_central_reduction {G : Type*} [Group G] [Finite G] (hG : Nat.card G = 32) :
    ∃ (i : Fin 14) (f : order16_wild_reps i → order16_wild_reps i → ZMod 2)
      (hf : IsCentralCocycle f), Nonempty (G ≃* CocycleGroup f hf) := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  obtain ⟨z, hzc, hzp, hzn, hquot⟩ := order_prime_pow_central_reduction
    (p := 2) (n := 4) (by rw [hG]; norm_num)
  obtain ⟨i, ⟨e⟩⟩ := order16_wild_classification hquot
  haveI := hzn
  obtain ⟨f, hf, hiso⟩ := cocycleGroup_reconstruction_of_quotient_iso
    (n := 2) hzc hzp e
  exact ⟨i, f, hf, hiso⟩

/-- An element of order dividing 2 is `1` or itself. -/
theorem sq_eq_one_zpow_cases {G : Type*} [Group G] {z : G} (hz2 : z ^ 2 = 1)
    (k : ℤ) : z ^ k = 1 ∨ z ^ k = z := by
  have hk2 : (2 : ℤ) * (k / 2) + k % 2 = k := Int.mul_ediv_add_emod k 2
  have hzz : z ^ (2 : ℤ) = 1 := by norm_cast
  rcases Int.emod_two_eq k with hm | hm
  · left
    rw [← hk2, hm, add_zero, zpow_mul, hzz, one_zpow]
  · right
    rw [← hk2, hm, zpow_add, zpow_mul, hzz, one_zpow, one_mul, zpow_one]

/-- If two commuting elements both square to the same order-`2` element `z`, their product
squares to `1`. -/
theorem sym_merge_sq_one {G : Type*} [Group G] {x y z : G} (hxy : Commute x y)
    (hx2 : x ^ 2 = z) (hy2 : y ^ 2 = z) (hz2 : z ^ 2 = 1) : (x * y) ^ 2 = 1 := by
  rw [hxy.mul_pow, hx2, hy2, ← sq]; exact hz2

/-- Any element of a subgroup generated by an order-`2` element `z` is `1` or `z`. -/
theorem central_pow_cases {G : Type*} [Group G] {z g : G} (hz2 : z ^ 2 = 1)
    (hmem : g ∈ Subgroup.zpowers z) : g = 1 ∨ g = z := by
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hmem
  rcases sq_eq_one_zpow_cases hz2 k with hcase | hcase
  · left; rw [← hk, hcase]
  · right; rw [← hk, hcase]

/-- If `n ∣ orderOf g` and `g ^ n` is the nontrivial "half-order" element `z` (order 2),
then `orderOf g = 2 * n`. -/
theorem order_double_of_pow_eq_central {G : Type*} [Group G] [Finite G] {g z : G}
    {n : ℕ} (hnpos : 0 < n) (hdvd : n ∣ orderOf g) (hgn : g ^ n = z) (hzne1 : z ≠ 1)
    (hz2 : z ^ 2 = 1) : orderOf g = 2 * n := by
  have hg2n : g ^ (2 * n) = 1 := by rw [mul_comm 2 n, pow_mul, hgn, hz2]
  have hdvd2n : orderOf g ∣ 2 * n := orderOf_dvd_of_pow_eq_one hg2n
  obtain ⟨m, hm⟩ := hdvd
  rw [hm, mul_comm 2 n] at hdvd2n
  have hm2 : m ∣ 2 := (mul_dvd_mul_iff_left hnpos.ne').mp hdvd2n
  have hmle : m ≤ 2 := Nat.le_of_dvd (by norm_num) hm2
  have hmpos : 0 < m := by
    rcases Nat.eq_zero_or_pos m with h0 | h0
    · exact absurd (hm.trans (by rw [h0, mul_zero])) (orderOf_pos g).ne'
    · exact h0
  interval_cases m
  · exfalso
    have h1 : g ^ (n * 1) = 1 := by rw [← hm]; exact pow_orderOf_eq_one g
    rw [mul_one, hgn] at h1
    exact hzne1 h1
  · omega

/-- Two commuting elements `g, h` of a group of order `32`, of orders exactly `m` and `n`
respectively with `m * n = 32`, that are independent (`hindep`), generate `G` as
`Multiplicative (ZMod m) × Multiplicative (ZMod n)`. -/
theorem two_commuting_gens_iso {G : Type*} [Group G] [Finite G]
    (hG : Nat.card G = 32) {g h : G} {m n : ℕ} [NeZero m] [NeZero n]
    (hgm : g ^ m = 1) (hhn : h ^ n = 1) (hcomm : Commute g h)
    (hindep : ∀ i j : ℕ, i < m → j < n → g ^ i * h ^ j = 1 → i = 0 ∧ j = 0)
    (hmn : m * n = 32) :
    Nonempty (G ≃* Multiplicative (ZMod m) × Multiplicative (ZMod n)) := by
  classical
  set fg : Multiplicative (ZMod m) →* G := zmodZPowHom m g hgm with hfgdef
  set fh : Multiplicative (ZMod n) →* G := zmodZPowHom n h hhn with hfhdef
  have hfg_val : ∀ a : Multiplicative (ZMod m), fg a = g ^ (Multiplicative.toAdd a).val := by
    intro a
    have ha : a = Multiplicative.ofAdd (((Multiplicative.toAdd a).val : ZMod m)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd a).val : ℕ) : ℤ) : ZMod m)
        = ((Multiplicative.toAdd a).val : ZMod m) := by push_cast; ring
    conv_lhs => rw [ha, ← hcast]
    rw [hfgdef, zmodZPowHom_intCast, zpow_natCast]
  have hfh_val : ∀ b : Multiplicative (ZMod n), fh b = h ^ (Multiplicative.toAdd b).val := by
    intro b
    have hb : b = Multiplicative.ofAdd (((Multiplicative.toAdd b).val : ZMod n)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd b).val : ℕ) : ℤ) : ZMod n)
        = ((Multiplicative.toAdd b).val : ZMod n) := by push_cast; ring
    conv_lhs => rw [hb, ← hcast]
    rw [hfhdef, zmodZPowHom_intCast, zpow_natCast]
  have hcomm' : ∀ (a : Multiplicative (ZMod m)) (b : Multiplicative (ZMod n)),
      Commute (fg a) (fh b) := by
    intro a b; rw [hfg_val a, hfh_val b]; exact hcomm.pow_pow _ _
  have hinj : Function.Injective (fg.noncommCoprod fh hcomm') := by
    refine (injective_iff_map_eq_one _).mpr ?_
    rintro ⟨a, b⟩ hab
    simp only [MonoidHom.noncommCoprod_apply] at hab
    rw [hfg_val a, hfh_val b] at hab
    have hbv_lt : (Multiplicative.toAdd b).val < n := ZMod.val_lt _
    have hav_lt : (Multiplicative.toAdd a).val < m := ZMod.val_lt _
    obtain ⟨hav0, hbv0⟩ := hindep _ _ hav_lt hbv_lt hab
    have ha1 : a = 1 := by
      have h0 : Multiplicative.toAdd a = 0 := (ZMod.val_eq_zero _).mp hav0
      rw [← ofAdd_toAdd a, h0, ofAdd_zero]
    have hb1 : b = 1 := by
      have h0 : Multiplicative.toAdd b = 0 := (ZMod.val_eq_zero _).mp hbv0
      rw [← ofAdd_toAdd b, h0, ofAdd_zero]
    rw [ha1, hb1]; rfl
  have e_range : Multiplicative (ZMod m) × Multiplicative (ZMod n)
      ≃* (fg.noncommCoprod fh hcomm').range := MonoidHom.ofInjective hinj
  have hcardRange : Nat.card (fg.noncommCoprod fh hcomm').range = 32 := by
    rw [← Nat.card_congr e_range.toEquiv, Nat.card_prod]
    simp [Nat.card_eq_fintype_card, ZMod.card, hmn]
  have hrange_top : (fg.noncommCoprod fh hcomm').range = ⊤ :=
    Subgroup.eq_top_of_card_eq _ (by rw [hcardRange, hG])
  exact ⟨(e_range.trans ((MulEquiv.subgroupCongr hrange_top).trans Subgroup.topEquiv)).symm⟩

/-- Three pairwise-commuting elements `g, h, k` of a group of order `32`, of orders exactly
`m, n, p` with `m * n * p = 32`, that are independent (`hindep`), generate `G` as
`Multiplicative (ZMod m) × Multiplicative (ZMod n) × Multiplicative (ZMod p)`. -/
theorem three_commuting_gens_iso {G : Type*} [Group G] [Finite G]
    (hG : Nat.card G = 32) {g h k : G} {m n p : ℕ} [NeZero m] [NeZero n] [NeZero p]
    (hgm : g ^ m = 1) (hhn : h ^ n = 1) (hkp : k ^ p = 1)
    (hcommgh : Commute g h) (hcommgk : Commute g k) (hcommhk : Commute h k)
    (hindep : ∀ i j l : ℕ, i < m → j < n → l < p →
      g ^ i * h ^ j * k ^ l = 1 → i = 0 ∧ j = 0 ∧ l = 0)
    (hmnp : m * n * p = 32) :
    Nonempty
      (G ≃* Multiplicative (ZMod m) × Multiplicative (ZMod n) × Multiplicative (ZMod p)) := by
  classical
  set fg : Multiplicative (ZMod m) →* G := zmodZPowHom m g hgm with hfgdef
  set fh : Multiplicative (ZMod n) →* G := zmodZPowHom n h hhn with hfhdef
  set fk : Multiplicative (ZMod p) →* G := zmodZPowHom p k hkp with hfkdef
  have hfg_val : ∀ a : Multiplicative (ZMod m), fg a = g ^ (Multiplicative.toAdd a).val := by
    intro a
    have ha : a = Multiplicative.ofAdd (((Multiplicative.toAdd a).val : ZMod m)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd a).val : ℕ) : ℤ) : ZMod m)
        = ((Multiplicative.toAdd a).val : ZMod m) := by push_cast; ring
    conv_lhs => rw [ha, ← hcast]
    rw [hfgdef, zmodZPowHom_intCast, zpow_natCast]
  have hfh_val : ∀ b : Multiplicative (ZMod n), fh b = h ^ (Multiplicative.toAdd b).val := by
    intro b
    have hb : b = Multiplicative.ofAdd (((Multiplicative.toAdd b).val : ZMod n)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd b).val : ℕ) : ℤ) : ZMod n)
        = ((Multiplicative.toAdd b).val : ZMod n) := by push_cast; ring
    conv_lhs => rw [hb, ← hcast]
    rw [hfhdef, zmodZPowHom_intCast, zpow_natCast]
  have hfk_val : ∀ c : Multiplicative (ZMod p), fk c = k ^ (Multiplicative.toAdd c).val := by
    intro c
    have hcc : c = Multiplicative.ofAdd (((Multiplicative.toAdd c).val : ZMod p)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd c).val : ℕ) : ℤ) : ZMod p)
        = ((Multiplicative.toAdd c).val : ZMod p) := by push_cast; ring
    conv_lhs => rw [hcc, ← hcast]
    rw [hfkdef, zmodZPowHom_intCast, zpow_natCast]
  have hcommgh' : ∀ (a : Multiplicative (ZMod m)) (b : Multiplicative (ZMod n)),
      Commute (fg a) (fh b) := by
    intro a b; rw [hfg_val a, hfh_val b]; exact hcommgh.pow_pow _ _
  set Fgh := fg.noncommCoprod fh hcommgh' with hFghdef
  have hcommFghk : ∀ (x : Multiplicative (ZMod m) × Multiplicative (ZMod n))
      (c : Multiplicative (ZMod p)), Commute (Fgh x) (fk c) := by
    intro x c
    rw [hFghdef, MonoidHom.noncommCoprod_apply, hfg_val, hfh_val, hfk_val]
    exact (hcommgk.pow_pow _ _).mul_left (hcommhk.pow_pow _ _)
  set Φ := Fgh.noncommCoprod fk hcommFghk with hΦdef
  have hinj : Function.Injective Φ := by
    refine (injective_iff_map_eq_one _).mpr ?_
    rintro ⟨⟨a, b⟩, c⟩ habc
    simp only [hΦdef, hFghdef, MonoidHom.noncommCoprod_apply] at habc
    rw [hfg_val a, hfh_val b, hfk_val c] at habc
    have hav_lt : (Multiplicative.toAdd a).val < m := ZMod.val_lt _
    have hbv_lt : (Multiplicative.toAdd b).val < n := ZMod.val_lt _
    have hcv_lt : (Multiplicative.toAdd c).val < p := ZMod.val_lt _
    obtain ⟨hav0, hbv0, hcv0⟩ := hindep _ _ _ hav_lt hbv_lt hcv_lt habc
    have ha1 : a = 1 := by
      have h0 : Multiplicative.toAdd a = 0 := (ZMod.val_eq_zero _).mp hav0
      rw [← ofAdd_toAdd a, h0, ofAdd_zero]
    have hb1 : b = 1 := by
      have h0 : Multiplicative.toAdd b = 0 := (ZMod.val_eq_zero _).mp hbv0
      rw [← ofAdd_toAdd b, h0, ofAdd_zero]
    have hc1 : c = 1 := by
      have h0 : Multiplicative.toAdd c = 0 := (ZMod.val_eq_zero _).mp hcv0
      rw [← ofAdd_toAdd c, h0, ofAdd_zero]
    rw [ha1, hb1, hc1]; rfl
  have e_range : (Multiplicative (ZMod m) × Multiplicative (ZMod n)) × Multiplicative (ZMod p)
      ≃* Φ.range := MonoidHom.ofInjective hinj
  have hcardRange : Nat.card Φ.range = 32 := by
    rw [← Nat.card_congr e_range.toEquiv, Nat.card_prod, Nat.card_prod]
    simp [Nat.card_eq_fintype_card, ZMod.card, hmnp]
  have hrange_top : Φ.range = ⊤ := Subgroup.eq_top_of_card_eq _ (by rw [hcardRange, hG])
  have hfin :
      G ≃* (Multiplicative (ZMod m) × Multiplicative (ZMod n)) × Multiplicative (ZMod p) :=
    (e_range.trans ((MulEquiv.subgroupCongr hrange_top).trans Subgroup.topEquiv)).symm
  exact ⟨hfin.trans MulEquiv.prodAssoc⟩

/-- Four pairwise-commuting elements `g, h, k, l` of a group of order `32`, of orders
exactly `m, n, p, q` with `m * n * p * q = 32`, that are independent (`hindep`), generate
`G` as `Multiplicative (ZMod m) × Multiplicative (ZMod n) × Multiplicative (ZMod p) ×
Multiplicative (ZMod q)`. -/
theorem four_commuting_gens_iso {G : Type*} [Group G] [Finite G]
    (hG : Nat.card G = 32) {g h k l : G} {m n p q : ℕ}
    [NeZero m] [NeZero n] [NeZero p] [NeZero q]
    (hgm : g ^ m = 1) (hhn : h ^ n = 1) (hkp : k ^ p = 1) (hlq : l ^ q = 1)
    (hcommgh : Commute g h) (hcommgk : Commute g k) (hcommgl : Commute g l)
    (hcommhk : Commute h k) (hcommhl : Commute h l) (hcommkl : Commute k l)
    (hindep : ∀ i j u v : ℕ, i < m → j < n → u < p → v < q →
      g ^ i * h ^ j * k ^ u * l ^ v = 1 → i = 0 ∧ j = 0 ∧ u = 0 ∧ v = 0)
    (hmnpq : m * n * p * q = 32) :
    Nonempty (G ≃* Multiplicative (ZMod m) × Multiplicative (ZMod n)
      × Multiplicative (ZMod p) × Multiplicative (ZMod q)) := by
  classical
  set fg : Multiplicative (ZMod m) →* G := zmodZPowHom m g hgm with hfgdef
  set fh : Multiplicative (ZMod n) →* G := zmodZPowHom n h hhn with hfhdef
  set fk : Multiplicative (ZMod p) →* G := zmodZPowHom p k hkp with hfkdef
  set fl : Multiplicative (ZMod q) →* G := zmodZPowHom q l hlq with hfldef
  have hfg_val : ∀ a : Multiplicative (ZMod m), fg a = g ^ (Multiplicative.toAdd a).val := by
    intro a
    have ha : a = Multiplicative.ofAdd (((Multiplicative.toAdd a).val : ZMod m)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd a).val : ℕ) : ℤ) : ZMod m)
        = ((Multiplicative.toAdd a).val : ZMod m) := by push_cast; ring
    conv_lhs => rw [ha, ← hcast]
    rw [hfgdef, zmodZPowHom_intCast, zpow_natCast]
  have hfh_val : ∀ b : Multiplicative (ZMod n), fh b = h ^ (Multiplicative.toAdd b).val := by
    intro b
    have hb : b = Multiplicative.ofAdd (((Multiplicative.toAdd b).val : ZMod n)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd b).val : ℕ) : ℤ) : ZMod n)
        = ((Multiplicative.toAdd b).val : ZMod n) := by push_cast; ring
    conv_lhs => rw [hb, ← hcast]
    rw [hfhdef, zmodZPowHom_intCast, zpow_natCast]
  have hfk_val : ∀ c : Multiplicative (ZMod p), fk c = k ^ (Multiplicative.toAdd c).val := by
    intro c
    have hcc : c = Multiplicative.ofAdd (((Multiplicative.toAdd c).val : ZMod p)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd c).val : ℕ) : ℤ) : ZMod p)
        = ((Multiplicative.toAdd c).val : ZMod p) := by push_cast; ring
    conv_lhs => rw [hcc, ← hcast]
    rw [hfkdef, zmodZPowHom_intCast, zpow_natCast]
  have hfl_val : ∀ d : Multiplicative (ZMod q), fl d = l ^ (Multiplicative.toAdd d).val := by
    intro d
    have hd : d = Multiplicative.ofAdd (((Multiplicative.toAdd d).val : ZMod q)) := by
      rw [ZMod.natCast_val, ZMod.cast_id, ofAdd_toAdd]
    have hcast : ((((Multiplicative.toAdd d).val : ℕ) : ℤ) : ZMod q)
        = ((Multiplicative.toAdd d).val : ZMod q) := by push_cast; ring
    conv_lhs => rw [hd, ← hcast]
    rw [hfldef, zmodZPowHom_intCast, zpow_natCast]
  have hcommgh' : ∀ (a : Multiplicative (ZMod m)) (b : Multiplicative (ZMod n)),
      Commute (fg a) (fh b) := by
    intro a b; rw [hfg_val a, hfh_val b]; exact hcommgh.pow_pow _ _
  set Fgh := fg.noncommCoprod fh hcommgh' with hFghdef
  have hcommFghk : ∀ (x : Multiplicative (ZMod m) × Multiplicative (ZMod n))
      (c : Multiplicative (ZMod p)), Commute (Fgh x) (fk c) := by
    intro x c
    rw [hFghdef, MonoidHom.noncommCoprod_apply, hfg_val, hfh_val, hfk_val]
    exact (hcommgk.pow_pow _ _).mul_left (hcommhk.pow_pow _ _)
  set Fghk := Fgh.noncommCoprod fk hcommFghk with hFghkdef
  have hcommFghkl : ∀ (x : (Multiplicative (ZMod m) × Multiplicative (ZMod n))
      × Multiplicative (ZMod p)) (d : Multiplicative (ZMod q)), Commute (Fghk x) (fl d) := by
    intro x d
    rw [hFghkdef, MonoidHom.noncommCoprod_apply, hFghdef, MonoidHom.noncommCoprod_apply,
      hfg_val, hfh_val, hfk_val, hfl_val]
    exact ((hcommgl.pow_pow _ _).mul_left (hcommhl.pow_pow _ _)).mul_left
      (hcommkl.pow_pow _ _)
  set Φ := Fghk.noncommCoprod fl hcommFghkl with hΦdef
  have hinj : Function.Injective Φ := by
    refine (injective_iff_map_eq_one _).mpr ?_
    rintro ⟨⟨⟨a, b⟩, c⟩, d⟩ habcd
    simp only [hΦdef, hFghkdef, hFghdef, MonoidHom.noncommCoprod_apply] at habcd
    rw [hfg_val a, hfh_val b, hfk_val c, hfl_val d] at habcd
    have hav_lt : (Multiplicative.toAdd a).val < m := ZMod.val_lt _
    have hbv_lt : (Multiplicative.toAdd b).val < n := ZMod.val_lt _
    have hcv_lt : (Multiplicative.toAdd c).val < p := ZMod.val_lt _
    have hdv_lt : (Multiplicative.toAdd d).val < q := ZMod.val_lt _
    obtain ⟨hav0, hbv0, hcv0, hdv0⟩ :=
      hindep _ _ _ _ hav_lt hbv_lt hcv_lt hdv_lt habcd
    have ha1 : a = 1 := by
      have h0 : Multiplicative.toAdd a = 0 := (ZMod.val_eq_zero _).mp hav0
      rw [← ofAdd_toAdd a, h0, ofAdd_zero]
    have hb1 : b = 1 := by
      have h0 : Multiplicative.toAdd b = 0 := (ZMod.val_eq_zero _).mp hbv0
      rw [← ofAdd_toAdd b, h0, ofAdd_zero]
    have hc1 : c = 1 := by
      have h0 : Multiplicative.toAdd c = 0 := (ZMod.val_eq_zero _).mp hcv0
      rw [← ofAdd_toAdd c, h0, ofAdd_zero]
    have hd1 : d = 1 := by
      have h0 : Multiplicative.toAdd d = 0 := (ZMod.val_eq_zero _).mp hdv0
      rw [← ofAdd_toAdd d, h0, ofAdd_zero]
    rw [ha1, hb1, hc1, hd1]; rfl
  have e_range : ((Multiplicative (ZMod m) × Multiplicative (ZMod n))
      × Multiplicative (ZMod p)) × Multiplicative (ZMod q) ≃* Φ.range :=
    MonoidHom.ofInjective hinj
  have hcardRange : Nat.card Φ.range = 32 := by
    rw [← Nat.card_congr e_range.toEquiv, Nat.card_prod, Nat.card_prod, Nat.card_prod]
    simp [Nat.card_eq_fintype_card, ZMod.card, hmnpq]
  have hrange_top : Φ.range = ⊤ := Subgroup.eq_top_of_card_eq _ (by rw [hcardRange, hG])
  have hfin : G ≃* ((Multiplicative (ZMod m) × Multiplicative (ZMod n))
      × Multiplicative (ZMod p)) × Multiplicative (ZMod q) :=
    (e_range.trans ((MulEquiv.subgroupCongr hrange_top).trans Subgroup.topEquiv)).symm
  exact ⟨(hfin.trans MulEquiv.prodAssoc).trans MulEquiv.prodAssoc⟩

end Smallgroups.UsefulTheorems
