/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Mathlib.GroupTheory.Nilpotent
import Mathlib.GroupTheory.PGroup
import Mathlib.GroupTheory.Sylow
import Mathlib.GroupTheory.Commutator.Basic
import Smallgroups.UsefulTheorems.PGroupGeneration.CentralExtension

/-!
# p-group generation: the lower exponent-p central series

The organizing filtration of the p-group generation algorithm.  For a prime `p` the
**lower exponent-`p` central series** of `G` is

  `P₀ = ⊤`,  `P_{n+1} = ⁅P_n, G⁆ ⊔ Pₙᵖ`

where `Hᵖ = pPowSubgroup p H` is the subgroup generated by the `p`-th powers of `H`.  Each
term is characteristic (hence normal), the series is descending, and successive quotients
are central and of exponent `p` (in element form: `⁅x, g⁆` and `x ^ p` land in the next
term).

The main structural result is **termination**: for a finite `p`-group the series reaches
`⊥` (`pLowerCentralSeries_eq_bot`), via the strict-descent lemma
`sup_commutator_pPow_lt`: if `H ≠ ⊥` is normal then `⁅H, G⁆ ⊔ Hᵖ < H`.  (Proof: otherwise
the image of `H` in `G ⧸ ⁅H, G⁆` is a central subgroup equal to its own `p`-th powers,
which forces it to be trivial by Cauchy + `Finite.injective_iff_surjective`; then
`H = ⁅H, G⁆` contradicts nilpotency of finite `p`-groups.)

The smallest `c` with `P_c = ⊥` is the *p-class* of `G`; `P₁ = ⁅G,G⁆Gᵖ` is identified with
the Frattini subgroup in `PGroupGeneration/Frattini.lean`.
-/

namespace Smallgroups.UsefulTheorems

open scoped commutatorElement

variable {G : Type*} [Group G]

/-! ### The subgroup generated by `p`-th powers -/

/-- The subgroup generated by the `p`-th powers of elements of `H`. -/
def pPowSubgroup (p : ℕ) (H : Subgroup G) : Subgroup G :=
  Subgroup.closure ((· ^ p) '' (H : Set G))

theorem pow_mem_pPowSubgroup (p : ℕ) {H : Subgroup G} {x : G} (hx : x ∈ H) :
    x ^ p ∈ pPowSubgroup p H :=
  Subgroup.subset_closure ⟨x, hx, rfl⟩

theorem pPowSubgroup_le (p : ℕ) {H K : Subgroup G} (h : ∀ x ∈ H, x ^ p ∈ K) :
    pPowSubgroup p H ≤ K :=
  (Subgroup.closure_le K).mpr (by rintro _ ⟨y, hy, rfl⟩; exact h y hy)

theorem pPowSubgroup_le_self (p : ℕ) (H : Subgroup G) : pPowSubgroup p H ≤ H :=
  pPowSubgroup_le p fun _ hx => H.pow_mem hx p

theorem pPowSubgroup_mono (p : ℕ) {H K : Subgroup G} (h : H ≤ K) :
    pPowSubgroup p H ≤ pPowSubgroup p K :=
  Subgroup.closure_mono (Set.image_mono h)

/-- `pPowSubgroup` commutes with images under group homomorphisms. -/
theorem map_pPowSubgroup {G' : Type*} [Group G'] (φ : G →* G') (p : ℕ) (H : Subgroup G) :
    (pPowSubgroup p H).map φ = pPowSubgroup p (H.map φ) := by
  rw [pPowSubgroup, MonoidHom.map_closure, pPowSubgroup, Subgroup.coe_map,
    Set.image_image, Set.image_image]
  exact congrArg _ (Set.image_congr' fun x => map_pow φ x p)

instance pPowSubgroup_characteristic (p : ℕ) (H : Subgroup G) [H.Characteristic] :
    (pPowSubgroup p H).Characteristic := by
  rw [Subgroup.characteristic_iff_map_eq]
  intro φ
  rw [map_pPowSubgroup, Subgroup.characteristic_iff_map_eq.mp ‹_› φ]

/-- The join of two characteristic subgroups is characteristic. -/
theorem characteristic_sup {H K : Subgroup G} [H.Characteristic] [K.Characteristic] :
    (H ⊔ K).Characteristic := by
  rw [Subgroup.characteristic_iff_map_eq]
  intro φ
  rw [Subgroup.map_sup, Subgroup.characteristic_iff_map_eq.mp ‹H.Characteristic› φ,
    Subgroup.characteristic_iff_map_eq.mp ‹K.Characteristic› φ]

/-! ### The series -/

/-- The lower exponent-`p` central series: `P₀ = ⊤` and `P_{n+1} = ⁅P_n, G⁆ ⊔ Pₙᵖ`. -/
def pLowerCentralSeries (p : ℕ) (G : Type*) [Group G] : ℕ → Subgroup G
  | 0 => ⊤
  | n + 1 => ⁅pLowerCentralSeries p G n, (⊤ : Subgroup G)⁆
      ⊔ pPowSubgroup p (pLowerCentralSeries p G n)

@[simp]
theorem pLowerCentralSeries_zero (p : ℕ) : pLowerCentralSeries p G 0 = ⊤ := rfl

theorem pLowerCentralSeries_succ (p n : ℕ) :
    pLowerCentralSeries p G (n + 1) = ⁅pLowerCentralSeries p G n, (⊤ : Subgroup G)⁆
      ⊔ pPowSubgroup p (pLowerCentralSeries p G n) := rfl

instance pLowerCentralSeries_characteristic (p n : ℕ) :
    (pLowerCentralSeries p G n).Characteristic := by
  induction n with
  | zero => exact Subgroup.topCharacteristic
  | succ n ih => exact characteristic_sup

theorem pLowerCentralSeries_succ_le (p n : ℕ) :
    pLowerCentralSeries p G (n + 1) ≤ pLowerCentralSeries p G n :=
  sup_le (Subgroup.commutator_le_left _ _) (pPowSubgroup_le_self p _)

theorem pLowerCentralSeries_antitone (p : ℕ) : Antitone (pLowerCentralSeries p G) :=
  antitone_nat_of_succ_le (pLowerCentralSeries_succ_le p)

/-- Successive quotients are central, in element form. -/
theorem commutator_mem_pLowerCentralSeries_succ {p n : ℕ} {x : G}
    (hx : x ∈ pLowerCentralSeries p G n) (g : G) :
    ⁅x, g⁆ ∈ pLowerCentralSeries p G (n + 1) :=
  (le_sup_left : _ ≤ pLowerCentralSeries p G (n + 1))
    (Subgroup.commutator_mem_commutator hx (Subgroup.mem_top g))

/-- Successive quotients have exponent `p`, in element form. -/
theorem pow_mem_pLowerCentralSeries_succ {p n : ℕ} {x : G}
    (hx : x ∈ pLowerCentralSeries p G n) :
    x ^ p ∈ pLowerCentralSeries p G (n + 1) :=
  (le_sup_right : _ ≤ pLowerCentralSeries p G (n + 1)) (pow_mem_pPowSubgroup p hx)

theorem pLowerCentralSeries_succ_eq_bot {p n : ℕ}
    (h : pLowerCentralSeries p G n = ⊥) : pLowerCentralSeries p G (n + 1) = ⊥ := by
  rw [pLowerCentralSeries_succ, h, Subgroup.commutator_bot_left, bot_sup_eq]
  exact le_bot_iff.mp (pPowSubgroup_le_self p ⊥)

/-! ### Strict descent and termination -/

/-- A nontrivial finite `p`-group has an element of order `p`. -/
theorem exists_orderOf_eq_prime_of_isPGroup {A : Type*} [Group A] [Finite A] [Nontrivial A]
    {p : ℕ} (hp : p.Prime) (hA : IsPGroup p A) : ∃ a : A, orderOf a = p := by
  haveI := Fact.mk hp
  have hdvd : p ∣ Nat.card A := by
    obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp hA
    rcases Nat.eq_zero_or_pos k with rfl | hkpos
    · exact absurd (hk.trans (pow_zero p)) (Finite.one_lt_card (α := A)).ne'
    · exact hk ▸ dvd_pow_self p hkpos.ne'
  exact exists_prime_orderOf_dvd_card' p hdvd

/-- A finite commutative `p`-group generated by its `p`-th powers is trivial: the `p`-th
power map is then a surjective, hence injective, self-map, but a nontrivial finite
`p`-group has an element of order `p` in its kernel. -/
theorem subsingleton_of_pPowSubgroup_top {A : Type*} [Group A] [Finite A] {p : ℕ}
    (hp : p.Prime) (hA : IsPGroup p A) (hcomm : ∀ a b : A, a * b = b * a)
    (h : pPowSubgroup p (⊤ : Subgroup A) = ⊤) : Subsingleton A := by
  by_contra hns
  haveI : Nontrivial A := not_subsingleton_iff_nontrivial.mp hns
  obtain ⟨a, ha⟩ := exists_orderOf_eq_prime_of_isPGroup hp hA
  have hψsurj : Function.Surjective (MonoidHom.mk' (fun x : A => x ^ p)
      (fun x y => Commute.mul_pow (hcomm x y) p)) := by
    intro y
    have hle2 : pPowSubgroup p (⊤ : Subgroup A) ≤ (MonoidHom.mk' (fun x : A => x ^ p)
        (fun x y => Commute.mul_pow (hcomm x y) p)).range :=
      pPowSubgroup_le p fun w _ => ⟨w, rfl⟩
    have hy : y ∈ pPowSubgroup p (⊤ : Subgroup A) := by
      rw [h]; exact Subgroup.mem_top y
    exact hle2 hy
  have hinj := Finite.injective_iff_surjective.mpr hψsurj
  have ha1 : a = 1 := hinj (show a ^ p = 1 ^ p by
    rw [one_pow, ← ha]; exact pow_orderOf_eq_one a)
  rw [ha1, orderOf_one] at ha
  exact hp.one_lt.ne' ha.symm

/-- A subgroup containment which is strict has strictly smaller cardinality. -/
theorem card_lt_card_of_lt [Finite G] {H K : Subgroup G} (h : H < K) :
    Nat.card H < Nat.card K := by
  have h1 : Nat.card H = ((H : Set G)).ncard := Nat.card_coe_set_eq _
  have h2 : Nat.card K = ((K : Set G)).ncard := Nat.card_coe_set_eq _
  rw [h1, h2]
  exact Set.ncard_lt_ncard
    ((SetLike.coe_subset_coe.mpr h.le).ssubset_of_ne
      fun heq => h.ne (SetLike.coe_injective heq))
    (Set.toFinite _)

/-- **Strict descent**: in a finite `p`-group, `⁅H, G⁆ ⊔ Hᵖ < H` for every nontrivial
normal subgroup `H`.  This is the engine behind the termination of the lower exponent-`p`
central series. -/
theorem sup_commutator_pPow_lt [Finite G] {p : ℕ} (hp : p.Prime) (hG : IsPGroup p G)
    (H : Subgroup G) [H.Normal] (hne : H ≠ ⊥) :
    ⁅H, (⊤ : Subgroup G)⁆ ⊔ pPowSubgroup p H < H := by
  haveI := Fact.mk hp
  have hle : ⁅H, (⊤ : Subgroup G)⁆ ⊔ pPowSubgroup p H ≤ H :=
    sup_le (Subgroup.commutator_le_left _ _) (pPowSubgroup_le_self p H)
  rcases hle.lt_or_eq with hlt | heq
  · exact hlt
  exfalso; apply hne
  have hNleH : ⁅H, (⊤ : Subgroup G)⁆ ≤ H := Subgroup.commutator_le_left _ _
  -- the image of `H` in the quotient by `⁅H, G⁆` is central
  have hcent : ∀ x ∈ H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆),
      x ∈ Subgroup.center (G ⧸ ⁅H, (⊤ : Subgroup G)⁆) := by
    rintro _ ⟨y, hy, rfl⟩
    rw [Subgroup.mem_center_iff]
    intro g'
    obtain ⟨g, rfl⟩ := QuotientGroup.mk'_surjective _ g'
    rw [← commutatorElement_eq_one_iff_mul_comm, ← map_commutatorElement,
      ← MonoidHom.mem_ker, QuotientGroup.ker_mk']
    have := Subgroup.commutator_mem_commutator (Subgroup.mem_top g) hy
    rwa [Subgroup.commutator_comm] at this
  -- ... and is generated by its own `p`-th powers
  have hmap : H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆)
      = pPowSubgroup p (H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆)) :=
    calc H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆)
        = (⁅H, (⊤ : Subgroup G)⁆ ⊔ pPowSubgroup p H).map
            (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) := congrArg _ heq.symm
      _ = ⁅H, (⊤ : Subgroup G)⁆.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆)
            ⊔ (pPowSubgroup p H).map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) :=
          Subgroup.map_sup _ _ _
      _ = ⊥ ⊔ (pPowSubgroup p H).map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) := by
          rw [QuotientGroup.map_mk'_self]
      _ = (pPowSubgroup p H).map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) :=
          bot_sup_eq _
      _ = pPowSubgroup p (H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆)) :=
          map_pPowSubgroup _ p H
  -- hence that image is trivial
  have hHbbot : H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) = ⊥ := by
    by_contra hbb
    set Hb := H.map (QuotientGroup.mk' ⁅H, (⊤ : Subgroup G)⁆) with hHb
    haveI : Nontrivial Hb := (Subgroup.nontrivial_iff_ne_bot _).mpr hbb
    have hsub : Subsingleton Hb := by
      refine subsingleton_of_pPowSubgroup_top hp ((hG.to_quotient _).to_subgroup Hb)
        (fun a b => Subtype.ext (Subgroup.mem_center_iff.mp (hcent _ b.2) a.1)) ?_
      apply Subgroup.map_injective (Subgroup.subtype_injective Hb)
      rw [map_pPowSubgroup, ← MonoidHom.range_eq_map, Subgroup.range_subtype]
      exact hmap.symm
    exact not_subsingleton _ hsub
  -- so `H = ⁅H, G⁆`, which dies against nilpotency
  have hHeq : H = ⁅H, (⊤ : Subgroup G)⁆ := by
    refine le_antisymm ?_ hNleH
    rw [← QuotientGroup.ker_mk' ⁅H, (⊤ : Subgroup G)⁆, ← Subgroup.map_eq_bot_iff]
    exact hHbbot
  have hlcs : ∀ k, H ≤ Subgroup.lowerCentralSeries (⊤ : Subgroup G) k := by
    intro k
    induction k with
    | zero => exact le_top
    | succ k ih =>
      rw [Subgroup.lowerCentralSeries_succ]
      calc H = ⁅H, (⊤ : Subgroup G)⁆ := hHeq
        _ ≤ ⁅Subgroup.lowerCentralSeries (⊤ : Subgroup G) k, (⊤ : Subgroup G)⁆ :=
          Subgroup.commutator_mono ih le_rfl
  haveI : Group.IsNilpotent G := hG.isNilpotent
  obtain ⟨k, hk⟩ := Subgroup.nilpotent_iff_lowerCentralSeries.mp ‹_›
  exact le_bot_iff.mp (hk ▸ hlcs k)

/-- **Termination**: in a finite `p`-group the lower exponent-`p` central series reaches
`⊥` after at most `Nat.card G` steps.  The least such index is the *p-class* of `G`. -/
theorem pLowerCentralSeries_eq_bot [Finite G] {p : ℕ} (hp : p.Prime)
    (hG : IsPGroup p G) : pLowerCentralSeries p G (Nat.card G) = ⊥ := by
  have key : ∀ n, pLowerCentralSeries p G n = ⊥ ∨
      Nat.card (pLowerCentralSeries p G n) + n ≤ Nat.card G := by
    intro n
    induction n with
    | zero =>
      right
      rw [pLowerCentralSeries_zero, Subgroup.card_top]
      omega
    | succ n ih =>
      by_cases hb : pLowerCentralSeries p G n = ⊥
      · exact Or.inl (pLowerCentralSeries_succ_eq_bot hb)
      rcases ih with h | h
      · exact absurd h hb
      right
      have hlt : pLowerCentralSeries p G (n + 1) < pLowerCentralSeries p G n := by
        rw [pLowerCentralSeries_succ]
        exact sup_commutator_pPow_lt hp hG _ hb
      have hcard := card_lt_card_of_lt hlt
      omega
  rcases key (Nat.card G) with h | h
  · exact h
  · have hpos : 0 < Nat.card (pLowerCentralSeries p G (Nat.card G)) := Nat.card_pos
    exact absurd h (by omega)

/-- The `p`-class exists: some term of the series is trivial. -/
theorem exists_pLowerCentralSeries_eq_bot [Finite G] {p : ℕ} (hp : p.Prime)
    (hG : IsPGroup p G) : ∃ n, pLowerCentralSeries p G n = ⊥ :=
  ⟨Nat.card G, pLowerCentralSeries_eq_bot hp hG⟩

/-! ### Compatibility with direct products

Needed to identify the Frattini subgroup of a product `A × B` (e.g. `Qᵢ × C₂` order-32
descendants) with the product of the Frattini subgroups, in `PGroupGeneration/Frattini.lean`. -/

/-- The join of two "rectangular" subgroups of a direct product is again rectangular:
`(H₁ ×ˢ K₁) ⊔ (H₂ ×ˢ K₂) = (H₁ ⊔ H₂) ×ˢ (K₁ ⊔ K₂)`. -/
private theorem prod_sup_prod {A B : Type*} [Group A] [Group B]
    (H₁ H₂ : Subgroup A) (K₁ K₂ : Subgroup B) :
    (H₁.prod K₁) ⊔ (H₂.prod K₂) = (H₁ ⊔ H₂).prod (K₁ ⊔ K₂) := by
  apply le_antisymm
  · exact sup_le (Subgroup.prod_mono le_sup_left le_sup_left)
      (Subgroup.prod_mono le_sup_right le_sup_right)
  · rintro ⟨a, b⟩ ⟨ha, hb⟩
    have hA : H₁ ⊔ H₂ ≤ ((H₁.prod K₁) ⊔ (H₂.prod K₂)).comap (MonoidHom.inl A B) := by
      apply sup_le
      · intro x hx; exact le_sup_left (a := H₁.prod K₁) (b := H₂.prod K₂) ⟨hx, K₁.one_mem⟩
      · intro x hx; exact le_sup_right (a := H₁.prod K₁) (b := H₂.prod K₂) ⟨hx, K₂.one_mem⟩
    have hB : K₁ ⊔ K₂ ≤ ((H₁.prod K₁) ⊔ (H₂.prod K₂)).comap (MonoidHom.inr A B) := by
      apply sup_le
      · intro x hx; exact le_sup_left (a := H₁.prod K₁) (b := H₂.prod K₂) ⟨H₁.one_mem, hx⟩
      · intro x hx; exact le_sup_right (a := H₁.prod K₁) (b := H₂.prod K₂) ⟨H₂.one_mem, hx⟩
    have ha' : ((a, (1 : B)) : A × B) ∈ (H₁.prod K₁) ⊔ (H₂.prod K₂) := hA ha
    have hb' : (((1 : A), b) : A × B) ∈ (H₁.prod K₁) ⊔ (H₂.prod K₂) := hB hb
    have heq : ((a, (1 : B)) : A × B) * ((1 : A), b) = (a, b) := by simp
    rw [← heq]
    exact mul_mem ha' hb'

/-- `pPowSubgroup` distributes over direct products. -/
private theorem pPowSubgroup_prod (p : ℕ) {A B : Type*} [Group A] [Group B]
    (H : Subgroup A) (K : Subgroup B) :
    pPowSubgroup p (H.prod K) = (pPowSubgroup p H).prod (pPowSubgroup p K) := by
  have himg : (· ^ p) '' (↑(H.prod K) : Set (A × B))
      = ((· ^ p) '' (H : Set A)) ×ˢ ((· ^ p) '' (K : Set B)) := by
    ext ⟨a, b⟩
    simp only [Set.mem_image, Subgroup.coe_prod, Set.mem_prod, Prod.exists]
    constructor
    · rintro ⟨x, y, ⟨hx, hy⟩, hxy⟩
      rw [Prod.pow_mk] at hxy
      injection hxy with hax hby
      exact ⟨⟨x, hx, hax⟩, ⟨y, hy, hby⟩⟩
    · rintro ⟨⟨x, hx, hxa⟩, ⟨y, hy, hyb⟩⟩
      exact ⟨x, y, ⟨hx, hy⟩, by rw [Prod.pow_mk, hxa, hyb]⟩
  unfold pPowSubgroup
  rw [himg]
  exact Subgroup.closure_prod ⟨1, H.one_mem, one_pow p⟩ ⟨1, K.one_mem, one_pow p⟩

/-- The lower exponent-`p` central series of a direct product is the product of the
individual series. -/
theorem pLowerCentralSeries_prod {A B : Type*} [Group A] [Group B] (p n : ℕ) :
    pLowerCentralSeries p (A × B) n
      = (pLowerCentralSeries p A n).prod (pLowerCentralSeries p B n) := by
  induction n with
  | zero => simp [pLowerCentralSeries_zero]
  | succ n ih =>
    rw [pLowerCentralSeries_succ, pLowerCentralSeries_succ, pLowerCentralSeries_succ, ih,
      pPowSubgroup_prod, ← Subgroup.top_prod_top, Subgroup.commutator_prod_prod, prod_sup_prod]

end Smallgroups.UsefulTheorems
