/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order80.UniqueSylowFive
import Smallgroups.UsefulTheorems.Order80.UniqueSylowFive_K1to7
import Smallgroups.UsefulTheorems.SemidirectProductClassify

/-!
# Groups of order 80 with sixteen Sylow-5 subgroups

This file handles the second branch of `order80_sylow_dichotomy`
(`Order80/Sylow.lean`): if a group `G` of order `80` has `n₅ = 16`, then its
Sylow `2`-subgroup `P` (of order `16`) is unique, hence normal, and
Schur–Zassenhaus splits `G` as `P ⋊[φ] C₅`.

The classification then proceeds:

* the conjugation action of a generator of `C₅` on `P` is a **fixed-point-free**
  automorphism `σ` with `σ⁵ = 1` (`order80_sixteen_sylow_fpf`): a nontrivial
  fixed point would produce an involution `z` centralising the Sylow
  `5`-subgroup `Q = ⟨inr c⟩`; but `n₅ = 16` forces `N(Q) = Q` (order `5`),
  which cannot contain an involution;
* an order-`5` automorphism partitions any invariant subset into orbits of
  size `1` or `5` (`mulAut_five_card_modEq`, via
  `IsPGroup.card_modEq_card_fixedPoints`), so an invariant subset whose
  cardinality is not divisible by `5` contains a fixed point
  (`exists_fixed_of_five`);
* for `13` of the `14` isomorphism types of order-`16` groups the set of
  elements of a suitable fixed order (order `2`, or order `8` for `SD₁₆`) has
  cardinality not divisible by `5`, contradicting fixed-point-freeness
  (`no_fpf_of_pow_count`): this is the concrete form of the classical
  statement that `(C₂)⁴` is the only order-`16` group `P` with `5 ∣ |Aut P|`
  (a nontrivial `φ : C₅ →* Aut P` is automatically injective, so it forces an
  order-`5` element in `Aut P`);
* for `P = (C₂)⁴` all nontrivial actions `φ : C₅ →* Aut (C₂)⁴` give isomorphic
  semidirect products (`order80_nonnormal_unique`): fixed-point-freeness makes
  the `σ`-orbit of any `v ≠ 1` a basis `v, σv, σ²v, σ³v` of `(C₂)⁴` (again by
  orbit counting: the invariant subgroup generated by the orbit has order
  `≡ 1 (mod 5)`, hence is everything), on which `σ` acts as the companion
  matrix of `x⁴ + x³ + x² + x + 1` — a normal form independent of `φ`.

Main results:

* `order80_semidirectProduct_of_sylow_five_sixteen` — the Schur–Zassenhaus
  reduction `G ≃* P ⋊[φ] C₅` with `|P| = 16`;
* `order80_nonnormal_unique` — for every nontrivial
  `φ : C₅ →* Aut (C₂)⁴`, `(C₂)⁴ ⋊[φ] C₅ ≅ order80_nonnormal_rep`;
* `order80_sixteen_sylow_classification` — **every** group of order `80` with
  `n₅ = 16` is isomorphic to `order80_nonnormal_rep`: there is exactly one
  such group;
* `order80_nonnormal_rep_card`, `order80_nonnormal_rep_sylow_five` — the
  representative really is such a group: it has order `80` and `n₅ = 16`.
-/

namespace Smallgroups.UsefulTheorems

open Sylow

variable {G : Type*} [Group G]

/-! ### Transporting Sylow counts along a group isomorphism -/

/-- A group isomorphism induces an equivalence of Sylow `p`-subgroups. -/
noncomputable def sylowEquivOfMulEquiv {H : Type*} [Group H] {p : ℕ} (e : G ≃* H) :
    Sylow p G ≃ Sylow p H where
  toFun P := P.comapOfInjective e.symm.toMonoidHom e.symm.injective
    (by rw [MonoidHom.range_eq_top.mpr e.symm.surjective]; exact le_top)
  invFun Q := Q.comapOfInjective e.toMonoidHom e.injective
    (by rw [MonoidHom.range_eq_top.mpr e.surjective]; exact le_top)
  left_inv P := by
    apply Sylow.ext
    rw [Sylow.coe_comapOfInjective, Sylow.coe_comapOfInjective, Subgroup.comap_comap]
    have h : e.symm.toMonoidHom.comp e.toMonoidHom = MonoidHom.id G := by
      ext x; simp
    rw [h, Subgroup.comap_id]
  right_inv Q := by
    apply Sylow.ext
    rw [Sylow.coe_comapOfInjective, Sylow.coe_comapOfInjective, Subgroup.comap_comap]
    have h : e.toMonoidHom.comp e.symm.toMonoidHom = MonoidHom.id H := by
      ext x; simp
    rw [h, Subgroup.comap_id]

/-- Isomorphic groups have the same number of Sylow `p`-subgroups. -/
theorem card_sylow_of_mulEquiv {H : Type*} [Group H] (p : ℕ) (e : G ≃* H) :
    Nat.card (Sylow p G) = Nat.card (Sylow p H) :=
  Nat.card_congr (sylowEquivOfMulEquiv e)

/-! ### The Schur–Zassenhaus reduction: `G ≃* P ⋊[φ] K` with `|P| = 16`, `|K| = 5` -/

/-- **Semidirect-product reduction for order `80` with sixteen Sylow-`5`
subgroups.** If `G` has order `80` and `n₅ = 16`, its Sylow `2`-subgroup is
normal, and `G` is a semidirect product `N ⋊[φ] K` with `|N| = 16`, `|K| = 5`. -/
theorem order80_semidirectProduct_of_sylow_five_sixteen [Finite G] (hG : Nat.card G = 80)
    (hSyl : Nat.card (Sylow 5 G) = 16) :
    ∃ (N K : Subgroup G) (φ : K →* MulAut N),
      N.Normal ∧ Nat.card N = 16 ∧ Nat.card K = 5 ∧
        Nonempty (G ≃* SemidirectProduct N K φ) := by
  haveI : Fact (Nat.Prime 2) := ⟨by norm_num⟩
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 2 G))
  haveI hsub : Subsingleton (Sylow 2 G) :=
    (Nat.card_eq_one_iff_unique.mp
      (card_sylow_two_eq_one_of_card_sylow_five_eq_sixteen hG hSyl)).1
  haveI hnorm : (↑P0 : Subgroup G).Normal := Sylow.normal_of_subsingleton P0
  have hcardN : Nat.card (↑P0 : Subgroup G) = 16 := card_sylow_two_subgroup_of_card_80 hG P0
  have hidx : (↑P0 : Subgroup G).index = 5 := by
    have hmul := (↑P0 : Subgroup G).card_mul_index
    rw [hcardN, hG] at hmul
    omega
  have hcop : Nat.Coprime (Nat.card (↑P0 : Subgroup G)) (↑P0 : Subgroup G).index := by
    rw [hcardN, hidx]
    norm_num
  obtain ⟨K, φ, ⟨e⟩⟩ := schurZassenhaus_semidirectProduct (↑P0 : Subgroup G) hcop
  have hcardK : Nat.card K = 5 := by
    have h1 : Nat.card G = Nat.card (↑P0 : Subgroup G) * Nat.card K := by
      rw [Nat.card_congr e.toEquiv, Nat.card_congr SemidirectProduct.equivProd, Nat.card_prod]
    rw [hG, hcardN] at h1
    omega
  exact ⟨↑P0, K, φ, hnorm, hcardN, hcardK, ⟨e⟩⟩

/-! ### Orbit counting for an automorphism of order dividing `5`

An order-`5` permutation of a finite set has all orbits of size `1` or `5`, so
the total cardinality is congruent mod `5` to the number of fixed points.  We
derive it from `IsPGroup.card_modEq_card_fixedPoints` applied to the cyclic
subgroup generated by the permutation. -/

private theorem perm_five_card_modEq {α : Type*} [Finite α] (π : Equiv.Perm α)
    (h5 : ∀ y, π (π (π (π (π y)))) = y) :
    Nat.card α ≡ Nat.card {y : α // π y = y} [MOD 5] := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  have hpow : π ^ 5 = 1 := by
    have hπ5 : π ^ 5 = π * π * π * π * π := by
      rw [pow_succ, pow_succ, pow_succ, pow_succ, pow_one]
    ext y
    rw [hπ5]
    simpa [Equiv.Perm.mul_apply] using h5 y
  have hZ : IsPGroup 5 (Subgroup.zpowers π) := by
    rcases (Nat.dvd_prime (by norm_num)).mp (orderOf_dvd_of_pow_eq_one hpow) with h | h
    · exact IsPGroup.of_card (by rw [Nat.card_zpowers, h, pow_zero])
    · exact IsPGroup.of_card (by rw [Nat.card_zpowers, h, pow_one])
  have hmod := hZ.card_modEq_card_fixedPoints α
  have hcardeq : Nat.card (MulAction.fixedPoints (Subgroup.zpowers π) α)
      = Nat.card {y : α // π y = y} := by
    apply Nat.card_congr
    apply Equiv.subtypeEquivRight
    intro y
    rw [MulAction.mem_fixedPoints]
    constructor
    · intro hy
      have := hy ⟨π, Subgroup.mem_zpowers π⟩
      rwa [Submonoid.mk_smul, Equiv.Perm.smul_def] at this
    · intro hy g
      have hle : Subgroup.zpowers π ≤ MulAction.stabilizer (Equiv.Perm α) y :=
        Subgroup.zpowers_le.mpr (MulAction.mem_stabilizer_iff.mpr
          (by rw [Equiv.Perm.smul_def]; exact hy))
      have := hle g.2
      rw [MulAction.mem_stabilizer_iff] at this
      exact this
  rw [hcardeq] at hmod
  exact hmod

/-- **Orbit counting on an invariant subset.** If `σ` is an automorphism with
`σ⁵ = 1` (pointwise) and `p` is a `σ`-invariant predicate, the number of
elements satisfying `p` is congruent mod `5` to the number of `σ`-fixed ones. -/
theorem mulAut_five_card_modEq {K : Type*} [Group K] [Finite K] (σ : MulAut K)
    (h5 : ∀ x, σ (σ (σ (σ (σ x)))) = x) (p : K → Prop) (hp : ∀ x, p x → p (σ x)) :
    Nat.card {x : K // p x} ≡ Nat.card {x : K // p x ∧ σ x = x} [MOD 5] := by
  have hinj : Function.Injective
      (fun y : {x : K // p x} => (⟨σ y.1, hp y.1 y.2⟩ : {x : K // p x})) :=
    fun a b hab => Subtype.ext (σ.injective (congrArg Subtype.val hab))
  let π : Equiv.Perm {x : K // p x} :=
    Equiv.ofBijective _ ((Finite.injective_iff_bijective).mp hinj)
  have hπcoe : ∀ y : {x : K // p x}, (π y : K) = σ y.1 := fun y => rfl
  have h5' : ∀ y, π (π (π (π (π y)))) = y := by
    intro y
    apply Subtype.ext
    rw [hπcoe, hπcoe, hπcoe, hπcoe, hπcoe]
    exact h5 y.1
  have hmod := perm_five_card_modEq π h5'
  have h2 : Nat.card {y : {x : K // p x} // π y = y} = Nat.card {x : K // p x ∧ σ x = x} := by
    apply Nat.card_congr
    refine ⟨fun y => ⟨y.1.1, y.1.2, ?_⟩, fun x => ⟨⟨x.1, x.2.1⟩, ?_⟩, ?_, ?_⟩
    · have := congrArg Subtype.val y.2
      rwa [hπcoe] at this
    · exact Subtype.ext x.2.2
    · intro y; ext; rfl
    · intro x; rfl
  rw [h2] at hmod
  exact hmod

/-- If a `σ`-invariant predicate holds on a set of elements whose cardinality
is not divisible by `5`, then it holds at a `σ`-fixed element. -/
theorem exists_fixed_of_five {K : Type*} [Group K] [Finite K] (σ : MulAut K)
    (h5 : ∀ x, σ (σ (σ (σ (σ x)))) = x) (p : K → Prop) (hp : ∀ x, p x → p (σ x))
    (hcard : ¬ (5 ∣ Nat.card {x : K // p x})) : ∃ x, p x ∧ σ x = x := by
  by_contra hcon
  haveI hempty : IsEmpty {x : K // p x ∧ σ x = x} := ⟨fun y => hcon ⟨y.1, y.2⟩⟩
  have h0 : Nat.card {x : K // p x ∧ σ x = x} = 0 := Nat.card_of_isEmpty
  have hmod := mulAut_five_card_modEq σ h5 p hp
  rw [h0] at hmod
  exact hcard (Nat.modEq_zero_iff_dvd.mp hmod)

/-- **No fixed-point-free automorphism of order dividing `5`** on a group where
the number of elements `x` with `x ^ m = 1` and `x ^ d ≠ 1` is not divisible by
`5`.  (Applied with `(m, d) = (2, 1)` — involutions — for twelve of the
thirteen non-`(C₂)⁴` order-`16` groups, and `(m, d) = (8, 4)` — order-`8`
elements — for `SD₁₆`, which has exactly `5` involutions.) -/
theorem no_fpf_of_pow_count {K : Type*} [Group K] [Finite K] (σ : MulAut K)
    (h5 : ∀ x, σ (σ (σ (σ (σ x)))) = x) (hfpf : ∀ x, σ x = x → x = 1) (m d : ℕ)
    (hcard : ¬ (5 ∣ Nat.card {x : K // x ^ m = 1 ∧ x ^ d ≠ 1})) : False := by
  obtain ⟨x, ⟨hx1, hx2⟩, hfix⟩ := exists_fixed_of_five σ h5 _
    (fun y hy => ⟨by rw [← map_pow, hy.1, map_one],
      fun h => hy.2 (σ.injective (by rw [← map_pow] at h; rw [h, map_one]))⟩) hcard
  exact hx2 (by rw [hfpf x hfix, one_pow])

/-! ### Homomorphisms out of `C₅` -/

/-- The generator of `C₅ = Multiplicative (ZMod 5)`. -/
private noncomputable abbrev c5gen : Multiplicative (ZMod 5) :=
  Multiplicative.ofAdd (1 : ZMod 5)

private theorem c5gen_pow_five : c5gen ^ 5 = 1 := by decide

private theorem c5gen_ne_one : c5gen ≠ 1 := by decide

/-- A hom out of `C₅` into any group, sending the generator to a chosen
order-dividing-`5` element. -/
noncomputable def C5_powHom {H : Type*} [Group H] (A : H) (hA : A ^ 5 = 1) :
    Multiplicative (ZMod 5) →* H :=
  MonoidHom.mk' (fun x => A ^ (Multiplicative.toAdd x).val) (by
    intro x y
    change A ^ (Multiplicative.toAdd (x * y)).val =
      A ^ (Multiplicative.toAdd x).val * A ^ (Multiplicative.toAdd y).val
    rw [← pow_add]
    have hval : (Multiplicative.toAdd (x * y)).val =
        ((Multiplicative.toAdd x).val + (Multiplicative.toAdd y).val) % 5 := by
      change (Multiplicative.toAdd x + Multiplicative.toAdd y).val = _
      rw [ZMod.val_add]
    rw [hval, ← Nat.div_add_mod ((Multiplicative.toAdd x).val + (Multiplicative.toAdd y).val) 5,
      pow_add, pow_mul, hA, one_pow, one_mul]
    congr 1
    omega)

theorem C5_powHom_gen {H : Type*} [Group H] (A : H) (hA : A ^ 5 = 1) :
    C5_powHom A hA c5gen = A := by
  change A ^ (Multiplicative.toAdd (Multiplicative.ofAdd (1 : ZMod 5))).val = A
  norm_num [ZMod.val_one]

/-- Applying a power of an automorphism. -/
private theorem mulAut_pow_five_apply {K : Type*} [Group K] (f : MulAut K) (x : K) :
    (f ^ 5) x = f (f (f (f (f x)))) := by
  have h : f ^ 5 = f * f * f * f * f := by
    rw [pow_succ, pow_succ, pow_succ, pow_succ, pow_one]
  rw [h]
  rfl

/-- The generator of `C₅` acts through `φ` by an automorphism of order
dividing `5` (pointwise form). -/
theorem actionC5_gen_five_apply {K : Type*} [Group K]
    (φ : Multiplicative (ZMod 5) →* MulAut K) (x : K) :
    φ c5gen (φ c5gen (φ c5gen (φ c5gen (φ c5gen x)))) = x := by
  have hpow : φ c5gen ^ 5 = 1 := by rw [← map_pow, c5gen_pow_five, map_one]
  rw [← mulAut_pow_five_apply, hpow, MulAut.one_apply]

/-! ### Fixed-point-freeness from `n₅ = 16`

In `H = K ⋊[φ] C₅` with `n₅ = 16`, the Sylow-`5` subgroup `Q = ⟨inr c⟩` is
self-normalising (`|N(Q)| = 80 / 16 = 5`).  A nontrivial `φ(c)`-fixed point
`x ∈ K` yields an involution `z ∈ ⟨x⟩` with `inl z` centralising, hence
normalising, `Q` — an involution in a group of order `5`, contradiction. -/

theorem order80_sixteen_sylow_fpf {K : Type*} [Group K] [Finite K] (hK : Nat.card K = 16)
    (φ : Multiplicative (ZMod 5) →* MulAut K)
    (hSyl : Nat.card (Sylow 5 (SemidirectProduct K (Multiplicative (ZMod 5)) φ)) = 16) :
    ∀ x : K, φ c5gen x = x → x = 1 := by
  intro x hx
  by_contra hne
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  set H := SemidirectProduct K (Multiplicative (ZMod 5)) φ with hH
  haveI : Finite H := Finite.of_equiv _ SemidirectProduct.equivProd.symm
  have hcardH : Nat.card H = 80 := by
    rw [hH, SemidirectProduct.card, hK, Nat.card_eq_fintype_card]
    decide
  -- an involution z in ⟨x⟩ fixed by φ(c)
  have hdvd : orderOf x ∣ 16 := hK ▸ orderOf_dvd_natCard x
  have hdvd16 : orderOf x ∣ 2 ^ 4 := by
    rw [show (2 : ℕ) ^ 4 = 16 by norm_num]
    exact hdvd
  obtain ⟨i, hile, hord⟩ := (Nat.dvd_prime_pow Nat.prime_two).mp hdvd16
  have hipos : 1 ≤ i := by
    rcases Nat.eq_zero_or_pos i with h0 | h1
    · exfalso; apply hne; rw [← orderOf_eq_one_iff, hord, h0, pow_zero]
    · exact h1
  set z := x ^ (2 ^ (i - 1)) with hz
  have hz2 : z * z = 1 := by
    rw [hz, ← pow_add, ← two_mul, ← pow_succ']
    have : i - 1 + 1 = i := by omega
    rw [this, ← hord]
    exact pow_orderOf_eq_one x
  have hz1 : z ≠ 1 := by
    intro h
    have hdvd2 : orderOf x ∣ 2 ^ (i - 1) := orderOf_dvd_of_pow_eq_one h
    rw [hord] at hdvd2
    have := (Nat.pow_dvd_pow_iff_le_right (by norm_num : 1 < 2)).mp hdvd2
    omega
  have hzfix : φ c5gen z = z := by rw [hz, map_pow, hx]
  -- inl z commutes with inr c
  have haut := SemidirectProduct.inl_aut (φ := φ) c5gen z
  rw [hzfix, map_inv] at haut
  have hcomm1 : (SemidirectProduct.inl z : H) * SemidirectProduct.inr c5gen
      = SemidirectProduct.inr c5gen * SemidirectProduct.inl z := by
    conv_lhs => rw [haut]
    exact inv_mul_cancel_right _ _
  -- the Sylow-5 subgroup ⟨inr c⟩ and its normaliser
  have horder : orderOf (SemidirectProduct.inr c5gen : H) = 5 := by
    rw [orderOf_injective (SemidirectProduct.inr (φ := φ)) SemidirectProduct.inr_injective]
    exact orderOf_eq_prime c5gen_pow_five c5gen_ne_one
  have hzpcard : Nat.card (Subgroup.zpowers (SemidirectProduct.inr c5gen : H)) = 5 := by
    rw [Nat.card_zpowers, horder]
  have hzp : IsPGroup 5 (Subgroup.zpowers (SemidirectProduct.inr c5gen : H)) :=
    IsPGroup.of_card (by rw [hzpcard, pow_one])
  obtain ⟨Q, hle⟩ := hzp.exists_le_sylow
  have hQ5 : Nat.card (↑Q : Subgroup H) = 5 := card_sylow_five_subgroup_of_card_80 hcardH Q
  have heqzp : Subgroup.zpowers (SemidirectProduct.inr c5gen : H) = ↑Q :=
    eq_of_le_of_card_eq hle (by rw [hzpcard, hQ5])
  haveI : Finite (Sylow 5 H) := Nat.finite_of_card_ne_zero (by rw [hSyl]; norm_num)
  have hidx : (Subgroup.normalizer (Q : Set H)).index = 16 := by
    rw [← Q.card_eq_index_normalizer]
    exact hSyl
  have hNcard : Nat.card (Subgroup.normalizer (Q : Set H)) = 5 := by
    have hmul := Subgroup.card_mul_index (Subgroup.normalizer (Q : Set H))
    rw [hidx, hcardH] at hmul
    omega
  have heqQN : (↑Q : Subgroup H) = Subgroup.normalizer (Q : Set H) := by
    apply eq_of_le_of_card_eq
    · rw [← Sylow.coe_coe]
      exact Subgroup.le_normalizer
    · rw [hQ5, hNcard]
  -- inl z normalises Q
  have hmemN : SemidirectProduct.inl z ∈ Subgroup.normalizer (Q : Set H) := by
    rw [← Sylow.coe_coe, ← heqzp, Subgroup.mem_normalizer_iff]
    intro h
    have hcz : Commute (SemidirectProduct.inl z : H) (SemidirectProduct.inr c5gen) := hcomm1
    constructor
    · intro hh
      obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hh
      rw [← hk, (hcz.zpow_right k).eq, mul_assoc, mul_inv_cancel, mul_one]
      exact Subgroup.mem_zpowers_iff.mpr ⟨k, rfl⟩
    · intro hh
      obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hh
      have hh2 : h = (SemidirectProduct.inr c5gen : H) ^ k := by
        have h1 : (SemidirectProduct.inl z : H)⁻¹ *
            ((SemidirectProduct.inr c5gen : H) ^ k) * SemidirectProduct.inl z = h := by
          rw [hk]; group
        rw [← h1, ((hcz.zpow_right k).inv_left).eq, mul_assoc, inv_mul_cancel, mul_one]
      rw [hh2]
      exact Subgroup.mem_zpowers_iff.mpr ⟨k, rfl⟩
  -- hence inl z ∈ Q = ⟨inr c⟩, so z = 1: contradiction
  have hzQ : SemidirectProduct.inl z ∈ Subgroup.zpowers (SemidirectProduct.inr c5gen : H) := by
    rw [heqzp, heqQN]
    exact hmemN
  obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hzQ
  have hleft := congrArg SemidirectProduct.left hk
  rw [← map_zpow, SemidirectProduct.left_inr, SemidirectProduct.left_inl] at hleft
  exact hz1 hleft.symm

/-! ### Fixed-point-freeness from mere nontriviality (on a group of order 16)

The fixed subgroup of an order-`5` automorphism of a group of order `16` has
order `≡ 16 ≡ 1 (mod 5)` dividing `16`, i.e. `1` or `16`. -/

private def fixedSubgroup {K : Type*} [Group K] (σ : MulAut K) : Subgroup K where
  carrier := {x | σ x = x}
  one_mem' := map_one σ
  mul_mem' := by
    intro a b ha hb
    simp only [Set.mem_setOf_eq] at *
    rw [map_mul, ha, hb]
  inv_mem' := by
    intro a ha
    simp only [Set.mem_setOf_eq] at *
    rw [map_inv, ha]

/-- A nontrivial automorphism of order dividing `5` of a group of order `16`
is fixed-point-free. -/
theorem fpf_of_ne_one {K : Type*} [Group K] [Finite K] (hK : Nat.card K = 16)
    (σ : MulAut K) (h5 : ∀ x, σ (σ (σ (σ (σ x)))) = x) (hσ : ∃ x, σ x ≠ x) :
    ∀ x : K, σ x = x → x = 1 := by
  have hmod : Nat.card K ≡ Nat.card {x : K // x ∈ fixedSubgroup σ} [MOD 5] := by
    have h := mulAut_five_card_modEq σ h5 (fun _ => True) (fun _ _ => trivial)
    have h1 : Nat.card {x : K // True} = Nat.card K :=
      Nat.card_congr (Equiv.subtypeUnivEquiv fun _ => trivial)
    have h2 : Nat.card {x : K // True ∧ σ x = x} = Nat.card {x : K // x ∈ fixedSubgroup σ} :=
      Nat.card_congr (Equiv.subtypeEquivRight fun x => by
        simp [fixedSubgroup, Subgroup.mem_mk, Set.mem_setOf_eq])
    rw [h1, h2] at h
    exact h
  set d := Nat.card {x : K // x ∈ fixedSubgroup σ} with hd
  have hdvd : d ∣ 16 := by
    rw [hd, ← hK]
    exact Subgroup.card_subgroup_dvd_card (fixedSubgroup σ)
  have hdmod : d % 5 = 1 := by
    rw [hK] at hmod
    unfold Nat.ModEq at hmod
    omega
  have hdpos : 0 < d := Nat.card_pos
  have hdle : d ≤ 16 := Nat.le_of_dvd (by norm_num) hdvd
  have hd116 : d = 1 ∨ d = 16 := by interval_cases d <;> omega
  rcases hd116 with h1 | h16
  · -- fixed subgroup is trivial
    intro x hx
    have hxF : x ∈ fixedSubgroup σ := hx
    have hbot : fixedSubgroup σ = ⊥ := Subgroup.card_eq_one.mp h1
    rw [hbot] at hxF
    exact Subgroup.mem_bot.mp hxF
  · -- fixed subgroup is everything: σ = 1, contradiction
    exfalso
    obtain ⟨x, hx⟩ := hσ
    have htop : fixedSubgroup σ = ⊤ :=
      Subgroup.eq_top_of_card_eq _ (by rw [← hd, h16, hK])
    apply hx
    have : x ∈ fixedSubgroup σ := by rw [htop]; exact Subgroup.mem_top x
    exact this

/-! ### The elementary abelian case: generators and the companion normal form -/

/-- The four coordinate generators of `(C₂)⁴`. -/
private noncomputable def K0g1 : order16_wild_C2pow4 := (Multiplicative.ofAdd 1, 1, 1, 1)
private noncomputable def K0g2 : order16_wild_C2pow4 := (1, Multiplicative.ofAdd 1, 1, 1)
private noncomputable def K0g3 : order16_wild_C2pow4 := (1, 1, Multiplicative.ofAdd 1, 1)
private noncomputable def K0g4 : order16_wild_C2pow4 := (1, 1, 1, Multiplicative.ofAdd 1)

private theorem K0g1_ne_one : K0g1 ≠ 1 := by decide

private theorem K0_pow_two (x : order16_wild_C2pow4) : x ^ 2 = 1 := by revert x; decide

private theorem K0_mul_self (x : order16_wild_C2pow4) : x * x = 1 := by revert x; decide

/-- Homomorphisms out of `(C₂)⁴` into any monoid are determined by the four
coordinate generators. -/
theorem k0_hom_ext {M : Type*} [Monoid M] {f g : order16_wild_C2pow4 →* M}
    (h1 : f K0g1 = g K0g1) (h2 : f K0g2 = g K0g2)
    (h3 : f K0g3 = g K0g3) (h4 : f K0g4 = g K0g4) : f = g := by
  apply MonoidHom.ext
  intro x
  have hx : x = K0g1 ^ (Multiplicative.toAdd x.1).val *
      (K0g2 ^ (Multiplicative.toAdd x.2.1).val *
        (K0g3 ^ (Multiplicative.toAdd x.2.2.1).val *
          K0g4 ^ (Multiplicative.toAdd x.2.2.2).val)) := by
    revert x; decide
  rw [hx]
  simp only [map_mul, map_pow, h1, h2, h3, h4]

/-- The homomorphism `(C₂)⁴ →* (C₂)⁴` determined by images `w₁, w₂, w₃, w₄` of
the four coordinate generators. -/
private noncomputable def K0_basisHom (w1 w2 w3 w4 : order16_wild_C2pow4) :
    order16_wild_C2pow4 →* order16_wild_C2pow4 :=
  (C2_powHom w1 (K0_pow_two w1)).coprod ((C2_powHom w2 (K0_pow_two w2)).coprod
    ((C2_powHom w3 (K0_pow_two w3)).coprod (C2_powHom w4 (K0_pow_two w4))))

private theorem C2_powHom_gen {H : Type*} [Group H] (B : H) (hB : B ^ 2 = 1) :
    C2_powHom B hB (Multiplicative.ofAdd (1 : ZMod 2)) = B := by
  change B ^ (Multiplicative.toAdd (Multiplicative.ofAdd (1 : ZMod 2))).val = B
  norm_num [ZMod.val_one]

private theorem K0_basisHom_g1 (w1 w2 w3 w4 : order16_wild_C2pow4) :
    K0_basisHom w1 w2 w3 w4 K0g1 = w1 := by
  simp [K0_basisHom, K0g1, MonoidHom.coprod_apply, C2_powHom_gen, map_one]

private theorem K0_basisHom_g2 (w1 w2 w3 w4 : order16_wild_C2pow4) :
    K0_basisHom w1 w2 w3 w4 K0g2 = w2 := by
  simp [K0_basisHom, K0g2, MonoidHom.coprod_apply, C2_powHom_gen, map_one]

private theorem K0_basisHom_g3 (w1 w2 w3 w4 : order16_wild_C2pow4) :
    K0_basisHom w1 w2 w3 w4 K0g3 = w3 := by
  simp [K0_basisHom, K0g3, MonoidHom.coprod_apply, C2_powHom_gen, map_one]

private theorem K0_basisHom_g4 (w1 w2 w3 w4 : order16_wild_C2pow4) :
    K0_basisHom w1 w2 w3 w4 K0g4 = w4 := by
  simp [K0_basisHom, K0g4, MonoidHom.coprod_apply, C2_powHom_gen, map_one]

/-- The companion automorphism `σ₀` of `x⁴ + x³ + x² + x + 1` on `(C₂)⁴`:
`e₁ ↦ e₂ ↦ e₃ ↦ e₄ ↦ e₁e₂e₃e₄`. -/
noncomputable def order80_nonnormal_sigma0 : order16_wild_C2pow4 ≃* order16_wild_C2pow4 where
  toFun p := (p.2.2.2, (p.1 * p.2.2.2, (p.2.1 * p.2.2.2, p.2.2.1 * p.2.2.2)))
  invFun q := (q.2.1 * q.1, (q.2.2.1 * q.1, (q.2.2.2 * q.1, q.1)))
  left_inv := by rintro ⟨a, b, c, d⟩; ext <;> revert a b c d <;> decide
  right_inv := by rintro ⟨a, b, c, d⟩; ext <;> revert a b c d <;> decide
  map_mul' := by
    rintro ⟨a, b, c, d⟩ ⟨a', b', c', d'⟩; ext <;> revert a b c d a' b' c' d' <;> decide

private theorem sigma0_five (p : order16_wild_C2pow4) :
    order80_nonnormal_sigma0 (order80_nonnormal_sigma0 (order80_nonnormal_sigma0
      (order80_nonnormal_sigma0 (order80_nonnormal_sigma0 p)))) = p := by
  revert p; decide

private theorem sigma0_g1 : order80_nonnormal_sigma0 K0g1 = K0g2 := by decide
private theorem sigma0_g2 : order80_nonnormal_sigma0 K0g2 = K0g3 := by decide
private theorem sigma0_g3 : order80_nonnormal_sigma0 K0g3 = K0g4 := by decide
private theorem sigma0_g4 :
    order80_nonnormal_sigma0 K0g4 = K0g1 * K0g2 * K0g3 * K0g4 := by decide

private theorem sigma0_pow5 :
    (order80_nonnormal_sigma0 : MulAut order16_wild_C2pow4) ^ 5 = 1 := by
  apply MulEquiv.ext
  intro x
  rw [mulAut_pow_five_apply]
  exact sigma0_five x

/-- The reference action `φ₀ : C₅ →* Aut (C₂)⁴`, sending the generator to the
companion automorphism `σ₀`. -/
noncomputable def order80_nonnormal_phi0 :
    Multiplicative (ZMod 5) →* MulAut order16_wild_C2pow4 :=
  C5_powHom (order80_nonnormal_sigma0 : MulAut order16_wild_C2pow4) sigma0_pow5

theorem order80_nonnormal_phi0_gen :
    order80_nonnormal_phi0 c5gen = (order80_nonnormal_sigma0 : MulAut order16_wild_C2pow4) :=
  C5_powHom_gen _ _

/-- **The unique group of order `80` with `n₅ = 16`.** -/
noncomputable abbrev order80_nonnormal_rep : Type :=
  SemidirectProduct order16_wild_C2pow4 (Multiplicative (ZMod 5)) order80_nonnormal_phi0

private theorem K0g1_conj_left_ne :
    (1 : order16_wild_C2pow4) ≠ (SemidirectProduct.inl K0g1 * SemidirectProduct.inr c5gen *
      (SemidirectProduct.inl K0g1)⁻¹ : order80_nonnormal_rep).left := by decide

/-! ### Uniqueness: all nontrivial actions give the same group -/

/-- **Uniqueness of the nontrivial semidirect product `(C₂)⁴ ⋊ C₅`.** Every
nontrivial action `φ : C₅ →* Aut (C₂)⁴` gives a semidirect product isomorphic
to the reference one.  The generator's automorphism `σ = φ(c)` is
fixed-point-free (its fixed subgroup has order `≡ 1 (mod 5)` dividing `16`,
and it is not everything), so for any `v ≠ 1` the orbit `v, σv, σ²v, σ³v`
generates a `σ`-invariant subgroup of order `≡ 1 (mod 5)`, i.e. all of
`(C₂)⁴`; the resulting basis change conjugates `σ` to the companion
automorphism `σ₀`. -/
theorem order80_nonnormal_unique
    (φ : Multiplicative (ZMod 5) →* MulAut order16_wild_C2pow4) (hφ : φ ≠ 1) :
    Nonempty (SemidirectProduct order16_wild_C2pow4 (Multiplicative (ZMod 5)) φ ≃*
      order80_nonnormal_rep) := by
  set σ : MulAut order16_wild_C2pow4 := φ c5gen with hσdef
  have h5σ : ∀ x, σ (σ (σ (σ (σ x)))) = x := actionC5_gen_five_apply φ
  have hK0card : Nat.card order16_wild_C2pow4 = 16 := by
    rw [Nat.card_eq_fintype_card]; decide
  -- σ ≠ 1, hence fixed-point-free
  have hex : ∃ x, σ x ≠ x := by
    by_contra hall
    apply hφ
    apply c5_hom_ext
    apply MulEquiv.ext
    intro x
    simp only [MonoidHom.one_apply, MulAut.one_apply]
    exact not_not.mp fun h => hall ⟨x, h⟩
  have hfpf : ∀ x, σ x = x → x = 1 := fpf_of_ne_one hK0card σ h5σ hex
  -- a nontrivial element and its orbit
  obtain ⟨v, hv1⟩ := exists_ne (1 : order16_wild_C2pow4)
  -- the norm of v is a fixed point, hence trivial
  have hNv : v * σ v * σ (σ v) * σ (σ (σ v)) * σ (σ (σ (σ v))) = 1 := by
    apply hfpf
    rw [map_mul, map_mul, map_mul, map_mul, h5σ v, mul_comm]
    simp only [mul_assoc]
  have hnorm4 : v * σ v * σ (σ v) * σ (σ (σ v)) = σ (σ (σ (σ v))) := by
    have h2 := K0_mul_self (σ (σ (σ (σ v))))
    exact mul_right_cancel (hNv.trans h2.symm)
  -- the orbit generates everything
  set S : Set order16_wild_C2pow4 :=
    {v, σ v, σ (σ v), σ (σ (σ v)), σ (σ (σ (σ v)))} with hSdef
  set W : Subgroup order16_wild_C2pow4 := Subgroup.closure S with hWdef
  have hSsub : ∀ s ∈ S, σ s ∈ S := by
    intro s hs
    simp only [hSdef, Set.mem_insert_iff, Set.mem_singleton_iff] at hs ⊢
    rcases hs with rfl | rfl | rfl | rfl | rfl
    · exact Or.inr (Or.inl rfl)
    · exact Or.inr (Or.inr (Or.inl rfl))
    · exact Or.inr (Or.inr (Or.inr (Or.inl rfl)))
    · exact Or.inr (Or.inr (Or.inr (Or.inr rfl)))
    · exact Or.inl (h5σ v)
  have hWinv : ∀ x, x ∈ W → σ x ∈ W := by
    have hle : W ≤ W.comap (σ : order16_wild_C2pow4 ≃* order16_wild_C2pow4).toMonoidHom := by
      rw [hWdef, Subgroup.closure_le]
      intro s hs
      exact Subgroup.mem_comap.mpr (Subgroup.subset_closure (hSsub s hs))
    intro x hx
    exact Subgroup.mem_comap.mp (hle hx)
  have hvW : v ∈ W := Subgroup.subset_closure (by simp [hSdef])
  have hWfix : Nat.card {x : order16_wild_C2pow4 // x ∈ W ∧ σ x = x} = 1 := by
    rw [Nat.card_eq_one_iff_unique]
    constructor
    · constructor
      rintro ⟨a, haW, hafix⟩ ⟨b, hbW, hbfix⟩
      have ha := hfpf a hafix
      have hb := hfpf b hbfix
      subst ha
      subst hb
      rfl
    · exact ⟨⟨1, W.one_mem, map_one σ⟩⟩
  have hWmod := mulAut_five_card_modEq σ h5σ (· ∈ W) hWinv
  rw [hWfix] at hWmod
  have hWdvd : Nat.card {x : order16_wild_C2pow4 // x ∈ W} ∣ 16 := by
    rw [← hK0card]
    exact Subgroup.card_subgroup_dvd_card W
  have hWne1 : Nat.card {x : order16_wild_C2pow4 // x ∈ W} ≠ 1 := by
    intro h1
    have hbot : W = ⊥ := Subgroup.card_eq_one.mp h1
    rw [hbot] at hvW
    exact hv1 (Subgroup.mem_bot.mp hvW)
  have hW16 : Nat.card {x : order16_wild_C2pow4 // x ∈ W} = 16 := by
    set d := Nat.card {x : order16_wild_C2pow4 // x ∈ W} with hddef
    have hdmod : d % 5 = 1 := by unfold Nat.ModEq at hWmod; omega
    have hdpos : 0 < d := Nat.card_pos
    have hdle : d ≤ 16 := Nat.le_of_dvd (by norm_num) hWdvd
    interval_cases d <;> omega
  have hWtop : W = ⊤ := Subgroup.eq_top_of_card_eq _ (by rw [hW16, hK0card])
  -- the basis-change homomorphism and its bijectivity
  set T : order16_wild_C2pow4 →* order16_wild_C2pow4 :=
    K0_basisHom v (σ v) (σ (σ v)) (σ (σ (σ v))) with hTdef
  have hTrange : T.range = ⊤ := by
    rw [eq_top_iff, ← hWtop, hWdef, Subgroup.closure_le]
    intro s hs
    simp only [hSdef, Set.mem_insert_iff, Set.mem_singleton_iff] at hs
    rcases hs with rfl | rfl | rfl | rfl | rfl
    · exact ⟨K0g1, K0_basisHom_g1 _ _ _ _⟩
    · exact ⟨K0g2, K0_basisHom_g2 _ _ _ _⟩
    · exact ⟨K0g3, K0_basisHom_g3 _ _ _ _⟩
    · exact ⟨K0g4, K0_basisHom_g4 _ _ _ _⟩
    · refine ⟨K0g1 * K0g2 * K0g3 * K0g4, ?_⟩
      rw [map_mul, map_mul, map_mul, K0_basisHom_g1, K0_basisHom_g2, K0_basisHom_g3,
        K0_basisHom_g4]
      exact hnorm4
  have hTsurj : Function.Surjective T := MonoidHom.range_eq_top.mp hTrange
  have hTbij : Function.Bijective T :=
    ⟨(Finite.injective_iff_surjective).mpr hTsurj, hTsurj⟩
  set τ : order16_wild_C2pow4 ≃* order16_wild_C2pow4 := MulEquiv.ofBijective T hTbij with hτdef
  -- the intertwining relation σ ∘ T = T ∘ σ₀
  have hcommHom : (σ : order16_wild_C2pow4 ≃* order16_wild_C2pow4).toMonoidHom.comp T
      = T.comp (order80_nonnormal_sigma0 :
          order16_wild_C2pow4 ≃* order16_wild_C2pow4).toMonoidHom := by
    apply k0_hom_ext
    · simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, sigma0_g1, hTdef,
        K0_basisHom_g1, K0_basisHom_g2]
    · simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, sigma0_g2, hTdef,
        K0_basisHom_g2, K0_basisHom_g3]
    · simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, sigma0_g3, hTdef,
        K0_basisHom_g3, K0_basisHom_g4]
    · simp only [MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, sigma0_g4, hTdef,
        K0_basisHom_g4]
      rw [map_mul, map_mul, map_mul, K0_basisHom_g1, K0_basisHom_g2, K0_basisHom_g3,
        K0_basisHom_g4]
      exact hnorm4.symm
  have hpt : ∀ y, σ (T y) = T (order80_nonnormal_sigma0 y) := by
    intro y
    have := DFunLike.congr_fun hcommHom y
    simpa using this
  -- conjugating φ₀ by τ gives φ
  have hact : (MulAut.conj (τ : MulAut order16_wild_C2pow4)).toMonoidHom.comp
      order80_nonnormal_phi0 = φ := by
    apply c5_hom_ext
    change MulAut.conj (τ : MulAut order16_wild_C2pow4) (order80_nonnormal_phi0 c5gen) = φ c5gen
    rw [order80_nonnormal_phi0_gen, ← hσdef, MulAut.conj_apply, mul_inv_eq_iff_eq_mul]
    apply MulEquiv.ext
    intro y
    rw [MulAut.mul_apply, MulAut.mul_apply]
    exact (hpt y).symm
  exact ⟨(semidirectProductCongr_eq hact.symm).trans
    (semidirectProductCongrConj (τ : MulAut order16_wild_C2pow4)).symm⟩

/-! ### The classification: exactly one group of order `80` with `n₅ = 16` -/

/-- **Classification of groups of order `80` with sixteen Sylow-`5`
subgroups.** Any such group is isomorphic to `(C₂)⁴ ⋊[φ₀] C₅`.  Together with
the `51` classes of `order80_normal_classification`, this completes the `52`
isomorphism classes of groups of order `80`. -/
theorem order80_sixteen_sylow_classification [Finite G] (hG : Nat.card G = 80)
    (hSyl : Nat.card (Sylow 5 G) = 16) :
    Nonempty (G ≃* order80_nonnormal_rep) := by
  obtain ⟨N, K, φ, _, hcardN, hcardK, ⟨e⟩⟩ :=
    order80_semidirectProduct_of_sylow_five_sixteen hG hSyl
  obtain ⟨eK⟩ := prime_classification (p := 5) (by norm_num) hcardK
  obtain ⟨i, ⟨eN⟩⟩ := order16_wild_classification (G := N) hcardN
  -- the transported Sylow-5 count and fixed-point-freeness, for each branch
  fin_cases i
  -- i = 0 : the elementary abelian branch — the surviving case
  · obtain ⟨eC⟩ := order16_A5_iso_concrete
    have e' := e.trans (SemidirectProduct.congr' (eN.trans eC) eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    refine ⟨e'.trans (order80_nonnormal_unique _ ?_).some⟩
    intro h1
    exact absurd (hfpf K0g1 (by rw [h1]; simp)) K0g1_ne_one
  -- i = 1 : C₈ × C₂ — 3 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G1)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 2 : SD₁₆ — 5 involutions, but 4 elements of order 8
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G2)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 8 4
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 3 : M₁₆ — 3 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G3)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 4 : D₁₆ — 9 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G4)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 5 : Q₁₆ — 1 involution
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G5)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 6 : C₁₆ — 1 involution
  · obtain ⟨eC⟩ := order16_A1_iso_concrete
    have e' := e.trans (SemidirectProduct.congr' (eN.trans eC) eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := Multiplicative (ZMod 16))
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 7 : C₄ × C₂ × C₂ — 7 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G7)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 8 : D₈ × C₂ — 11 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G8)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 9 : (C₄ × C₂) ⋊ C₂ (SmallGroup(16,3))
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G9)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 10 : the Pauli group C₄ ∘ D₈ — 7 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G10)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 11 : Q₈ × C₂ — 3 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G11)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 12 : C₄ ⋊ C₄ — 3 involutions
  · have e' := e.trans (SemidirectProduct.congr' eN eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf (K := order16_wild_G12)
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim
  -- i = 13 : C₄ × C₄ — 3 involutions
  · obtain ⟨eC⟩ := order16_A3_iso_concrete
    have e' := e.trans (SemidirectProduct.congr' (eN.trans eC) eK)
    have hSyl' := (card_sylow_of_mulEquiv 5 e').symm.trans hSyl
    have hfpf := order80_sixteen_sylow_fpf
      (K := Multiplicative (ZMod 4) × Multiplicative (ZMod 4))
      (by rw [Nat.card_eq_fintype_card]; decide) _ hSyl'
    exact (no_fpf_of_pow_count _ (actionC5_gen_five_apply _) hfpf 2 1
      (by rw [Nat.card_eq_fintype_card]; decide)).elim

/-! ### The representative really has `n₅ = 16` -/

theorem order80_nonnormal_rep_card : Nat.card order80_nonnormal_rep = 80 := by
  change Nat.card (SemidirectProduct _ _ _) = 80
  rw [SemidirectProduct.card, Nat.card_eq_fintype_card, Nat.card_eq_fintype_card]
  decide

/-- The representative `(C₂)⁴ ⋊[φ₀] C₅` has sixteen Sylow-`5` subgroups: its
Sylow-`5` subgroup `⟨inr c⟩` is not normal, since conjugating `inr c` by
`inl e₁` moves it out. -/
theorem order80_nonnormal_rep_sylow_five :
    Nat.card (Sylow 5 order80_nonnormal_rep) = 16 := by
  haveI : Fact (Nat.Prime 5) := ⟨by norm_num⟩
  haveI : Finite order80_nonnormal_rep :=
    Finite.of_equiv _ (SemidirectProduct.equivProd
      (N := order16_wild_C2pow4) (G := Multiplicative (ZMod 5))).symm
  rcases card_sylow_five_of_card_80 order80_nonnormal_rep_card with h1 | h16
  · exfalso
    -- the Sylow-5 subgroup would be normal
    have horder : orderOf (SemidirectProduct.inr c5gen : order80_nonnormal_rep) = 5 := by
      rw [orderOf_injective (SemidirectProduct.inr (φ := order80_nonnormal_phi0))
        SemidirectProduct.inr_injective]
      exact orderOf_eq_prime c5gen_pow_five c5gen_ne_one
    have hzpcard :
        Nat.card (Subgroup.zpowers (SemidirectProduct.inr c5gen : order80_nonnormal_rep)) = 5 := by
      rw [Nat.card_zpowers, horder]
    have hzp : IsPGroup 5
        (Subgroup.zpowers (SemidirectProduct.inr c5gen : order80_nonnormal_rep)) :=
      IsPGroup.of_card (by rw [hzpcard, pow_one])
    obtain ⟨Q, hle⟩ := hzp.exists_le_sylow
    have hQ5 : Nat.card (↑Q : Subgroup order80_nonnormal_rep) = 5 :=
      card_sylow_five_subgroup_of_card_80 order80_nonnormal_rep_card Q
    have heqzp : Subgroup.zpowers (SemidirectProduct.inr c5gen : order80_nonnormal_rep) = ↑Q :=
      eq_of_le_of_card_eq hle (by rw [hzpcard, hQ5])
    have hnorm := sylow_five_normal_of_card_sylow_five_eq_one h1 Q
    have hmem : SemidirectProduct.inr c5gen ∈ (↑Q : Subgroup order80_nonnormal_rep) := by
      rw [← heqzp]
      exact Subgroup.mem_zpowers _
    have hconj := hnorm.conj_mem _ hmem (SemidirectProduct.inl K0g1)
    rw [← heqzp] at hconj
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp hconj
    have hleft := congrArg SemidirectProduct.left hk
    rw [← map_zpow, SemidirectProduct.left_inr] at hleft
    exact K0g1_conj_left_ne hleft
  · exact h16

end Smallgroups.UsefulTheorems
