/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order32Certificate.CoverageOrbitParent14Reduction
import Smallgroups.UsefulTheorems.PGroupGeneration.QuadraticCocycle

/-!
# The quadratic-form interface for Parent 14

`SmallGroup(16,14)` is the elementary abelian group `(C₂)^4`.  This file identifies its
certified multiplication table with the multiplicative type tag of the four-dimensional
`F₂` vector space and transports the Parent 14 cocycles to quadratic maps on that space.

The seven-orbit computational certificate remains the source of the current completeness
theorem.  The definitions here are the structural boundary at which rank, radical and Arf
invariant arguments can progressively replace the remaining finite orbit computation.
-/

namespace Smallgroups.UsefulTheorems.Order32Certificate

open Smallgroups.UsefulTheorems.GF2Certificate

/-- The four-dimensional `F₂` vector space underlying Parent 14. -/
abbrev Parent14V := Fin 4 → F2

/-- Table index to the binary coordinates generated by table elements `1,2,3,4`. -/
def parent14ToMask : Fin 16 → Fin 16 :=
  ![0, 1, 2, 4, 8, 3, 5, 9, 6, 10, 12, 7, 11, 13, 14, 15]

/-- Inverse lookup from binary coordinates to the Parent 14 table index. -/
def parent14FromMask : Fin 16 → Fin 16 :=
  ![0, 1, 2, 5, 3, 6, 8, 11, 4, 7, 9, 12, 10, 13, 14, 15]

/-- The explicit group equivalence `SmallGroup(16,14) ≃ (C₂)^4`. -/
def parent14VectorMulEquiv :
    Order16Table.Q parent14Table ≃* Multiplicative Parent14V where
  toFun x := Multiplicative.ofAdd (coeffMask 4 (parent14ToMask x.val).val)
  invFun x := Order16Table.elem parent14Table (parent14FromMask (vecIndex 4 x.toAdd))
  left_inv := by decide +kernel
  right_inv := by decide +kernel
  map_mul' := by decide +kernel

/-- A Parent 14 `H²` coordinate vector, expressed as a cocycle on `(C₂)^4`. -/
def parent14VectorCocycle (c : Fin 10 → F2) :
    Multiplicative Parent14V → Multiplicative Parent14V → F2 :=
  fun x y => orbitP14HCocycle c (parent14VectorMulEquiv.symm x)
    (parent14VectorMulEquiv.symm y)

theorem parent14VectorCocycle_consistent (c : Fin 10 → F2) :
    IsCentralCocycle (parent14VectorCocycle c) :=
  (orbitP14HCocycle_consistent c).comp parent14VectorMulEquiv.symm.toMonoidHom

/-- The square quadratic map attached to a Parent 14 central extension. -/
def parent14Quadratic (c : Fin 10 → F2) : QuadraticMap F2 Parent14V F2 :=
  cocycleQuadratic (parent14VectorCocycle c) (parent14VectorCocycle_consistent c)

@[simp] theorem parent14Quadratic_apply (c : Fin 10 → F2) (x : Parent14V) :
    parent14Quadratic c x =
      parent14VectorCocycle c (Multiplicative.ofAdd x) (Multiplicative.ofAdd x) :=
  rfl

/-- Polarization of the Parent 14 square map is its cocycle commutator pairing. -/
theorem parent14Quadratic_polar (c : Fin 10 → F2) (x y : Parent14V) :
    QuadraticMap.polar (parent14Quadratic c) x y =
      cocycleCommutator (parent14VectorCocycle c) x y :=
  cocycleQuadratic_polar _ _ x y

/-- Coefficients of one of the seven certified Parent 14 orbit representatives. -/
def parent14QuadraticRepresentativeCoeff (o : Fin 7) : Fin 10 → F2 :=
  coeffMask 10 (orbitP14RepresentativeMask o)

@[simp] theorem parent14QuadraticRepresentativeCoeff_zero :
    parent14QuadraticRepresentativeCoeff 0 = 0 := by
  funext i
  simp [parent14QuadraticRepresentativeCoeff, orbitP14RepresentativeMask, coeffMask]

theorem parent14VectorCocycle_zero :
    parent14VectorCocycle (parent14QuadraticRepresentativeCoeff 0) = 0 := by
  rw [parent14QuadraticRepresentativeCoeff_zero]
  funext x y
  simp [parent14VectorCocycle, orbitP14HCocycle, Order16Table.hCocycle,
    Order16Table.decodeTwo, synthesizeTwo]

/-- The first of the seven normal forms is the zero quadratic map. -/
theorem parent14Quadratic_zero_normal_form :
    parent14Quadratic (parent14QuadraticRepresentativeCoeff 0) = 0 := by
  ext x
  change parent14VectorCocycle (parent14QuadraticRepresentativeCoeff 0)
      (Multiplicative.ofAdd x) (Multiplicative.ofAdd x) = 0
  rw [parent14VectorCocycle_zero]
  rfl

/-- Existing seven-orbit completeness, exposed next to the structural quadratic interface.
Future rank/radical/Arf proofs can refine this theorem without changing its consumers. -/
theorem parent14_extension_reduces_to_seven
    (f : Order16Table.Q parent14Table → Order16Table.Q parent14Table → F2)
    (hf : IsCentralCocycle f) :
    ∃ o : Fin 7, Nonempty (CocycleGroup f hf ≃*
      CocycleGroup (orbitP14SelectedCocycle o) (orbitP14SelectedCocycle_consistent o)) :=
  orbitP14_cocycle_orbit_complete f hf

end Smallgroups.UsefulTheorems.Order32Certificate
