/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order32Certificate.CoverageOrbitParent14Core
import Smallgroups.UsefulTheorems.PGroupGeneration.QuadraticCocycle

/-!
# The quadratic-form interface for Parent 14

`SmallGroup(16,14)` is the elementary abelian group `(C₂)^4`.  This file identifies its
certified multiplication table with the multiplicative type tag of the four-dimensional
`F₂` vector space and transports the Parent 14 cocycles to quadratic maps on that space.

This interface depends only on the checked cocycle basis and orbit core.  It is independent
of the forest reduction and GAP alignments, so structural classification theorems can be
proved here and then used by the reduction theorem without creating an import cycle.
-/

namespace Smallgroups.UsefulTheorems.Order32Certificate

open Smallgroups.UsefulTheorems.GF2Certificate

/-- The four-dimensional `F₂` vector space underlying Parent 14. -/
abbrev Parent14V := Fin 4 → F2

/-- Table index to the binary coordinates generated by table elements `1,2,3,4`. -/
def parent14ToMask : Fin 16 → Fin 16 :=
  ![0, 1, 2, 4, 8, 3, 5, 9, 6, 10, 12, 7, 11, 13, 14, 15]

/-- Inverse lookup from binary coordinates to the Parent 14 table index. -/
def parent14FromMask : Fin 16 → Fin 16 :=
  ![0, 1, 2, 5, 3, 6, 8, 11, 4, 7, 9, 12, 10, 13, 14, 15]

/-- The explicit group equivalence `SmallGroup(16,14) ≃ (C₂)^4`. -/
def parent14VectorMulEquiv :
    Order16Table.Q parent14Table ≃* Multiplicative Parent14V where
  toFun x := Multiplicative.ofAdd (coeffMask 4 (parent14ToMask x.val).val)
  invFun x := Order16Table.elem parent14Table (parent14FromMask (vecIndex 4 x.toAdd))
  left_inv := by decide +kernel
  right_inv := by decide +kernel
  map_mul' := by decide +kernel

/-- A Parent 14 `H²` coordinate vector, expressed as a cocycle on `(C₂)^4`. -/
def parent14VectorCocycle (c : Fin 10 → F2) :
    Multiplicative Parent14V → Multiplicative Parent14V → F2 :=
  fun x y => Order16Table.hCocycle parent14Table parent14HBasis c (parent14VectorMulEquiv.symm x)
    (parent14VectorMulEquiv.symm y)

theorem parent14VectorCocycle_consistent (c : Fin 10 → F2) :
    IsCentralCocycle (parent14VectorCocycle c) :=
  (Order16Table.hCocycle_consistent parent14Table parent14HBasis
    orbitP14_hbasis_cocycle c).comp parent14VectorMulEquiv.symm.toMonoidHom

/-- The square quadratic map attached to a Parent 14 central extension. -/
def parent14Quadratic (c : Fin 10 → F2) : QuadraticMap F2 Parent14V F2 :=
  cocycleQuadratic (parent14VectorCocycle c) (parent14VectorCocycle_consistent c)

@[simp] theorem parent14Quadratic_apply (c : Fin 10 → F2) (x : Parent14V) :
    parent14Quadratic c x =
      parent14VectorCocycle c (Multiplicative.ofAdd x) (Multiplicative.ofAdd x) :=
  rfl

/-- Polarization of the Parent 14 square map is its cocycle commutator pairing. -/
theorem parent14Quadratic_polar (c : Fin 10 → F2) (x y : Parent14V) :
    QuadraticMap.polar (parent14Quadratic c) x y =
      cocycleCommutator (parent14VectorCocycle c) x y :=
  cocycleQuadratic_polar _ _ x y

/-- Coefficients of one of the seven certified Parent 14 orbit representatives. -/
def parent14QuadraticRepresentativeCoeff (o : Fin 7) : Fin 10 → F2 :=
  coeffMask 10 (orbitP14RepresentativeMask o)

@[simp] theorem parent14QuadraticRepresentativeCoeff_zero :
    parent14QuadraticRepresentativeCoeff 0 = 0 := by
  funext i
  simp [parent14QuadraticRepresentativeCoeff, orbitP14RepresentativeMask, coeffMask]

theorem parent14VectorCocycle_zero :
    parent14VectorCocycle (parent14QuadraticRepresentativeCoeff 0) = 0 := by
  rw [parent14QuadraticRepresentativeCoeff_zero]
  funext x y
  simp [parent14VectorCocycle, Order16Table.hCocycle,
    Order16Table.decodeTwo, synthesizeTwo]

/-- The first of the seven normal forms is the zero quadratic map. -/
theorem parent14Quadratic_zero_normal_form :
    parent14Quadratic (parent14QuadraticRepresentativeCoeff 0) = 0 := by
  ext x
  change parent14VectorCocycle (parent14QuadraticRepresentativeCoeff 0)
      (Multiplicative.ofAdd x) (Multiplicative.ofAdd x) = 0
  rw [parent14VectorCocycle_zero]
  rfl

end Smallgroups.UsefulTheorems.Order32Certificate
