/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Imported.Order1
import Smallgroups.GAP.Polycyclic.Imported.Order2
import Smallgroups.GAP.Polycyclic.Imported.Order4
import Smallgroups.GAP.Polycyclic.Imported.Order8
import Smallgroups.GAP.Polycyclic.Imported.Order4Match
import Smallgroups.GAP.Polycyclic.Imported.Order8Match
import Smallgroups.GAP.Polycyclic.Imported.Order9Match
import Smallgroups.GAP.Polycyclic.Imported.Order9
import Smallgroups.GAP.Polycyclic.Imported.Order16
import Smallgroups.GAP.Polycyclic.Imported.Order16Match
import Smallgroups.GAP.Polycyclic.Imported.Order25
import Smallgroups.GAP.Polycyclic.Imported.Order27
import Smallgroups.GAP.Polycyclic.Imported.Order25Match
import Smallgroups.GAP.Polycyclic.Imported.Order27Match
import Smallgroups.GAP.Polycyclic.Imported.Order49
import Smallgroups.GAP.Polycyclic.Imported.Order49Match

/-!
# Imported pc presentations from the GAP SmallGroups library

Generated by `Scripts/translate_pc.py` (do not edit the `OrderN.lean` files by
hand).  `OrderN.lean` contains the pc presentation `smallGroup_N_j` of every
`SmallGroup(N, j)`; `OrderNMatch.lean` files identify the imported groups with the
project's existing representatives.
-/
