/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.GAP.Polycyclic.Imported.Order1
import Smallgroups.GAP.Polycyclic.Imported.Order2
import Smallgroups.GAP.Polycyclic.Imported.Order4
import Smallgroups.GAP.Polycyclic.Imported.Order4Match
import Smallgroups.GAP.Polycyclic.Imported.Order6
import Smallgroups.GAP.Polycyclic.Imported.Order6Match
import Smallgroups.GAP.Polycyclic.Imported.Order8
import Smallgroups.GAP.Polycyclic.Imported.Order8Match
import Smallgroups.GAP.Polycyclic.Imported.Order9
import Smallgroups.GAP.Polycyclic.Imported.Order9Match
import Smallgroups.GAP.Polycyclic.Imported.Order10
import Smallgroups.GAP.Polycyclic.Imported.Order10Match
import Smallgroups.GAP.Polycyclic.Imported.Order14
import Smallgroups.GAP.Polycyclic.Imported.Order14Match
import Smallgroups.GAP.Polycyclic.Imported.Order15
import Smallgroups.GAP.Polycyclic.Imported.Order15Match
import Smallgroups.GAP.Polycyclic.Imported.Order16
import Smallgroups.GAP.Polycyclic.Imported.Order16Match
import Smallgroups.GAP.Polycyclic.Imported.Order21
import Smallgroups.GAP.Polycyclic.Imported.Order21Match
import Smallgroups.GAP.Polycyclic.Imported.Order22
import Smallgroups.GAP.Polycyclic.Imported.Order22Match
import Smallgroups.GAP.Polycyclic.Imported.Order25
import Smallgroups.GAP.Polycyclic.Imported.Order25Match
import Smallgroups.GAP.Polycyclic.Imported.Order26
import Smallgroups.GAP.Polycyclic.Imported.Order26Match
import Smallgroups.GAP.Polycyclic.Imported.Order27
import Smallgroups.GAP.Polycyclic.Imported.Order27Match
import Smallgroups.GAP.Polycyclic.Imported.Order33
import Smallgroups.GAP.Polycyclic.Imported.Order33Match
import Smallgroups.GAP.Polycyclic.Imported.Order34
import Smallgroups.GAP.Polycyclic.Imported.Order34Match
import Smallgroups.GAP.Polycyclic.Imported.Order35
import Smallgroups.GAP.Polycyclic.Imported.Order35Match
import Smallgroups.GAP.Polycyclic.Imported.Order38
import Smallgroups.GAP.Polycyclic.Imported.Order38Match
import Smallgroups.GAP.Polycyclic.Imported.Order39
import Smallgroups.GAP.Polycyclic.Imported.Order39Match
import Smallgroups.GAP.Polycyclic.Imported.Order46
import Smallgroups.GAP.Polycyclic.Imported.Order46Match
import Smallgroups.GAP.Polycyclic.Imported.Order49
import Smallgroups.GAP.Polycyclic.Imported.Order49Match
import Smallgroups.GAP.Polycyclic.Imported.Order51
import Smallgroups.GAP.Polycyclic.Imported.Order51Match
import Smallgroups.GAP.Polycyclic.Imported.Order55
import Smallgroups.GAP.Polycyclic.Imported.Order55Match
import Smallgroups.GAP.Polycyclic.Imported.Order57
import Smallgroups.GAP.Polycyclic.Imported.Order57Match
import Smallgroups.GAP.Polycyclic.Imported.Order58
import Smallgroups.GAP.Polycyclic.Imported.Order58Match
import Smallgroups.GAP.Polycyclic.Imported.Order62
import Smallgroups.GAP.Polycyclic.Imported.Order62Match
import Smallgroups.GAP.Polycyclic.Imported.Order65
import Smallgroups.GAP.Polycyclic.Imported.Order65Match
import Smallgroups.GAP.Polycyclic.Imported.Order69
import Smallgroups.GAP.Polycyclic.Imported.Order69Match
import Smallgroups.GAP.Polycyclic.Imported.Order74
import Smallgroups.GAP.Polycyclic.Imported.Order74Match
import Smallgroups.GAP.Polycyclic.Imported.Order77
import Smallgroups.GAP.Polycyclic.Imported.Order77Match
import Smallgroups.GAP.Polycyclic.Imported.Order82
import Smallgroups.GAP.Polycyclic.Imported.Order82Match
import Smallgroups.GAP.Polycyclic.Imported.Order85
import Smallgroups.GAP.Polycyclic.Imported.Order85Match
import Smallgroups.GAP.Polycyclic.Imported.Order86
import Smallgroups.GAP.Polycyclic.Imported.Order86Match
import Smallgroups.GAP.Polycyclic.Imported.Order87
import Smallgroups.GAP.Polycyclic.Imported.Order87Match
import Smallgroups.GAP.Polycyclic.Imported.Order91
import Smallgroups.GAP.Polycyclic.Imported.Order91Match
import Smallgroups.GAP.Polycyclic.Imported.Order93
import Smallgroups.GAP.Polycyclic.Imported.Order93Match
import Smallgroups.GAP.Polycyclic.Imported.Order94
import Smallgroups.GAP.Polycyclic.Imported.Order94Match
import Smallgroups.GAP.Polycyclic.Imported.Order95
import Smallgroups.GAP.Polycyclic.Imported.Order95Match

/-!
# Imported pc presentations from the GAP SmallGroups library

Generated by `Scripts/translate_pc.py` (do not edit the `OrderN.lean` files by
hand).  `OrderN.lean` contains the pc presentation `smallGroup_N_j` of every
`SmallGroup(N, j)`; `OrderNMatch.lean` files identify the imported groups with the
project's existing representatives.
-/
