#!/usr/bin/env python3
"""Generate GAP match and classification modules for squarefree prime-pair orders.

The pc presentations themselves are generated by ``translate_pc.py``.  This
script handles the two uniform families used by the existing classifications:

* odd ``p*q`` with ``q < p``;
* ``2*p`` with ``p`` odd.

For cyclic groups, the two pc generators are sent explicitly to ``p`` and
``q`` in ``ZMod (p*q)``.  For the nonabelian odd-prime-pair groups, the GAP pc
group is proved noncommutative by ``decide`` and the existing complete
classification then supplies its isomorphism to the project's representative.
"""

from pathlib import Path


REPO = Path(__file__).resolve().parent.parent

ODD_PRIME_PAIRS = [
    (15, 5, 3, False),
    (21, 7, 3, True),
    (33, 11, 3, False),
    (35, 7, 5, False),
    (39, 13, 3, True),
    (51, 17, 3, False),
    (55, 11, 5, True),
    (57, 19, 3, True),
    (65, 13, 5, False),
    (69, 23, 3, False),
    (77, 11, 7, False),
    (85, 17, 5, False),
    (87, 29, 3, False),
    (91, 13, 7, False),
    (93, 31, 3, True),
    (95, 19, 5, False),
]

TWO_PRIME = [
    (14, 7),
    (22, 11),
    (26, 13),
    (34, 17),
    (38, 19),
    (46, 23),
    (58, 29),
    (62, 31),
    (74, 37),
    (82, 41),
    (86, 43),
    (94, 47),
]

HEADER = """\
/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
"""


def decade(n: int) -> tuple[int, int]:
    lo = ((n - 1) // 10) * 10 + 1
    return lo, lo + 9


def original_module(n: int) -> str:
    lo, hi = decade(n)
    return f"Smallgroups.Classifications.Classifications_{lo}_to_{hi}.Order{n}"


def gap_dir(n: int) -> Path:
    lo, hi = decade(n)
    return REPO / "Smallgroups" / "GAP_Classifications" / f"GAP_{lo}_to_{hi}"


def odd_match(n: int, p: int, q: int, nonabelian: bool) -> str:
    if not nonabelian:
        body = f"""\
set_option maxRecDepth 10000 in
set_option maxHeartbeats 2000000 in
-- The finite homomorphism and bijectivity checks need larger reduction limits.
/-- `SmallGroup({n}, 1) = ℤ/{n}`, mapping the order-`{q}` generator to `{p}`
and the order-`{p}` generator to `{q}`. -/
noncomputable def order{n}_1_equiv :
    PCGroup smallGroup_{n}_1 ≃* CyclicRep {n} :=
  mulEquivOfDecide
    (pcEval [sg{n}_1_L1, sg{n}_1_L2]
      [Multiplicative.ofAdd {p}, Multiplicative.ofAdd {q}])
"""
        description = (
            f"The unique group `SmallGroup({n}, 1)` is cyclic.  Its isomorphism\n"
            "to the existing representative is certified by an explicit pc-generator map."
        )
    else:
        body = f"""\
/-- The first GAP group of order `{n}` is noncommutative. -/
theorem order{n}_1_not_comm :
    ¬ ∀ a b : PCGroup smallGroup_{n}_1, a * b = b * a := by
  intro h
  have hne :
      (pcGens [sg{n}_1_L1, sg{n}_1_L2])[0] *
          (pcGens [sg{n}_1_L1, sg{n}_1_L2])[1] ≠
        (pcGens [sg{n}_1_L1, sg{n}_1_L2])[1] *
          (pcGens [sg{n}_1_L1, sg{n}_1_L2])[0] := by decide
  exact hne (h _ _)

/-- `SmallGroup({n}, 1)` is the nonabelian representative from the existing
order-`{n}` classification. -/
noncomputable def order{n}_1_equiv :
    PCGroup smallGroup_{n}_1 ≃*
      Smallgroups.Classifications.Order{n}.NonabRep{n} :=
  Classical.choice (by
    rcases Smallgroups.Classifications.Order{n}.classification
        card_smallGroup_{n}_1 with hcyc | hnonab
    · exfalso
      apply order{n}_1_not_comm
      intro a b
      apply hcyc.some.injective
      simpa only [map_mul] using mul_comm (hcyc.some a) (hcyc.some b)
    · exact hnonab)

set_option maxRecDepth 10000 in
set_option maxHeartbeats 2000000 in
-- The finite homomorphism and bijectivity checks need larger reduction limits.
/-- `SmallGroup({n}, 2) = ℤ/{n}`, mapping the order-`{q}` generator to `{p}`
and the order-`{p}` generator to `{q}`. -/
noncomputable def order{n}_2_equiv :
    PCGroup smallGroup_{n}_2 ≃* CyclicRep {n} :=
  mulEquivOfDecide
    (pcEval [sg{n}_2_L1, sg{n}_2_L2]
      [Multiplicative.ofAdd {p}, Multiplicative.ofAdd {q}])
"""
        description = (
            f"`SmallGroup({n}, 1)` is nonabelian and `SmallGroup({n}, 2)` is "
            f"cyclic.\nNoncommutativity of the first pc group is checked on its two "
            "generators; the existing\ncomplete classification supplies its isomorphism to the "
            "project's noncomputably\nchosen semidirect-product representative."
        )
    return f"""{HEADER}import Smallgroups.GAP.Polycyclic.Imported.Order{n}
import {original_module(n)}

/-!
# Verification: order `{n}` — GAP pc groups match the existing representatives

{description}
-/

namespace Smallgroups.GAP

open Smallgroups.UsefulTheorems

{body}
end Smallgroups.GAP
"""


def two_prime_match(n: int, p: int) -> str:
    return f"""{HEADER}import Smallgroups.GAP.Polycyclic.Imported.Order{n}
import {original_module(n)}

/-!
# Verification: order `{n}` — GAP pc groups match the existing representatives

`SmallGroup({n}, 1) = DihedralGroup {p}` and `SmallGroup({n}, 2) = ℤ/{n}`.
This reverses the project's existing cyclic/dihedral representative order.
-/

namespace Smallgroups.GAP

open Smallgroups.UsefulTheorems

set_option maxRecDepth 10000 in
set_option maxHeartbeats 2000000 in
-- The finite homomorphism and bijectivity checks need larger reduction limits.
/-- `SmallGroup({n}, 1) = DihedralGroup {p}`, mapping the order-two generator
to a reflection and the order-`{p}` generator to a rotation. -/
noncomputable def order{n}_1_equiv :
    PCGroup smallGroup_{n}_1 ≃* DihedralGroup {p} :=
  mulEquivOfDecide
    (pcEval [sg{n}_1_L1, sg{n}_1_L2]
      [DihedralGroup.sr 0, DihedralGroup.r 1])

set_option maxRecDepth 10000 in
set_option maxHeartbeats 2000000 in
-- The finite homomorphism and bijectivity checks need larger reduction limits.
/-- `SmallGroup({n}, 2) = ℤ/{n}`, mapping the order-two generator to `{p}` and
the order-`{p}` generator to `2`. -/
noncomputable def order{n}_2_equiv :
    PCGroup smallGroup_{n}_2 ≃* CyclicRep {n} :=
  mulEquivOfDecide
    (pcEval [sg{n}_2_L1, sg{n}_2_L2]
      [Multiplicative.ofAdd {p}, Multiplicative.ofAdd 2])

end Smallgroups.GAP
"""


def single_classification(n: int) -> str:
    count = 1
    gap_rep = f"rep1 (smallGroup {n} 1)"
    target = f"rep1 (CyclicRep {n})"
    equiv_cases = f"  | 0 => order{n}_1_equiv"
    permutation = ""
    order_text = f"`SmallGroup({n}, 1) = ℤ/{n}`."
    list_text = f"`[SmallGroup({n}, 1)]`"
    return classification_file(
        n, count, gap_rep, target, equiv_cases, permutation, order_text, list_text
    )


def two_classification(n: int, second_type: str, order_text: str) -> str:
    gap_rep = f"rep2 (smallGroup {n} 1) (smallGroup {n} 2)"
    target = f"rep2 (CyclicRep {n}) ({second_type})"
    equiv_cases = f"  | 0 => order{n}_1_equiv\n  | 1 => order{n}_2_equiv"
    permutation = """\
/-- Swapping the existing list puts it in GAP order. -/
private def swap : Fin 2 ≃ Fin 2 := Equiv.swap 0 1

"""
    return classification_file(
        n,
        2,
        gap_rep,
        target,
        equiv_cases,
        permutation,
        order_text,
        f"`[SmallGroup({n}, 1), SmallGroup({n}, 2)]`",
    )


def classification_file(
    n: int,
    count: int,
    gap_rep: str,
    target: str,
    equiv_cases: str,
    permutation: str,
    order_text: str,
    list_text: str,
) -> str:
    perm_arg = " (swap i)" if count == 2 else " i"
    base = (
        f"IsClassif.of_perm Smallgroups.Classifications.Order{n}.isClassif swap"
        if count == 2
        else f"Smallgroups.Classifications.Order{n}.isClassif"
    )
    match_kind = "permuted " if count == 2 else ""
    return f"""{HEADER}import Smallgroups.GAP.SmallGroup
import Smallgroups.GAP.Polycyclic.Imported.Order{n}Match
import {original_module(n)}

/-!
# GAP-numbered classification of groups of order {n}

{order_text}
The representatives are the imported pc groups `smallGroup {n} j`.
-/

namespace Smallgroups.GAP_Classifications.Order{n}

open Smallgroups.GAP Smallgroups.UsefulTheorems

/-- The GAP-numbered representatives of order `{n}`. -/
abbrev gapRep : Fin {count} → Type := {gap_rep}

{permutation}/-- The GAP representatives match the {match_kind}existing list. -/
private noncomputable def gapEquivs :
    ∀ i, gapRep i ≃* {target}{perm_arg}
{equiv_cases}

/-- **(1)+(2)+(3).** The GAP-numbered list {list_text}
is complete and non-redundant. -/
theorem isClassif : IsClassif {n} gapRep :=
  IsClassif.of_equivs
    ({base}) gapEquivs

/-- **(1) Exhaustiveness.** Every group of order `{n}` is isomorphic to a GAP
representative. -/
theorem classification {{G : Type}} [Group G] (h : Nat.card G = {n}) :
    ∃ i, Nonempty (G ≃* gapRep i) :=
  isClassif.complete G h

/-- **(2) Distinctness.** Different GAP indices give non-isomorphic groups. -/
theorem distinct {{i j : Fin {count}}} (hij : i ≠ j) :
    ¬ Nonempty (gapRep i ≃* gapRep j) :=
  fun h => hij (isClassif.distinct i j h)

/-- **(3) Counting.** There are exactly `{count}` isomorphism classes. -/
theorem numIsoClasses_eq {{k : ℕ}} {{rep : Fin k → Type}} [∀ i, Group (rep i)]
    (h : IsClassif {n} rep) : k = {count} :=
  (isClassif.card_unique h).symm

end Smallgroups.GAP_Classifications.Order{n}
"""


def write_order(n: int, match_src: str, class_src: str) -> None:
    imported = REPO / "Smallgroups" / "GAP" / "Polycyclic" / "Imported"
    match_path = imported / f"Order{n}Match.lean"
    class_path = gap_dir(n) / f"Order{n}.lean"
    class_path.parent.mkdir(parents=True, exist_ok=True)
    match_path.write_text(match_src, encoding="utf-8")
    class_path.write_text(class_src, encoding="utf-8")
    print(f"wrote {match_path.relative_to(REPO)}")
    print(f"wrote {class_path.relative_to(REPO)}")


def main() -> None:
    for n, p, q, nonabelian in ODD_PRIME_PAIRS:
        if nonabelian:
            class_src = two_classification(
                n,
                f"Smallgroups.Classifications.Order{n}.NonabRep{n}",
                f"`SmallGroup({n}, 1)` is nonabelian and `SmallGroup({n}, 2) = ℤ/{n}`.",
            )
        else:
            class_src = single_classification(n)
        write_order(n, odd_match(n, p, q, nonabelian), class_src)

    for n, p in TWO_PRIME:
        write_order(
            n,
            two_prime_match(n, p),
            two_classification(
                n,
                f"DihedralGroup {p}",
                f"`SmallGroup({n}, 1) = DihedralGroup {p}` and "
                f"`SmallGroup({n}, 2) = ℤ/{n}`.",
            ),
        )


if __name__ == "__main__":
    main()
