#!/usr/bin/env python3
"""Translate GAP SmallGroup pc-presentation data into Lean `PCPres` definitions.

Usage:
    python Scripts/translate_pc.py [--chunk-size N] <order> [<order> ...]

For each order N, runs GAP (via the wrapper `Scripts/gap/export_pc.g`), parses the
pc-presentation data of every `SmallGroup(N, j)`, and writes

    Smallgroups/GAP/Polycyclic/Imported/OrderN.lean

containing, for each j: the presentation `smallGroup_N_j : PCPres`, the per-layer
consistency instances (by `decide`), the `Group` instance, and an order check
`Nat.card (PCGroup smallGroup_N_j) = N`.
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
TEMPLATE = (REPO / "Scripts" / "gap" / "export_pc.g").read_text(encoding="utf-8")

LIST_RE = re.compile(r"\[([^\]]*)\]")


def parse_gap_list(s):
    """Parse a GAP list `[ 2, 0, 1 ]` into a Python list of ints."""
    body = LIST_RE.search(s).group(1).strip()
    if not body:
        return []
    return [int(x) for x in body.split(",")]


def default_gap_bash():
    """Locate the GAP Windows/Cygwin wrapper, unless explicitly configured."""
    configured = os.environ.get("SMALLGROUPS_GAP_BASH")
    if configured:
        return Path(configured)
    return Path("D:/GAP/runtime/bin/bash.exe")


def default_gap_exe(gap_bash):
    """Locate GAP under the runtime containing ``gap_bash``.

    The path returned here is interpreted by the runtime's bash, so the Windows
    ``.../runtime/opt/gap-X.Y.Z`` directory becomes ``/opt/gap-X.Y.Z``.
    ``SMALLGROUPS_GAP_EXE`` overrides discovery for nonstandard installations.
    """
    configured = os.environ.get("SMALLGROUPS_GAP_EXE")
    if configured:
        return configured
    runtime = gap_bash.parent.parent
    candidates = sorted((runtime / "opt").glob("gap-*"))
    if not candidates:
        raise RuntimeError(
            f"could not find GAP under {runtime / 'opt'}; set SMALLGROUPS_GAP_EXE"
        )
    return f"/opt/{candidates[-1].name}/gap"


def run_gap(order, gap_bash, gap_exe):
    """Run the export script for `order` and return GAP's stdout."""
    script = TEMPLATE.replace("@N@", str(order))
    if not gap_bash.is_file():
        raise RuntimeError(
            f"GAP bash wrapper not found at {gap_bash}; set SMALLGROUPS_GAP_BASH"
        )
    cmd = [str(gap_bash), "--login", "-c", f"{gap_exe} -q"]
    res = subprocess.run(
        cmd, input=script, capture_output=True, text=True, timeout=600
    )
    if res.returncode != 0:
        raise RuntimeError(f"GAP failed for order {order}:\n{res.stderr}\n{res.stdout}")
    return res.stdout


def parse_groups(out):
    """Parse GAP output into a list of (j, relorders, powers, conjs)."""
    groups = []
    cur = None
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("GROUP "):
            cur = {"j": int(line.split()[2]), "powers": {}, "conjs": {}}
            groups.append(cur)
        elif line.startswith("RELORDERS "):
            cur["ro"] = parse_gap_list(line)
        elif line.startswith("POWER "):
            cur["powers"][int(line.split()[1])] = parse_gap_list(line)
        elif line.startswith("CONJ "):
            parts = line.split()
            cur["conjs"][(int(parts[1]), int(parts[2]))] = parse_gap_list(line)
        elif line.startswith("END"):
            cur = None
    for g in groups:
        g["layers"] = build_layers(g["ro"], g["powers"], g["conjs"])
    indices = [g["j"] for g in groups]
    expected = list(range(1, len(groups) + 1))
    if indices != expected:
        raise RuntimeError(
            f"GAP output has missing, duplicate, or reordered indices: {indices}"
        )
    return groups


def build_layers(ro, powers, conjs):
    """Build the Lean-side layer data: for layer i (1-based), the power vector and
    the conjugation vectors, all restricted to positions i+1..n."""
    n = len(ro)
    layers = []
    for i in range(1, n + 1):
        power = powers[i][i:]
        conj = [conjs[(i, k)][i:] for k in range(i + 1, n + 1)]
        layers.append((ro[i - 1], power, conj))
    return layers


def lean_list(xs):
    return "[" + ", ".join(str(x) for x in xs) + "]"


def emit_lean(order, groups, generated_by="Scripts/translate_pc.py"):
    """Emit the Lean source for one order."""
    lines = [
        "/-",
        "Copyright (c) 2026 Smallgroups contributors. All rights reserved.",
        "Released under Apache 2.0 license as described in the file LICENSE.",
        "Authors: Smallgroups contributors",
        "-/",
        "import Smallgroups.GAP.Polycyclic.Basic",
        "",
        "set_option maxRecDepth 100000",
        "set_option linter.style.longLine false",
        "",
        "/-!",
        f"# Imported pc presentations: order {order}",
        "",
        f"Generated by `{generated_by}` from the GAP SmallGroups library",
        "(do not edit by hand).  `smallGroup_%d_j` is the pc presentation of the"
        % order,
        "GAP group `SmallGroup(%d, j)`; layers are given outermost generator first."
        % order,
        "",
        "Each group carries: per-layer consistency instances (`by decide`), the",
        "`Group` instance on `PCGroup`, and the order check `card_smallGroup_%d_j`."
        % order,
        "-/",
        "",
        "namespace Smallgroups.GAP",
        "",
    ]
    for g in groups:
        j = g["j"]
        layers = g["layers"]
        names = []
        for i, (r, power, conj) in enumerate(layers, start=1):
            name = f"sg{order}_{j}_L{i}"
            names.append(name)
            conj_str = "[" + ", ".join(lean_list(c) for c in conj) + "]"
            lines.append(
                f"def {name} : PCLayer := ⟨{r}, by decide, {lean_list(power)}, {conj_str}⟩")
        pres = f"smallGroup_{order}_{j}"
        lines.append("")
        lines.append(f"def {pres} : PCPres := ⟨[{', '.join(names)}]⟩")
        if not layers:
            lines.append("")
        else:
            # per-layer consistency instances and the group instance
            for i in range(len(layers), 0, -1):
                tail = ", ".join(names[i:])
                lines.append(
                    f"instance : CycExtData.Consistent\n"
                    f"    (pcTowerLayerData {names[i - 1]} [{tail}]) := by decide")
            lines.append(
                f"instance : Group (PCGroup {pres}) :=\n"
                f"  CycExt.group (pcTowerLayerData {names[0]} [{', '.join(names[1:])}])")
        lines.append("")
        lines.append(
            f"theorem card_{pres} : Nat.card (PCGroup {pres}) = {order} := by\n"
            "  rw [card_PCGroup]; decide")
        lines.append("")
    lines.append("end Smallgroups.GAP")
    lines.append("")
    return "\n".join(lines)


def emit_umbrella(order, part_names, count):
    """Emit the stable ``OrderN`` module importing generated chunks."""
    imports = "\n".join(
        f"import Smallgroups.GAP.Polycyclic.Imported.{name}" for name in part_names
    )
    return f"""/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
{imports}

/-!
# Imported pc presentations: order {order}

Generated by `Scripts/translate_pc.py --chunk-size`; the imported chunks contain
all {count} GAP groups `SmallGroup({order}, j)` in the consecutive range
`1 <= j <= {count}`.
-/
"""


def write_order(order, groups, chunk_size):
    out_dir = REPO / "Smallgroups" / "GAP" / "Polycyclic" / "Imported"
    out_dir.mkdir(parents=True, exist_ok=True)
    if chunk_size <= 0 or len(groups) <= chunk_size:
        path = out_dir / f"Order{order}.lean"
        path.write_text(emit_lean(order, groups), encoding="utf-8")
        print(f"wrote {path} ({len(groups)} groups)")
        return

    chunks = [groups[i : i + chunk_size] for i in range(0, len(groups), chunk_size)]
    part_names = []
    for number, chunk in enumerate(chunks, start=1):
        name = f"Order{order}Part{number:02d}"
        part_names.append(name)
        path = out_dir / f"{name}.lean"
        command = f"Scripts/translate_pc.py --chunk-size {chunk_size} {order}"
        path.write_text(emit_lean(order, chunk, command), encoding="utf-8")
        lo, hi = chunk[0]["j"], chunk[-1]["j"]
        print(f"wrote {path} (SmallGroup({order}, {lo})..SmallGroup({order}, {hi}))")
    umbrella = out_dir / f"Order{order}.lean"
    umbrella.write_text(
        emit_umbrella(order, part_names, len(groups)), encoding="utf-8"
    )
    print(f"wrote {umbrella} ({len(groups)} groups in {len(chunks)} chunks)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("orders", metavar="ORDER", type=int, nargs="+")
    parser.add_argument(
        "--chunk-size",
        type=int,
        default=0,
        help="write groups in chunks of this size and make OrderN.lean an umbrella",
    )
    parser.add_argument(
        "--gap-bash",
        type=Path,
        default=None,
        help="GAP runtime bash wrapper (or set SMALLGROUPS_GAP_BASH)",
    )
    parser.add_argument(
        "--gap-exe",
        default=None,
        help="GAP executable as seen by its bash (or set SMALLGROUPS_GAP_EXE)",
    )
    args = parser.parse_args()
    if args.chunk_size < 0:
        parser.error("--chunk-size must be nonnegative")
    gap_bash = args.gap_bash or default_gap_bash()
    gap_exe = args.gap_exe or default_gap_exe(gap_bash)
    for order in args.orders:
        out = run_gap(order, gap_bash, gap_exe)
        groups = parse_groups(out)
        if not groups:
            raise RuntimeError(f"GAP returned no groups of order {order}")
        write_order(order, groups, args.chunk_size)


if __name__ == "__main__":
    main()
