#!/usr/bin/env python3
"""Translate GAP SmallGroup pc-presentation data into Lean `PCPres` definitions.

Usage:
    python Scripts/translate_pc.py <order> [<order> ...]

For each order N, runs GAP (via the wrapper `Scripts/gap/export_pc.g`), parses the
pc-presentation data of every `SmallGroup(N, j)`, and writes

    Smallgroups/GAP/Polycyclic/Imported/OrderN.lean

containing, for each j: the presentation `smallGroup_N_j : PCPres`, the per-layer
consistency instances (by `decide`), the `Group` instance, and an order check
`Nat.card (PCGroup smallGroup_N_j) = N`.
"""

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GAP_BASH = "D:/GAP/runtime/bin/bash.exe"
GAP_TMP_POSIX = "D:/GAP/runtime/tmp"
GAP_TMP_CYGWIN = "/cygdrive/d/GAP/runtime/tmp"
GAP_EXE = "/opt/gap-4.16.0/gap"
TEMPLATE = (REPO / "Scripts" / "gap" / "export_pc.g").read_text(encoding="utf-8")

LIST_RE = re.compile(r"\[([^\]]*)\]")


def parse_gap_list(s):
    """Parse a GAP list `[ 2, 0, 1 ]` into a Python list of ints."""
    body = LIST_RE.search(s).group(1).strip()
    if not body:
        return []
    return [int(x) for x in body.split(",")]


def run_gap(order):
    """Run the export script for `order` and return GAP's stdout."""
    script = TEMPLATE.replace("@N@", str(order))
    script_path = Path(GAP_TMP_POSIX) / f"export_{order}.g"
    script_path.write_text(script, encoding="utf-8")
    cmd = [
        GAP_BASH, "--login", "-c",
        f"cat {GAP_TMP_CYGWIN}/export_{order}.g | {GAP_EXE} -q",
    ]
    res = subprocess.run(cmd, capture_output=True, text=True, timeout=600)
    if res.returncode != 0:
        raise RuntimeError(f"GAP failed for order {order}:\n{res.stderr}\n{res.stdout}")
    return res.stdout


def parse_groups(out):
    """Parse GAP output into a list of (j, relorders, powers, conjs)."""
    groups = []
    cur = None
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("GROUP "):
            cur = {"j": int(line.split()[2]), "powers": {}, "conjs": {}}
            groups.append(cur)
        elif line.startswith("RELORDERS "):
            cur["ro"] = parse_gap_list(line)
        elif line.startswith("POWER "):
            cur["powers"][int(line.split()[1])] = parse_gap_list(line)
        elif line.startswith("CONJ "):
            parts = line.split()
            cur["conjs"][(int(parts[1]), int(parts[2]))] = parse_gap_list(line)
        elif line.startswith("END"):
            cur = None
    for g in groups:
        g["layers"] = build_layers(g["ro"], g["powers"], g["conjs"])
    return groups


def build_layers(ro, powers, conjs):
    """Build the Lean-side layer data: for layer i (1-based), the power vector and
    the conjugation vectors, all restricted to positions i+1..n."""
    n = len(ro)
    layers = []
    for i in range(1, n + 1):
        power = powers[i][i:]
        conj = [conjs[(i, k)][i:] for k in range(i + 1, n + 1)]
        layers.append((ro[i - 1], power, conj))
    return layers


def lean_list(xs):
    return "[" + ", ".join(str(x) for x in xs) + "]"


def emit_lean(order, groups):
    """Emit the Lean source for one order."""
    lines = [
        "/-",
        "Copyright (c) 2026 Smallgroups contributors. All rights reserved.",
        "Released under Apache 2.0 license as described in the file LICENSE.",
        "Authors: Smallgroups contributors",
        "-/",
        "import Smallgroups.GAP.Polycyclic.Basic",
        "",
        "/-!",
        f"# Imported pc presentations: order {order}",
        "",
        "Generated by `Scripts/translate_pc.py` from the GAP SmallGroups library",
        "(do not edit by hand).  `smallGroup_%d_j` is the pc presentation of the"
        % order,
        "GAP group `SmallGroup(%d, j)`; layers are given outermost generator first."
        % order,
        "",
        "Each group carries: per-layer consistency instances (`by decide`), the",
        "`Group` instance on `PCGroup`, and the order check `card_smallGroup_%d_j`."
        % order,
        "-/",
        "",
        "namespace Smallgroups.GAP",
        "",
    ]
    for g in groups:
        j = g["j"]
        layers = g["layers"]
        names = []
        for i, (r, power, conj) in enumerate(layers, start=1):
            name = f"sg{order}_{j}_L{i}"
            names.append(name)
            conj_str = "[" + ", ".join(lean_list(c) for c in conj) + "]"
            lines.append(
                f"def {name} : PCLayer := ⟨{r}, by decide, {lean_list(power)}, {conj_str}⟩")
        pres = f"smallGroup_{order}_{j}"
        lines.append("")
        lines.append(f"def {pres} : PCPres := ⟨[{', '.join(names)}]⟩")
        if not layers:
            lines.append("")
        else:
            # per-layer consistency instances and the group instance
            for i in range(len(layers), 0, -1):
                tail = ", ".join(names[i:])
                lines.append(
                    f"instance : CycExtData.Consistent\n"
                    f"    (pcTowerLayerData {names[i - 1]} [{tail}]) := by decide")
            lines.append(
                f"instance : Group (PCGroup {pres}) :=\n"
                f"  CycExt.group (pcTowerLayerData {names[0]} [{', '.join(names[1:])}])")
        lines.append("")
        lines.append(
            f"theorem card_{pres} : Nat.card (PCGroup {pres}) = {order} := by\n"
            "  rw [card_PCGroup]; decide")
        lines.append("")
    lines.append("end Smallgroups.GAP")
    lines.append("")
    return "\n".join(lines)


def main():
    orders = [int(x) for x in sys.argv[1:]]
    if not orders:
        print(__doc__)
        sys.exit(1)
    for order in orders:
        out = run_gap(order)
        groups = parse_groups(out)
        src = emit_lean(order, groups)
        out_dir = REPO / "Smallgroups" / "GAP" / "Polycyclic" / "Imported"
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"Order{order}.lean"
        path.write_text(src, encoding="utf-8")
        print(f"wrote {path} ({len(groups)} groups)")


if __name__ == "__main__":
    main()
