/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order48.FourSylowThreeReps

/-!
# Distinctness of the order-48 four-Sylow-three representatives

This file develops computable isomorphism invariants for the eight explicit
representatives in `FourSylowThreeReps`.
-/

namespace Smallgroups.UsefulTheorems

open scoped commutatorElement

variable {H : Type*} [Group H]

/-- The cyclic subgroup generated by an element of order two consists of the
identity and that element. -/
theorem zpowers_eq_pair_of_order_two [Finite H] {z : H} (hz2 : orderOf z = 2) :
    (Subgroup.zpowers z : Set H) = {1, z} := by
  let Z : Subgroup H := Subgroup.zpowers z
  have hZcard : Nat.card Z = 2 := by
    dsimp [Z]
    rw [Nat.card_zpowers, hz2]
  have hz_ne : z ≠ 1 := by
    intro hz
    rw [hz, orderOf_one] at hz2
    norm_num at hz2
  symm
  refine Set.eq_of_subset_of_ncard_le ?_ ?_ (Set.toFinite _)
  · simp only [Set.insert_subset_iff, Set.singleton_subset_iff]
    exact ⟨Subgroup.one_mem _, Subgroup.mem_zpowers z⟩
  · have hZncard : (Z : Set H).ncard = 2 := by
      rw [← Nat.card_coe_set_eq]
      exact hZcard
    rw [hZncard, Set.ncard_pair hz_ne.symm]

/-- For a quotient by an involution, the preimage of the `n`-th roots of one
consists exactly of the elements whose `n`-th power is either `1` or the
involution.  Each quotient element has two lifts. -/
theorem card_pow_eq_one_quotient_central_involution [Finite H]
    {z : H} (hz2 : orderOf z = 2) [(Subgroup.zpowers z).Normal] (n : ℕ) :
    Nat.card {x : H // x ^ n = 1 ∨ x ^ n = z} =
      2 * Nat.card {x : H ⧸ Subgroup.zpowers z // x ^ n = 1} := by
  let Z : Subgroup H := Subgroup.zpowers z
  let q : H →* H ⧸ Z := QuotientGroup.mk' Z
  have hZcard : Nat.card Z = 2 := by
    dsimp [Z]
    rw [Nat.card_zpowers, hz2]
  have hZpair : (Z : Set H) = {1, z} :=
    zpowers_eq_pair_of_order_two hz2
  let T : Set (H ⧸ Z) := {y | y ^ n = 1}
  have hpre := QuotientGroup.card_preimage_mk Z T
  have hpre' : Nat.card {x : H // (q x) ^ n = 1} =
      Nat.card Z * Nat.card {y : H ⧸ Z // y ^ n = 1} := by
    change Nat.card {x : H // (QuotientGroup.mk x : H ⧸ Z) ^ n = 1} =
      Nat.card Z * Nat.card {y : H ⧸ Z // y ^ n = 1} at hpre
    exact hpre
  let e : {x : H // x ^ n = 1 ∨ x ^ n = z} ≃
      {x : H // (q x) ^ n = 1} := {
    toFun x := ⟨x.1, by
      change (QuotientGroup.mk (x.1 ^ n) : H ⧸ Z) = 1
      rw [QuotientGroup.eq_one_iff]
      change x.1 ^ n ∈ (Z : Set H)
      rw [hZpair]
      exact x.2⟩
    invFun x := ⟨x.1, by
      have hx := x.2
      change (QuotientGroup.mk (x.1 ^ n) : H ⧸ Z) = 1 at hx
      rw [QuotientGroup.eq_one_iff] at hx
      change x.1 ^ n ∈ (Z : Set H) at hx
      rw [hZpair] at hx
      exact hx⟩
    left_inv x := by ext; rfl
    right_inv x := by ext; rfl }
  rw [Nat.card_congr e, hpre', hZcard]

/-- The cardinality of the commutator subgroup is preserved by a group
isomorphism. -/
theorem card_commutator_eq_of_mulEquiv {K : Type*} [Group K]
    (e : H ≃* K) : Nat.card (commutator H) = Nat.card (commutator K) := by
  have hmap : (commutator H).map e.toMonoidHom = commutator K := by
    simp only [_root_.commutator_def]
    rw [Subgroup.map_commutator,
      Subgroup.map_top_of_surjective _ e.surjective]
  exact Nat.card_congr
    ((MulEquiv.subgroupMap e (commutator H)).trans
      (MulEquiv.subgroupCongr hmap)).toEquiv

/-! ### Power-count invariant -/

/-- The numbers of square roots and fourth roots of one.  These two counts
already separate six of the eight representatives and leave only the two
central `C₄`-extensions over `A₄` to compare. -/
noncomputable def order48FourPowerInvariant (K : Type*) [Group K] : ℕ × ℕ :=
  (pow_eq_one_card K 2, pow_eq_one_card K 4)

theorem order48FourPowerInvariant_eq_of_mulEquiv {K : Type*} [Group K]
    (e : H ≃* K) :
    order48FourPowerInvariant H = order48FourPowerInvariant K := by
  exact Prod.ext (pow_eq_one_card_eq_of_mulEquiv 2 e)
    (pow_eq_one_card_eq_of_mulEquiv 4 e)

private theorem order48_four_power_C2xS4 :
    order48FourPowerInvariant order48_four_C2xS4 = (20, 32) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_power_GL23 :
    order48FourPowerInvariant order48_four_GL23 = (14, 20) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_power_C4fiberS4 :
    order48FourPowerInvariant order48_four_C4fiberS4 = (8, 32) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_power_C4xA4 :
    order48FourPowerInvariant order48_four_C4xA4 = (8, 16) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_power_V4xA4 :
    order48FourPowerInvariant order48_four_V4xA4 = (16, 16) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_power_C2xSL23 :
    order48FourPowerInvariant order48_four_C2xSL23 = (4, 16) := by
  simp only [order48FourPowerInvariant, pow_eq_one_card,
    Nat.card_eq_fintype_card]
  apply Prod.ext <;> decide +kernel

private theorem order48_four_c4SL23_parent_roots_two :
    Nat.card {x : CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) //
      x ^ 2 = 1 ∨ x ^ 2 = order48_four_c4SL23Diagonal} = 16 := by
  rw [Nat.card_eq_fintype_card]
  decide +kernel

private theorem order48_four_c4SL23_parent_roots_four :
    Nat.card {x : CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) //
      x ^ 4 = 1 ∨ x ^ 4 = order48_four_c4SL23Diagonal} = 32 := by
  rw [Nat.card_eq_fintype_card]
  decide +kernel

private theorem order48_four_power_C4centralSL23 :
    order48FourPowerInvariant order48_four_C4centralSL23 = (8, 16) := by
  have hz2 : orderOf order48_four_c4SL23Diagonal = 2 := by
    simpa only [Nat.card_zpowers] using
      card_order48_four_c4SL23Diagonal_zpowers
  have h2 := card_pow_eq_one_quotient_central_involution
    (H := CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3)) hz2 2
  have h4 := card_pow_eq_one_quotient_central_involution
    (H := CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3)) hz2 4
  rw [order48_four_c4SL23_parent_roots_two] at h2
  rw [order48_four_c4SL23_parent_roots_four] at h4
  change 16 = 2 * pow_eq_one_card order48_four_C4centralSL23 2 at h2
  change 32 = 2 * pow_eq_one_card order48_four_C4centralSL23 4 at h4
  simp only [order48FourPowerInvariant]
  exact Prod.ext (by omega) (by omega)

private theorem order48_four_c4fiberGL23_parent_roots_two :
    Nat.card {x : order48_four_C4fiberGL23 //
      x ^ 2 = 1 ∨ x ^ 2 = order48_four_C4fiberGL23Diagonal} = 4 := by
  rw [Nat.card_eq_fintype_card]
  decide +kernel

private theorem order48_four_c4fiberGL23_parent_roots_four :
    Nat.card {x : order48_four_C4fiberGL23 //
      x ^ 4 = 1 ∨ x ^ 4 = order48_four_C4fiberGL23Diagonal} = 40 := by
  rw [Nat.card_eq_fintype_card]
  decide +kernel

private theorem order48_four_power_GL23DetTwist :
    order48FourPowerInvariant order48_four_GL23DetTwist = (2, 20) := by
  have hz2 : orderOf order48_four_C4fiberGL23Diagonal = 2 := by
    simpa only [Nat.card_zpowers] using
      card_order48_four_C4fiberGL23Diagonal_zpowers
  have h2 := card_pow_eq_one_quotient_central_involution
    (H := order48_four_C4fiberGL23) hz2 2
  have h4 := card_pow_eq_one_quotient_central_involution
    (H := order48_four_C4fiberGL23) hz2 4
  rw [order48_four_c4fiberGL23_parent_roots_two] at h2
  rw [order48_four_c4fiberGL23_parent_roots_four] at h4
  change 4 = 2 * pow_eq_one_card order48_four_GL23DetTwist 2 at h2
  change 40 = 2 * pow_eq_one_card order48_four_GL23DetTwist 4 at h4
  simp only [order48FourPowerInvariant]
  exact Prod.ext (by omega) (by omega)

/-- The expected power-count values for the eight residual representatives. -/
def order48_four_powerInvariantTable : Fin 8 → ℕ × ℕ
  | 0 => (20, 32)
  | 1 => (14, 20)
  | 2 => (8, 32)
  | 3 => (8, 16)
  | 4 => (8, 16)
  | 5 => (16, 16)
  | 6 => (4, 16)
  | 7 => (2, 20)

theorem order48_four_powerInvariant_spec (i : Fin 8) :
    order48FourPowerInvariant (order48_four_residualKnownReps i) =
      order48_four_powerInvariantTable i := by
  fin_cases i
  exacts [order48_four_power_C2xS4, order48_four_power_GL23,
    order48_four_power_C4fiberS4, order48_four_power_C4xA4,
    order48_four_power_C4centralSL23, order48_four_power_V4xA4,
    order48_four_power_C2xSL23, order48_four_power_GL23DetTwist]

private theorem order48_four_powerInvariantTable_collision {i j : Fin 8}
    (h : order48_four_powerInvariantTable i = order48_four_powerInvariantTable j) :
    i = j ∨ (i = 3 ∧ j = 4) ∨ (i = 4 ∧ j = 3) := by
  fin_cases i <;> fin_cases j <;>
    simp [order48_four_powerInvariantTable] at h ⊢

/-- Power counts reduce pairwise distinctness of the residual family to the
single comparison `C₄ × A₄ ≠ C₄ * SL(2,3)`. -/
theorem order48_four_residualKnownReps_pairwise_of_exceptional
    (h34 : ¬ Nonempty (order48_four_C4xA4 ≃* order48_four_C4centralSL23)) :
    PairwiseNonMulEquiv order48_four_residualKnownReps := by
  apply PairwiseNonMulEquiv.of_invariant order48_four_powerInvariantTable
  · intro i j ⟨e⟩
    rw [← order48_four_powerInvariant_spec i,
      ← order48_four_powerInvariant_spec j]
    exact order48FourPowerInvariant_eq_of_mulEquiv e
  · intro i j hij hiso
    rcases order48_four_powerInvariantTable_collision hij with h | h | h
    · exact h
    · rcases h with ⟨rfl, rfl⟩
      exact (h34 hiso).elim
    · rcases h with ⟨rfl, rfl⟩
      obtain ⟨e⟩ := hiso
      exact (h34 ⟨e.symm⟩).elim

/-! ### The exceptional central-product comparison -/

/-- Whether every single commutator in a group has square one. -/
def AllCommutatorsSquareOne (K : Type*) [Group K] : Prop :=
  ∀ x y : K, ⁅x, y⁆ ^ 2 = 1

theorem allCommutatorsSquareOne_iff_of_mulEquiv {K : Type*} [Group K]
    (e : H ≃* K) :
    AllCommutatorsSquareOne H ↔ AllCommutatorsSquareOne K := by
  constructor
  · intro h x y
    apply e.symm.injective
    rw [map_pow, map_one, map_commutatorElement]
    exact h (e.symm x) (e.symm y)
  · intro h x y
    apply e.injective
    rw [map_pow, map_one, map_commutatorElement]
    exact h (e x) (e y)

private theorem order48_four_A4_all_commutators_square_one :
    AllCommutatorsSquareOne (alternatingGroup (Fin 4)) := by
  intro x y
  exact (by decide +kernel +revert)

theorem order48_four_C4xA4_all_commutators_square_one :
    AllCommutatorsSquareOne order48_four_C4xA4 := by
  rintro ⟨a, b⟩ ⟨c, d⟩
  apply Prod.ext
  · simp [commutatorElement_def]
  · exact order48_four_A4_all_commutators_square_one b d

/-- The standard order-four matrix in `SL(2,3)`. -/
def order48_four_SL23S : Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) :=
  ⟨!![0, -1; 1, 0], by simp [Matrix.det_fin_two_of]⟩

/-- A standard transvection in `SL(2,3)`. -/
def order48_four_SL23T : Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) :=
  ⟨!![1, 1; 0, 1], by simp [Matrix.det_fin_two_of]⟩

private def order48_four_c4SL23WitnessLeft :
    CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) :=
  (1, order48_four_SL23S)

private def order48_four_c4SL23WitnessRight :
    CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3) :=
  (1, order48_four_SL23T)

private theorem order48_four_c4SL23_witness_commutator_square_not_mem_diagonal :
    ⁅order48_four_c4SL23WitnessLeft,
      order48_four_c4SL23WitnessRight⁆ ^ 2 ∉
        Subgroup.zpowers order48_four_c4SL23Diagonal := by
  change ⁅order48_four_c4SL23WitnessLeft,
      order48_four_c4SL23WitnessRight⁆ ^ 2 ∉
    (Subgroup.zpowers order48_four_c4SL23Diagonal : Set
      (CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3)))
  rw [zpowers_eq_pair_of_order_two (by
    simpa only [Nat.card_zpowers] using
      card_order48_four_c4SL23Diagonal_zpowers)]
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff, not_or]
  constructor <;> decide +kernel

theorem order48_four_C4centralSL23_not_all_commutators_square_one :
    ¬ AllCommutatorsSquareOne order48_four_C4centralSL23 := by
  intro h
  let q :
      (CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3)) →*
        order48_four_C4centralSL23 :=
    QuotientGroup.mk' (Subgroup.zpowers order48_four_c4SL23Diagonal)
  have hsq := h (q order48_four_c4SL23WitnessLeft)
    (q order48_four_c4SL23WitnessRight)
  rw [← map_commutatorElement, ← map_pow] at hsq
  change (QuotientGroup.mk
      (⁅order48_four_c4SL23WitnessLeft,
        order48_four_c4SL23WitnessRight⁆ ^ 2) :
      (CyclicRep 4 × Matrix.SpecialLinearGroup (Fin 2) (ZMod 3)) ⧸
        Subgroup.zpowers order48_four_c4SL23Diagonal) = 1 at hsq
  rw [QuotientGroup.eq_one_iff] at hsq
  exact order48_four_c4SL23_witness_commutator_square_not_mem_diagonal hsq

theorem order48_four_C4xA4_not_mulEquiv_C4centralSL23 :
    ¬ Nonempty (order48_four_C4xA4 ≃* order48_four_C4centralSL23) := by
  rintro ⟨e⟩
  exact order48_four_C4centralSL23_not_all_commutators_square_one
    ((allCommutatorsSquareOne_iff_of_mulEquiv e).mp
      order48_four_C4xA4_all_commutators_square_one)

/-- The eight explicit representatives in the four-Sylow-three branch are
pairwise non-isomorphic. -/
theorem order48_four_residualKnownReps_pairwise :
    PairwiseNonMulEquiv order48_four_residualKnownReps :=
  order48_four_residualKnownReps_pairwise_of_exceptional
    order48_four_C4xA4_not_mulEquiv_C4centralSL23

end Smallgroups.UsefulTheorems
