/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order48.FourSylowThreeActionClassifiers

/-!
# Absence of order-three automorphisms of `G₁₂`

The group `G₁₂ = C₄ ⋊ C₄` is generated by `a,b`, with `b` acting on `a`
by inversion.  A kernel-checked two-generator calculation shows that every
automorphism whose cube is one fixes both generators.
-/

namespace Smallgroups.UsefulTheorems

private noncomputable def order48_G12_a : order16_wild_G12 :=
  SemidirectProduct.inl (Multiplicative.ofAdd (1 : ZMod 4))

private noncomputable def order48_G12_b : order16_wild_G12 :=
  SemidirectProduct.inr (Multiplicative.ofAdd (1 : ZMod 4))

private noncomputable def order48_G12_word
    (a b x : order16_wild_G12) : order16_wild_G12 :=
  a ^ (Multiplicative.toAdd x.left).val *
    b ^ (Multiplicative.toAdd x.right).val

private theorem order48_G12_hom_eval
    (f : order16_wild_G12 →* order16_wild_G12) (x : order16_wild_G12) :
    f x = order48_G12_word (f order48_G12_a) (f order48_G12_b) x := by
  have hx : x = order48_G12_a ^ (Multiplicative.toAdd x.left).val *
      order48_G12_b ^ (Multiplicative.toAdd x.right).val := by
    revert x
    decide +kernel
  change f x = f order48_G12_a ^ (Multiplicative.toAdd x.left).val *
    f order48_G12_b ^ (Multiplicative.toAdd x.right).val
  calc
    f x = f (order48_G12_a ^ (Multiplicative.toAdd x.left).val *
        order48_G12_b ^ (Multiplicative.toAdd x.right).val) := congrArg f hx
    _ = _ := by rw [map_mul, map_pow, map_pow]

private def order48_G12_decidableForallTwo {α : Type*} [Fintype α]
    (p : α → α → Prop) (hp : ∀ a b, Decidable (p a b)) :
    Decidable (∀ a b, p a b) :=
  @Fintype.decidableForallFintype α (fun a => ∀ b, p a b)
    (fun a => @Fintype.decidableForallFintype α (p a)
      (fun b => hp a b) inferInstance) inferInstance

private def order48_G12_decidableImp {p q : Prop}
    (hp : Decidable p) (hq : Decidable q) : Decidable (p → q) :=
  match hp, hq with
  | isFalse hp, _ => isTrue (fun h => False.elim (hp h))
  | isTrue _, isTrue hq => isTrue (fun _ => hq)
  | isTrue hp, isFalse hq => isFalse (fun h => hq (h hp))

private noncomputable def order48_G12_coordinateRigidity : Prop :=
  ∀ a b : order16_wild_G12,
    a ^ 4 = 1 →
    b ^ 4 = 1 →
    b * a * b⁻¹ = a⁻¹ →
    order48_G12_word a b
      (order48_G12_word a b (order48_G12_word a b order48_G12_a)) =
        order48_G12_a →
    order48_G12_word a b
      (order48_G12_word a b (order48_G12_word a b order48_G12_b)) =
        order48_G12_b →
    (∀ x, order48_G12_word a b x = 1 → x = 1) →
    a = order48_G12_a ∧ b = order48_G12_b

private noncomputable def order48_G12_coordinateRigidity_decidable :
    Decidable order48_G12_coordinateRigidity :=
  order48_G12_decidableForallTwo _ (fun a b => by
    have h1 : Decidable (a ^ 4 = 1) := inferInstance
    have h2 : Decidable (b ^ 4 = 1) := inferInstance
    have h3 : Decidable (b * a * b⁻¹ = a⁻¹) := inferInstance
    have h4 : Decidable (order48_G12_word a b
        (order48_G12_word a b (order48_G12_word a b order48_G12_a)) =
          order48_G12_a) := inferInstance
    have h5 : Decidable (order48_G12_word a b
        (order48_G12_word a b (order48_G12_word a b order48_G12_b)) =
          order48_G12_b) := inferInstance
    have h6 : Decidable (∀ x, order48_G12_word a b x = 1 → x = 1) :=
      inferInstance
    have h7 : Decidable (a = order48_G12_a ∧ b = order48_G12_b) :=
      inferInstance
    exact order48_G12_decidableImp h1 <| order48_G12_decidableImp h2 <|
      order48_G12_decidableImp h3 <| order48_G12_decidableImp h4 <|
      order48_G12_decidableImp h5 <| order48_G12_decidableImp h6 h7)

set_option maxRecDepth 10000 in
set_option maxHeartbeats 1000000 in
-- The 256 possible generator-image pairs are checked by Lean's kernel.
private theorem order48_G12_coordinateRigidity_proof :
    order48_G12_coordinateRigidity := by
  exact @of_decide_eq_true order48_G12_coordinateRigidity
    order48_G12_coordinateRigidity_decidable (by decide +kernel)

private theorem order48_G12_aut_cube_eq_one
    (α : MulAut order16_wild_G12) (hcube : α ^ 3 = 1) : α = 1 := by
  let a := α order48_G12_a
  let b := α order48_G12_b
  let F := order48_G12_word a b
  have heval : ∀ x, α x = F x := order48_G12_hom_eval α.toMonoidHom
  have ha4 : a ^ 4 = 1 := by
    have h : order48_G12_a ^ 4 = 1 := by decide +kernel
    simpa [a] using congrArg α h
  have hb4 : b ^ 4 = 1 := by
    have h : order48_G12_b ^ 4 = 1 := by decide +kernel
    simpa [b] using congrArg α h
  have hba : b * a * b⁻¹ = a⁻¹ := by
    have h : order48_G12_b * order48_G12_a * order48_G12_b⁻¹ =
        order48_G12_a⁻¹ := by decide +kernel
    simpa [a, b] using congrArg α h
  have hcubeF : ∀ x, F (F (F x)) = x := by
    intro x
    have hx := congrArg (fun β : MulAut order16_wild_G12 => β x) hcube
    rw [← heval (F (F x)), ← heval (F x), ← heval x]
    simpa only [pow_succ, pow_zero, one_mul, MulAut.mul_apply,
      MulAut.one_apply] using hx
  have hker : ∀ x, F x = 1 → x = 1 := by
    intro x hx
    apply α.injective
    rw [heval]
    simpa only [map_one] using hx
  obtain ⟨ha, hb⟩ := order48_G12_coordinateRigidity_proof a b
    ha4 hb4 hba (hcubeF order48_G12_a) (hcubeF order48_G12_b) hker
  apply MulEquiv.ext
  intro x
  rw [heval]
  dsimp [F]
  rw [ha, hb]
  change _ = (MonoidHom.id order16_wild_G12) x
  exact (order48_G12_hom_eval (MonoidHom.id order16_wild_G12) x).symm

/-- The four-Sylow-three residual branch with kernel `G₁₂` is empty. -/
theorem order48_G12_action_complete : Order48WildKernelActionComplete 12 := by
  change ∀ φ : Multiplicative (ZMod 3) →* MulAut order16_wild_G12,
    Nat.card {x : SemidirectProduct order16_wild_G12
      (Multiplicative (ZMod 3)) φ // x ^ 3 = 1} = 9 → _
  intro φ hRoots
  have hSyl := (order48_c3_action_card_sylow_three_eq_four_iff
    card_order16_wild_G12 φ).mpr hRoots
  have hne := order48_c3_action_generator_ne_one_of_card_sylow_four
    card_order16_wild_G12 φ hSyl
  exact (hne (order48_G12_aut_cube_eq_one _
    (order48_c3_action_generator_pow_three φ))).elim

end Smallgroups.UsefulTheorems
