/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Order48.FourSylowThreeCocycles

/-!
# Basic facts for the three order-`24` cocycle branches

This file records the common part of the remaining RM/RN/RO calculations.
For a `ZMod 2` central cocycle over an order-`24` quotient, the canonical
central copy of `ZMod 2` is exactly the cyclic subgroup generated by its
nontrivial element.  Consequently the quotient of the cocycle group by that
involution is the original quotient group.  If the quotient has nine cube
roots, the cocycle group has order `48` and four Sylow `3`-subgroups.

The actual orbit calculations over `order24_RM`, `order24_RN`, and
`order24_RO` remain separate; these lemmas avoid reproving this bookkeeping in
each of the three branches.
-/

namespace Smallgroups.UsefulTheorems

private def order48_cocycle_involution
    {Q : Type*} [Group Q]
    {f : Q → Q → ZMod 2} (hf : IsCentralCocycle f) : CocycleGroup f hf :=
  CocycleGroup.inl (hf := hf) (Multiplicative.ofAdd (1 : ZMod 2))

private theorem order48_cocycle_involution_order_two
    {Q : Type*} [Group Q]
    {f : Q → Q → ZMod 2} (hf : IsCentralCocycle f) :
    orderOf (order48_cocycle_involution hf) = 2 := by
  apply (orderOf_injective (CocycleGroup.inl (hf := hf))
    CocycleGroup.inl_injective _).trans
  rw [orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one]

private theorem order48_cocycle_involution_mem_center
    {Q : Type*} [Group Q]
    {f : Q → Q → ZMod 2} (hf : IsCentralCocycle f) :
    order48_cocycle_involution hf ∈ Subgroup.center (CocycleGroup f hf) :=
  CocycleGroup.inl_mem_center _

private theorem order48_cocycle_zpowers_eq_inl_range
    {Q : Type*} [Group Q] [Finite Q]
    {f : Q → Q → ZMod 2} (hf : IsCentralCocycle f) :
    Subgroup.zpowers (order48_cocycle_involution hf) =
      (CocycleGroup.inl (hf := hf)).range := by
  let z := order48_cocycle_involution hf
  let ι := CocycleGroup.inl (hf := hf)
  have hzmem : z ∈ ι.range := ⟨_, rfl⟩
  have hle : Subgroup.zpowers z ≤ ι.range := Subgroup.zpowers_le.mpr hzmem
  have hιcard : Nat.card ι.range = 2 := by
    rw [← Nat.card_congr
      (MonoidHom.ofInjective CocycleGroup.inl_injective).toEquiv]
    rw [Nat.card_eq_fintype_card]
    decide
  apply Subgroup.eq_of_le_of_card_ge hle
  rw [Nat.card_zpowers, order48_cocycle_involution_order_two hf, hιcard]

theorem order48_cocycleGroup_card_and_sylow_three
    {Q : Type*} [Group Q] [Finite Q]
    (f : Q → Q → ZMod 2) (hf : IsCentralCocycle f)
    (hQcard : Nat.card Q = 24)
    (hQroots : pow_eq_one_card Q 3 = 9) :
    Nat.card (CocycleGroup f hf) = 48 ∧
      Nat.card (Sylow 3 (CocycleGroup f hf)) = 4 := by
  let z := order48_cocycle_involution hf
  let Z := Subgroup.zpowers z
  have hz2 : orderOf z = 2 := order48_cocycle_involution_order_two hf
  have hzcenter : z ∈ Subgroup.center (CocycleGroup f hf) :=
    order48_cocycle_involution_mem_center hf
  letI : Z.Normal := by
    dsimp [Z]
    exact normal_of_le_center (Subgroup.zpowers_le.mpr hzcenter)
  have hcard : Nat.card (CocycleGroup f hf) = 48 := by
    rw [CocycleGroup.card_eq, hQcard]
    rw [Nat.card_eq_fintype_card]
    decide
  have hquot : Nonempty ((CocycleGroup f hf) ⧸ Z ≃* Q) := by
    have hZeq : Z = (CocycleGroup.inl (hf := hf)).range := by
      exact order48_cocycle_zpowers_eq_inl_range hf
    exact ⟨(QuotientGroup.quotientMulEquivOfEq hZeq).trans
      (CocycleGroup.quotientRangeInlEquiv (hf := hf))⟩
  have hquotRoots : pow_eq_one_card ((CocycleGroup f hf) ⧸ Z) 3 = 9 := by
    obtain ⟨e⟩ := hquot
    rw [pow_eq_one_card_eq_of_mulEquiv 3 e, hQroots]
  refine ⟨hcard, ?_⟩
  exact order48_card_sylow_three_eq_four_of_quotient_cube_roots
    hcard hzcenter hz2 hquotRoots

theorem order48_RM_cocycle_card_and_sylow_three
    (f : order24_RM → order24_RM → ZMod 2) (hf : IsCentralCocycle f) :
    Nat.card (CocycleGroup f hf) = 48 ∧
      Nat.card (Sylow 3 (CocycleGroup f hf)) = 4 :=
  order48_cocycleGroup_card_and_sylow_three f hf card_order24_RM
    card_pow_three_eq_one_order24_RM

theorem order48_RN_cocycle_card_and_sylow_three
    (f : order24_RN → order24_RN → ZMod 2) (hf : IsCentralCocycle f) :
    Nat.card (CocycleGroup f hf) = 48 ∧
      Nat.card (Sylow 3 (CocycleGroup f hf)) = 4 :=
  order48_cocycleGroup_card_and_sylow_three f hf card_order24_RN
    card_pow_three_eq_one_order24_RN

theorem order48_RO_cocycle_card_and_sylow_three
    (f : order24_RO → order24_RO → ZMod 2) (hf : IsCentralCocycle f) :
    Nat.card (CocycleGroup f hf) = 48 ∧
      Nat.card (Sylow 3 (CocycleGroup f hf)) = 4 :=
  order48_cocycleGroup_card_and_sylow_three f hf card_order24_RO
    card_pow_three_eq_one_order24_RO

end Smallgroups.UsefulTheorems
