/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Mathlib.GroupTheory.FreeGroup.Basic
import Smallgroups.UsefulTheorems.Order48.FourSylowThreeRO

/-!
# A kernel-checked normal form for the Coxeter presentation of `S₄`

The three adjacent involutions satisfying the type-`A₃` Coxeter relations
have 24 explicit normal forms.  GAP was used only to discover the transition
table below; every entry is verified symbolically by Lean.
-/

namespace Smallgroups.UsefulTheorems

section S4NormalForm

variable {H : Type*} [Group H] (a b c : H)

private def order48_s4NormalA : Fin 2 → H
  | 0 => 1
  | 1 => a

private def order48_s4NormalB : Fin 3 → H
  | 0 => 1
  | 1 => b
  | 2 => b * a

private def order48_s4NormalC : Fin 4 → H
  | 0 => 1
  | 1 => c
  | 2 => c * b
  | 3 => c * b * a

private def order48_s4Normal (s : Fin 24) : H :=
  order48_s4NormalA a ⟨s.val / 12, by omega⟩ *
    order48_s4NormalB a b ⟨s.val % 12 / 4, by omega⟩ *
    order48_s4NormalC a b c ⟨s.val % 4, by omega⟩

/-- Left multiplication by an adjacent generator on the 24 normal forms. -/
private def order48_s4NormalNext : Fin 3 → Fin 24 → Fin 24
  | 0, s => ![12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] s
  | 1, s => ![4, 5, 6, 7, 0, 1, 2, 3, 12, 13, 14, 15,
      8, 9, 10, 11, 20, 21, 22, 23, 16, 17, 18, 19] s
  | 2, s => ![1, 0, 4, 8, 2, 6, 5, 9, 3, 7, 11, 10,
      13, 12, 16, 20, 14, 18, 17, 21, 15, 19, 23, 22] s

def order48_s4NormalGen : Fin 3 → H
  | 0 => a
  | 1 => b
  | 2 => c

private theorem order48_s4Normal_transition
    (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) (hc : c ^ 2 = 1)
    (hab : (a * b) ^ 3 = 1) (hbc : (b * c) ^ 3 = 1)
    (hac : a * c = c * a) (g : Fin 3) (s : Fin 24) :
    (if g = 0 then a else if g = 1 then b else c) * order48_s4Normal a b c s =
      order48_s4Normal a b c (order48_s4NormalNext g s) := by
  have haa : a * a = 1 := by simpa [pow_two] using ha
  have hbb : b * b = 1 := by simpa [pow_two] using hb
  have hcc : c * c = 1 := by simpa [pow_two] using hc
  have ha_inv : a⁻¹ = a := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    exact haa
  have hb_inv : b⁻¹ = b := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    exact hbb
  have hc_inv : c⁻¹ = c := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    exact hcc
  have haba : a * b * a = b * a * b := by
    have h2 : (a * b) ^ 2 = (a * b)⁻¹ := by
      rw [eq_inv_iff_mul_eq_one, ← pow_succ]
      exact hab
    apply mul_right_cancel (b := b)
    calc
      (a * b * a) * b = (a * b) ^ 2 := by simp [pow_two, mul_assoc]
      _ = (a * b)⁻¹ := h2
      _ = b * a := by rw [mul_inv_rev, ha_inv, hb_inv]
      _ = (b * a * b) * b := by rw [mul_assoc, hbb, mul_one]
  have hbcb : b * c * b = c * b * c := by
    have h2 : (b * c) ^ 2 = (b * c)⁻¹ := by
      rw [eq_inv_iff_mul_eq_one, ← pow_succ]
      exact hbc
    apply mul_right_cancel (b := c)
    calc
      (b * c * b) * c = (b * c) ^ 2 := by simp [pow_two, mul_assoc]
      _ = (b * c)⁻¹ := h2
      _ = c * b := by rw [mul_inv_rev, hb_inv, hc_inv]
      _ = (c * b * c) * c := by rw [mul_assoc, hcc, mul_one]
  have haa' (x : H) : a * (a * x) = x := by rw [← mul_assoc, haa, one_mul]
  have hbb' (x : H) : b * (b * x) = x := by rw [← mul_assoc, hbb, one_mul]
  have hcc' (x : H) : c * (c * x) = x := by rw [← mul_assoc, hcc, one_mul]
  have haba' (x : H) : b * (a * (b * x)) = a * (b * (a * x)) := by
    rw [← mul_assoc, ← mul_assoc, haba.symm]
    group
  have hbcb' (x : H) : c * (b * (c * x)) = b * (c * (b * x)) := by
    rw [← mul_assoc, ← mul_assoc, hbcb.symm]
    group
  have hac' (x : H) : c * (a * x) = a * (c * x) := by
    rw [← mul_assoc, hac.symm, mul_assoc]
  have haba0 : b * (a * b) = a * (b * a) := by simpa [mul_assoc] using haba.symm
  have hbcb0 : c * (b * c) = b * (c * b) := by simpa [mul_assoc] using hbcb.symm
  have hac0 : c * a = a * c := hac.symm
  have hcbac (x : H) :
      c * (b * (a * (c * x))) = b * (c * (b * (a * x))) := by
    rw [← mul_assoc a c, hac, mul_assoc c a, hbcb']
  have hcbac0 : c * (b * (a * c)) = b * (c * (b * a)) := by
    simpa using hcbac 1
  fin_cases g <;> fin_cases s <;>
    simp [order48_s4NormalNext, order48_s4Normal, order48_s4NormalA,
      order48_s4NormalB, order48_s4NormalC, haa, hbb, hcc, haa', hbb', hcc',
      haba', hbcb', hac', haba0, hbcb0, hac0, hcbac, hcbac0, mul_assoc]

/-- A group generated by three type-`A₃` Coxeter generators has at most 24
elements.  The proof uses an explicit 24-state normal form and free-group
induction, rather than a VM computation. -/
theorem natCard_le_24_of_s4_coxeter_generators [Finite H]
    (ha : a ^ 2 = 1) (hb : b ^ 2 = 1) (hc : c ^ 2 = 1)
    (hab : (a * b) ^ 3 = 1) (hbc : (b * c) ^ 3 = 1)
    (hac : a * c = c * a)
    (hgen : Subgroup.closure (Set.range (order48_s4NormalGen a b c)) = ⊤) :
    Nat.card H ≤ 24 := by
  have htransition (g : Fin 3) (s : Fin 24) :
      order48_s4NormalGen a b c g * order48_s4Normal a b c s =
        order48_s4Normal a b c (order48_s4NormalNext g s) := by
    fin_cases g
    · simpa [order48_s4NormalGen] using
        order48_s4Normal_transition a b c ha hb hc hab hbc hac (0 : Fin 3) s
    · simpa [order48_s4NormalGen] using
        order48_s4Normal_transition a b c ha hb hc hab hbc hac (1 : Fin 3) s
    · simpa [order48_s4NormalGen] using
        order48_s4Normal_transition a b c ha hb hc hab hbc hac (2 : Fin 3) s
  have ha_inv : a⁻¹ = a := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    simpa [pow_two] using ha
  have hb_inv : b⁻¹ = b := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    simpa [pow_two] using hb
  have hc_inv : c⁻¹ = c := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    simpa [pow_two] using hc
  have hgen_inv (g : Fin 3) :
      (order48_s4NormalGen a b c g)⁻¹ = order48_s4NormalGen a b c g := by
    fin_cases g <;> simp [order48_s4NormalGen, ha_inv, hb_inv, hc_inv]
  have hsurj : Function.Surjective (FreeGroup.lift (order48_s4NormalGen a b c)) := by
    rw [← MonoidHom.range_eq_top, FreeGroup.range_lift_eq_closure]
    exact hgen
  have hword (z : FreeGroup (Fin 3)) : ∀ s : Fin 24, ∃ t : Fin 24,
      FreeGroup.lift (order48_s4NormalGen a b c) z * order48_s4Normal a b c s =
        order48_s4Normal a b c t := by
    induction z using FreeGroup.induction_on with
    | C1 => exact fun s => ⟨s, by simp⟩
    | of g => exact fun s => ⟨order48_s4NormalNext g s, by simpa using htransition g s⟩
    | inv_of g hg =>
        exact fun s => ⟨order48_s4NormalNext g s, by
          simpa [hgen_inv g] using htransition g s⟩
    | mul x y hx hy =>
        intro s
        obtain ⟨t, ht⟩ := hy s
        obtain ⟨u, hu⟩ := hx t
        exact ⟨u, by rw [map_mul, mul_assoc, ht, hu]⟩
  have hnormalSurj : Function.Surjective (order48_s4Normal a b c) := by
    intro x
    obtain ⟨z, rfl⟩ := hsurj x
    obtain ⟨t, ht⟩ := hword z 0
    refine ⟨t, ?_⟩
    simpa [order48_s4Normal, order48_s4NormalA, order48_s4NormalB,
      order48_s4NormalC] using ht.symm
  simpa using Nat.card_le_card_of_surjective (order48_s4Normal a b c) hnormalSurj

/-! ### Central two-sign version -/

/-- The central exponent introduced by a signed Coxeter generator transition.
The table was discovered in the four order-48 presentations and is checked
symbolically by `order48_s4SignedNormal_transition`. -/
private def order48_s4SignedDelta : Fin 2 → Fin 2 → Fin 3 → Fin 24 → Fin 2
  | 0, 0, _, _ => 0
  | 0, 1, 0, _ => 0
  | 0, 1, 1, _ => 0
  | 0, 1, 2, s => ![0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
      1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1] s
  | 1, 0, 0, s => ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] s
  | 1, 0, 1, s => ![0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0] s
  | 1, 0, 2, s => ![0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
      0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1] s
  | 1, 1, 0, s => ![0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1] s
  | 1, 1, 1, s => ![0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
      0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0] s
  | 1, 1, 2, s => ![0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
      1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0] s

set_option maxHeartbeats 1200000 in
-- Checking the four signed 72-entry transition tables needs extra symbolic reductions.
private theorem order48_s4SignedNormal_transition
    (z : H) (squareSign commutatorSign : Fin 2)
    (hzcenter : z ∈ Subgroup.center H) (hz2 : z ^ 2 = 1)
    (ha : a ^ 2 = z ^ squareSign.val)
    (hb : b ^ 2 = z ^ squareSign.val)
    (hc : c ^ 2 = z ^ squareSign.val)
    (hab : (a * b) ^ 3 = 1) (hbc : (b * c) ^ 3 = 1)
    (hac : a * c * a⁻¹ * c⁻¹ = z ^ commutatorSign.val)
    (g : Fin 3) (s : Fin 24) :
    ∃ e : Fin 2,
      order48_s4NormalGen a b c g * order48_s4Normal a b c s =
        z ^ e.val * order48_s4Normal a b c (order48_s4NormalNext g s) := by
  let t := z ^ squareSign.val
  let u := z ^ commutatorSign.val
  have htcenter : t ∈ Subgroup.center H := Subgroup.pow_mem _ hzcenter _
  have hucenter : u ∈ Subgroup.center H := Subgroup.pow_mem _ hzcenter _
  have htcomm (x : H) : Commute t x := (Subgroup.mem_center_iff.mp htcenter x).symm
  have hucomm (x : H) : Commute u x := (Subgroup.mem_center_iff.mp hucenter x).symm
  have ht2 : t * t = 1 := by
    fin_cases squareSign
    · simp [t]
    · simpa [t, pow_two] using hz2
  have hu2 : u * u = 1 := by
    fin_cases commutatorSign
    · simp [u]
    · simpa [u, pow_two] using hz2
  have haa : a * a = t := by simpa [pow_two, t] using ha
  have hbb : b * b = t := by simpa [pow_two, t] using hb
  have hcc : c * c = t := by simpa [pow_two, t] using hc
  have htpull (x y : H) : x * (t * y) = t * (x * y) := by
    rw [← mul_assoc, (htcomm x).eq.symm, mul_assoc]
  have ha_inv : a⁻¹ = t * a := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    calc
      a * (t * a) = t * (a * a) := by
        rw [← mul_assoc, (htcomm a).eq.symm, mul_assoc]
      _ = t * t := by rw [haa]
      _ = 1 := ht2
  have hb_inv : b⁻¹ = t * b := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    calc
      b * (t * b) = t * (b * b) := by
        rw [← mul_assoc, (htcomm b).eq.symm, mul_assoc]
      _ = t * t := by rw [hbb]
      _ = 1 := ht2
  have hc_inv : c⁻¹ = t * c := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    calc
      c * (t * c) = t * (c * c) := by
        rw [← mul_assoc, (htcomm c).eq.symm, mul_assoc]
      _ = t * t := by rw [hcc]
      _ = 1 := ht2
  have habInv : (a * b)⁻¹ = b * a := by
    rw [mul_inv_rev, ha_inv, hb_inv]
    calc
      (t * b) * (t * a) = t * (b * (t * a)) := by group
      _ = t * (t * (b * a)) := by rw [htpull]
      _ = (t * t) * (b * a) := by group
      _ = b * a := by rw [ht2, one_mul]
  have hbcInv : (b * c)⁻¹ = c * b := by
    rw [mul_inv_rev, hb_inv, hc_inv]
    calc
      (t * c) * (t * b) = t * (c * (t * b)) := by group
      _ = t * (t * (c * b)) := by rw [htpull]
      _ = (t * t) * (c * b) := by group
      _ = c * b := by rw [ht2, one_mul]
  have haba : a * b * a = t * (b * a * b) := by
    have h2 : (a * b) ^ 2 = (a * b)⁻¹ := by
      rw [eq_inv_iff_mul_eq_one, ← pow_succ]
      exact hab
    apply mul_right_cancel (b := b)
    calc
      (a * b * a) * b = (a * b) ^ 2 := by simp [pow_two, mul_assoc]
      _ = (a * b)⁻¹ := h2
      _ = b * a := habInv
      _ = (t * (b * a * b)) * b := by
        calc
          b * a = 1 * (b * a) := by rw [one_mul]
          _ = (t * t) * (b * a) := by rw [ht2]
          _ = t * ((b * a) * t) := by rw [← (htcomm (b * a)).eq]; group
          _ = t * ((b * a * b) * b) := by
            congr 1
            rw [← hbb]
            group
          _ = (t * (b * a * b)) * b := by group
  have hbcb : b * c * b = t * (c * b * c) := by
    have h2 : (b * c) ^ 2 = (b * c)⁻¹ := by
      rw [eq_inv_iff_mul_eq_one, ← pow_succ]
      exact hbc
    apply mul_right_cancel (b := c)
    calc
      (b * c * b) * c = (b * c) ^ 2 := by simp [pow_two, mul_assoc]
      _ = (b * c)⁻¹ := h2
      _ = c * b := hbcInv
      _ = (t * (c * b * c)) * c := by
        calc
          c * b = 1 * (c * b) := by rw [one_mul]
          _ = (t * t) * (c * b) := by rw [ht2]
          _ = t * ((c * b) * t) := by rw [← (htcomm (c * b)).eq]; group
          _ = t * ((c * b * c) * c) := by
            congr 1
            rw [← hcc]
            group
          _ = (t * (c * b * c)) * c := by group
  have hac' : a * c = u * (c * a) := by
    calc
      a * c = (a * c * a⁻¹ * c⁻¹) * (c * a) := by group
      _ = u * (c * a) := by rw [hac]
  have hca : c * a = u * (a * c) := by
    calc
      c * a = 1 * (c * a) := by rw [one_mul]
      _ = (u * u) * (c * a) := by rw [hu2]
      _ = u * (u * (c * a)) := by group
      _ = u * (a * c) := by rw [← hac']
  have haa' (x : H) : a * (a * x) = t * x := by rw [← mul_assoc, haa]
  have hbb' (x : H) : b * (b * x) = t * x := by rw [← mul_assoc, hbb]
  have hcc' (x : H) : c * (c * x) = t * x := by rw [← mul_assoc, hcc]
  have hbaba : b * a * b = t * (a * b * a) := by
    calc
      b * a * b = 1 * (b * a * b) := by rw [one_mul]
      _ = (t * t) * (b * a * b) := by rw [ht2]
      _ = t * (t * (b * a * b)) := by group
      _ = t * (a * b * a) := by rw [← haba]
  have hcbcb : c * b * c = t * (b * c * b) := by
    calc
      c * b * c = 1 * (c * b * c) := by rw [one_mul]
      _ = (t * t) * (c * b * c) := by rw [ht2]
      _ = t * (t * (c * b * c)) := by group
      _ = t * (b * c * b) := by rw [← hbcb]
  have haba' (x : H) : b * (a * (b * x)) = t * (a * (b * (a * x))) := by
    calc
      b * (a * (b * x)) = (b * a * b) * x := by group
      _ = (t * (a * b * a)) * x := by rw [hbaba]
      _ = t * (a * (b * (a * x))) := by group
  have hbcb' (x : H) : c * (b * (c * x)) = t * (b * (c * (b * x))) := by
    calc
      c * (b * (c * x)) = (c * b * c) * x := by group
      _ = (t * (b * c * b)) * x := by rw [hcbcb]
      _ = t * (b * (c * (b * x))) := by group
  have hca' (x : H) : c * (a * x) = u * (a * (c * x)) := by
    rw [← mul_assoc, hca]
    group
  have hac'' (x : H) : a * (c * x) = u * (c * (a * x)) := by
    rw [← mul_assoc, hac']
    group
  have hupull (x y : H) : x * (u * y) = u * (x * y) := by
    rw [← mul_assoc, (hucomm x).eq.symm, mul_assoc]
  have hcbac (x : H) :
      c * (b * (a * (c * x))) =
        (u * t) * (b * (c * (b * (a * x)))) := by
    rw [hac'', hupull, hupull, hbcb']
    group
  have haba0 : b * (a * b) = t * (a * (b * a)) := by simpa using haba' 1
  have hbcb0 : c * (b * c) = t * (b * (c * b)) := by simpa using hbcb' 1
  have hca0 : c * a = u * (a * c) := hca
  have hcbac0 : c * (b * (a * c)) = (u * t) * (b * (c * (b * a))) := by
    simpa using hcbac 1
  have hzcomm (x : H) : Commute z x :=
    (Subgroup.mem_center_iff.mp hzcenter x).symm
  have hzz : z * z = 1 := by simpa [pow_two] using hz2
  refine ⟨order48_s4SignedDelta squareSign commutatorSign g s, ?_⟩
  fin_cases squareSign <;> fin_cases commutatorSign <;> fin_cases g <;> fin_cases s <;>
    simp [order48_s4SignedDelta, order48_s4NormalGen, order48_s4NormalNext,
      order48_s4Normal, order48_s4NormalA, order48_s4NormalB, order48_s4NormalC,
      t, u, haa, hbb, hcc, haa', hbb', hcc', haba', hbcb', hca', hcbac,
      haba0, hbcb0, hca0, hcbac0, hzz, (hzcomm _).eq, mul_assoc]

private def order48_s4SignedNormal (z a b c : H) (q : Fin 2 × Fin 24) : H :=
  z ^ q.1.val * order48_s4Normal a b c q.2

def order48_s4SignedGen (z a b c : H) : Fin 4 → H
  | 0 => z
  | 1 => a
  | 2 => b
  | 3 => c

/-- The signed type-`A₃` relations give an explicit 48-element spanning
family.  This is the finite-presentation bound needed for central double
covers of `S₄`. -/
theorem finite_and_natCard_le_48_of_s4_signed_coxeter_generators
    (z : H) (squareSign commutatorSign : Fin 2)
    (hzcenter : z ∈ Subgroup.center H) (hz2 : z ^ 2 = 1)
    (ha : a ^ 2 = z ^ squareSign.val)
    (hb : b ^ 2 = z ^ squareSign.val)
    (hc : c ^ 2 = z ^ squareSign.val)
    (hab : (a * b) ^ 3 = 1) (hbc : (b * c) ^ 3 = 1)
    (hac : a * c * a⁻¹ * c⁻¹ = z ^ commutatorSign.val)
    (hgen : Subgroup.closure (Set.range (order48_s4SignedGen z a b c)) = ⊤) :
    Finite H ∧ Nat.card H ≤ 48 := by
  have hzcomm (x : H) : Commute z x :=
    (Subgroup.mem_center_iff.mp hzcenter x).symm
  have hzz : z * z = 1 := by simpa [pow_two] using hz2
  have hbase (g : Fin 3) (e : Fin 2) (s : Fin 24) :
      ∃ e' : Fin 2,
        order48_s4NormalGen a b c g * order48_s4SignedNormal z a b c (e, s) =
          order48_s4SignedNormal z a b c
            (e', order48_s4NormalNext g s) := by
    obtain ⟨d, hd⟩ := order48_s4SignedNormal_transition a b c z squareSign
      commutatorSign hzcenter hz2 ha hb hc hab hbc hac g s
    fin_cases e <;> fin_cases d
    · exact ⟨0, by simpa [order48_s4SignedNormal] using hd⟩
    · exact ⟨1, by simpa [order48_s4SignedNormal] using hd⟩
    · exact ⟨1, by
        simp only [order48_s4SignedNormal, pow_one]
        rw [show order48_s4NormalGen a b c g *
            (z * order48_s4Normal a b c s) =
            z * (order48_s4NormalGen a b c g * order48_s4Normal a b c s) by
          rw [← mul_assoc, (hzcomm _).eq.symm, mul_assoc], hd]
        simp⟩
    · exact ⟨0, by
        simp only [order48_s4SignedNormal, pow_one]
        norm_num at hd ⊢
        rw [show order48_s4NormalGen a b c g *
            (z * order48_s4Normal a b c s) =
            z * (order48_s4NormalGen a b c g * order48_s4Normal a b c s) by
          rw [← mul_assoc, (hzcomm _).eq.symm, mul_assoc], hd]
        rw [← mul_assoc, hzz, one_mul]⟩
  have hleft (g : Fin 4) (q : Fin 2 × Fin 24) :
      ∃ q' : Fin 2 × Fin 24,
        order48_s4SignedGen z a b c g * order48_s4SignedNormal z a b c q =
          order48_s4SignedNormal z a b c q' := by
    rcases q with ⟨e, s⟩
    fin_cases g
    · fin_cases e
      · exact ⟨(1, s), by simp [order48_s4SignedGen, order48_s4SignedNormal]⟩
      · exact ⟨(0, s), by
          simp only [order48_s4SignedGen, order48_s4SignedNormal, pow_one]
          rw [← mul_assoc, hzz, one_mul]
          simp⟩
    · obtain ⟨e', he'⟩ := hbase 0 e s
      exact ⟨(e', order48_s4NormalNext 0 s), by
        simpa [order48_s4SignedGen, order48_s4NormalGen] using he'⟩
    · obtain ⟨e', he'⟩ := hbase 1 e s
      exact ⟨(e', order48_s4NormalNext 1 s), by
        simpa [order48_s4SignedGen, order48_s4NormalGen] using he'⟩
    · obtain ⟨e', he'⟩ := hbase 2 e s
      exact ⟨(e', order48_s4NormalNext 2 s), by
        simpa [order48_s4SignedGen, order48_s4NormalGen] using he'⟩
  have hz_inv : z⁻¹ = z := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    exact hzz
  have hinvOfSquare (x : H) (hx : x ^ 2 = z ^ squareSign.val) :
      x⁻¹ = z ^ squareSign.val * x := by
    rw [inv_eq_iff_eq_inv, eq_inv_iff_mul_eq_one]
    have hpowcomm : Commute (z ^ squareSign.val) x :=
      ((hzcomm x).pow_left squareSign.val)
    calc
      x * (z ^ squareSign.val * x) = z ^ squareSign.val * (x * x) := by
        rw [← mul_assoc, hpowcomm.eq.symm, mul_assoc]
      _ = z ^ squareSign.val * z ^ squareSign.val := by
        rw [show x * x = z ^ squareSign.val by simpa [pow_two] using hx]
      _ = 1 := by
        fin_cases squareSign
        · simp
        · simpa [pow_two] using hz2
  have ha_inv := hinvOfSquare a ha
  have hb_inv := hinvOfSquare b hb
  have hc_inv := hinvOfSquare c hc
  have hzleft (q : Fin 2 × Fin 24) :
      ∃ q', z * order48_s4SignedNormal z a b c q = order48_s4SignedNormal z a b c q' := by
    obtain ⟨q', hq'⟩ := hleft (0 : Fin 4) q
    exact ⟨q', by simpa only [order48_s4SignedGen] using hq'⟩
  have haleft (q : Fin 2 × Fin 24) :
      ∃ q', a * order48_s4SignedNormal z a b c q = order48_s4SignedNormal z a b c q' := by
    obtain ⟨q', hq'⟩ := hleft (1 : Fin 4) q
    exact ⟨q', by simpa only [order48_s4SignedGen] using hq'⟩
  have hbleft (q : Fin 2 × Fin 24) :
      ∃ q', b * order48_s4SignedNormal z a b c q = order48_s4SignedNormal z a b c q' := by
    obtain ⟨q', hq'⟩ := hleft (2 : Fin 4) q
    exact ⟨q', by simpa only [order48_s4SignedGen] using hq'⟩
  have hcleft (q : Fin 2 × Fin 24) :
      ∃ q', c * order48_s4SignedNormal z a b c q = order48_s4SignedNormal z a b c q' := by
    obtain ⟨q', hq'⟩ := hleft (3 : Fin 4) q
    exact ⟨q', by simpa only [order48_s4SignedGen] using hq'⟩
  have hleftInv (g : Fin 4) (q : Fin 2 × Fin 24) :
      ∃ q' : Fin 2 × Fin 24,
        (order48_s4SignedGen z a b c g)⁻¹ * order48_s4SignedNormal z a b c q =
          order48_s4SignedNormal z a b c q' := by
    fin_cases g
    · simpa [order48_s4SignedGen, hz_inv] using hleft (0 : Fin 4) q
    · simp only [order48_s4SignedGen]
      rw [ha_inv]
      fin_cases squareSign
      · simpa using haleft q
      · obtain ⟨q₁, hq₁⟩ := haleft q
        obtain ⟨q₂, hq₂⟩ := hzleft q₁
        exact ⟨q₂, by rw [pow_one, mul_assoc, hq₁, hq₂]⟩
    · simp only [order48_s4SignedGen]
      rw [hb_inv]
      fin_cases squareSign
      · simpa using hbleft q
      · obtain ⟨q₁, hq₁⟩ := hbleft q
        obtain ⟨q₂, hq₂⟩ := hzleft q₁
        exact ⟨q₂, by rw [pow_one, mul_assoc, hq₁, hq₂]⟩
    · simp only [order48_s4SignedGen]
      rw [hc_inv]
      fin_cases squareSign
      · simpa using hcleft q
      · obtain ⟨q₁, hq₁⟩ := hcleft q
        obtain ⟨q₂, hq₂⟩ := hzleft q₁
        exact ⟨q₂, by rw [pow_one, mul_assoc, hq₁, hq₂]⟩
  have hsurj : Function.Surjective (FreeGroup.lift (order48_s4SignedGen z a b c)) := by
    rw [← MonoidHom.range_eq_top, FreeGroup.range_lift_eq_closure]
    exact hgen
  have hword (w : FreeGroup (Fin 4)) : ∀ q : Fin 2 × Fin 24,
      ∃ q' : Fin 2 × Fin 24,
        FreeGroup.lift (order48_s4SignedGen z a b c) w *
            order48_s4SignedNormal z a b c q = order48_s4SignedNormal z a b c q' := by
    induction w using FreeGroup.induction_on with
    | C1 => exact fun q => ⟨q, by simp⟩
    | of g =>
        intro q
        simpa only [FreeGroup.lift_apply_of] using hleft g q
    | inv_of g hg =>
        intro q
        simpa only [map_inv, FreeGroup.lift_apply_of] using hleftInv g q
    | mul x y hx hy =>
        intro q
        obtain ⟨q₁, hq₁⟩ := hy q
        obtain ⟨q₂, hq₂⟩ := hx q₁
        exact ⟨q₂, by rw [map_mul, mul_assoc, hq₁, hq₂]⟩
  have hnormalSurj : Function.Surjective (order48_s4SignedNormal z a b c) := by
    intro x
    obtain ⟨w, rfl⟩ := hsurj x
    obtain ⟨q, hq⟩ := hword w (0, 0)
    exact ⟨q, by
      simpa [order48_s4SignedNormal, order48_s4Normal, order48_s4NormalA,
        order48_s4NormalB, order48_s4NormalC] using hq.symm⟩
  letI : Finite H := Finite.of_surjective (order48_s4SignedNormal z a b c) hnormalSurj
  refine ⟨inferInstance, ?_⟩
  simpa [Nat.card_prod] using
    Nat.card_le_card_of_surjective (order48_s4SignedNormal z a b c) hnormalSurj

/-- Cardinal-only form of the signed normal-form theorem. -/
theorem natCard_le_48_of_s4_signed_coxeter_generators
    (z : H) (squareSign commutatorSign : Fin 2)
    (hzcenter : z ∈ Subgroup.center H) (hz2 : z ^ 2 = 1)
    (ha : a ^ 2 = z ^ squareSign.val)
    (hb : b ^ 2 = z ^ squareSign.val)
    (hc : c ^ 2 = z ^ squareSign.val)
    (hab : (a * b) ^ 3 = 1) (hbc : (b * c) ^ 3 = 1)
    (hac : a * c * a⁻¹ * c⁻¹ = z ^ commutatorSign.val)
    (hgen : Subgroup.closure (Set.range (order48_s4SignedGen z a b c)) = ⊤) :
    Nat.card H ≤ 48 :=
  (finite_and_natCard_le_48_of_s4_signed_coxeter_generators a b c z squareSign
    commutatorSign hzcenter hz2 ha hb hc hab hbc hac hgen).2

end S4NormalForm

end Smallgroups.UsefulTheorems
