/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.Counting
import Smallgroups.UsefulTheorems.P3Group
import Smallgroups.UsefulTheorems.PrimePairNonabelian
import Smallgroups.UsefulTheorems.OrderP4_Abel
import Smallgroups.UsefulTheorems.OrderP4_NonAbel
import Mathlib.Tactic.NormNum.Prime

/-!
# First structural facts for groups of order `81`

`81 = 3^4`.  The abelian part is already covered by the general classification of abelian
groups of order `p^4`, giving the five groups corresponding to the partitions of `4`.

For the non-abelian part, this file records the first split supplied by the existing
`OrderP4_NonAbel` development: the center has order `3` or `9`, and hence is one of
`C_3`, `C_9`, or `C_3 × C_3`.

This is intentionally not yet a full classification of groups of order `81`: it records the
fifteen representatives and their pairwise distinctness, but not the exhaustiveness theorem.
-/

namespace Smallgroups.UsefulTheorems

open Subgroup
open P3Group
open scoped commutatorElement

noncomputable local instance instFintypeOrder81SemidirectProduct {N H : Type*} [Group N]
    [Group H] [Fintype N] [Fintype H] (φ : H →* MulAut N) :
    Fintype (SemidirectProduct N H φ) :=
  Fintype.ofEquiv (N × H) SemidirectProduct.equivProd.symm

/-! ## Counting power torsion as an isomorphism invariant -/

/-- The cardinality of `{x | x ^ n = 1}`. -/
noncomputable def order81_pow_eq_one_card (H : Type*) [Group H] (n : ℕ) : ℕ :=
  Nat.card {x : H // x ^ n = 1}

noncomputable local instance instFintypeOrder81PowEqOneSubtype {H : Type*} [Group H]
    [Fintype H] [DecidableEq H] (n : ℕ) : Fintype {x : H // x ^ n = 1} :=
  Subtype.fintype _

/-- The cardinality of `{z ∈ Z(H) | z ^ n = 1}`. -/
noncomputable def order81_center_pow_eq_one_card (H : Type*) [Group H] (n : ℕ) : ℕ :=
  Nat.card {z : Subgroup.center H // z.1 ^ n = 1}

noncomputable local instance instFintypeOrder81CenterPowEqOneSubtype {H : Type*} [Group H]
    [Fintype H] [DecidableEq H] (n : ℕ) :
    Fintype {z : Subgroup.center H // z.1 ^ n = 1} :=
  Subtype.fintype _

private theorem order81_nat_card_eq_of_fintype_card_eq {α : Type*} [Fintype α] {n : Nat}
    (h : Fintype.card α = n) : Nat.card α = n :=
  Nat.card_eq_of_equiv_fin (Fintype.equivFinOfCardEq h)

noncomputable def order81_powEqOneEquivOfMulEquiv {H K : Type*} [Group H] [Group K]
    (n : ℕ) (e : H ≃* K) : {x : H // x ^ n = 1} ≃ {x : K // x ^ n = 1} where
  toFun x := ⟨e x.1, by rw [← map_pow, x.2, map_one]⟩
  invFun x := ⟨e.symm x.1, by
    rw [← map_pow]
    exact e.injective (by simp [x.2])⟩
  left_inv x := by ext; simp
  right_inv x := by ext; simp

theorem order81_pow_eq_one_card_eq_of_mulEquiv {H K : Type*} [Group H] [Group K]
    (n : ℕ) (e : H ≃* K) :
    order81_pow_eq_one_card H n = order81_pow_eq_one_card K n :=
  Nat.card_congr (order81_powEqOneEquivOfMulEquiv n e)

theorem order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne {H K : Type*} [Group H]
    [Group K] {n : ℕ}
    (h : order81_pow_eq_one_card H n ≠ order81_pow_eq_one_card K n) :
    ¬ Nonempty (H ≃* K) := by
  rintro ⟨e⟩
  exact h (order81_pow_eq_one_card_eq_of_mulEquiv n e)

noncomputable def order81_centerPowEqOneEquivOfMulEquiv {H K : Type*} [Group H] [Group K]
    (n : ℕ) (e : H ≃* K) :
    {z : Subgroup.center H // z.1 ^ n = 1} ≃ {z : Subgroup.center K // z.1 ^ n = 1} where
  toFun z := ⟨⟨e z.1.1, by
    rw [Subgroup.mem_center_iff]
    intro y
    have hzmem := z.1.2
    rw [Subgroup.mem_center_iff] at hzmem
    have h := congrArg e (hzmem (e.symm y))
    simpa using h⟩, by rw [← map_pow, z.2, map_one]⟩
  invFun z := ⟨⟨e.symm z.1.1, by
    rw [Subgroup.mem_center_iff]
    intro x
    have hzmem := z.1.2
    rw [Subgroup.mem_center_iff] at hzmem
    have h := congrArg e.symm (hzmem (e x))
    simpa using h⟩, by
      rw [← map_pow]
      exact e.injective (by simp [z.2])⟩
  left_inv z := by ext; simp
  right_inv z := by ext; simp

theorem order81_center_pow_eq_one_card_eq_of_mulEquiv {H K : Type*} [Group H] [Group K]
    (n : ℕ) (e : H ≃* K) :
    order81_center_pow_eq_one_card H n = order81_center_pow_eq_one_card K n :=
  Nat.card_congr (order81_centerPowEqOneEquivOfMulEquiv n e)

theorem order81_not_nonempty_mulEquiv_of_center_pow_eq_one_card_ne {H K : Type*} [Group H]
    [Group K] {n : ℕ}
    (h : order81_center_pow_eq_one_card H n ≠ order81_center_pow_eq_one_card K n) :
    ¬ Nonempty (H ≃* K) := by
  rintro ⟨e⟩
  exact h (order81_center_pow_eq_one_card_eq_of_mulEquiv n e)

/-! ## The cube subgroup as an isomorphism invariant -/

/-- The subgroup generated by all cubes. -/
def cubeSubgroup (G : Type*) [Group G] : Subgroup G :=
  Subgroup.closure {x : G | ∃ y : G, y ^ 3 = x}

theorem cube_mem_cubeSubgroup {G : Type*} [Group G] (x : G) :
    x ^ 3 ∈ cubeSubgroup G := by
  exact Subgroup.subset_closure ⟨x, rfl⟩

/-- The cube subgroup is preserved by group isomorphisms. -/
theorem map_cubeSubgroup {G H : Type*} [Group G] [Group H] (e : G ≃* H) :
    Subgroup.map e.toMonoidHom (cubeSubgroup G) = cubeSubgroup H := by
  apply le_antisymm
  · rw [cubeSubgroup, MonoidHom.map_closure]
    rw [Subgroup.closure_le]
    rintro y ⟨x, hx, rfl⟩
    rcases hx with ⟨z, rfl⟩
    simpa [map_pow] using cube_mem_cubeSubgroup (e z)
  · rw [cubeSubgroup, Subgroup.closure_le]
    intro y hy
    rcases hy with ⟨z, rfl⟩
    exact ⟨(e.symm z) ^ 3, cube_mem_cubeSubgroup (e.symm z), by simp [map_pow]⟩

/-- If all commutators of `G` lie in the cube subgroup, the same is true for any isomorphic
group. -/
theorem commutators_mem_cubeSubgroup_of_mulEquiv {G H : Type*} [Group G] [Group H]
    (e : G ≃* H) (hG : ∀ x y : G, x * y * x⁻¹ * y⁻¹ ∈ cubeSubgroup G) :
    ∀ x y : H, x * y * x⁻¹ * y⁻¹ ∈ cubeSubgroup H := by
  intro x y
  let x' := e.symm x
  let y' := e.symm y
  have hmapped : e (x' * y' * x'⁻¹ * y'⁻¹) ∈
      Subgroup.map e.toMonoidHom (cubeSubgroup G) := by
    exact ⟨x' * y' * x'⁻¹ * y'⁻¹, hG x' y', rfl⟩
  rw [map_cubeSubgroup e] at hmapped
  simpa [x', y', map_mul, map_inv] using hmapped

/-! ## The five abelian representatives -/

/-- The five abelian representatives of order `81`. -/
noncomputable abbrev order81_abelian_reps : Fin 5 → Type :=
  orderP4Abel_reps 3

noncomputable instance instCommGroupOrder81AbelianReps (i : Fin 5) :
    CommGroup (order81_abelian_reps i) :=
  inferInstance

/-- Every abelian representative has order `81`. -/
theorem card_order81_abelian_reps (i : Fin 5) :
    Nat.card (order81_abelian_reps i) = 81 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  dsimp [order81_abelian_reps]
  rw [card_orderP4Abel_reps 3 i]
  norm_num

/-- Every abelian group of order `81` is isomorphic to one of the five abelian representatives. -/
theorem order81_abelian_complete (G : Type*) [CommGroup G] (hcard : Nat.card G = 81) :
    ∃ i, Nonempty (G ≃* order81_abelian_reps i) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  dsimp [order81_abelian_reps]
  exact orderP4Abel_complete 3 G (by rw [hcard]; norm_num)

/-- The five abelian representatives of order `81` are pairwise non-isomorphic. -/
theorem order81_abelian_distinct : PairwiseNonMulEquiv order81_abelian_reps := by
  intro i j h
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  dsimp [order81_abelian_reps] at h ⊢
  exact orderP4Abel_distinct 3 i j h

/-! ## The first non-abelian split -/

/-- In a non-abelian group of order `81`, the center has order `3` or `9`. -/
theorem order81_center_card_eq_three_or_nine {G : Type*} [Group G]
    (hcard : Nat.card G = 81) (hnonab : ¬ (∀ a b : G, a * b = b * a)) :
    Nat.card (center G) = 3 ∨ Nat.card (center G) = 9 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Finite G := Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  have hcard' : Nat.card G = 3 ^ 4 := by
    rw [hcard]
    norm_num
  rcases center_card_eq_p_or_p_sq_of_nonabelian_p4 (p := 3) hcard' hnonab with hcenter | hcenter
  · exact Or.inl hcenter
  · right
    rw [hcenter]
    norm_num

/-- In a non-abelian group of order `81`, the center is `C_3`, `C_9`, or `C_3 × C_3`. -/
theorem order81_center_classification_of_nonabelian {G : Type*} [Group G]
    (hcard : Nat.card G = 81) (hnonab : ¬ (∀ a b : G, a * b = b * a)) :
    Nonempty (center G ≃* CyclicRep 3) ∨
    Nonempty (center G ≃* CyclicRep 9) ∨
    Nonempty (center G ≃* ElemAbelianRep 3) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Finite G := Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  have hcard' : Nat.card G = 3 ^ 4 := by
    rw [hcard]
    norm_num
  simpa using center_classification_of_nonabelian_p4 (p := 3) hcard' hnonab

/-! ## Two immediate non-abelian representatives -/

/-- The non-abelian group of order `27` and exponent `9`, reused in order `81` products. -/
abbrev order81_SemidirectP2P : Type :=
  SemidirectP2P 3

/-- The standard order-`9` generator in `SemidirectP2P 3`. -/
abbrev order81_p2pA : order81_SemidirectP2P :=
  ⟨1, 0⟩

/-- `HeisenbergGroup 3 × C_3`, a non-abelian group of order `81`. -/
abbrev order81_heisenberg_prod_cyclic : Type :=
  HeisenbergGroup 3 × CyclicRep 3

/-- `SemidirectP2P 3 × C_3`, a non-abelian group of order `81`. -/
abbrev order81_semidirectP2P_prod_cyclic : Type :=
  order81_SemidirectP2P × CyclicRep 3

/-- `HeisenbergGroup 3 × C_3` has order `81`. -/
theorem card_order81_heisenberg_prod_cyclic :
    Nat.card order81_heisenberg_prod_cyclic = 81 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  rw [order81_heisenberg_prod_cyclic, Nat.card_prod, HeisenbergGroup.card_heisenberg 3,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]
  norm_num

/-- `SemidirectP2P 3 × C_3` has order `81`. -/
theorem card_order81_semidirectP2P_prod_cyclic :
    Nat.card order81_semidirectP2P_prod_cyclic = 81 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  rw [order81_semidirectP2P_prod_cyclic, Nat.card_prod,
    SemidirectP2P.card_semidirectP2P 3, card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]
  norm_num

/-- `HeisenbergGroup 3 × C_3` is non-abelian. -/
theorem order81_heisenberg_prod_cyclic_nonabelian :
    ¬ ∀ x y : order81_heisenberg_prod_cyclic, x * y = y * x := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  intro hcomm
  exact HeisenbergGroup.heisenberg_nonabelian 3 (by
    intro x y
    have h := hcomm ((x, (1 : CyclicRep 3)) : order81_heisenberg_prod_cyclic)
      ((y, (1 : CyclicRep 3)) : order81_heisenberg_prod_cyclic)
    exact congrArg Prod.fst h)

/-- `SemidirectP2P 3 × C_3` is non-abelian. -/
theorem order81_semidirectP2P_prod_cyclic_nonabelian :
    ¬ ∀ x y : order81_semidirectP2P_prod_cyclic, x * y = y * x := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  intro hcomm
  exact SemidirectP2P.semidirectP2P_nonabelian 3 (by
    intro x y
    have h := hcomm ((x, (1 : CyclicRep 3)) : order81_semidirectP2P_prod_cyclic)
      ((y, (1 : CyclicRep 3)) : order81_semidirectP2P_prod_cyclic)
    exact congrArg Prod.fst h)

theorem order81_p2pA_cube_mem_center :
    order81_p2pA ^ 3 ∈ Subgroup.center order81_SemidirectP2P := by
  rw [Subgroup.mem_center_iff]
  intro x
  cases x with
  | mk a b =>
      fin_cases a <;> fin_cases b <;> decide +kernel

theorem orderOf_order81_p2pA_cube : orderOf (order81_p2pA ^ 3) = 3 := by
  have hpow : (order81_p2pA ^ 3) ^ 3 = 1 := by decide +kernel
  have hne : order81_p2pA ^ 3 ≠ 1 := by decide +kernel
  exact orderOf_eq_prime hpow hne

/-- The center of `SemidirectP2P 3` is generated by the cube of its order-`9` generator. -/
theorem order81_semidirectP2P_center_eq_zpowers :
    Subgroup.zpowers (order81_p2pA ^ 3) =
      Subgroup.center order81_SemidirectP2P := by
  apply le_antisymm
  · intro x hx
    rw [Subgroup.mem_zpowers_iff] at hx
    rcases hx with ⟨n, rfl⟩
    exact Subgroup.zpow_mem _ order81_p2pA_cube_mem_center n
  · intro x hx
    have hcenter_card : Nat.card (Subgroup.center order81_SemidirectP2P) = 3 :=
      P3Group.center_card_eq_p_of_nonabelian
        (p := 3) (by
          haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
          simpa [order81_SemidirectP2P] using P3Group.SemidirectP2P.card_semidirectP2P 3)
        (P3Group.SemidirectP2P.semidirectP2P_nonabelian 3)
    have hzp_card : Nat.card (Subgroup.zpowers (order81_p2pA ^ 3)) = 3 := by
      rw [Nat.card_zpowers]
      exact orderOf_order81_p2pA_cube
    have hle : Subgroup.zpowers (order81_p2pA ^ 3) ≤
        Subgroup.center order81_SemidirectP2P := by
      intro y hy
      rw [Subgroup.mem_zpowers_iff] at hy
      rcases hy with ⟨n, rfl⟩
      exact Subgroup.zpow_mem _ order81_p2pA_cube_mem_center n
    have htop := Subgroup.eq_of_le_of_card_ge hle (by rw [hzp_card, hcenter_card])
    exact htop ▸ hx

theorem order81_semidirectP2P_commutator_mem_zpowers (x y : order81_SemidirectP2P) :
    x * y * x⁻¹ * y⁻¹ ∈ Subgroup.zpowers (order81_p2pA ^ 3) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  have hmem : ⁅x, y⁆ ∈ _root_.commutator order81_SemidirectP2P := by
    change ⁅x, y⁆ ∈ ⁅(⊤ : Subgroup order81_SemidirectP2P),
      (⊤ : Subgroup order81_SemidirectP2P)⁆
    exact Subgroup.commutator_mem_commutator (Subgroup.mem_top x) (Subgroup.mem_top y)
  have hcenter : ⁅x, y⁆ ∈ Subgroup.center order81_SemidirectP2P := by
    rwa [P3Group.commutator_eq_center
        (p := 3)
        (by simpa [order81_SemidirectP2P] using P3Group.SemidirectP2P.card_semidirectP2P 3)
        (P3Group.SemidirectP2P.semidirectP2P_nonabelian 3)] at hmem
  rw [order81_semidirectP2P_center_eq_zpowers]
  simpa [commutatorElement_def] using hcenter

/-- In `SemidirectP2P 3 × C_3`, every commutator lies in the cube subgroup. -/
theorem order81_semidirectP2P_prod_cyclic_commutators_mem_cubeSubgroup :
    ∀ x y : order81_semidirectP2P_prod_cyclic,
      x * y * x⁻¹ * y⁻¹ ∈ cubeSubgroup order81_semidirectP2P_prod_cyclic := by
  rintro ⟨x₁, x₂⟩ ⟨y₁, y₂⟩
  have hzp := order81_semidirectP2P_commutator_mem_zpowers x₁ y₁
  rcases Subgroup.mem_zpowers_iff.mp hzp with ⟨k, hk⟩
  let c : order81_semidirectP2P_prod_cyclic := (order81_p2pA, 1)
  have hc : c ^ 3 ∈ cubeSubgroup order81_semidirectP2P_prod_cyclic :=
    cube_mem_cubeSubgroup c
  have hk_mem : (c ^ 3) ^ k ∈ cubeSubgroup order81_semidirectP2P_prod_cyclic :=
    Subgroup.zpow_mem _ hc k
  have hcyc : x₂ * y₂ * x₂⁻¹ * y₂⁻¹ = 1 := by
    simp [mul_assoc]
  simpa [c, hk, hcyc] using hk_mem

/-- `HeisenbergGroup 3 × C_3` has exponent `3`. -/
theorem exponent_order81_heisenberg_prod_cyclic :
    Monoid.exponent order81_heisenberg_prod_cyclic = 3 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  change Monoid.exponent (HeisenbergGroup 3 × CyclicRep 3) = 3
  rw [Monoid.exponent_prod, HeisenbergGroup.heisenberg_exponent 3 (by norm_num)]
  simp only [Monoid.exponent_multiplicative, ZMod.exponent]
  norm_num [lcm_eq_nat_lcm]

/-- `SemidirectP2P 3 × C_3` has exponent `9`. -/
theorem exponent_order81_semidirectP2P_prod_cyclic :
    Monoid.exponent order81_semidirectP2P_prod_cyclic = 9 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  change Monoid.exponent (SemidirectP2P 3 × CyclicRep 3) = 9
  rw [Monoid.exponent_prod, SemidirectP2P.semidirectP2P_exponent 3]
  simp only [Monoid.exponent_multiplicative, ZMod.exponent]
  norm_num [lcm_eq_nat_lcm]

/-- The two direct-product non-abelian representatives are not isomorphic. -/
theorem order81_heisenberg_prod_cyclic_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_heisenberg_prod_cyclic ≃* order81_semidirectP2P_prod_cyclic) := by
  rintro ⟨e⟩
  have hExp : Monoid.exponent order81_heisenberg_prod_cyclic =
      Monoid.exponent order81_semidirectP2P_prod_cyclic :=
    Monoid.exponent_eq_of_mulEquiv e
  rw [exponent_order81_heisenberg_prod_cyclic, exponent_order81_semidirectP2P_prod_cyclic] at hExp
  norm_num at hExp

/-- The two direct-product non-abelian representatives of order `81`. -/
abbrev order81_direct_nonabelian_reps : Fin 2 → Type :=
  rep2 order81_heisenberg_prod_cyclic order81_semidirectP2P_prod_cyclic

/-- Each direct-product non-abelian representative has order `81`. -/
theorem card_order81_direct_nonabelian_reps (i : Fin 2) :
    Nat.card (order81_direct_nonabelian_reps i) = 81 := by
  fin_cases i
  · exact card_order81_heisenberg_prod_cyclic
  · exact card_order81_semidirectP2P_prod_cyclic

/-- Each direct-product non-abelian representative is non-abelian. -/
theorem order81_direct_nonabelian_reps_nonabelian (i : Fin 2) :
    ¬ ∀ x y : order81_direct_nonabelian_reps i, x * y = y * x := by
  fin_cases i
  · exact order81_heisenberg_prod_cyclic_nonabelian
  · exact order81_semidirectP2P_prod_cyclic_nonabelian

/-- The two direct-product non-abelian representatives are pairwise non-isomorphic. -/
theorem order81_direct_nonabelian_reps_pairwise :
    PairwiseNonMulEquiv order81_direct_nonabelian_reps := by
  intro i j h
  fin_cases i <;> fin_cases j
  · rfl
  · exact absurd h order81_heisenberg_prod_cyclic_not_equiv_semidirectP2P_prod_cyclic
  · exact absurd ⟨h.some.symm⟩
      order81_heisenberg_prod_cyclic_not_equiv_semidirectP2P_prod_cyclic
  · rfl

/-! ## A split `C_9 × C_3` extension by `C_3` -/

/-- `C_9 × C_3`, written multiplicatively. -/
abbrev order81_C9C3 : Type :=
  Multiplicative (ZMod 9) × Multiplicative (ZMod 3)

/-- Reduction modulo `3`, as a ring hom `ZMod 9 →+* ZMod 3`. -/
noncomputable abbrev order81_zmod9To3 : ZMod 9 →+* ZMod 3 :=
  ZMod.castHom (by norm_num : 3 ∣ 9) (ZMod 3)

/-- The additive shear `(a, b) ↦ (a, b + a mod 3)` on `ZMod 9 × ZMod 3`. -/
noncomputable def order81_c9c3_shearAddEquiv : (ZMod 9 × ZMod 3) ≃+ (ZMod 9 × ZMod 3) where
  toFun x := (x.1, x.2 + order81_zmod9To3 x.1)
  invFun x := (x.1, x.2 - order81_zmod9To3 x.1)
  left_inv := by
    intro x
    ext <;> simp [order81_zmod9To3]
  right_inv := by
    intro x
    ext <;> simp [order81_zmod9To3]
  map_add' := by
    intro x y
    ext <;> simp [order81_zmod9To3, add_assoc, add_left_comm]

/-- The corresponding automorphism of `C_9 × C_3`. -/
noncomputable def order81_c9c3_shearAut : MulAut order81_C9C3 :=
  (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)).symm.trans
    ((AddEquiv.toMultiplicative order81_c9c3_shearAddEquiv).trans
      (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)))

@[simp] theorem order81_c9c3_shearAut_apply (a : ZMod 9) (b : ZMod 3) :
    order81_c9c3_shearAut
      ((Multiplicative.ofAdd a, Multiplicative.ofAdd b) : order81_C9C3) =
      (Multiplicative.ofAdd a, Multiplicative.ofAdd (b + order81_zmod9To3 a)) := by
  rfl

/-- The shear automorphism has order dividing `3`. -/
theorem order81_c9c3_shearAut_pow_three : order81_c9c3_shearAut ^ 3 = 1 := by
  ext x <;> fin_cases x <;> rfl

/-- The action of `C_3` generated by a chosen automorphism whose cube is the identity. -/
noncomputable def order81_actionOfOrderThree {N : Type*} [Group N]
    (α : MulAut N) (hα : α ^ 3 = 1) : CyclicRep 3 →* MulAut N :=
  MonoidHom.mk' (fun x => α ^ (Multiplicative.toAdd x).val)
    (fun x y => pow_val_add hα (Multiplicative.toAdd x) (Multiplicative.toAdd y))

theorem order81_actionOfOrderThree_ofAdd_one {N : Type*} [Group N]
    (α : MulAut N) (hα : α ^ 3 = 1) :
    order81_actionOfOrderThree α hα (Multiplicative.ofAdd (1 : ZMod 3)) = α := by
  change α ^ (1 : ZMod 3).val = α
  rw [show (1 : ZMod 3).val = 1 by decide, pow_one]

/-- The `C_3` action on `C_9 × C_3` generated by the shear automorphism. -/
noncomputable abbrev order81_c9c3_shearAction : CyclicRep 3 →* MulAut order81_C9C3 :=
  order81_actionOfOrderThree order81_c9c3_shearAut order81_c9c3_shearAut_pow_three

/-- The split semidirect product `(C_9 × C_3) ⋊ C_3` using the shear action. -/
abbrev order81_c9c3_shear_rep : Type :=
  SemidirectProduct order81_C9C3 (CyclicRep 3) order81_c9c3_shearAction

theorem card_order81_C9C3 : Nat.card order81_C9C3 = 27 := by
  rw [order81_C9C3, Nat.card_prod, card_cyclicRep (by norm_num : (9 : ℕ) ≠ 0),
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

/-- The shear semidirect product has order `81`. -/
theorem card_order81_c9c3_shear_rep : Nat.card order81_c9c3_shear_rep = 81 := by
  rw [order81_c9c3_shear_rep, SemidirectProduct.card, card_order81_C9C3,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

/-- The shear semidirect product is non-abelian. -/
theorem order81_c9c3_shear_rep_nonabelian :
    ¬ ∀ x y : order81_c9c3_shear_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_C9C3 :=
    (Multiplicative.ofAdd (1 : ZMod 9), Multiplicative.ofAdd (0 : ZMod 3))
  have hfix : order81_c9c3_shearAut n = n := by
    have heq : (SemidirectProduct.inl (order81_c9c3_shearAction g n) :
        order81_c9c3_shear_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c9c3_shear_rep)
        (SemidirectProduct.inl n : order81_c9c3_shear_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c9c3_shearAction) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [order81_c9c3_shearAction, g, order81_actionOfOrderThree_ofAdd_one] using hinj
  have hnot : order81_c9c3_shearAut n ≠ n := by
    intro h
    have hsnd := congrArg (fun z : order81_C9C3 => Multiplicative.toAdd z.2) h
    norm_num [order81_c9c3_shearAut, order81_c9c3_shearAddEquiv, order81_zmod9To3, n] at hsnd
  exact hnot hfix

/-- A visible element of order `9` in the shear semidirect product. -/
noncomputable def order81_c9c3_shear_orderNineElem : order81_c9c3_shear_rep :=
  SemidirectProduct.inl
    ((Multiplicative.ofAdd (1 : ZMod 9), Multiplicative.ofAdd (0 : ZMod 3)) : order81_C9C3)

theorem orderOf_order81_c9c3_shear_orderNineElem :
    orderOf order81_c9c3_shear_orderNineElem = 9 := by
  unfold order81_c9c3_shear_orderNineElem
  rw [orderOf_injective SemidirectProduct.inl SemidirectProduct.inl_injective]
  rw [Prod.orderOf_mk]
  rw [orderOf_ofAdd_eq_addOrderOf, orderOf_ofAdd_eq_addOrderOf]
  rw [ZMod.addOrderOf_one]
  norm_num [lcm_eq_nat_lcm]

/-- The shear semidirect product is not the exponent-`3` direct-product representative. -/
theorem order81_c9c3_shear_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9c3_shear_rep ≃* order81_heisenberg_prod_cyclic) := by
  rintro ⟨e⟩
  have hord : orderOf (e order81_c9c3_shear_orderNineElem) = 9 := by
    rw [MulEquiv.orderOf_eq e, orderOf_order81_c9c3_shear_orderNineElem]
  have hdvd : orderOf (e order81_c9c3_shear_orderNineElem) ∣
      Monoid.exponent order81_heisenberg_prod_cyclic :=
    Monoid.order_dvd_exponent _
  rw [hord, exponent_order81_heisenberg_prod_cyclic] at hdvd
  norm_num at hdvd

/-- The `C_3` generator acting on the shear semidirect product. -/
noncomputable def order81_c9c3_shear_actionGen : order81_c9c3_shear_rep :=
  SemidirectProduct.inr (Multiplicative.ofAdd (1 : ZMod 3))

/-- The second `C_3` generator in the normal `C_9 × C_3` subgroup. -/
noncomputable def order81_c9c3_shear_bElem : order81_c9c3_shear_rep :=
  SemidirectProduct.inl
    ((Multiplicative.ofAdd (0 : ZMod 9), Multiplicative.ofAdd (1 : ZMod 3)) :
      order81_C9C3)

theorem order81_c9c3_shear_cube_mem_zpowers (x : order81_c9c3_shear_rep) :
    x ^ 3 ∈ Subgroup.zpowers (order81_c9c3_shear_orderNineElem ^ 3) := by
  cases x with
  | mk n g =>
      cases n with
      | mk a b =>
          fin_cases a <;> fin_cases b <;> fin_cases g <;>
            rw [Subgroup.mem_zpowers_iff] <;>
            first
            | exact ⟨0, by decide +kernel⟩
            | exact ⟨1, by decide +kernel⟩
            | exact ⟨2, by decide +kernel⟩

theorem order81_c9c3_shear_cubeSubgroup_le_zpowers :
    cubeSubgroup order81_c9c3_shear_rep ≤
      Subgroup.zpowers (order81_c9c3_shear_orderNineElem ^ 3) := by
  rw [cubeSubgroup, Subgroup.closure_le]
  intro z hz
  rcases hz with ⟨x, rfl⟩
  exact order81_c9c3_shear_cube_mem_zpowers x

theorem orderOf_order81_c9c3_shear_orderNineElem_cube :
    orderOf (order81_c9c3_shear_orderNineElem ^ 3) = 3 := by
  have hpow : (order81_c9c3_shear_orderNineElem ^ 3) ^ 3 = 1 := by decide +kernel
  have hne : order81_c9c3_shear_orderNineElem ^ 3 ≠ 1 := by decide +kernel
  exact orderOf_eq_prime hpow hne

theorem order81_c9c3_shear_commutator_witness_eq :
    order81_c9c3_shear_actionGen * order81_c9c3_shear_orderNineElem *
        order81_c9c3_shear_actionGen⁻¹ * order81_c9c3_shear_orderNineElem⁻¹ =
      order81_c9c3_shear_bElem := by
  decide +kernel

theorem order81_c9c3_shear_bElem_not_mem_zpowers :
    order81_c9c3_shear_bElem ∉
      Subgroup.zpowers (order81_c9c3_shear_orderNineElem ^ 3) := by
  intro h
  rw [Subgroup.mem_zpowers_iff] at h
  rcases h with ⟨k, hk⟩
  have hmod : k ≡ k % 3 [ZMOD (3 : ℤ)] := by
    rw [Int.modEq_iff_dvd]
    refine ⟨-(k / 3), ?_⟩
    have h := Int.emod_add_mul_ediv k 3
    omega
  have hpow : (order81_c9c3_shear_orderNineElem ^ 3) ^ k =
      (order81_c9c3_shear_orderNineElem ^ 3) ^ (k % 3) := by
    apply zpow_eq_zpow_iff_modEq.mpr
    rw [orderOf_order81_c9c3_shear_orderNineElem_cube]
    exact hmod
  have hcases : k % 3 = 0 ∨ k % 3 = 1 ∨ k % 3 = 2 := by
    have hnonneg : 0 ≤ k % 3 := Int.emod_nonneg k (by norm_num)
    have hlt : k % 3 < 3 := Int.emod_lt_of_pos k (by norm_num)
    omega
  rcases hcases with h0 | h1 | h2
  · have hb : order81_c9c3_shear_bElem = 1 := by rw [← hk, hpow, h0]; simp
    have : order81_c9c3_shear_bElem ≠ 1 := by decide +kernel
    exact this hb
  · have hb : order81_c9c3_shear_bElem = order81_c9c3_shear_orderNineElem ^ 3 := by
      rw [← hk, hpow, h1]
      simp
    have : order81_c9c3_shear_bElem ≠ order81_c9c3_shear_orderNineElem ^ 3 := by
      decide +kernel
    exact this hb
  · have hb : order81_c9c3_shear_bElem = order81_c9c3_shear_orderNineElem ^ 6 := by
      rw [← hk, hpow, h2]
      change (order81_c9c3_shear_orderNineElem ^ 3) ^ (2 : ℕ) =
        order81_c9c3_shear_orderNineElem ^ 6
      rw [← pow_mul]
    have : order81_c9c3_shear_bElem ≠ order81_c9c3_shear_orderNineElem ^ 6 := by
      decide +kernel
    exact this hb

/-- In the shear semidirect product, not every commutator lies in the cube subgroup. -/
theorem order81_c9c3_shear_has_commutator_not_mem_cubeSubgroup :
    ¬ ∀ x y : order81_c9c3_shear_rep,
      x * y * x⁻¹ * y⁻¹ ∈ cubeSubgroup order81_c9c3_shear_rep := by
  intro h
  have hb_cube := h order81_c9c3_shear_actionGen order81_c9c3_shear_orderNineElem
  rw [order81_c9c3_shear_commutator_witness_eq] at hb_cube
  exact order81_c9c3_shear_bElem_not_mem_zpowers
    (order81_c9c3_shear_cubeSubgroup_le_zpowers hb_cube)

/-- The shear semidirect product is not isomorphic to `SemidirectP2P 3 × C_3`.

The invariant is the cube subgroup: for `SemidirectP2P 3 × C_3`, all commutators lie in the
subgroup generated by cubes; for the shear product, a concrete commutator survives modulo that
subgroup. -/
theorem order81_c9c3_shear_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9c3_shear_rep ≃* order81_semidirectP2P_prod_cyclic) := by
  rintro ⟨e⟩
  have hshear := commutators_mem_cubeSubgroup_of_mulEquiv e.symm
    order81_semidirectP2P_prod_cyclic_commutators_mem_cubeSubgroup
  exact order81_c9c3_shear_has_commutator_not_mem_cubeSubgroup hshear

theorem order81_c9c3_shear_pow_nine (x : order81_c9c3_shear_rep) : x ^ 9 = 1 := by
  cases x with
  | mk n g =>
      cases n with
      | mk a b =>
          fin_cases a <;> fin_cases b <;> fin_cases g <;> decide +kernel

theorem card_pow_three_eq_one_order81_heisenberg_prod_cyclic :
    order81_pow_eq_one_card order81_heisenberg_prod_cyclic 3 = 81 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_pow_three_eq_one_order81_semidirectP2P_prod_cyclic :
    order81_pow_eq_one_card order81_semidirectP2P_prod_cyclic 3 = 27 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_pow_three_eq_one_order81_c9c3_shear_rep :
    order81_pow_eq_one_card order81_c9c3_shear_rep 3 = 27 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

/-! ## A second split `C_9 × C_3` extension by `C_3` -/

/-- The additive homomorphism `ZMod 3 → ZMod 9`, `b ↦ 3 * b`. -/
noncomputable def order81_c9c3_liftAddHom : ZMod 3 →+ ZMod 9 where
  toFun b := (3 : ZMod 9) * b.val
  map_zero' := by decide +kernel
  map_add' := by
    intro b d
    fin_cases b <;> fin_cases d <;> decide +kernel

/-- The additive shear `(a, b) ↦ (a + 3b, b)` on `ZMod 9 × ZMod 3`. -/
noncomputable def order81_c9c3_liftAddEquiv : (ZMod 9 × ZMod 3) ≃+ (ZMod 9 × ZMod 3) where
  toFun x := (x.1 + order81_c9c3_liftAddHom x.2, x.2)
  invFun x := (x.1 - order81_c9c3_liftAddHom x.2, x.2)
  left_inv := by
    intro x
    ext
    · simp
    · rfl
  right_inv := by
    intro x
    ext
    · simp
    · rfl
  map_add' := by
    intro x y
    ext
    · simp [map_add, add_assoc, add_left_comm, add_comm]
    · rfl

/-- The corresponding automorphism of `C_9 × C_3`. -/
noncomputable def order81_c9c3_liftAut : MulAut order81_C9C3 :=
  (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)).symm.trans
    ((AddEquiv.toMultiplicative order81_c9c3_liftAddEquiv).trans
      (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)))

@[simp] theorem order81_c9c3_liftAut_apply (a : ZMod 9) (b : ZMod 3) :
    order81_c9c3_liftAut
      ((Multiplicative.ofAdd a, Multiplicative.ofAdd b) : order81_C9C3) =
      (Multiplicative.ofAdd (a + order81_c9c3_liftAddHom b), Multiplicative.ofAdd b) := by
  rfl

/-- The lift automorphism has order dividing `3`. -/
theorem order81_c9c3_liftAut_pow_three : order81_c9c3_liftAut ^ 3 = 1 := by
  ext x <;> fin_cases x <;> rfl

/-- The `C_3` action on `C_9 × C_3` generated by the lift automorphism. -/
noncomputable abbrev order81_c9c3_liftAction : CyclicRep 3 →* MulAut order81_C9C3 :=
  order81_actionOfOrderThree order81_c9c3_liftAut order81_c9c3_liftAut_pow_three

/-- The split semidirect product `(C_9 × C_3) ⋊ C_3` using the lift action. -/
abbrev order81_c9c3_lift_rep : Type :=
  SemidirectProduct order81_C9C3 (CyclicRep 3) order81_c9c3_liftAction

/-- The lift semidirect product has order `81`. -/
theorem card_order81_c9c3_lift_rep : Nat.card order81_c9c3_lift_rep = 81 := by
  rw [order81_c9c3_lift_rep, SemidirectProduct.card, card_order81_C9C3,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

theorem order81_c9c3_liftAction_gen :
    order81_c9c3_liftAction (Multiplicative.ofAdd (1 : ZMod 3)) =
      order81_c9c3_liftAut :=
  order81_actionOfOrderThree_ofAdd_one _ _

/-- The lift semidirect product is non-abelian. -/
theorem order81_c9c3_lift_rep_nonabelian :
    ¬ ∀ x y : order81_c9c3_lift_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_C9C3 := (1, Multiplicative.ofAdd (1 : ZMod 3))
  have hfix : order81_c9c3_liftAut n = n := by
    have heq : (SemidirectProduct.inl (order81_c9c3_liftAction g n) :
        order81_c9c3_lift_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c9c3_lift_rep)
        (SemidirectProduct.inl n : order81_c9c3_lift_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c9c3_liftAction) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_c9c3_liftAction_gen] using hinj
  have hnot : order81_c9c3_liftAut n ≠ n := by decide +kernel
  exact hnot hfix

theorem order81_c9c3_lift_pow_nine (x : order81_c9c3_lift_rep) : x ^ 9 = 1 := by
  cases x with
  | mk n g =>
      cases n with
      | mk a b =>
          fin_cases a <;> fin_cases b <;> fin_cases g <;> decide +kernel

theorem card_pow_three_eq_one_order81_c9c3_lift_rep :
    order81_pow_eq_one_card order81_c9c3_lift_rep 3 = 27 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_pow_three_eq_one_order81_c9c3_lift_rep :
    order81_center_pow_eq_one_card order81_c9c3_lift_rep 3 = 3 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_pow_three_eq_one_order81_semidirectP2P_prod_cyclic :
    order81_center_pow_eq_one_card order81_semidirectP2P_prod_cyclic 3 = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_pow_three_eq_one_order81_c9c3_shear_rep :
    order81_center_pow_eq_one_card order81_c9c3_shear_rep 3 = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_c9c3_lift_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_lift_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_c9c3_lift_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_center_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_semidirectP2P_prod_cyclic) (n := 3) (by
      rw [card_center_pow_three_eq_one_order81_c9c3_lift_rep,
        card_center_pow_three_eq_one_order81_semidirectP2P_prod_cyclic]
      norm_num)

theorem order81_c9c3_lift_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_c9c3_shear_rep) :=
  order81_not_nonempty_mulEquiv_of_center_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_c9c3_shear_rep) (n := 3) (by
      rw [card_center_pow_three_eq_one_order81_c9c3_lift_rep,
        card_center_pow_three_eq_one_order81_c9c3_shear_rep]
      norm_num)

/-! ## A class-three split `C_9 × C_3` extension by `C_3` -/

/-- The combined additive shear `(a, b) ↦ (a + 3b, b + a mod 3)`. -/
noncomputable def order81_c9c3_doubleShearAddEquiv :
    (ZMod 9 × ZMod 3) ≃+ (ZMod 9 × ZMod 3) :=
  order81_c9c3_liftAddEquiv.trans order81_c9c3_shearAddEquiv

/-- The corresponding automorphism of `C_9 × C_3`. -/
noncomputable def order81_c9c3_doubleShearAut : MulAut order81_C9C3 :=
  (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)).symm.trans
    ((AddEquiv.toMultiplicative order81_c9c3_doubleShearAddEquiv).trans
      (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)))

@[simp] theorem order81_c9c3_doubleShearAut_apply (a : ZMod 9) (b : ZMod 3) :
    order81_c9c3_doubleShearAut
      ((Multiplicative.ofAdd a, Multiplicative.ofAdd b) : order81_C9C3) =
      (Multiplicative.ofAdd (a + order81_c9c3_liftAddHom b),
        Multiplicative.ofAdd (b + order81_zmod9To3 (a + order81_c9c3_liftAddHom b))) := by
  rfl

/-- The combined shear automorphism has order dividing `3`. -/
theorem order81_c9c3_doubleShearAut_pow_three : order81_c9c3_doubleShearAut ^ 3 = 1 := by
  ext x <;> fin_cases x <;> rfl

/-- The `C_3` action on `C_9 × C_3` generated by the combined shear automorphism. -/
noncomputable abbrev order81_c9c3_doubleShearAction : CyclicRep 3 →* MulAut order81_C9C3 :=
  order81_actionOfOrderThree order81_c9c3_doubleShearAut
    order81_c9c3_doubleShearAut_pow_three

/-- The split semidirect product `(C_9 × C_3) ⋊ C_3` using the combined shear action. -/
abbrev order81_c9c3_doubleShear_rep : Type :=
  SemidirectProduct order81_C9C3 (CyclicRep 3) order81_c9c3_doubleShearAction

/-- The combined-shear semidirect product has order `81`. -/
theorem card_order81_c9c3_doubleShear_rep :
    Nat.card order81_c9c3_doubleShear_rep = 81 := by
  rw [order81_c9c3_doubleShear_rep, SemidirectProduct.card, card_order81_C9C3,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

theorem order81_c9c3_doubleShearAction_gen :
    order81_c9c3_doubleShearAction (Multiplicative.ofAdd (1 : ZMod 3)) =
      order81_c9c3_doubleShearAut :=
  order81_actionOfOrderThree_ofAdd_one _ _

/-- The combined-shear semidirect product is non-abelian. -/
theorem order81_c9c3_doubleShear_rep_nonabelian :
    ¬ ∀ x y : order81_c9c3_doubleShear_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_C9C3 := (Multiplicative.ofAdd (1 : ZMod 9), 1)
  have hfix : order81_c9c3_doubleShearAut n = n := by
    have heq : (SemidirectProduct.inl (order81_c9c3_doubleShearAction g n) :
        order81_c9c3_doubleShear_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c9c3_doubleShear_rep)
        (SemidirectProduct.inl n : order81_c9c3_doubleShear_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c9c3_doubleShearAction) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_c9c3_doubleShearAction_gen] using hinj
  have hnot : order81_c9c3_doubleShearAut n ≠ n := by decide +kernel
  exact hnot hfix

theorem order81_c9c3_doubleShear_pow_nine (x : order81_c9c3_doubleShear_rep) : x ^ 9 = 1 := by
  cases x with
  | mk n g =>
      cases n with
      | mk a b =>
          fin_cases a <;> fin_cases b <;> fin_cases g <;> decide +kernel

theorem card_pow_three_eq_one_order81_c9c3_doubleShear_rep :
    order81_pow_eq_one_card order81_c9c3_doubleShear_rep 3 = 27 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c9c3_doubleShear_rep :
    Nat.card (Subgroup.center order81_c9c3_doubleShear_rep) = 3 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_semidirectP2P_prod_cyclic :
    Nat.card (Subgroup.center order81_semidirectP2P_prod_cyclic) = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c9c3_shear_rep :
    Nat.card (Subgroup.center order81_c9c3_shear_rep) = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c9c3_lift_rep :
    Nat.card (Subgroup.center order81_c9c3_lift_rep) = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_c9c3_doubleShear_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_doubleShear_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_doubleShear_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  not_nonempty_mulEquiv_of_card_center_ne (by
    rw [card_center_order81_c9c3_doubleShear_rep,
      card_center_order81_semidirectP2P_prod_cyclic]
    norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_c9c3_shear_rep) :=
  not_nonempty_mulEquiv_of_card_center_ne (by
    rw [card_center_order81_c9c3_doubleShear_rep, card_center_order81_c9c3_shear_rep]
    norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_c9c3_lift_rep :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_c9c3_lift_rep) :=
  not_nonempty_mulEquiv_of_card_center_ne (by
    rw [card_center_order81_c9c3_doubleShear_rep, card_center_order81_c9c3_lift_rep]
    norm_num)

/-! ## The remaining split class-three `C_9 × C_3` extension by `C_3` -/

/-- The additive homomorphism `ZMod 3 → ZMod 9`, `b ↦ 6 * b`. -/
noncomputable def order81_c9c3_sixAddHom : ZMod 3 →+ ZMod 9 where
  toFun b := (6 : ZMod 9) * b.val
  map_zero' := by decide +kernel
  map_add' := by
    intro b d
    fin_cases b <;> fin_cases d <;> decide +kernel

/-- The additive shear `(a, b) ↦ (a + 6b, b + a mod 3)`. -/
noncomputable def order81_c9c3_sixShearAddFun (x : ZMod 9 × ZMod 3) :
    ZMod 9 × ZMod 3 :=
  (x.1 + order81_c9c3_sixAddHom x.2, x.2 + order81_zmod9To3 x.1)

/-- The additive automorphism `(a, b) ↦ (a + 6b, b + a mod 3)`. -/
noncomputable def order81_c9c3_sixShearAddEquiv :
    (ZMod 9 × ZMod 3) ≃+ (ZMod 9 × ZMod 3) where
  toFun := order81_c9c3_sixShearAddFun
  invFun x := order81_c9c3_sixShearAddFun (order81_c9c3_sixShearAddFun x)
  left_inv := by
    intro x
    fin_cases x <;> rfl
  right_inv := by
    intro x
    fin_cases x <;> rfl
  map_add' := by
    intro x y
    fin_cases x <;> fin_cases y <;> rfl

/-- The corresponding automorphism of `C_9 × C_3`. -/
noncomputable def order81_c9c3_sixShearAut : MulAut order81_C9C3 :=
  (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)).symm.trans
    ((AddEquiv.toMultiplicative order81_c9c3_sixShearAddEquiv).trans
      (MulEquiv.prodMultiplicative (ZMod 9) (ZMod 3)))

@[simp] theorem order81_c9c3_sixShearAut_apply (a : ZMod 9) (b : ZMod 3) :
    order81_c9c3_sixShearAut
      ((Multiplicative.ofAdd a, Multiplicative.ofAdd b) : order81_C9C3) =
      (Multiplicative.ofAdd (a + order81_c9c3_sixAddHom b),
        Multiplicative.ofAdd (b + order81_zmod9To3 a)) := by
  rfl

/-- The six-shear automorphism has order dividing `3`. -/
theorem order81_c9c3_sixShearAut_pow_three : order81_c9c3_sixShearAut ^ 3 = 1 := by
  ext x <;> fin_cases x <;> rfl

/-- The `C_3` action on `C_9 × C_3` generated by the six-shear automorphism. -/
noncomputable abbrev order81_c9c3_sixShearAction : CyclicRep 3 →* MulAut order81_C9C3 :=
  order81_actionOfOrderThree order81_c9c3_sixShearAut order81_c9c3_sixShearAut_pow_three

/-- The split semidirect product `(C_9 × C_3) ⋊ C_3` using the six-shear action. -/
abbrev order81_c9c3_sixShear_rep : Type :=
  SemidirectProduct order81_C9C3 (CyclicRep 3) order81_c9c3_sixShearAction

/-- The six-shear semidirect product has order `81`. -/
theorem card_order81_c9c3_sixShear_rep :
    Nat.card order81_c9c3_sixShear_rep = 81 := by
  rw [order81_c9c3_sixShear_rep, SemidirectProduct.card, card_order81_C9C3,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

theorem order81_c9c3_sixShearAction_gen :
    order81_c9c3_sixShearAction (Multiplicative.ofAdd (1 : ZMod 3)) =
      order81_c9c3_sixShearAut :=
  order81_actionOfOrderThree_ofAdd_one _ _

/-- The six-shear semidirect product is non-abelian. -/
theorem order81_c9c3_sixShear_rep_nonabelian :
    ¬ ∀ x y : order81_c9c3_sixShear_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_C9C3 := (Multiplicative.ofAdd (1 : ZMod 9), 1)
  have hfix : order81_c9c3_sixShearAut n = n := by
    have heq : (SemidirectProduct.inl (order81_c9c3_sixShearAction g n) :
        order81_c9c3_sixShear_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c9c3_sixShear_rep)
        (SemidirectProduct.inl n : order81_c9c3_sixShear_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c9c3_sixShearAction) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_c9c3_sixShearAction_gen] using hinj
  have hnot : order81_c9c3_sixShearAut n ≠ n := by decide +kernel
  exact hnot hfix

theorem order81_c9c3_sixShear_pow_nine (x : order81_c9c3_sixShear_rep) : x ^ 9 = 1 := by
  cases x with
  | mk n g =>
      cases n with
      | mk a b =>
          fin_cases a <;> fin_cases b <;> fin_cases g <;> decide +kernel

theorem card_pow_three_eq_one_order81_c9c3_sixShear_rep :
    order81_pow_eq_one_card order81_c9c3_sixShear_rep 3 = 63 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_c9c3_sixShear_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_semidirectP2P_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_semidirectP2P_prod_cyclic]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_c9c3_shear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_c9c3_shear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_c9c3_shear_rep]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_c9c3_lift_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_c9c3_lift_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_c9c3_lift_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_c9c3_lift_rep]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_c9c3_doubleShear_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_c9c3_doubleShear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_c9c3_doubleShear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_c9c3_doubleShear_rep]
      norm_num)

/-! ## A split `C_27` extension by `C_3` -/

/-- `C_27`, written multiplicatively. -/
abbrev order81_C27 : Type :=
  CyclicRep 27

/-- The unit `10` of `ZMod 27`, whose cube is `1`. -/
noncomputable abbrev order81_u10 : (ZMod 27)ˣ :=
  ZMod.unitOfCoprime 10 (by norm_num : Nat.Coprime 10 27)

theorem order81_u10_cube : order81_u10 ^ 3 = 1 := by
  decide

/-- The `C_3` action on `C_27` generated by multiplication by `10`. -/
noncomputable abbrev order81_c27Action : CyclicRep 3 →* MulAut order81_C27 :=
  unitAutHom.comp (powHom (p := 27) (q := 3) order81_u10 order81_u10_cube)

/-- The split semidirect product `C_27 ⋊ C_3` with action generated by multiplication by `10`. -/
abbrev order81_c27_semidirect_rep : Type :=
  SemidirectProduct order81_C27 (CyclicRep 3) order81_c27Action

theorem card_order81_C27 : Nat.card order81_C27 = 27 := by
  rw [card_cyclicRep (by norm_num : (27 : ℕ) ≠ 0)]

/-- The `C_27 ⋊ C_3` representative has order `81`. -/
theorem card_order81_c27_semidirect_rep : Nat.card order81_c27_semidirect_rep = 81 := by
  rw [order81_c27_semidirect_rep, SemidirectProduct.card, card_order81_C27,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

theorem order81_c27Action_gen :
    order81_c27Action (Multiplicative.ofAdd (1 : ZMod 3)) = unitAutHom order81_u10 := by
  change unitAutHom (powHom (p := 27) (q := 3) order81_u10 order81_u10_cube
    (Multiplicative.ofAdd (1 : ZMod 3))) = unitAutHom order81_u10
  change unitAutHom (order81_u10 ^ (1 : ZMod 3).val) = unitAutHom order81_u10
  rw [show (1 : ZMod 3).val = 1 by decide, pow_one]

/-- The `C_27 ⋊ C_3` representative is non-abelian. -/
theorem order81_c27_semidirect_rep_nonabelian :
    ¬ ∀ x y : order81_c27_semidirect_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_C27 := Multiplicative.ofAdd (1 : ZMod 27)
  have hfix : unitAutHom order81_u10 n = n := by
    have heq : (SemidirectProduct.inl (order81_c27Action g n) :
        order81_c27_semidirect_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c27_semidirect_rep)
        (SemidirectProduct.inl n : order81_c27_semidirect_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c27Action) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_c27Action_gen] using hinj
  have hnot : unitAutHom order81_u10 n ≠ n := by
    intro h
    have hadd := congrArg Multiplicative.toAdd h
    norm_num [unitAutHom_apply, order81_u10, n] at hadd
    exact (by decide : (10 : ZMod 27) ≠ 1) hadd
  exact hnot hfix

/-- A visible element of order `27` in `C_27 ⋊ C_3`. -/
noncomputable def order81_c27_semidirect_orderElem : order81_c27_semidirect_rep :=
  SemidirectProduct.inl (Multiplicative.ofAdd (1 : ZMod 27))

theorem orderOf_order81_c27_semidirect_orderElem :
    orderOf order81_c27_semidirect_orderElem = 27 := by
  unfold order81_c27_semidirect_orderElem
  rw [orderOf_injective SemidirectProduct.inl SemidirectProduct.inl_injective]
  rw [orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one]

/-- `C_27 ⋊ C_3` is not isomorphic to the exponent-`3` direct-product representative. -/
theorem order81_c27_semidirect_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c27_semidirect_rep ≃* order81_heisenberg_prod_cyclic) := by
  rintro ⟨e⟩
  have hord : orderOf (e order81_c27_semidirect_orderElem) = 27 := by
    rw [MulEquiv.orderOf_eq e, orderOf_order81_c27_semidirect_orderElem]
  have hdvd : orderOf (e order81_c27_semidirect_orderElem) ∣
      Monoid.exponent order81_heisenberg_prod_cyclic :=
    Monoid.order_dvd_exponent _
  rw [hord, exponent_order81_heisenberg_prod_cyclic] at hdvd
  norm_num at hdvd

/-- `C_27 ⋊ C_3` is not isomorphic to `SemidirectP2P 3 × C_3`. -/
theorem order81_c27_semidirect_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c27_semidirect_rep ≃* order81_semidirectP2P_prod_cyclic) := by
  rintro ⟨e⟩
  have hord : orderOf (e order81_c27_semidirect_orderElem) = 27 := by
    rw [MulEquiv.orderOf_eq e, orderOf_order81_c27_semidirect_orderElem]
  have hdvd : orderOf (e order81_c27_semidirect_orderElem) ∣
      Monoid.exponent order81_semidirectP2P_prod_cyclic :=
    Monoid.order_dvd_exponent _
  rw [hord, exponent_order81_semidirectP2P_prod_cyclic] at hdvd
  norm_num at hdvd

/-- `C_27 ⋊ C_3` is not isomorphic to the shear `C_9 × C_3` semidirect product. -/
theorem order81_c27_semidirect_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c27_semidirect_rep ≃* order81_c9c3_shear_rep) := by
  rintro ⟨e⟩
  have hord : orderOf (e order81_c27_semidirect_orderElem) = 27 := by
    rw [MulEquiv.orderOf_eq e, orderOf_order81_c27_semidirect_orderElem]
  have hpow : (e order81_c27_semidirect_orderElem) ^ 9 = 1 :=
    order81_c9c3_shear_pow_nine _
  have hdvd : orderOf (e order81_c27_semidirect_orderElem) ∣ 9 :=
    orderOf_dvd_of_pow_eq_one hpow
  rw [hord] at hdvd
  norm_num at hdvd

theorem card_pow_three_eq_one_order81_c27_semidirect_rep :
    order81_pow_eq_one_card order81_c27_semidirect_rep 3 = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

/-! ## A split `C_9` extension by `C_9` -/

/-- `C_9`, written multiplicatively. -/
abbrev order81_C9 : Type :=
  CyclicRep 9

/-- The unit `4` of `ZMod 9`, whose order divides `9`. -/
noncomputable abbrev order81_u4 : (ZMod 9)ˣ :=
  ZMod.unitOfCoprime 4 (by norm_num : Nat.Coprime 4 9)

theorem order81_u4_pow_nine : order81_u4 ^ 9 = 1 := by
  decide

/-- The `C_9` action on `C_9` generated by multiplication by `4`. -/
noncomputable abbrev order81_c9Action : order81_C9 →* MulAut order81_C9 :=
  unitAutHom.comp (powHom (p := 9) (q := 9) order81_u4 order81_u4_pow_nine)

/-- The split semidirect product `C_9 ⋊ C_9` with action generated by multiplication by `4`. -/
abbrev order81_c9_semidirect_c9_rep : Type :=
  SemidirectProduct order81_C9 order81_C9 order81_c9Action

theorem card_order81_C9 : Nat.card order81_C9 = 9 := by
  rw [card_cyclicRep (by norm_num : (9 : ℕ) ≠ 0)]

/-- The `C_9 ⋊ C_9` representative has order `81`. -/
theorem card_order81_c9_semidirect_c9_rep : Nat.card order81_c9_semidirect_c9_rep = 81 := by
  rw [order81_c9_semidirect_c9_rep, SemidirectProduct.card, card_order81_C9]

theorem order81_c9Action_gen :
    order81_c9Action (Multiplicative.ofAdd (1 : ZMod 9)) = unitAutHom order81_u4 := by
  change unitAutHom (powHom (p := 9) (q := 9) order81_u4 order81_u4_pow_nine
    (Multiplicative.ofAdd (1 : ZMod 9))) = unitAutHom order81_u4
  change unitAutHom (order81_u4 ^ (1 : ZMod 9).val) = unitAutHom order81_u4
  rw [show (1 : ZMod 9).val = 1 by decide, pow_one]

/-- The `C_9 ⋊ C_9` representative is non-abelian. -/
theorem order81_c9_semidirect_c9_rep_nonabelian :
    ¬ ∀ x y : order81_c9_semidirect_c9_rep, x * y = y * x := by
  intro hcomm
  let g : order81_C9 := Multiplicative.ofAdd (1 : ZMod 9)
  let n : order81_C9 := Multiplicative.ofAdd (1 : ZMod 9)
  have hfix : unitAutHom order81_u4 n = n := by
    have heq : (SemidirectProduct.inl (order81_c9Action g n) :
        order81_c9_semidirect_c9_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_c9_semidirect_c9_rep)
        (SemidirectProduct.inl n : order81_c9_semidirect_c9_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_c9Action) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_c9Action_gen] using hinj
  have hnot : unitAutHom order81_u4 n ≠ n := by
    intro h
    have hadd := congrArg Multiplicative.toAdd h
    norm_num [unitAutHom_apply, order81_u4, n] at hadd
    exact (by decide : (4 : ZMod 9) ≠ 1) hadd
  exact hnot hfix

/-- A visible element of order `9` in `C_9 ⋊ C_9`. -/
noncomputable def order81_c9_semidirect_c9_orderElem : order81_c9_semidirect_c9_rep :=
  SemidirectProduct.inl (Multiplicative.ofAdd (1 : ZMod 9))

theorem orderOf_order81_c9_semidirect_c9_orderElem :
    orderOf order81_c9_semidirect_c9_orderElem = 9 := by
  unfold order81_c9_semidirect_c9_orderElem
  rw [orderOf_injective SemidirectProduct.inl SemidirectProduct.inl_injective]
  rw [orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one]

theorem order81_c9_semidirect_c9_pow_nine (x : order81_c9_semidirect_c9_rep) :
    x ^ 9 = 1 := by
  cases x with
  | mk n g =>
      fin_cases n <;> fin_cases g <;> decide +kernel

theorem card_pow_three_eq_one_order81_c9_semidirect_c9_rep :
    order81_pow_eq_one_card order81_c9_semidirect_c9_rep 3 = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_c9_semidirect_c9_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9_semidirect_c9_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9_semidirect_c9_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9_semidirect_c9_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_c9_semidirect_c9_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9_semidirect_c9_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9_semidirect_c9_rep) (K := order81_semidirectP2P_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9_semidirect_c9_rep,
        card_pow_three_eq_one_order81_semidirectP2P_prod_cyclic]
      norm_num)

theorem order81_c9_semidirect_c9_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c9_semidirect_c9_rep ≃* order81_c9c3_shear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9_semidirect_c9_rep) (K := order81_c9c3_shear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9_semidirect_c9_rep,
        card_pow_three_eq_one_order81_c9c3_shear_rep]
      norm_num)

theorem order81_c27_semidirect_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_c27_semidirect_rep ≃* order81_c9_semidirect_c9_rep) := by
  rintro ⟨e⟩
  have hord : orderOf (e order81_c27_semidirect_orderElem) = 27 := by
    rw [MulEquiv.orderOf_eq e, orderOf_order81_c27_semidirect_orderElem]
  have hpow : (e order81_c27_semidirect_orderElem) ^ 9 = 1 :=
    order81_c9_semidirect_c9_pow_nine _
  have hdvd : orderOf (e order81_c27_semidirect_orderElem) ∣ 9 :=
    orderOf_dvd_of_pow_eq_one hpow
  rw [hord] at hdvd
  norm_num at hdvd

/-! ## A split elementary-abelian extension by `C_3` -/

/-- `C_3 × C_3 × C_3`, written multiplicatively. -/
abbrev order81_E27 : Type :=
  Multiplicative ((ZMod 3 × ZMod 3) × ZMod 3)

/-- The additive Jordan shear `(a, b, c) ↦ (a, b + a, c + b)` on `(ZMod 3)^3`. -/
noncomputable def order81_e27_jordanAddEquiv :
    ((ZMod 3 × ZMod 3) × ZMod 3) ≃+ ((ZMod 3 × ZMod 3) × ZMod 3) where
  toFun x := ((x.1.1, x.1.2 + x.1.1), x.2 + x.1.2)
  invFun x := ((x.1.1, x.1.2 - x.1.1), x.2 - x.1.2 + x.1.1)
  left_inv := by
    intro x
    ext <;> simp [add_comm]
  right_inv := by
    intro x
    ext <;> simp [add_assoc, add_comm]
  map_add' := by
    intro x y
    ext <;> simp [add_left_comm, add_comm]

/-- The corresponding automorphism of `C_3 × C_3 × C_3`. -/
noncomputable def order81_e27_jordanAut : MulAut order81_E27 :=
  AddEquiv.toMultiplicative order81_e27_jordanAddEquiv

@[simp] theorem order81_e27_jordanAut_apply (a b c : ZMod 3) :
    order81_e27_jordanAut
      (Multiplicative.ofAdd (((a, b), c) : (ZMod 3 × ZMod 3) × ZMod 3)) =
      Multiplicative.ofAdd (((a, b + a), c + b) : (ZMod 3 × ZMod 3) × ZMod 3) := by
  rfl

/-- The Jordan automorphism has order dividing `3`. -/
theorem order81_e27_jordanAut_pow_three : order81_e27_jordanAut ^ 3 = 1 := by
  ext x <;> fin_cases x <;> rfl

/-- The `C_3` action on `C_3 × C_3 × C_3` generated by the Jordan automorphism. -/
noncomputable abbrev order81_e27_jordanAction : CyclicRep 3 →* MulAut order81_E27 :=
  order81_actionOfOrderThree order81_e27_jordanAut order81_e27_jordanAut_pow_three

/-- The split semidirect product `(C_3 × C_3 × C_3) ⋊ C_3` with Jordan action. -/
abbrev order81_e27_jordan_rep : Type :=
  SemidirectProduct order81_E27 (CyclicRep 3) order81_e27_jordanAction

theorem card_order81_E27 : Nat.card order81_E27 = 27 := by
  simp [order81_E27, Nat.card_eq_fintype_card, Fintype.card_multiplicative,
    Fintype.card_prod]

/-- The Jordan representative has order `81`. -/
theorem card_order81_e27_jordan_rep : Nat.card order81_e27_jordan_rep = 81 := by
  rw [order81_e27_jordan_rep, SemidirectProduct.card, card_order81_E27,
    card_cyclicRep (by norm_num : (3 : ℕ) ≠ 0)]

theorem order81_e27_jordanAction_gen :
    order81_e27_jordanAction (Multiplicative.ofAdd (1 : ZMod 3)) =
      order81_e27_jordanAut :=
  order81_actionOfOrderThree_ofAdd_one _ _

/-- The Jordan representative is non-abelian. -/
theorem order81_e27_jordan_rep_nonabelian :
    ¬ ∀ x y : order81_e27_jordan_rep, x * y = y * x := by
  intro hcomm
  let g : CyclicRep 3 := Multiplicative.ofAdd (1 : ZMod 3)
  let n : order81_E27 :=
    Multiplicative.ofAdd ((((1 : ZMod 3), 0), 0) : (ZMod 3 × ZMod 3) × ZMod 3)
  have hfix : order81_e27_jordanAut n = n := by
    have heq : (SemidirectProduct.inl (order81_e27_jordanAction g n) :
        order81_e27_jordan_rep) = SemidirectProduct.inl n := by
      have h := hcomm (SemidirectProduct.inr g : order81_e27_jordan_rep)
        (SemidirectProduct.inl n : order81_e27_jordan_rep)
      rw [SemidirectProduct.inl_aut (φ := order81_e27_jordanAction) g n]
      rw [h, mul_assoc, ← map_mul, mul_inv_cancel, map_one]
      simp
    have hinj := SemidirectProduct.inl_injective heq
    simpa [g, order81_e27_jordanAction_gen] using hinj
  have hnot : order81_e27_jordanAut n ≠ n := by
    intro h
    have hadd := congrArg Multiplicative.toAdd h
    norm_num [n] at hadd
  exact hnot hfix

theorem card_pow_three_eq_one_order81_e27_jordan_rep :
    order81_pow_eq_one_card order81_e27_jordan_rep 3 = 45 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_e27_jordan_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_e27_jordan_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_e27_jordan_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_e27_jordan_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_e27_jordan_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_e27_jordan_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_e27_jordan_rep) (K := order81_semidirectP2P_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_e27_jordan_rep,
        card_pow_three_eq_one_order81_semidirectP2P_prod_cyclic]
      norm_num)

theorem order81_e27_jordan_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_e27_jordan_rep ≃* order81_c9c3_shear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_e27_jordan_rep) (K := order81_c9c3_shear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_e27_jordan_rep,
        card_pow_three_eq_one_order81_c9c3_shear_rep]
      norm_num)

theorem order81_e27_jordan_rep_not_equiv_c27_semidirect_rep :
    ¬ Nonempty (order81_e27_jordan_rep ≃* order81_c27_semidirect_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_e27_jordan_rep) (K := order81_c27_semidirect_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_e27_jordan_rep,
        card_pow_three_eq_one_order81_c27_semidirect_rep]
      norm_num)

theorem order81_e27_jordan_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_e27_jordan_rep ≃* order81_c9_semidirect_c9_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_e27_jordan_rep) (K := order81_c9_semidirect_c9_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_e27_jordan_rep,
        card_pow_three_eq_one_order81_c9_semidirect_c9_rep]
      norm_num)

theorem order81_c9c3_lift_rep_not_equiv_c27_semidirect_rep :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_c27_semidirect_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_c27_semidirect_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_lift_rep,
        card_pow_three_eq_one_order81_c27_semidirect_rep]
      norm_num)

theorem order81_c9c3_lift_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_c9_semidirect_c9_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_c9_semidirect_c9_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_lift_rep,
        card_pow_three_eq_one_order81_c9_semidirect_c9_rep]
      norm_num)

theorem order81_c9c3_lift_rep_not_equiv_e27_jordan_rep :
    ¬ Nonempty (order81_c9c3_lift_rep ≃* order81_e27_jordan_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_lift_rep) (K := order81_e27_jordan_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_lift_rep,
        card_pow_three_eq_one_order81_e27_jordan_rep]
      norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_c27_semidirect_rep :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_c27_semidirect_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_doubleShear_rep) (K := order81_c27_semidirect_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_doubleShear_rep,
        card_pow_three_eq_one_order81_c27_semidirect_rep]
      norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_c9_semidirect_c9_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_doubleShear_rep) (K := order81_c9_semidirect_c9_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_doubleShear_rep,
        card_pow_three_eq_one_order81_c9_semidirect_c9_rep]
      norm_num)

theorem order81_c9c3_doubleShear_rep_not_equiv_e27_jordan_rep :
    ¬ Nonempty (order81_c9c3_doubleShear_rep ≃* order81_e27_jordan_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_doubleShear_rep) (K := order81_e27_jordan_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_doubleShear_rep,
        card_pow_three_eq_one_order81_e27_jordan_rep]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_c27_semidirect_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_c27_semidirect_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_c27_semidirect_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_c27_semidirect_rep]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_c9_semidirect_c9_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_c9_semidirect_c9_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_c9_semidirect_c9_rep]
      norm_num)

theorem order81_c9c3_sixShear_rep_not_equiv_e27_jordan_rep :
    ¬ Nonempty (order81_c9c3_sixShear_rep ≃* order81_e27_jordan_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_sixShear_rep) (K := order81_e27_jordan_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_sixShear_rep,
        card_pow_three_eq_one_order81_e27_jordan_rep]
      norm_num)

/-! ## A non-split six-shear `C_9 × C_3` extension by `C_3` -/

/-- The additive kernel used for the non-split `C_9 × C_3` extension. -/
abbrev order81_C9C3Add : Type :=
  ZMod 9 × ZMod 3

/-- The central carry element `v = (3, 0)` used to make the six-shear extension non-split. -/
def order81_c9c3_nonSplitTwist : order81_C9C3Add :=
  (3, 0)

/-- The `0`, `1`, or `2`-fold iterate of the six-shear additive automorphism. -/
noncomputable def order81_c9c3_nonSplitAct (t : ZMod 3) :
    order81_C9C3Add ≃+ order81_C9C3Add :=
  if t = 0 then AddEquiv.refl order81_C9C3Add
  else if t = 1 then order81_c9c3_sixShearAddEquiv
  else order81_c9c3_sixShearAddEquiv.trans order81_c9c3_sixShearAddEquiv

/-- The carry cocycle for the section `ZMod 3 → {0,1,2}` with `t^3 = (3,0)`. -/
def order81_c9c3_nonSplitCarry (i j : ZMod 3) : order81_C9C3Add :=
  if 3 ≤ i.val + j.val then order81_c9c3_nonSplitTwist else 0

@[simp] theorem order81_c9c3_nonSplitAct_zero_apply (n : order81_C9C3Add) :
    order81_c9c3_nonSplitAct 0 n = n := by
  simp [order81_c9c3_nonSplitAct]

@[simp] theorem order81_c9c3_nonSplitAct_apply_zero (i : ZMod 3) :
    order81_c9c3_nonSplitAct i (0 : order81_C9C3Add) = 0 :=
  (order81_c9c3_nonSplitAct i).map_zero

theorem order81_c9c3_nonSplitAct_add_apply (i j : ZMod 3) (n : order81_C9C3Add) :
    order81_c9c3_nonSplitAct (i + j) n =
      order81_c9c3_nonSplitAct i (order81_c9c3_nonSplitAct j n) := by
  fin_cases i <;> fin_cases j <;> fin_cases n <;> rfl

theorem order81_c9c3_nonSplitAct_carry (i j k : ZMod 3) :
    order81_c9c3_nonSplitAct i (order81_c9c3_nonSplitCarry j k) =
      order81_c9c3_nonSplitCarry j k := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> rfl

theorem order81_c9c3_nonSplitCarry_cocycle (i j k : ZMod 3) :
    order81_c9c3_nonSplitCarry i j + order81_c9c3_nonSplitCarry (i + j) k =
      order81_c9c3_nonSplitAct i (order81_c9c3_nonSplitCarry j k) +
        order81_c9c3_nonSplitCarry i (j + k) := by
  fin_cases i <;> fin_cases j <;> fin_cases k <;> rfl

@[simp] theorem order81_c9c3_nonSplitCarry_zero_left (i : ZMod 3) :
    order81_c9c3_nonSplitCarry 0 i = 0 := by
  fin_cases i <;> rfl

@[simp] theorem order81_c9c3_nonSplitCarry_zero_right (i : ZMod 3) :
    order81_c9c3_nonSplitCarry i 0 = 0 := by
  fin_cases i <;> rfl

/-- The non-split extension with kernel `C_9 × C_3`, quotient `C_3`, six-shear action, and
`t^3 = (3,0)`. -/
@[ext]
structure Order81C9C3NonSplit where
  n : order81_C9C3Add
  t : ZMod 3
  deriving DecidableEq

namespace Order81C9C3NonSplit

noncomputable def mul (x y : Order81C9C3NonSplit) : Order81C9C3NonSplit :=
  ⟨x.n + order81_c9c3_nonSplitAct x.t y.n + order81_c9c3_nonSplitCarry x.t y.t,
    x.t + y.t⟩

noncomputable def inv (x : Order81C9C3NonSplit) : Order81C9C3NonSplit :=
  ⟨-(order81_c9c3_nonSplitAct (-x.t) x.n + order81_c9c3_nonSplitCarry (-x.t) x.t),
    -x.t⟩

noncomputable instance instMul : Mul Order81C9C3NonSplit :=
  ⟨mul⟩

instance instOne : One Order81C9C3NonSplit :=
  ⟨⟨0, 0⟩⟩

noncomputable instance instInv : Inv Order81C9C3NonSplit :=
  ⟨inv⟩

@[simp] theorem mul_n (x y : Order81C9C3NonSplit) :
    (x * y).n =
      x.n + order81_c9c3_nonSplitAct x.t y.n + order81_c9c3_nonSplitCarry x.t y.t :=
  rfl

@[simp] theorem mul_t (x y : Order81C9C3NonSplit) :
    (x * y).t = x.t + y.t :=
  rfl

@[simp] theorem one_n : (1 : Order81C9C3NonSplit).n = 0 :=
  rfl

@[simp] theorem one_t : (1 : Order81C9C3NonSplit).t = 0 :=
  rfl

@[simp] theorem inv_n (x : Order81C9C3NonSplit) :
    x⁻¹.n =
      -(order81_c9c3_nonSplitAct (-x.t) x.n + order81_c9c3_nonSplitCarry (-x.t) x.t) :=
  rfl

@[simp] theorem inv_t (x : Order81C9C3NonSplit) :
    x⁻¹.t = -x.t :=
  rfl

noncomputable instance instGroup : Group Order81C9C3NonSplit where
  mul_assoc x y z := by
    apply Order81C9C3NonSplit.ext
    · simp only [mul_n, mul_t]
      calc
        x.n + order81_c9c3_nonSplitAct x.t y.n +
            order81_c9c3_nonSplitCarry x.t y.t +
            order81_c9c3_nonSplitAct (x.t + y.t) z.n +
            order81_c9c3_nonSplitCarry (x.t + y.t) z.t =
          x.n + order81_c9c3_nonSplitAct x.t y.n +
            order81_c9c3_nonSplitAct x.t (order81_c9c3_nonSplitAct y.t z.n) +
            (order81_c9c3_nonSplitCarry x.t y.t +
              order81_c9c3_nonSplitCarry (x.t + y.t) z.t) := by
            rw [order81_c9c3_nonSplitAct_add_apply]
            abel
        _ = x.n + order81_c9c3_nonSplitAct x.t y.n +
            order81_c9c3_nonSplitAct x.t (order81_c9c3_nonSplitAct y.t z.n) +
            (order81_c9c3_nonSplitAct x.t (order81_c9c3_nonSplitCarry y.t z.t) +
              order81_c9c3_nonSplitCarry x.t (y.t + z.t)) := by
            rw [order81_c9c3_nonSplitCarry_cocycle]
        _ = x.n + order81_c9c3_nonSplitAct x.t
            (y.n + order81_c9c3_nonSplitAct y.t z.n +
              order81_c9c3_nonSplitCarry y.t z.t) +
            order81_c9c3_nonSplitCarry x.t (y.t + z.t) := by
            rw [(order81_c9c3_nonSplitAct x.t).map_add,
              (order81_c9c3_nonSplitAct x.t).map_add]
            abel
    · simp only [mul_t]
      abel
  one_mul x := by
    apply Order81C9C3NonSplit.ext <;> simp
  mul_one x := by
    apply Order81C9C3NonSplit.ext <;> simp
  inv_mul_cancel x := by
    apply Order81C9C3NonSplit.ext <;> simp

def equivProd : Order81C9C3NonSplit ≃ (order81_C9C3Add × ZMod 3) where
  toFun x := (x.n, x.t)
  invFun x := ⟨x.1, x.2⟩
  left_inv x := by cases x; rfl
  right_inv x := by cases x; rfl

noncomputable instance instFintype : Fintype Order81C9C3NonSplit :=
  Fintype.ofEquiv _ equivProd.symm

end Order81C9C3NonSplit

/-- The non-split six-shear representative of order `81`. -/
abbrev order81_c9c3_nonSplit_rep : Type :=
  Order81C9C3NonSplit

theorem card_order81_c9c3_nonSplit_rep :
    Nat.card order81_c9c3_nonSplit_rep = 81 := by
  rw [Nat.card_congr Order81C9C3NonSplit.equivProd]
  simp [order81_C9C3Add, Fintype.card_prod]

theorem order81_c9c3_nonSplit_rep_nonabelian :
    ¬ ∀ x y : order81_c9c3_nonSplit_rep, x * y = y * x := by
  let x : order81_c9c3_nonSplit_rep := ⟨0, 1⟩
  let y : order81_c9c3_nonSplit_rep := ⟨((1 : ZMod 9), (0 : ZMod 3)), 0⟩
  intro hcomm
  exact (by decide +kernel : x * y ≠ y * x) (hcomm x y)

theorem card_pow_three_eq_one_order81_c9c3_nonSplit_rep :
    order81_pow_eq_one_card order81_c9c3_nonSplit_rep 3 = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c9c3_nonSplit_rep :
    Nat.card (Subgroup.center order81_c9c3_nonSplit_rep) = 3 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c27_semidirect_rep :
    Nat.card (Subgroup.center order81_c27_semidirect_rep) = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem card_center_order81_c9_semidirect_c9_rep :
    Nat.card (Subgroup.center order81_c9_semidirect_c9_rep) = 9 :=
  order81_nat_card_eq_of_fintype_card_eq (by decide +kernel)

theorem order81_c9c3_nonSplit_rep_not_equiv_heisenberg_prod_cyclic :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_heisenberg_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_heisenberg_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_heisenberg_prod_cyclic]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_semidirectP2P_prod_cyclic :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_semidirectP2P_prod_cyclic) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_semidirectP2P_prod_cyclic) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_semidirectP2P_prod_cyclic]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c9c3_shear_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c9c3_shear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_c9c3_shear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_c9c3_shear_rep]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c9c3_lift_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c9c3_lift_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_c9c3_lift_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_c9c3_lift_rep]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c9c3_doubleShear_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c9c3_doubleShear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_c9c3_doubleShear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_c9c3_doubleShear_rep]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c9c3_sixShear_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c9c3_sixShear_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_c9c3_sixShear_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_c9c3_sixShear_rep]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_e27_jordan_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_e27_jordan_rep) :=
  order81_not_nonempty_mulEquiv_of_pow_eq_one_card_ne
    (H := order81_c9c3_nonSplit_rep) (K := order81_e27_jordan_rep) (n := 3) (by
      rw [card_pow_three_eq_one_order81_c9c3_nonSplit_rep,
        card_pow_three_eq_one_order81_e27_jordan_rep]
      norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c27_semidirect_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c27_semidirect_rep) :=
  not_nonempty_mulEquiv_of_card_center_ne (by
    rw [card_center_order81_c9c3_nonSplit_rep, card_center_order81_c27_semidirect_rep]
    norm_num)

theorem order81_c9c3_nonSplit_rep_not_equiv_c9_semidirect_c9_rep :
    ¬ Nonempty (order81_c9c3_nonSplit_rep ≃* order81_c9_semidirect_c9_rep) :=
  not_nonempty_mulEquiv_of_card_center_ne (by
    rw [card_center_order81_c9c3_nonSplit_rep, card_center_order81_c9_semidirect_c9_rep]
    norm_num)

/-! ## The currently formalized representatives -/

/-- The first nine certified non-abelian representatives of order `81`. -/
abbrev order81_nonabelian_reps9 : Fin 9 → Type :=
  rep9 order81_heisenberg_prod_cyclic order81_semidirectP2P_prod_cyclic
    order81_c9c3_shear_rep order81_c27_semidirect_rep order81_c9_semidirect_c9_rep
    order81_e27_jordan_rep order81_c9c3_lift_rep order81_c9c3_doubleShear_rep
    order81_c9c3_sixShear_rep

/-- Each of the first nine certified non-abelian representatives has order `81`. -/
theorem card_order81_nonabelian_reps9 (i : Fin 9) :
    Nat.card (order81_nonabelian_reps9 i) = 81 := by
  fin_cases i
  · exact card_order81_heisenberg_prod_cyclic
  · exact card_order81_semidirectP2P_prod_cyclic
  · exact card_order81_c9c3_shear_rep
  · exact card_order81_c27_semidirect_rep
  · exact card_order81_c9_semidirect_c9_rep
  · exact card_order81_e27_jordan_rep
  · exact card_order81_c9c3_lift_rep
  · exact card_order81_c9c3_doubleShear_rep
  · exact card_order81_c9c3_sixShear_rep

/-- Each of the first nine certified non-abelian representatives is non-abelian. -/
theorem order81_nonabelian_reps9_nonabelian (i : Fin 9) :
    ¬ ∀ x y : order81_nonabelian_reps9 i, x * y = y * x := by
  fin_cases i
  · exact order81_heisenberg_prod_cyclic_nonabelian
  · exact order81_semidirectP2P_prod_cyclic_nonabelian
  · exact order81_c9c3_shear_rep_nonabelian
  · exact order81_c27_semidirect_rep_nonabelian
  · exact order81_c9_semidirect_c9_rep_nonabelian
  · exact order81_e27_jordan_rep_nonabelian
  · exact order81_c9c3_lift_rep_nonabelian
  · exact order81_c9c3_doubleShear_rep_nonabelian
  · exact order81_c9c3_sixShear_rep_nonabelian

/-- The first nine certified non-abelian representatives are pairwise non-isomorphic. -/
theorem order81_nonabelian_reps9_pairwise :
    PairwiseNonMulEquiv order81_nonabelian_reps9 := by
  intro i j h
  fin_cases i
  · fin_cases j
    · rfl
    · exact absurd h order81_heisenberg_prod_cyclic_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_shear_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c27_semidirect_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c9_semidirect_c9_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_e27_jordan_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_lift_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_heisenberg_prod_cyclic
  · fin_cases j
    · exact absurd ⟨h.some.symm⟩
        order81_heisenberg_prod_cyclic_not_equiv_semidirectP2P_prod_cyclic
    · rfl
    · exact absurd ⟨h.some.symm⟩
        order81_c9c3_shear_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_c27_semidirect_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_c9_semidirect_c9_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_e27_jordan_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_c9c3_lift_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_c9c3_doubleShear_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd ⟨h.some.symm⟩
        order81_c9c3_sixShear_rep_not_equiv_semidirectP2P_prod_cyclic
  · fin_cases j
    · exact absurd h order81_c9c3_shear_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c9c3_shear_rep_not_equiv_semidirectP2P_prod_cyclic
    · rfl
    · exact absurd ⟨h.some.symm⟩ order81_c27_semidirect_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9_semidirect_c9_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_e27_jordan_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_lift_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_c9c3_shear_rep
  · fin_cases j
    · exact absurd h order81_c27_semidirect_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c27_semidirect_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_c27_semidirect_rep_not_equiv_c9c3_shear_rep
    · rfl
    · exact absurd h order81_c27_semidirect_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd ⟨h.some.symm⟩ order81_e27_jordan_rep_not_equiv_c27_semidirect_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_lift_rep_not_equiv_c27_semidirect_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_c27_semidirect_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_c27_semidirect_rep
  · fin_cases j
    · exact absurd h order81_c9_semidirect_c9_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c9_semidirect_c9_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_c9_semidirect_c9_rep_not_equiv_c9c3_shear_rep
    · exact absurd ⟨h.some.symm⟩ order81_c27_semidirect_rep_not_equiv_c9_semidirect_c9_rep
    · rfl
    · exact absurd ⟨h.some.symm⟩ order81_e27_jordan_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_lift_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_c9_semidirect_c9_rep
  · fin_cases j
    · exact absurd h order81_e27_jordan_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_e27_jordan_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_e27_jordan_rep_not_equiv_c9c3_shear_rep
    · exact absurd h order81_e27_jordan_rep_not_equiv_c27_semidirect_rep
    · exact absurd h order81_e27_jordan_rep_not_equiv_c9_semidirect_c9_rep
    · rfl
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_lift_rep_not_equiv_e27_jordan_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_e27_jordan_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_e27_jordan_rep
  · fin_cases j
    · exact absurd h order81_c9c3_lift_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c9c3_lift_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_c9c3_lift_rep_not_equiv_c9c3_shear_rep
    · exact absurd h order81_c9c3_lift_rep_not_equiv_c27_semidirect_rep
    · exact absurd h order81_c9c3_lift_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd h order81_c9c3_lift_rep_not_equiv_e27_jordan_rep
    · rfl
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_doubleShear_rep_not_equiv_c9c3_lift_rep
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_c9c3_lift_rep
  · fin_cases j
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_c9c3_shear_rep
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_c27_semidirect_rep
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_e27_jordan_rep
    · exact absurd h order81_c9c3_doubleShear_rep_not_equiv_c9c3_lift_rep
    · rfl
    · exact absurd ⟨h.some.symm⟩ order81_c9c3_sixShear_rep_not_equiv_c9c3_doubleShear_rep
  · fin_cases j
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_heisenberg_prod_cyclic
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_semidirectP2P_prod_cyclic
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_c9c3_shear_rep
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_c27_semidirect_rep
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_c9_semidirect_c9_rep
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_e27_jordan_rep
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_c9c3_lift_rep
    · exact absurd h order81_c9c3_sixShear_rep_not_equiv_c9c3_doubleShear_rep
    · rfl

/-- The final non-split non-abelian representative, kept separate from the first nine for
bookkeeping. -/
abbrev order81_nonabelian_extra_reps : Fin 1 → Type :=
  rep1 order81_c9c3_nonSplit_rep

theorem card_order81_nonabelian_extra_reps (i : Fin 1) :
    Nat.card (order81_nonabelian_extra_reps i) = 81 := by
  fin_cases i
  exact card_order81_c9c3_nonSplit_rep

theorem order81_nonabelian_extra_reps_nonabelian (i : Fin 1) :
    ¬ ∀ x y : order81_nonabelian_extra_reps i, x * y = y * x := by
  fin_cases i
  exact order81_c9c3_nonSplit_rep_nonabelian

theorem order81_nonabelian_extra_reps_pairwise :
    PairwiseNonMulEquiv order81_nonabelian_extra_reps := by
  intro i j _
  fin_cases i
  fin_cases j
  rfl

theorem order81_nonabelian_reps9_extra_disjoint :
    ∀ i j, ¬ Nonempty (order81_nonabelian_reps9 i ≃* order81_nonabelian_extra_reps j) := by
  intro i j h
  fin_cases i <;> fin_cases j
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_heisenberg_prod_cyclic
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_semidirectP2P_prod_cyclic
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c9c3_shear_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c27_semidirect_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c9_semidirect_c9_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_e27_jordan_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c9c3_lift_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c9c3_doubleShear_rep
  · exact absurd ⟨h.some.symm⟩ order81_c9c3_nonSplit_rep_not_equiv_c9c3_sixShear_rep

/-- The ten currently certified non-abelian representatives of order `81`. -/
abbrev order81_nonabelian_reps : Fin 9 ⊕ Fin 1 → Type :=
  Sum.elim order81_nonabelian_reps9 order81_nonabelian_extra_reps

noncomputable instance instGroupOrder81NonabelianReps (i : Fin 9 ⊕ Fin 1) :
    Group (order81_nonabelian_reps i) := by
  rcases i with i | i
  · exact inferInstanceAs (Group (order81_nonabelian_reps9 i))
  · exact inferInstanceAs (Group (order81_nonabelian_extra_reps i))

theorem card_order81_nonabelian_reps (i : Fin 9 ⊕ Fin 1) :
    Nat.card (order81_nonabelian_reps i) = 81 := by
  rcases i with i | i
  · exact card_order81_nonabelian_reps9 i
  · exact card_order81_nonabelian_extra_reps i

theorem order81_nonabelian_reps_nonabelian (i : Fin 9 ⊕ Fin 1) :
    ¬ ∀ x y : order81_nonabelian_reps i, x * y = y * x := by
  rcases i with i | i
  · exact order81_nonabelian_reps9_nonabelian i
  · exact order81_nonabelian_extra_reps_nonabelian i

theorem order81_nonabelian_reps_pairwise :
    PairwiseNonMulEquiv order81_nonabelian_reps := by
  rintro (i | i) (j | j) h
  · exact congrArg Sum.inl (order81_nonabelian_reps9_pairwise i j h)
  · exact absurd h (order81_nonabelian_reps9_extra_disjoint i j)
  · exact absurd ⟨h.some.symm⟩ (order81_nonabelian_reps9_extra_disjoint j i)
  · exact congrArg Sum.inr (order81_nonabelian_extra_reps_pairwise i j h)

/-- The five abelian representatives together with the currently certified non-abelian
representatives formalized above. -/
abbrev order81_known_reps : Fin 5 ⊕ (Fin 9 ⊕ Fin 1) → Type :=
  Sum.elim order81_abelian_reps order81_nonabelian_reps

noncomputable instance instGroupOrder81KnownReps (i : Fin 5 ⊕ (Fin 9 ⊕ Fin 1)) :
    Group (order81_known_reps i) := by
  rcases i with i | i
  · exact inferInstanceAs (Group (order81_abelian_reps i))
  · exact inferInstanceAs (Group (order81_nonabelian_reps i))

/-- Every currently formalized representative has order `81`. -/
theorem card_order81_known_reps (i : Fin 5 ⊕ (Fin 9 ⊕ Fin 1)) :
    Nat.card (order81_known_reps i) = 81 := by
  rcases i with i | i
  · exact card_order81_abelian_reps i
  · exact card_order81_nonabelian_reps i

/-- No abelian representative is isomorphic to one of the currently certified non-abelian
representatives. -/
theorem order81_abelian_nonabelian_disjoint :
    ∀ i j, ¬ Nonempty (order81_abelian_reps i ≃* order81_nonabelian_reps j) :=
  pairwise_disjoint_of_comm_noncomm
    (fun _ a b => mul_comm a b)
    order81_nonabelian_reps_nonabelian

/-- The currently formalized fifteen representatives are pairwise non-isomorphic. -/
theorem order81_known_reps_pairwise : PairwiseNonMulEquiv order81_known_reps := by
  rintro (i | i) (j | j) h
  · exact congrArg Sum.inl (order81_abelian_distinct i j h)
  · exact absurd h (order81_abelian_nonabelian_disjoint i j)
  · exact absurd ⟨h.some.symm⟩ (order81_abelian_nonabelian_disjoint j i)
  · exact congrArg Sum.inr (order81_nonabelian_reps_pairwise i j h)

/-- A concrete reindexing of the five abelian and ten non-abelian representatives by `Fin 15`. -/
def order81_fin15Equiv : Fin 15 ≃ Fin 5 ⊕ (Fin 9 ⊕ Fin 1) where
  toFun
    | 0 => Sum.inl 0
    | 1 => Sum.inl 1
    | 2 => Sum.inl 2
    | 3 => Sum.inl 3
    | 4 => Sum.inl 4
    | 5 => Sum.inr (Sum.inl 0)
    | 6 => Sum.inr (Sum.inl 1)
    | 7 => Sum.inr (Sum.inl 2)
    | 8 => Sum.inr (Sum.inl 3)
    | 9 => Sum.inr (Sum.inl 4)
    | 10 => Sum.inr (Sum.inl 5)
    | 11 => Sum.inr (Sum.inl 6)
    | 12 => Sum.inr (Sum.inl 7)
    | 13 => Sum.inr (Sum.inl 8)
    | 14 => Sum.inr (Sum.inr 0)
  invFun
    | Sum.inl 0 => 0
    | Sum.inl 1 => 1
    | Sum.inl 2 => 2
    | Sum.inl 3 => 3
    | Sum.inl 4 => 4
    | Sum.inr (Sum.inl 0) => 5
    | Sum.inr (Sum.inl 1) => 6
    | Sum.inr (Sum.inl 2) => 7
    | Sum.inr (Sum.inl 3) => 8
    | Sum.inr (Sum.inl 4) => 9
    | Sum.inr (Sum.inl 5) => 10
    | Sum.inr (Sum.inl 6) => 11
    | Sum.inr (Sum.inl 7) => 12
    | Sum.inr (Sum.inl 8) => 13
    | Sum.inr (Sum.inr 0) => 14
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by
    rcases i with i | i
    · fin_cases i <;> rfl
    · rcases i with i | i
      · fin_cases i <;> rfl
      · fin_cases i
        rfl

/-- The fifteen currently formalized representatives of order `81`, indexed by `Fin 15`. -/
abbrev order81_reps : Fin 15 → Type :=
  fun i => order81_known_reps (order81_fin15Equiv i)

noncomputable instance instGroupOrder81Reps (i : Fin 15) : Group (order81_reps i) :=
  inferInstanceAs (Group (order81_known_reps (order81_fin15Equiv i)))

/-- Every representative in the `Fin 15` list has order `81`. -/
theorem card_order81_reps (i : Fin 15) : Nat.card (order81_reps i) = 81 :=
  card_order81_known_reps (order81_fin15Equiv i)

/-- The `Fin 15` list of representatives is pairwise non-isomorphic. -/
theorem order81_reps_pairwise : PairwiseNonMulEquiv order81_reps :=
  PairwiseNonMulEquiv.reindex order81_fin15Equiv order81_known_reps_pairwise

/-- Any complete classification of groups of order `81` has at least fifteen representatives. -/
theorem order81_atLeast15 {k : ℕ} {rep : Fin k → Type} [∀ i, Group (rep i)]
    (h : IsClassif 81 rep) : 15 ≤ k :=
  IsClassif.card_ge_of_pairwise h card_order81_reps order81_reps_pairwise

end Smallgroups.UsefulTheorems
