/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.SchurZassenhaus
import Smallgroups.UsefulTheorems.Order2PSq
import Smallgroups.UsefulTheorems.Order2PSqElem
import Smallgroups.UsefulTheorems.PrimePairNonabelian
import Smallgroups.UsefulTheorems.PrimeSqClassification
import Smallgroups.UsefulTheorems.SemidirectProductClassify
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.GroupTheory.SpecificGroups.Alternating
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Mathlib.GroupTheory.Sylow
import Mathlib.Tactic.NormNum.Prime

/-!
# First reductions for groups of order `36`

For a group `G` of order `36 = 4 * 3^2`, the number of Sylow `3`-subgroups is
`1` or `4`.

* If it is `1`, the Sylow `3`-subgroup is normal of order `9`, and Schur--Zassenhaus
  writes `G` as a semidirect product `N ⋊ H` with `|N| = 9` and `|H| = 4`.
* If it is `4`, the conjugation action on the four Sylow `3`-subgroups has kernel
  of order `3` and image the alternating group `A₄` after identifying the four
  Sylow subgroups with `Fin 4`.

These are the two structural branches used in the classification of groups of order `36`.
-/

namespace Smallgroups.UsefulTheorems

open Sylow Equiv.Perm Subgroup

variable {G : Type*} [Group G]

/-! ### Standard factors and representatives for the normal Sylow branch -/

/-- The cyclic group `C₂`. -/
abbrev order36_C2 : Type := CyclicRep 2

/-- The cyclic group `C₄`. -/
abbrev order36_C4 : Type := CyclicRep 4

/-- The Klein four group, written as `C₂ × C₂`. -/
abbrev order36_V4 : Type := order36_C2 × order36_C2

/-- The cyclic group `C₉`. -/
abbrev order36_C9 : Type := CyclicRep 9

/-- The elementary abelian group `C₃ × C₃`. -/
abbrev order36_E9 : Type := ElemAbelianRep 3

/-- A `C₄` action generated by an automorphism whose fourth power is the identity. -/
noncomputable def order36_c4ActionOfAut {N : Type*} [Group N]
    (α : MulAut N) (hα : α ^ 4 = 1) : order36_C4 →* MulAut N :=
  MonoidHom.mk' (fun x => α ^ (Multiplicative.toAdd x).val)
    (fun x y => pow_val_add hα (Multiplicative.toAdd x) (Multiplicative.toAdd y))

private theorem order36_neg_one_pow_four_units :
    (-1 : (ZMod 9)ˣ) ^ 4 = 1 := by
  rw [show (4 : ℕ) = 2 * 2 by norm_num, pow_mul]
  simp [sq]

/-- Multiplication by units embeds into the automorphism group of `C₉`. -/
theorem order36_unitAutHom_injective : Function.Injective (unitAutHom (p := 9)) := by
  intro u v h
  have h1 : unitAutHom u (Multiplicative.ofAdd (1 : ZMod 9)) =
      unitAutHom v (Multiplicative.ofAdd (1 : ZMod 9)) := by rw [h]
  simp only [unitAutHom_apply, mul_one, EmbeddingLike.apply_eq_iff_eq] at h1
  exact Units.ext (congrArg Multiplicative.toAdd h1)

/-- Every automorphism of `C₉` is multiplication by a unit of `ZMod 9`. -/
theorem order36_mulAut_c9_eq_unitAutHom (σ : MulAut order36_C9) :
    ∃ u : (ZMod 9)ˣ, σ = unitAutHom u := by
  let f : AddAut (ZMod 9) := Multiplicative.toAdd ((MulAutMultiplicative (ZMod 9)) σ)
  let u : (ZMod 9)ˣ := Additive.toMul ((ZMod.AddAutEquivUnits 9) f)
  refine ⟨u, ?_⟩
  ext x
  obtain ⟨m, rfl⟩ := Multiplicative.ofAdd.surjective x
  change Multiplicative.ofAdd (f m) = unitAutHom u (Multiplicative.ofAdd m)
  have hu : Additive.ofMul u = (ZMod.AddAutEquivUnits 9) f := by simp [u]
  have hf : f = (ZMod.AddAutEquivUnits 9).symm (Additive.ofMul u) := by
    symm
    rw [hu]
    exact AddEquiv.symm_apply_apply (ZMod.AddAutEquivUnits 9) f
  rw [hf, unitAutHom_apply]
  simp [ZMod.AddAutEquivUnits_symm_apply, Units.smul_def]

/-- A unit of `ZMod 9` whose fourth power is `1` is `1` or `-1`. -/
theorem order36_unit_pow_four_eq_one_cases (u : (ZMod 9)ˣ) (_hu : u ^ 4 = 1) :
    u = 1 ∨ u = -1 := by
  decide +revert

/-- A unit of `ZMod 9` whose square is `1` is `1` or `-1`. -/
theorem order36_unit_sq_eq_one_cases (u : (ZMod 9)ˣ) (_hu : u ^ 2 = 1) :
    u = 1 ∨ u = -1 := by
  decide +revert

/-- Turn a unit-valued character into the corresponding action on `C₉`. -/
noncomputable abbrev order36_c9Action {H : Type*} [Group H] (χ : H →* (ZMod 9)ˣ) :
    H →* MulAut order36_C9 :=
  unitAutHom.comp χ

theorem order36_c9Action_one {H : Type*} [Group H] :
    order36_c9Action (H := H) 1 = 1 := by
  ext h x
  simp [order36_c9Action]

/-- If a product of acting groups acts only through the first factor, split off the second
factor. -/
noncomputable def semidirectProductActingProdFst {N H K : Type*} [Group N] [Group H] [Group K]
    (ψ : H →* MulAut N) :
    SemidirectProduct N (H × K) (ψ.comp (MonoidHom.fst H K)) ≃*
      SemidirectProduct N H ψ × K where
  toFun x := (⟨x.left, x.right.1⟩, x.right.2)
  invFun x := ⟨x.1.left, (x.1.right, x.2)⟩
  left_inv x := by
    cases x
    rfl
  right_inv x := by
    cases x with
    | mk x1 x2 =>
      cases x1
      rfl
  map_mul' x y := by
    rfl

noncomputable def order36_c9Action_precomp_mulEquiv {H : Type*} [Group H]
    (χ : H →* (ZMod 9)ˣ) (σ : H ≃* H) :
    SemidirectProduct order36_C9 H (order36_c9Action (χ.comp σ.toMonoidHom)) ≃*
      SemidirectProduct order36_C9 H (order36_c9Action χ) :=
  semidirectProductCongrAut (N := order36_C9) (H := H) (φ := order36_c9Action χ) σ

noncomputable def order36_c9Action_precomp_eq_mulEquiv {H : Type*} [Group H]
    (χ ψ : H →* (ZMod 9)ˣ) (σ : H ≃* H)
    (h : χ.comp σ.toMonoidHom = ψ) :
    SemidirectProduct order36_C9 H (order36_c9Action ψ) ≃*
      SemidirectProduct order36_C9 H (order36_c9Action χ) := by
  have haction : order36_c9Action ψ = order36_c9Action (χ.comp σ.toMonoidHom) := by
    rw [h]
  exact (semidirectProductCongr_eq haction).trans
    (order36_c9Action_precomp_mulEquiv χ σ)

/-- The non-trivial `C₄` character with image generated by `-1`. -/
noncomputable abbrev order36_chiC4_inv : order36_C4 →* (ZMod 9)ˣ :=
  powHom (p := 9) (q := 4) (-1 : (ZMod 9)ˣ) order36_neg_one_pow_four_units

@[simp]
theorem order36_chiC4_inv_gen :
    order36_chiC4_inv (Multiplicative.ofAdd (1 : ZMod 4)) = (-1 : (ZMod 9)ˣ) := by
  change (-1 : (ZMod 9)ˣ) ^ (1 : ZMod 4).val = -1
  rw [show (1 : ZMod 4).val = 1 by decide]
  simp

/-- Homomorphisms out of `C₄` are determined by the additive generator `1`. -/
theorem order36_c4_hom_ext {M : Type*} [Group M] {χ ψ : order36_C4 →* M}
    (hgen : χ (Multiplicative.ofAdd (1 : ZMod 4)) =
      ψ (Multiplicative.ofAdd (1 : ZMod 4))) :
    χ = ψ := by
  apply MonoidHom.ext
  intro x
  let n : ZMod 4 := Multiplicative.toAdd x
  have hx : x = (Multiplicative.ofAdd (1 : ZMod 4)) ^ n.val := by
    rw [show x = Multiplicative.ofAdd n from (ofAdd_toAdd _).symm]
    calc
      Multiplicative.ofAdd n = Multiplicative.ofAdd ((n.val : ZMod 4)) := by
        rw [ZMod.natCast_zmod_val]
      _ = Multiplicative.ofAdd (n.val • (1 : ZMod 4)) := by simp
      _ = (Multiplicative.ofAdd (1 : ZMod 4)) ^ n.val := by rw [ofAdd_nsmul]
  rw [hx, map_pow, map_pow, hgen]

theorem order36_c4_unit_character_cases (χ : order36_C4 →* (ZMod 9)ˣ) :
    χ = 1 ∨ χ = order36_chiC4_inv := by
  let g : order36_C4 := Multiplicative.ofAdd (1 : ZMod 4)
  have hpow : χ g ^ 4 = 1 := by
    rw [← map_pow, show g ^ 4 = 1 by decide, map_one]
  rcases order36_unit_pow_four_eq_one_cases (χ g) hpow with h | h
  · left
    apply order36_c4_hom_ext
    simp [g, h]
  · right
    apply order36_c4_hom_ext
    rw [h, order36_chiC4_inv_gen]

/-- Every action `C₄ → Aut(C₉)` is induced by a unit-valued character. -/
theorem order36_c4_c9Action_eq (φ : order36_C4 →* MulAut order36_C9) :
    ∃ χ : order36_C4 →* (ZMod 9)ˣ, φ = order36_c9Action χ := by
  let g : order36_C4 := Multiplicative.ofAdd (1 : ZMod 4)
  obtain ⟨u, huφ⟩ := order36_mulAut_c9_eq_unitAutHom (φ g)
  have hg4 : g ^ 4 = 1 := by decide
  have hφg4 : (φ g) ^ 4 = 1 := by rw [← map_pow, hg4, map_one]
  have hu4 : u ^ 4 = 1 := by
    apply order36_unitAutHom_injective
    rw [map_pow, ← huφ, hφg4]
    exact (map_one (unitAutHom (p := 9))).symm
  refine ⟨powHom (p := 9) (q := 4) u hu4, ?_⟩
  apply order36_c4_hom_ext
  rw [huφ]
  change unitAutHom u = unitAutHom (u ^ (1 : ZMod 4).val)
  rw [show (1 : ZMod 4).val = 1 by decide]
  simp

theorem order36_c4_c9Action_cases (φ : order36_C4 →* MulAut order36_C9) :
    φ = 1 ∨ φ = order36_c9Action order36_chiC4_inv := by
  obtain ⟨χ, hφ⟩ := order36_c4_c9Action_eq φ
  rw [hφ]
  rcases order36_c4_unit_character_cases χ with hχ | hχ
  · left
    rw [hχ]
    exact order36_c9Action_one
  · right
    rw [hχ]

/-- The quotient map `C₂ → (ZMod 9)ˣ` sending the generator to `-1`. -/
noncomputable abbrev order36_c2UnitHom : CyclicRep 2 →* (ZMod 9)ˣ :=
  powHom (p := 9) (q := 2) (-1 : (ZMod 9)ˣ) (by decide)

@[simp]
theorem order36_c2UnitHom_gen :
    order36_c2UnitHom (Multiplicative.ofAdd (1 : ZMod 2)) =
      (-1 : (ZMod 9)ˣ) := by
  decide

theorem order36_c9Action_c2UnitHom_eq_invActionHom :
    order36_c9Action order36_c2UnitHom = invActionHom order36_C9 := by
  apply MonoidHom.ext
  intro h
  rcases multiplicative_zmod_two_cases h with rfl | rfl
  · simp [order36_c9Action, invActionHom]
  · change unitAutHom (order36_c2UnitHom (Multiplicative.ofAdd (1 : ZMod 2))) =
      invActionHom order36_C9 (Multiplicative.ofAdd (1 : ZMod 2))
    rw [order36_c2UnitHom_gen, invActionHom_ofAdd_one]
    ext x
    obtain ⟨m, rfl⟩ := Multiplicative.ofAdd.surjective x
    simp [unitAutHom_apply, invAut_apply]

noncomputable abbrev order36_chiV4_fst : order36_V4 →* (ZMod 9)ˣ :=
  order36_c2UnitHom.comp (MonoidHom.fst (CyclicRep 2) (CyclicRep 2))

noncomputable abbrev order36_chiV4_snd : order36_V4 →* (ZMod 9)ˣ :=
  order36_c2UnitHom.comp (MonoidHom.snd (CyclicRep 2) (CyclicRep 2))

noncomputable abbrev order36_chiV4_prod : order36_V4 →* (ZMod 9)ˣ :=
  order36_chiV4_fst * order36_chiV4_snd

/-- Homomorphisms out of `V₄ = C₂ × C₂` are determined by the two standard generators. -/
theorem order36_v4_hom_ext {M : Type*} [Group M] {χ ψ : order36_V4 →* M}
    (h1 : χ (Multiplicative.ofAdd (1 : ZMod 2), 1) =
      ψ (Multiplicative.ofAdd (1 : ZMod 2), 1))
    (h2 : χ (1, Multiplicative.ofAdd (1 : ZMod 2)) =
      ψ (1, Multiplicative.ofAdd (1 : ZMod 2))) :
    χ = ψ := by
  apply MonoidHom.ext
  rintro ⟨x1, x2⟩
  obtain ⟨a, rfl⟩ := Multiplicative.ofAdd.surjective x1
  obtain ⟨b, rfl⟩ := Multiplicative.ofAdd.surjective x2
  let g1 : order36_V4 := (Multiplicative.ofAdd (1 : ZMod 2), 1)
  let g2 : order36_V4 := (1, Multiplicative.ofAdd (1 : ZMod 2))
  have ha : Multiplicative.ofAdd a = (Multiplicative.ofAdd (1 : ZMod 2)) ^ a.val := by
    calc
      Multiplicative.ofAdd a = Multiplicative.ofAdd ((a.val : ZMod 2)) := by
        rw [ZMod.natCast_zmod_val]
      _ = Multiplicative.ofAdd (a.val • (1 : ZMod 2)) := by simp
      _ = (Multiplicative.ofAdd (1 : ZMod 2)) ^ a.val := by rw [ofAdd_nsmul]
  have hb : Multiplicative.ofAdd b = (Multiplicative.ofAdd (1 : ZMod 2)) ^ b.val := by
    calc
      Multiplicative.ofAdd b = Multiplicative.ofAdd ((b.val : ZMod 2)) := by
        rw [ZMod.natCast_zmod_val]
      _ = Multiplicative.ofAdd (b.val • (1 : ZMod 2)) := by simp
      _ = (Multiplicative.ofAdd (1 : ZMod 2)) ^ b.val := by rw [ofAdd_nsmul]
  have hx : (Multiplicative.ofAdd a, Multiplicative.ofAdd b) = g1 ^ a.val * g2 ^ b.val := by
    simp [g1, g2, Prod.pow_mk, ha, hb]
  rw [hx, map_mul, map_mul, map_pow, map_pow, map_pow, map_pow, h1, h2]

@[simp]
theorem order36_chiV4_fst_g1 :
    order36_chiV4_fst (Multiplicative.ofAdd (1 : ZMod 2), 1) =
      (-1 : (ZMod 9)ˣ) := by
  decide

@[simp]
theorem order36_chiV4_fst_g2 :
    order36_chiV4_fst (1, Multiplicative.ofAdd (1 : ZMod 2)) = 1 := by
  decide

@[simp]
theorem order36_chiV4_snd_g1 :
    order36_chiV4_snd (Multiplicative.ofAdd (1 : ZMod 2), 1) = 1 := by
  decide

@[simp]
theorem order36_chiV4_snd_g2 :
    order36_chiV4_snd (1, Multiplicative.ofAdd (1 : ZMod 2)) =
      (-1 : (ZMod 9)ˣ) := by
  decide

@[simp]
theorem order36_chiV4_prod_g1 :
    order36_chiV4_prod (Multiplicative.ofAdd (1 : ZMod 2), 1) =
      (-1 : (ZMod 9)ˣ) := by
  decide

@[simp]
theorem order36_chiV4_prod_g2 :
    order36_chiV4_prod (1, Multiplicative.ofAdd (1 : ZMod 2)) =
      (-1 : (ZMod 9)ˣ) := by
  decide

theorem order36_v4_unit_character_cases (χ : order36_V4 →* (ZMod 9)ˣ) :
    χ = 1 ∨ χ = order36_chiV4_fst ∨ χ = order36_chiV4_snd ∨
      χ = order36_chiV4_prod := by
  let g1 : order36_V4 := (Multiplicative.ofAdd (1 : ZMod 2), 1)
  let g2 : order36_V4 := (1, Multiplicative.ofAdd (1 : ZMod 2))
  have hsq1 : χ g1 ^ 2 = 1 := by
    rw [← map_pow, show g1 ^ 2 = 1 by decide, map_one]
  have hsq2 : χ g2 ^ 2 = 1 := by
    rw [← map_pow, show g2 ^ 2 = 1 by decide, map_one]
  rcases order36_unit_sq_eq_one_cases (χ g1) hsq1 with h1 | h1 <;>
    rcases order36_unit_sq_eq_one_cases (χ g2) hsq2 with h2 | h2
  · left
    apply order36_v4_hom_ext <;>
      simp [g1, g2, h1, h2]
  · right
    right
    left
    apply order36_v4_hom_ext <;>
      simp [g1, g2, h1, h2]
  · right
    left
    apply order36_v4_hom_ext <;>
      simp [g1, g2, h1, h2]
  · right
    right
    right
    apply order36_v4_hom_ext <;>
      simp [g1, g2, h1, h2]

/-- Every action `V₄ → Aut(C₉)` is induced by a unit-valued character. -/
theorem order36_v4_c9Action_eq (φ : order36_V4 →* MulAut order36_C9) :
    ∃ χ : order36_V4 →* (ZMod 9)ˣ, φ = order36_c9Action χ := by
  let g1 : order36_V4 := (Multiplicative.ofAdd (1 : ZMod 2), 1)
  let g2 : order36_V4 := (1, Multiplicative.ofAdd (1 : ZMod 2))
  obtain ⟨u, huφ⟩ := order36_mulAut_c9_eq_unitAutHom (φ g1)
  obtain ⟨v, hvφ⟩ := order36_mulAut_c9_eq_unitAutHom (φ g2)
  have hg1sq : g1 ^ 2 = 1 := by decide
  have hg2sq : g2 ^ 2 = 1 := by decide
  have hφg1sq : (φ g1) ^ 2 = 1 := by rw [← map_pow, hg1sq, map_one]
  have hφg2sq : (φ g2) ^ 2 = 1 := by rw [← map_pow, hg2sq, map_one]
  have hu2 : u ^ 2 = 1 := by
    apply order36_unitAutHom_injective
    rw [map_pow, ← huφ, hφg1sq]
    exact (map_one (unitAutHom (p := 9))).symm
  have hv2 : v ^ 2 = 1 := by
    apply order36_unitAutHom_injective
    rw [map_pow, ← hvφ, hφg2sq]
    exact (map_one (unitAutHom (p := 9))).symm
  let χ1 : order36_V4 →* (ZMod 9)ˣ :=
    (powHom (p := 9) (q := 2) u hu2).comp (MonoidHom.fst (CyclicRep 2) (CyclicRep 2))
  let χ2 : order36_V4 →* (ZMod 9)ˣ :=
    (powHom (p := 9) (q := 2) v hv2).comp (MonoidHom.snd (CyclicRep 2) (CyclicRep 2))
  refine ⟨χ1 * χ2, ?_⟩
  apply order36_v4_hom_ext
  · rw [huφ]
    change unitAutHom u = unitAutHom ((χ1 * χ2) g1)
    change unitAutHom u = unitAutHom (u ^ (1 : ZMod 2).val * v ^ (0 : ZMod 2).val)
    rw [show (1 : ZMod 2).val = 1 by decide, show (0 : ZMod 2).val = 0 by decide]
    simp
  · rw [hvφ]
    change unitAutHom v = unitAutHom ((χ1 * χ2) g2)
    change unitAutHom v = unitAutHom (u ^ (0 : ZMod 2).val * v ^ (1 : ZMod 2).val)
    rw [show (1 : ZMod 2).val = 1 by decide, show (0 : ZMod 2).val = 0 by decide]
    simp

theorem order36_v4_c9Action_cases (φ : order36_V4 →* MulAut order36_C9) :
    φ = 1 ∨ φ = order36_c9Action order36_chiV4_fst ∨
      φ = order36_c9Action order36_chiV4_snd ∨
        φ = order36_c9Action order36_chiV4_prod := by
  obtain ⟨χ, hφ⟩ := order36_v4_c9Action_eq φ
  rw [hφ]
  rcases order36_v4_unit_character_cases χ with hχ | hχ | hχ | hχ
  · left
    rw [hχ]
    exact order36_c9Action_one
  · right
    left
    rw [hχ]
  · right
    right
    left
    rw [hχ]
  · right
    right
    right
    rw [hχ]

theorem order36_c2_mul_self (x : CyclicRep 2) : x * x = 1 := by
  decide +revert

/-- Swap the two factors of `V₄ = C₂ × C₂`. -/
noncomputable def order36_V4_swap : order36_V4 ≃* order36_V4 where
  toFun x := (x.2, x.1)
  invFun x := (x.2, x.1)
  left_inv x := by cases x; rfl
  right_inv x := by cases x; rfl
  map_mul' x y := by rfl

/-- The shear `(x, y) ↦ (x, xy)` of `V₄ = C₂ × C₂`. -/
noncomputable def order36_V4_shear : order36_V4 ≃* order36_V4 where
  toFun x := (x.1, x.1 * x.2)
  invFun x := (x.1, x.1 * x.2)
  left_inv x := by
    ext
    · rfl
    · change x.1 * (x.1 * x.2) = x.2
      rw [← mul_assoc, order36_c2_mul_self x.1, one_mul]
  right_inv x := by
    ext
    · rfl
    · change x.1 * (x.1 * x.2) = x.2
      rw [← mul_assoc, order36_c2_mul_self x.1, one_mul]
  map_mul' x y := by ext <;> simp [mul_comm, mul_left_comm]

noncomputable def order36_V4_toProd : order36_V4 ≃* order36_V4 :=
  order36_V4_shear.trans order36_V4_swap

theorem order36_chiV4_fst_comp_swap :
    order36_chiV4_fst.comp order36_V4_swap.toMonoidHom = order36_chiV4_snd := by
  apply order36_v4_hom_ext <;> decide

theorem order36_chiV4_fst_comp_toProd :
    order36_chiV4_fst.comp order36_V4_toProd.toMonoidHom = order36_chiV4_prod := by
  apply order36_v4_hom_ext <;> decide

noncomputable def order36_c9V4_snd_equiv_fst :
    SemidirectProduct order36_C9 order36_V4 (order36_c9Action order36_chiV4_snd) ≃*
      SemidirectProduct order36_C9 order36_V4 (order36_c9Action order36_chiV4_fst) :=
  order36_c9Action_precomp_eq_mulEquiv order36_chiV4_fst order36_chiV4_snd
    order36_V4_swap order36_chiV4_fst_comp_swap

noncomputable def order36_c9V4_prod_equiv_fst :
    SemidirectProduct order36_C9 order36_V4 (order36_c9Action order36_chiV4_prod) ≃*
      SemidirectProduct order36_C9 order36_V4 (order36_c9Action order36_chiV4_fst) :=
  order36_c9Action_precomp_eq_mulEquiv order36_chiV4_fst order36_chiV4_prod
    order36_V4_toProd order36_chiV4_fst_comp_toProd

noncomputable def order36_c9V4_fst_equiv_dihedral_prod :
    SemidirectProduct order36_C9 order36_V4 (order36_c9Action order36_chiV4_fst) ≃*
      DihedralGroup 9 × order36_C2 := by
  have haction : order36_c9Action order36_chiV4_fst =
      (order36_c9Action order36_c2UnitHom).comp
        (MonoidHom.fst order36_C2 order36_C2) := by
    rfl
  haveI : NeZero 9 := ⟨by norm_num⟩
  exact (semidirectProductCongr_eq haction).trans <|
    (semidirectProductActingProdFst (N := order36_C9) (H := order36_C2) (K := order36_C2)
      (order36_c9Action order36_c2UnitHom)).trans <|
    MulEquiv.prodCongr
      ((semidirectProductCongr_eq order36_c9Action_c2UnitHom_eq_invActionHom).trans
        (genDihedralCyclicIso 9))
      (MulEquiv.refl order36_C2)

/-- The inversion action of `C₄` on `C₉`, factoring through `C₂`. -/
noncomputable abbrev order36_C9_C4_invAction : order36_C4 →* MulAut order36_C9 :=
  order36_c9Action order36_chiC4_inv

/-- The additive group underlying `C₃ × C₃`. -/
abbrev order36_E9Add : Type := ZMod 3 × ZMod 3

/-- Negate both coordinates of `C₃ × C₃`. -/
def order36_E9_negBothAddEquiv : order36_E9Add ≃+ order36_E9Add where
  toFun x := (-x.1, -x.2)
  invFun x := (-x.1, -x.2)
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_add' x y := by
    ext
    · change -(x.1 + y.1) = -x.1 + -y.1
      abel
    · change -(x.2 + y.2) = -x.2 + -y.2
      abel

/-- Negate the first coordinate of `C₃ × C₃`. -/
def order36_E9_negFirstAddEquiv : order36_E9Add ≃+ order36_E9Add where
  toFun x := (-x.1, x.2)
  invFun x := (-x.1, x.2)
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_add' x y := by
    ext
    · change -(x.1 + y.1) = -x.1 + -y.1
      abel
    · change x.2 + y.2 = x.2 + y.2
      rfl

/-- An order-four rotation of `C₃ × C₃`: `(x, y) ↦ (-y, x)`. -/
def order36_E9_rotAddEquiv : order36_E9Add ≃+ order36_E9Add where
  toFun x := (-x.2, x.1)
  invFun x := (x.2, -x.1)
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_add' x y := by
    ext
    · change -(x.2 + y.2) = -x.2 + -y.2
      abel
    · change x.1 + y.1 = x.1 + y.1
      rfl

/-- The automorphism `-I` of `C₃ × C₃`. -/
def order36_E9_negBothAut : MulAut order36_E9 :=
  AddEquiv.toMultiplicative order36_E9_negBothAddEquiv

/-- The reflection automorphism `(x, y) ↦ (-x, y)` of `C₃ × C₃`. -/
def order36_E9_negFirstAut : MulAut order36_E9 :=
  AddEquiv.toMultiplicative order36_E9_negFirstAddEquiv

/-- The order-four automorphism `(x, y) ↦ (-y, x)` of `C₃ × C₃`. -/
def order36_E9_rotAut : MulAut order36_E9 :=
  AddEquiv.toMultiplicative order36_E9_rotAddEquiv

theorem order36_E9_negBothAut_pow_four : order36_E9_negBothAut ^ 4 = 1 := by
  ext x <;> fin_cases x <;> decide

theorem order36_E9_negFirstAut_pow_four : order36_E9_negFirstAut ^ 4 = 1 := by
  ext x <;> fin_cases x <;> decide

theorem order36_E9_rotAut_pow_four : order36_E9_rotAut ^ 4 = 1 := by
  ext x <;> fin_cases x <;> decide

/-- `C₃ × C₃` with a `C₄` action by `-I`. -/
noncomputable abbrev order36_E9_C4_negBothAction : order36_C4 →* MulAut order36_E9 :=
  order36_c4ActionOfAut order36_E9_negBothAut order36_E9_negBothAut_pow_four

/-- `C₃ × C₃` with a `C₄` action by a reflection. -/
noncomputable abbrev order36_E9_C4_negFirstAction : order36_C4 →* MulAut order36_E9 :=
  order36_c4ActionOfAut order36_E9_negFirstAut order36_E9_negFirstAut_pow_four

/-- `C₃ × C₃` with a faithful `C₄` action. -/
noncomputable abbrev order36_E9_C4_rotAction : order36_C4 →* MulAut order36_E9 :=
  order36_c4ActionOfAut order36_E9_rotAut order36_E9_rotAut_pow_four

/-- The twelve representatives arising from the normal Sylow-`3` branch of order `36`. -/
noncomputable def order36_normal_reps : Fin 12 → Type
  | 0 => order36_C9 × order36_C4
  | 1 => SemidirectProduct order36_C9 order36_C4 order36_C9_C4_invAction
  | 2 => order36_C9 × order36_V4
  | 3 => DihedralGroup 9 × order36_C2
  | 4 => order36_E9 × order36_C4
  | 5 => SemidirectProduct order36_E9 order36_C4 order36_E9_C4_negBothAction
  | 6 => SemidirectProduct order36_E9 order36_C4 order36_E9_C4_negFirstAction
  | 7 => SemidirectProduct order36_E9 order36_C4 order36_E9_C4_rotAction
  | 8 => order36_E9 × order36_V4
  | 9 => SemidirectProduct order36_E9 order36_C2 (invActionHom order36_E9) × order36_C2
  | 10 => DihedralGroup 3 × CyclicRep 3 × order36_C2
  | 11 => DihedralGroup 3 × DihedralGroup 3

noncomputable instance order36_normal_reps_group : ∀ i, Group (order36_normal_reps i)
  | 0 => by dsimp [order36_normal_reps]; infer_instance
  | 1 => by dsimp [order36_normal_reps]; infer_instance
  | 2 => by dsimp [order36_normal_reps]; infer_instance
  | 3 => by dsimp [order36_normal_reps]; infer_instance
  | 4 => by dsimp [order36_normal_reps]; infer_instance
  | 5 => by dsimp [order36_normal_reps]; infer_instance
  | 6 => by dsimp [order36_normal_reps]; infer_instance
  | 7 => by dsimp [order36_normal_reps]; infer_instance
  | 8 => by dsimp [order36_normal_reps]; infer_instance
  | 9 => by dsimp [order36_normal_reps]; infer_instance
  | 10 => by dsimp [order36_normal_reps]; infer_instance
  | 11 => by dsimp [order36_normal_reps]; infer_instance

/-- Every representative in the normal Sylow-`3` branch has order `36`. -/
theorem card_order36_normal_reps (i : Fin 12) : Nat.card (order36_normal_reps i) = 36 := by
  fin_cases i <;>
    simp [order36_normal_reps, SemidirectProduct.card, Nat.card_prod, DihedralGroup.card]

theorem order36_c9_c4_action_rep_cases (φ : order36_C4 →* MulAut order36_C9) :
    Nonempty (SemidirectProduct order36_C9 order36_C4 φ ≃*
      order36_normal_reps (0 : Fin 12)) ∨
      Nonempty (SemidirectProduct order36_C9 order36_C4 φ ≃*
        order36_normal_reps (1 : Fin 12)) := by
  rcases order36_c4_c9Action_cases φ with hφ | hφ
  · left
    exact ⟨(semidirectProductCongr_eq hφ).trans SemidirectProduct.mulEquivProd⟩
  · right
    exact ⟨semidirectProductCongr_eq hφ⟩

theorem order36_c9_v4_action_rep_cases (φ : order36_V4 →* MulAut order36_C9) :
    Nonempty (SemidirectProduct order36_C9 order36_V4 φ ≃*
      order36_normal_reps (2 : Fin 12)) ∨
      Nonempty (SemidirectProduct order36_C9 order36_V4 φ ≃*
        order36_normal_reps (3 : Fin 12)) := by
  rcases order36_v4_c9Action_cases φ with hφ | hφ | hφ | hφ
  · left
    exact ⟨(semidirectProductCongr_eq hφ).trans SemidirectProduct.mulEquivProd⟩
  · right
    exact ⟨(semidirectProductCongr_eq hφ).trans order36_c9V4_fst_equiv_dihedral_prod⟩
  · right
    exact ⟨(semidirectProductCongr_eq hφ).trans
      (order36_c9V4_snd_equiv_fst.trans order36_c9V4_fst_equiv_dihedral_prod)⟩
  · right
    exact ⟨(semidirectProductCongr_eq hφ).trans
      (order36_c9V4_prod_equiv_fst.trans order36_c9V4_fst_equiv_dihedral_prod)⟩

/-! ### Sylow `3` counting and the normal Sylow branch -/

/-- In a group of order `36`, the number of Sylow `3`-subgroups is `1` or `4`. -/
theorem card_sylow_3_eq_one_or_four_of_card_36 [Finite G] (hG : Nat.card G = 36) :
    Nat.card (Sylow 3 G) = 1 ∨ Nat.card (Sylow 3 G) = 4 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 3 G))
  have hdvd36 : Nat.card (Sylow 3 G) ∣ 36 := by
    rw [← hG]
    exact P0.card_dvd_index.trans (Subgroup.index_dvd_card _)
  have hndvd : ¬ 3 ∣ Nat.card (Sylow 3 G) := not_dvd_card_sylow 3 G
  have hcop : Nat.Coprime (Nat.card (Sylow 3 G)) (3 ^ 2) :=
    ((Nat.prime_three.coprime_iff_not_dvd.mpr hndvd).symm).pow_right 2
  have hdvd4_mul : Nat.card (Sylow 3 G) ∣ 4 * 3 ^ 2 := by
    simpa [show 36 = 4 * 3 ^ 2 by norm_num] using hdvd36
  have hdvd4 : Nat.card (Sylow 3 G) ∣ 4 :=
    hcop.dvd_of_dvd_mul_right hdvd4_mul
  have hmod := card_sylow_modEq_one 3 G
  have hle : Nat.card (Sylow 3 G) ≤ 4 := Nat.le_of_dvd (by norm_num) hdvd4
  have hpos : 0 < Nat.card (Sylow 3 G) := Nat.card_pos
  interval_cases h : Nat.card (Sylow 3 G)
  · left
    rfl
  · unfold Nat.ModEq at hmod
    omega
  · norm_num at hdvd4
  · right
    rfl

/-- A Sylow `3`-subgroup of a group of order `36` has order `9`. -/
theorem card_sylow_3_subgroup_of_card_36 [Finite G] (hG : Nat.card G = 36)
    (P : Sylow 3 G) : Nat.card (↑P : Subgroup G) = 9 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  have hfact : (36 : ℕ).factorization 3 = 2 := by
    rw [show 36 = 4 * 3 ^ 2 by norm_num,
      Nat.factorization_mul (by norm_num) (by norm_num), Finsupp.add_apply,
      Nat.factorization_eq_zero_of_not_dvd (by norm_num : ¬ (3 : ℕ) ∣ 4),
      Nat.factorization_pow_self (by norm_num : Nat.Prime 3), zero_add]
  rw [Sylow.card_eq_multiplicity, hG, hfact]
  norm_num

/-- If there is a unique Sylow `3`-subgroup in a group of order `36`, it is normal. -/
theorem sylow_3_normal_of_card_36_of_card_sylow_eq_one [Finite G]
    (hSyl : Nat.card (Sylow 3 G) = 1) (P : Sylow 3 G) :
    (↑P : Subgroup G).Normal := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Subsingleton (Sylow 3 G) := (Nat.card_eq_one_iff_unique.mp hSyl).1
  exact normal_of_subsingleton P

/-- **Schur--Zassenhaus reduction for the normal Sylow-`3` branch of order `36`.** -/
theorem order36_semidirectProduct_of_card_sylow_3_eq_one [Finite G] (hG : Nat.card G = 36)
    (hSyl : Nat.card (Sylow 3 G) = 1) :
    ∃ (N H : Subgroup G) (φ : H →* MulAut N),
      N.Normal ∧ Nat.card N = 9 ∧ Nat.card H = 4 ∧
        Nonempty (G ≃* SemidirectProduct N H φ) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 3 G))
  haveI hnorm : (↑P0 : Subgroup G).Normal :=
    sylow_3_normal_of_card_36_of_card_sylow_eq_one hSyl P0
  have hcardN : Nat.card (↑P0 : Subgroup G) = 9 :=
    card_sylow_3_subgroup_of_card_36 hG P0
  haveI : (↑P0 : Subgroup G).FiniteIndex := ⟨Subgroup.index_ne_zero_of_finite⟩
  have hcop : Nat.Coprime (Nat.card (↑P0 : Subgroup G)) (↑P0 : Subgroup G).index := by
    rw [hcardN]
    have hidx : (↑P0 : Subgroup G).index = 4 := by
      have := (↑P0 : Subgroup G).card_mul_index
      rw [hcardN, hG] at this
      omega
    rw [hidx]
    norm_num
  obtain ⟨H, φ, ⟨e⟩⟩ := schurZassenhaus_semidirectProduct (↑P0 : Subgroup G) hcop
  have hcardH : Nat.card H = 4 := by
    have h1 : Nat.card G = Nat.card (↑P0 : Subgroup G) * Nat.card H := by
      rw [Nat.card_congr e.toEquiv, Nat.card_congr SemidirectProduct.equivProd, Nat.card_prod]
    rw [hG, hcardN] at h1
    have h1' : 9 * Nat.card H = 9 * 4 := by omega
    exact Nat.eq_of_mul_eq_mul_left (by norm_num : 0 < 9) h1'
  exact ⟨↑P0, H, φ, hnorm, hcardN, hcardH, ⟨e⟩⟩

/-! ### The non-normal Sylow branch -/

/-- If there are four Sylow `3`-subgroups, each Sylow `3`-subgroup is self-normalizing. -/
theorem sylow_3_eq_normalizer_of_card_36_of_card_sylow_3_eq_four [Finite G]
    (hG : Nat.card G = 36) (hSyl : Nat.card (Sylow 3 G) = 4) (P : Sylow 3 G) :
    (↑P : Subgroup G) = Subgroup.normalizer (P : Set G) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  have hcardP : Nat.card (↑P : Subgroup G) = 9 :=
    card_sylow_3_subgroup_of_card_36 hG P
  have hidx : (Subgroup.normalizer (P : Set G)).index = 4 := by
    rwa [← Sylow.card_eq_index_normalizer P]
  have hcardNorm : Nat.card (Subgroup.normalizer (P : Set G)) = 9 := by
    have := (Subgroup.normalizer (P : Set G)).card_mul_index
    rw [hidx, hG] at this
    omega
  exact Subgroup.eq_of_le_of_card_ge Subgroup.le_normalizer (by rw [hcardNorm, hcardP])

/-- In the non-normal Sylow-`3` branch of order `36`, the conjugation action on the four
Sylow `3`-subgroups has kernel of order `3` and image `A₄`, after the Sylow subgroups are
identified with `Fin 4`. -/
theorem order36_sylow_3_conj_action_A4_of_card_sylow_3_eq_four [Finite G]
    (hG : Nat.card G = 36) (hSyl : Nat.card (Sylow 3 G) = 4) :
    ∃ ψ : G →* Equiv.Perm (Fin 4),
      Nat.card ψ.ker = 3 ∧ ψ.range = alternatingGroup (Fin 4) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Fintype (Sylow 3 G) := Fintype.ofFinite _
  have hfincard : Fintype.card (Sylow 3 G) = 4 := by
    rwa [← Nat.card_eq_fintype_card]
  let ε : Sylow 3 G ≃ Fin 4 := by rw [← hfincard]; exact Fintype.equivFin _
  let φ := MulAction.toPermHom G (Sylow 3 G)
  let ψ : G →* Equiv.Perm (Fin 4) :=
    (Equiv.permCongrHom ε).toMonoidHom.comp φ
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 3 G))
  have hP_eq_norm :
      (↑P0 : Subgroup G) = Subgroup.normalizer (P0 : Set G) :=
    sylow_3_eq_normalizer_of_card_36_of_card_sylow_3_eq_four hG hSyl P0
  have hker_le : ψ.ker ≤ ↑P0 := by
    intro g hg
    rw [hP_eq_norm]
    have hgψ := MonoidHom.mem_ker.mp hg
    have hgφ : φ g = 1 := by
      have hgφ' : ε.permCongr (φ g) = 1 := by
        change ψ g = 1 at hgψ
        exact hgψ
      have hgφ'' : ε.permCongr (φ g) = ε.permCongr 1 := by
        have h_one : ε.permCongr 1 = (1 : Equiv.Perm (Fin 4)) := by
          ext x
          simp [Equiv.permCongr_apply]
        rw [h_one]
        exact hgφ'
      exact ε.permCongr.injective hgφ''
    rw [← Sylow.stabilizer_eq_normalizer]
    rw [MulAction.mem_stabilizer_iff]
    exact Equiv.Perm.ext_iff.mp hgφ P0
  have hcardP : Nat.card (↑P0 : Subgroup G) = 9 :=
    card_sylow_3_subgroup_of_card_36 hG P0
  have hker_card_dvd : Nat.card ψ.ker ∣ Nat.card (↑P0 : Subgroup G) :=
    Subgroup.card_dvd_of_le hker_le
  rw [hcardP] at hker_card_dvd
  have hker_card_ne_nine : Nat.card ψ.ker ≠ 9 := by
    intro hker_card
    have hker_eq : ψ.ker = ↑P0 :=
      Subgroup.eq_of_le_of_card_ge hker_le (by rw [hcardP, hker_card])
    haveI : (↑P0 : Subgroup G).Normal := hker_eq ▸ MonoidHom.normal_ker ψ
    haveI := Sylow.unique_of_normal P0 (by assumption)
    have : Nat.card (Sylow 3 G) = 1 := Nat.card_unique
    omega
  have hker_card_ne_one : Nat.card ψ.ker ≠ 1 := by
    intro hker_card
    have hker_bot : ψ.ker = ⊥ := ψ.ker.eq_bot_of_card_eq hker_card
    have hψ_inj : Function.Injective ψ := ψ.ker_eq_bot_iff.mp hker_bot
    have e_range : G ≃* ψ.range := MonoidHom.ofInjective hψ_inj
    have h_range_card : Nat.card ψ.range = 36 := by
      rw [← hG, Nat.card_congr e_range.toEquiv]
    have h_perm_card : Nat.card (Equiv.Perm (Fin 4)) = 24 := by
      rw [Nat.card_perm, Nat.card_fin]
      decide
    have h_dvd : Nat.card ψ.range ∣ Nat.card (Equiv.Perm (Fin 4)) :=
      Subgroup.card_subgroup_dvd_card ψ.range
    rw [h_range_card, h_perm_card] at h_dvd
    norm_num at h_dvd
  have hker_card : Nat.card ψ.ker = 3 := by
    have hcases : Nat.card ψ.ker = 1 ∨ Nat.card ψ.ker = 3 ∨ Nat.card ψ.ker = 9 := by
      have hle : Nat.card ψ.ker ≤ 9 := Nat.le_of_dvd (by norm_num) hker_card_dvd
      have hpos : 0 < Nat.card ψ.ker := Nat.card_pos
      interval_cases h : Nat.card ψ.ker
      · left
        rfl
      · exfalso
        norm_num [h] at hker_card_dvd
      · right
        left
        rfl
      · exfalso
        norm_num [h] at hker_card_dvd
      · exfalso
        norm_num [h] at hker_card_dvd
      · exfalso
        norm_num [h] at hker_card_dvd
      · exfalso
        norm_num [h] at hker_card_dvd
      · exfalso
        norm_num [h] at hker_card_dvd
      · right
        right
        rfl
    rcases hcases with h | h | h
    · exact absurd h hker_card_ne_one
    · exact h
    · exact absurd h hker_card_ne_nine
  have h_range_card : Nat.card ψ.range = 12 := by
    have hidx : ψ.ker.index = 12 := by
      have := ψ.ker.card_mul_index
      rw [hker_card, hG] at this
      omega
    rwa [← Subgroup.index_ker ψ]
  have h_perm_card : Nat.card (Equiv.Perm (Fin 4)) = 24 := by
    rw [Nat.card_perm, Nat.card_fin]
    decide
  have h_range_idx : ψ.range.index = 2 := by
    have := ψ.range.card_mul_index
    rw [h_range_card, h_perm_card] at this
    omega
  have h_alt : ψ.range = alternatingGroup (Fin 4) :=
    Equiv.Perm.eq_alternatingGroup_of_index_eq_two h_range_idx
  exact ⟨ψ, hker_card, h_alt⟩

/-- In the non-normal Sylow-`3` branch of order `36`, there is a normal subgroup of order `3`
whose quotient is `A₄`. -/
theorem order36_has_normal_order_three_and_A4_quotient_of_card_sylow_3_eq_four [Finite G]
    (hG : Nat.card G = 36) (hSyl : Nat.card (Sylow 3 G) = 4) :
    ∃ (K : Subgroup G) (_ : K.Normal), Nat.card K = 3 ∧
      Nonempty (G ⧸ K ≃* alternatingGroup (Fin 4)) := by
  obtain ⟨ψ, hker_card, h_alt⟩ :=
    order36_sylow_3_conj_action_A4_of_card_sylow_3_eq_four (G := G) hG hSyl
  exact ⟨ψ.ker, MonoidHom.normal_ker ψ, hker_card,
    ⟨(QuotientGroup.quotientKerEquivRange ψ).trans (MulEquiv.subgroupCongr h_alt)⟩⟩

end Smallgroups.UsefulTheorems
