/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Smallgroups.UsefulTheorems.P3Group
import Smallgroups.UsefulTheorems.Order2PSqElem
import Smallgroups.UsefulTheorems.PrimeOrderClassification
import Smallgroups.UsefulTheorems.SchurZassenhaus
import Mathlib.GroupTheory.Sylow
import Mathlib.Tactic.NormNum.Prime

/-!
# First reductions for groups of order 54

Since `54 = 2 * 3^3`, the Sylow `3`-subgroup of a group of order `54` is
unique.  Thus every group of order `54` has a normal subgroup of order `27`,
and Schur--Zassenhaus splits it as a semidirect product `N ⋊ H` with
`|N| = 27` and `|H| = 2`.

The remaining classification problem is the orbit calculation for actions
`H → Aut(N)`, where `N` is one of the five groups of order `27` from
`P3Group.classification`.
-/

namespace Smallgroups.UsefulTheorems

open Sylow

variable {G : Type*} [Group G]

/-! ### Standard factors -/

/-- The complement in the order-`54` semidirect-product reduction. -/
abbrev order54_C2 : Type := CyclicRep 2

/-- `C₅₄`. -/
abbrev order54_C54 : Type := CyclicRep 54

/-- `C₂₇`. -/
abbrev order54_C27 : Type := CyclicRep 27

/-- `C₉ × C₃`. -/
abbrev order54_C9C3 : Type :=
  Multiplicative (ZMod (3 ^ 2)) × Multiplicative (ZMod 3)

/-- `(C₃)³`. -/
abbrev order54_C3C3C3 : Type :=
  Multiplicative (ZMod 3) × Multiplicative (ZMod 3) × Multiplicative (ZMod 3)

/-- The non-abelian exponent-`3` group of order `27`. -/
abbrev order54_Heisenberg : Type := P3Group.HeisenbergGroup 3

/-- The non-abelian exponent-`9` group of order `27`. -/
abbrev order54_SemidirectP2P : Type := P3Group.SemidirectP2P 3

/-- The dihedral group of order `54`. -/
abbrev order54_D27 : Type := DihedralGroup 27

/-- The dihedral group of order `6`. -/
abbrev order54_D3 : Type := DihedralGroup 3

/-- The `C₃³` kernel with trivial `C₂` action. -/
abbrev order54_Elem0 : Type := order54_C3C3C3 × order54_C2

/-- The `C₃³` kernel with a one-dimensional inversion eigenspace. -/
abbrev order54_Elem1 : Type := ElemAbelianRep 3 × order54_D3

/-- The `C₃³` kernel with a two-dimensional inversion eigenspace. -/
abbrev order54_Elem2 : Type :=
  CyclicRep 3 × SemidirectProduct (ElemAbelianRep 3) order54_C2
    (invActionHom (ElemAbelianRep 3))

/-- The `C₃³` kernel with full inversion action. -/
abbrev order54_Elem3 : Type :=
  SemidirectProduct order54_C3C3C3 order54_C2 (invActionHom order54_C3C3C3)

/-- The `(C₉ × C₃)` kernel with trivial `C₂` action. -/
abbrev order54_Mixed0 : Type := order54_C9C3 × order54_C2

/-- The `(C₉ × C₃)` kernel with a cyclic order-`3` inversion eigenspace. -/
abbrev order54_Mixed1 : Type := CyclicRep 9 × order54_D3

/-- The `(C₉ × C₃)` kernel with a cyclic order-`9` inversion eigenspace. -/
abbrev order54_Mixed2 : Type := CyclicRep 3 × DihedralGroup 9

/-- The `(C₉ × C₃)` kernel with full inversion action. -/
abbrev order54_Mixed3 : Type :=
  SemidirectProduct order54_C9C3 order54_C2 (invActionHom order54_C9C3)

/-! ### Standard non-abelian kernel actions -/

/-- The action of `C₂` generated by a chosen involutive automorphism. -/
noncomputable def order54_actionOfInvolution {N : Type*} [Group N]
    (α : MulAut N) (hα : α ^ 2 = 1) : order54_C2 →* MulAut N :=
  MonoidHom.mk' (fun x => α ^ (Multiplicative.toAdd x).val)
    (fun x y => pow_val_add hα (Multiplicative.toAdd x) (Multiplicative.toAdd y))

/-- The Heisenberg automorphism induced by `-I` on the central quotient. -/
def order54_heisenbergNegBothAut : MulAut order54_Heisenberg where
  toFun x := ⟨-x.a, -x.b, x.c⟩
  invFun x := ⟨-x.a, -x.b, x.c⟩
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_mul' x y := by
    ext
    · change -(x.a + y.a) = -x.a + -y.a
      ring
    · change -(x.b + y.b) = -x.b + -y.b
      ring
    · change x.c + y.c + x.a * y.b = x.c + y.c + (-x.a) * (-y.b)
      ring

theorem order54_heisenbergNegBothAut_sq :
    order54_heisenbergNegBothAut ^ 2 = 1 := by
  ext x <;> simp [order54_heisenbergNegBothAut, sq]

/-- A Heisenberg involution with one fixed and one inverted quotient direction. -/
def order54_heisenbergNegBAut : MulAut order54_Heisenberg where
  toFun x := ⟨x.a, -x.b, -x.c⟩
  invFun x := ⟨x.a, -x.b, -x.c⟩
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_mul' x y := by
    ext
    · change x.a + y.a = x.a + y.a
      ring
    · change -(x.b + y.b) = -x.b + -y.b
      ring
    · change -(x.c + y.c + x.a * y.b) = -x.c + -y.c + x.a * (-y.b)
      ring

theorem order54_heisenbergNegBAut_sq :
    order54_heisenbergNegBAut ^ 2 = 1 := by
  ext x <;> simp [order54_heisenbergNegBAut, sq]

/-- The exponent-`9` non-abelian kernel involution inverting the cyclic `C₉` direction. -/
def order54_semidirectP2PNegAAut : MulAut order54_SemidirectP2P where
  toFun x := ⟨-x.a, x.b⟩
  invFun x := ⟨-x.a, x.b⟩
  left_inv x := by ext <;> simp
  right_inv x := by ext <;> simp
  map_mul' x y := by
    ext
    · simp
      ring
    · simp

theorem order54_semidirectP2PNegAAut_sq :
    order54_semidirectP2PNegAAut ^ 2 = 1 := by
  ext x <;> simp [order54_semidirectP2PNegAAut, sq]

noncomputable abbrev order54_heisenbergNegBothAction :
    order54_C2 →* MulAut order54_Heisenberg :=
  order54_actionOfInvolution order54_heisenbergNegBothAut order54_heisenbergNegBothAut_sq

noncomputable abbrev order54_heisenbergNegBAction :
    order54_C2 →* MulAut order54_Heisenberg :=
  order54_actionOfInvolution order54_heisenbergNegBAut order54_heisenbergNegBAut_sq

noncomputable abbrev order54_semidirectP2PNegAAction :
    order54_C2 →* MulAut order54_SemidirectP2P :=
  order54_actionOfInvolution order54_semidirectP2PNegAAut order54_semidirectP2PNegAAut_sq

/-- The Heisenberg kernel with trivial `C₂` action. -/
abbrev order54_Heis0 : Type := order54_Heisenberg × order54_C2

/-- The Heisenberg kernel with the `-I` quotient action. -/
abbrev order54_Heis1 : Type :=
  SemidirectProduct order54_Heisenberg order54_C2 order54_heisenbergNegBothAction

/-- The Heisenberg kernel with a reflection-type quotient action. -/
abbrev order54_Heis2 : Type :=
  SemidirectProduct order54_Heisenberg order54_C2 order54_heisenbergNegBAction

/-- The exponent-`9` non-abelian kernel with trivial `C₂` action. -/
abbrev order54_P2P0 : Type := order54_SemidirectP2P × order54_C2

/-- The exponent-`9` non-abelian kernel with the cyclic direction inverted. -/
abbrev order54_P2P1 : Type :=
  SemidirectProduct order54_SemidirectP2P order54_C2 order54_semidirectP2PNegAAction

/-! ### Cardinalities of the standard factors -/

theorem card_order54_C2 : Nat.card order54_C2 = 2 :=
  card_cyclicRep (by norm_num)

theorem card_order54_C54 : Nat.card order54_C54 = 54 :=
  card_cyclicRep (by norm_num)

theorem card_order54_C27 : Nat.card order54_C27 = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  simp

theorem card_order54_C9C3 : Nat.card order54_C9C3 = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  simp

theorem card_order54_C3C3C3 : Nat.card order54_C3C3C3 = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  simp

theorem card_order54_Heisenberg : Nat.card order54_Heisenberg = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  simpa using P3Group.HeisenbergGroup.card_heisenberg 3

theorem card_order54_SemidirectP2P : Nat.card order54_SemidirectP2P = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  simpa using P3Group.SemidirectP2P.card_semidirectP2P 3

theorem card_order54_D27 : Nat.card order54_D27 = 54 := by
  rw [DihedralGroup.nat_card]

theorem card_order54_semidirect_C27 (φ : order54_C2 →* MulAut order54_C27) :
    Nat.card (SemidirectProduct order54_C27 order54_C2 φ) = 54 := by
  rw [SemidirectProduct.card, card_order54_C27, card_order54_C2]

theorem card_order54_semidirect_C9C3 (φ : order54_C2 →* MulAut order54_C9C3) :
    Nat.card (SemidirectProduct order54_C9C3 order54_C2 φ) = 54 := by
  rw [SemidirectProduct.card, card_order54_C9C3, card_order54_C2]

theorem card_order54_semidirect_C3C3C3 (φ : order54_C2 →* MulAut order54_C3C3C3) :
    Nat.card (SemidirectProduct order54_C3C3C3 order54_C2 φ) = 54 := by
  rw [SemidirectProduct.card, card_order54_C3C3C3, card_order54_C2]

theorem card_order54_semidirect_Heisenberg (φ : order54_C2 →* MulAut order54_Heisenberg) :
    Nat.card (SemidirectProduct order54_Heisenberg order54_C2 φ) = 54 := by
  rw [SemidirectProduct.card, card_order54_Heisenberg, card_order54_C2]

theorem card_order54_semidirect_SemidirectP2P
    (φ : order54_C2 →* MulAut order54_SemidirectP2P) :
    Nat.card (SemidirectProduct order54_SemidirectP2P order54_C2 φ) = 54 := by
  rw [SemidirectProduct.card, card_order54_SemidirectP2P, card_order54_C2]

theorem card_order54_Heis0 : Nat.card order54_Heis0 = 54 := by
  rw [Nat.card_prod, card_order54_Heisenberg, card_order54_C2]

theorem card_order54_Heis1 : Nat.card order54_Heis1 = 54 :=
  card_order54_semidirect_Heisenberg order54_heisenbergNegBothAction

theorem card_order54_Heis2 : Nat.card order54_Heis2 = 54 :=
  card_order54_semidirect_Heisenberg order54_heisenbergNegBAction

theorem card_order54_P2P0 : Nat.card order54_P2P0 = 54 := by
  rw [Nat.card_prod, card_order54_SemidirectP2P, card_order54_C2]

theorem card_order54_P2P1 : Nat.card order54_P2P1 = 54 :=
  card_order54_semidirect_SemidirectP2P order54_semidirectP2PNegAAction

/-- A trivial `C₂`-action semidirect product is the direct product. -/
noncomputable def order54_trivial_semidirect_iso (N : Type*) [Group N] :
    SemidirectProduct N order54_C2 (1 : order54_C2 →* MulAut N) ≃* N × order54_C2 :=
  { toEquiv := SemidirectProduct.equivProd
    map_mul' := fun x y => by
      rcases x with ⟨n₁, h₁⟩
      rcases y with ⟨n₂, h₂⟩
      simp }

theorem order54_heisenberg_trivial_semidirect_iso :
    Nonempty (SemidirectProduct order54_Heisenberg order54_C2
      (1 : order54_C2 →* MulAut order54_Heisenberg) ≃* order54_Heis0) :=
  ⟨order54_trivial_semidirect_iso order54_Heisenberg⟩

theorem order54_semidirectP2P_trivial_semidirect_iso :
    Nonempty (SemidirectProduct order54_SemidirectP2P order54_C2
      (1 : order54_C2 →* MulAut order54_SemidirectP2P) ≃* order54_P2P0) :=
  ⟨order54_trivial_semidirect_iso order54_SemidirectP2P⟩

/-! ### The cyclic kernel case `C₂₇ ⋊ C₂` -/

theorem square_eq_one_zmod_27 (k : ZMod 27) (h : k ^ 2 = 1) : k = 1 ∨ k = -1 := by
  haveI : Fact (1 < 27) := ⟨by norm_num⟩
  have hklt : k.val < 27 := k.val_lt
  have hcast : ((k.val * k.val : ℕ) : ZMod 27) = 1 := by
    calc
      ((k.val * k.val : ℕ) : ZMod 27) = ((k.val : ZMod 27) * (k.val : ZMod 27)) := by
        norm_num
      _ = k * k := by rw [ZMod.natCast_zmod_val]
      _ = k ^ 2 := by ring
      _ = 1 := h
  have hmod : k.val * k.val ≡ 1 [MOD 27] := by
    exact (ZMod.natCast_eq_natCast_iff (k.val * k.val) 1 27).mp hcast
  unfold Nat.ModEq at hmod
  interval_cases hk : k.val <;> try exact False.elim (by omega)
  · left
    apply ZMod.val_injective 27
    rw [hk, ZMod.val_one]
  · right
    apply ZMod.val_injective 27
    rw [hk]
    norm_num

private lemma order54_c27_pow_gen (m : ℕ) :
    ((Multiplicative.ofAdd 1 : order54_C27) ^ m) =
      Multiplicative.ofAdd (m : ZMod 27) := by
  induction m with
  | zero => simp
  | succ m ih =>
      rw [pow_succ, ih]
      simp

private lemma order54_c27_cyclicRep_pow_gen (x : order54_C27) :
    x = ((Multiplicative.ofAdd 1 : order54_C27) ^ (Multiplicative.toAdd x).val) := by
  let v := (Multiplicative.toAdd x).val
  calc
    x = Multiplicative.ofAdd (Multiplicative.toAdd x) := rfl
    _ = Multiplicative.ofAdd ((v : ZMod 27)) := by
      rw [← ZMod.natCast_zmod_val (Multiplicative.toAdd x)]
    _ = ((Multiplicative.ofAdd 1 : order54_C27) ^ v) := by
      rw [← order54_c27_pow_gen v]

theorem order54_c27_mulAut_involution (α : MulAut order54_C27) (hα : α ^ 2 = 1) :
    α = 1 ∨ α = invAut order54_C27 := by
  let g : order54_C27 := Multiplicative.ofAdd 1
  let k := (Multiplicative.toAdd (α g)).val
  have hαg : α g = g ^ k := by rw [order54_c27_cyclicRep_pow_gen (α g)]
  have h_sq_eq : (α ^ 2) g = g := by rw [hα, MulAut.one_apply]
  have h_pow_sq : (α ^ 2) g = g ^ (k * k) := by
    calc
      (α ^ 2) g = α (α g) := by simp [sq]
      _ = α (g ^ k) := by rw [hαg]
      _ = (α g) ^ k := map_pow _ _ _
      _ = (g ^ k) ^ k := by rw [hαg]
      _ = g ^ (k * k) := by rw [← pow_mul, mul_comm]
  rw [h_pow_sq] at h_sq_eq
  rw [order54_c27_pow_gen (k * k), ← pow_one g, order54_c27_pow_gen 1] at h_sq_eq
  have h_sq_mod : ((k : ℕ) : ZMod 27) ^ 2 = 1 := by
    have := congrArg Multiplicative.toAdd h_sq_eq
    simpa [Nat.cast_mul, sq] using this
  rcases square_eq_one_zmod_27 (k : ZMod 27) h_sq_mod with hk | hk
  · have hαg_one : α g = g := by
      rw [hαg, order54_c27_pow_gen, hk]
    left
    ext x
    have hx : x = g ^ (Multiplicative.toAdd x).val := order54_c27_cyclicRep_pow_gen x
    rw [hx]
    simp [hαg_one]
  · have hαg_inv : α g = invAut order54_C27 g := by
      rw [hαg, invAut_apply, order54_c27_pow_gen, hk]
      dsimp [g]
    right
    ext x
    have hx : x = g ^ (Multiplicative.toAdd x).val := order54_c27_cyclicRep_pow_gen x
    rw [hx]
    simp [hαg_inv]

theorem order54_c27_action_cases (φ : order54_C2 →* MulAut order54_C27) :
    φ = 1 ∨ φ = invActionHom order54_C27 := by
  let α := φ (Multiplicative.ofAdd 1)
  have hα2 : α ^ 2 = 1 := by
    have h_order_two : (Multiplicative.ofAdd (1 : ZMod 2) : order54_C2) ^ 2 = 1 := by
      decide
    calc
      α ^ 2 = (φ (Multiplicative.ofAdd 1)) ^ 2 := rfl
      _ = φ ((Multiplicative.ofAdd (1 : ZMod 2)) ^ 2) := by rw [map_pow]
      _ = φ 1 := by rw [h_order_two]
      _ = 1 := map_one _
  rcases order54_c27_mulAut_involution α hα2 with hα | hα
  · left
    exact MonoidHom.ext fun h => MulEquiv.ext fun x => by
      rcases multiplicative_zmod_two_cases h with rfl | rfl
      · simp
      · dsimp [α] at hα
        rw [hα]
        rfl
  · right
    exact MonoidHom.ext fun h => MulEquiv.ext fun x => by
      rcases multiplicative_zmod_two_cases h with rfl | rfl
      · simp
      · dsimp [α] at hα
        rw [hα, invActionHom_gen]

noncomputable def order54_c27_trivial_prod_iso :
    order54_C27 × order54_C2 ≃* order54_C54 := by
  have hcop : (27 : ℕ).Coprime 2 := by norm_num
  let e_crt : ZMod (27 * 2) ≃+* ZMod 27 × ZMod 2 := ZMod.chineseRemainder hcop
  let e_add : Multiplicative (ZMod (27 * 2)) ≃* Multiplicative (ZMod 27 × ZMod 2) :=
    AddEquiv.toMultiplicative e_crt.toAddEquiv
  let e_prod : Multiplicative (ZMod 27 × ZMod 2) ≃*
      Multiplicative (ZMod 27) × Multiplicative (ZMod 2) :=
    MulEquiv.prodMultiplicative (ZMod 27) (ZMod 2)
  let e_mul : order54_C54 ≃* Multiplicative (ZMod (27 * 2)) := by
    refine AddEquiv.toMultiplicative (ZMod.ringEquivCongr ?_).toAddEquiv
    norm_num
  exact (e_mul.trans (e_add.trans e_prod)).symm

noncomputable def order54_c27_trivial_semidirect_iso :
    SemidirectProduct order54_C27 order54_C2
      (1 : order54_C2 →* MulAut order54_C27) ≃* order54_C54 := by
  let e : SemidirectProduct order54_C27 order54_C2
      (1 : order54_C2 →* MulAut order54_C27) ≃* order54_C27 × order54_C2 :=
    { toEquiv := SemidirectProduct.equivProd
      map_mul' := fun x y => by
        rcases x with ⟨n₁, h₁⟩
        rcases y with ⟨n₂, h₂⟩
        simp }
  exact e.trans order54_c27_trivial_prod_iso

theorem order54_c27_inv_semidirect_iso :
    Nonempty (SemidirectProduct order54_C27 order54_C2
      (invActionHom order54_C27) ≃* order54_D27) := by
  haveI : NeZero 27 := ⟨by norm_num⟩
  exact ⟨genDihedralCyclicIso 27⟩

theorem order54_c27_semidirect_cases (φ : order54_C2 →* MulAut order54_C27) :
    Nonempty (SemidirectProduct order54_C27 order54_C2 φ ≃* order54_C54) ∨
      Nonempty (SemidirectProduct order54_C27 order54_C2 φ ≃* order54_D27) := by
  rcases order54_c27_action_cases φ with hφ | hφ
  · subst hφ
    exact Or.inl ⟨order54_c27_trivial_semidirect_iso⟩
  · subst hφ
    exact Or.inr order54_c27_inv_semidirect_iso

/-! ### The elementary kernel case `C₃³ ⋊ C₂` -/

theorem order54_c3c3c3_pow_three (x : order54_C3C3C3) : x ^ 3 = 1 := by
  have hpow : ∀ y : CyclicRep 3, y ^ 3 = 1 := fun y => by
    have h1 : y ^ Fintype.card (Multiplicative (ZMod 3)) = 1 := pow_card_eq_one
    rwa [Fintype.card_multiplicative, ZMod.card] at h1
  obtain ⟨a, b, c⟩ := x
  rw [Prod.pow_mk, Prod.pow_mk, hpow, hpow, hpow]
  rfl

/-- A commutative group of order `27` and exponent dividing `3` is `(C₃)³`. -/
theorem order54_mulEquiv_c3c3c3_of_exp {H : Type*} [CommGroup H]
    (hcard : Nat.card H = 27) (hexp : ∀ x : H, x ^ 3 = 1) :
    Nonempty (H ≃* order54_C3C3C3) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Finite H := Nat.finite_of_card_ne_zero (by rw [hcard]; norm_num)
  haveI : Fintype H := Fintype.ofFinite H
  rcases P3Group.abelian_p3_classification 3 H (hcard.trans (by norm_num)) with
    hcyc | hp2p | helem
  · exfalso
    obtain ⟨e⟩ := hcyc
    let x : H := e.symm (Multiplicative.ofAdd (1 : P3Group.CyclicP3 3))
    have hxord : orderOf x = 27 := by
      dsimp [x, P3Group.CyclicP3]
      rw [show e.symm (Multiplicative.ofAdd (1 : ZMod (3 ^ 3))) =
            e.symm.toMonoidHom (Multiplicative.ofAdd 1) from rfl,
        orderOf_injective e.symm.toMonoidHom e.symm.injective,
        orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one]
      norm_num
    have hdvd : 27 ∣ 3 := by
      rw [← hxord]
      exact orderOf_dvd_of_pow_eq_one (hexp x)
    norm_num at hdvd
  · exfalso
    obtain ⟨e⟩ := hp2p
    let x : H := e.symm (Multiplicative.ofAdd (1 : ZMod (3 ^ 2)),
      (1 : Multiplicative (ZMod 3)))
    have hxord : orderOf x = 9 := by
      dsimp [x]
      rw [show e.symm (Multiplicative.ofAdd (1 : ZMod (3 ^ 2)),
            (1 : Multiplicative (ZMod 3))) =
            e.symm.toMonoidHom (Multiplicative.ofAdd 1, 1) from rfl,
        orderOf_injective e.symm.toMonoidHom e.symm.injective]
      rw [Prod.orderOf_mk, orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one, orderOf_one]
      norm_num
    have hdvd : 9 ∣ 3 := by
      rw [← hxord]
      exact orderOf_dvd_of_pow_eq_one (hexp x)
    norm_num at hdvd
  · exact helem

theorem order54_c3c3c3_semidirect_cases (φ : order54_C2 →* MulAut order54_C3C3C3) :
    Nonempty (SemidirectProduct order54_C3C3C3 order54_C2 φ ≃* order54_Elem0) ∨
      Nonempty (SemidirectProduct order54_C3C3C3 order54_C2 φ ≃* order54_Elem1) ∨
      Nonempty (SemidirectProduct order54_C3C3C3 order54_C2 φ ≃* order54_Elem2) ∨
      Nonempty (SemidirectProduct order54_C3C3C3 order54_C2 φ ≃* order54_Elem3) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  set τ := φ (Multiplicative.ofAdd 1) with hτ
  have h2 : τ * τ = 1 := by
    rw [← sq, hτ, ← map_pow, show (Multiplicative.ofAdd (1 : ZMod 2)) ^ 2 = 1 from by decide,
      map_one]
  have hinv : ∀ x, τ (τ x) = x := fun x => by
    have hx := DFunLike.congr_fun h2 x
    rwa [MulAut.mul_apply, MulAut.one_apply] at hx
  have hexp : ∀ x : order54_C3C3C3, x ^ 3 = 1 := order54_c3c3c3_pow_three
  have ht : 2 * 2 = 3 + 1 := by norm_num
  have expFix : ∀ x : fixSubgroup τ, x ^ 3 = 1 := fun x =>
    Subtype.ext (by rw [SubmonoidClass.coe_pow, OneMemClass.coe_one]; exact hexp _)
  have expNeg : ∀ x : negSubgroup τ, x ^ 3 = 1 := fun x =>
    Subtype.ext (by rw [SubmonoidClass.coe_pow, OneMemClass.coe_one]; exact hexp _)
  let eMain :
      SemidirectProduct order54_C3C3C3 order54_C2 φ ≃*
        fixSubgroup τ × SemidirectProduct (negSubgroup τ) order54_C2
          (invActionHom (negSubgroup τ)) :=
    elem_decomp_semidirect hinv hexp ht φ rfl
  have hsplit : Nat.card (fixSubgroup τ) * Nat.card (negSubgroup τ) = 3 ^ 3 := by
    rw [← Nat.card_prod, ← Nat.card_congr (eigenEquiv hinv hexp ht).toEquiv]
    exact card_order54_C3C3C3
  have hd_dvd : Nat.card (negSubgroup τ) ∣ 3 ^ 3 :=
    ⟨Nat.card (fixSubgroup τ), by rw [mul_comm]; exact hsplit.symm⟩
  obtain ⟨i, hi_le, hi⟩ := (Nat.dvd_prime_pow (by norm_num : Nat.Prime 3)).mp hd_dvd
  interval_cases i
  · have hNeg1 : Nat.card (negSubgroup τ) = 1 := by simpa using hi
    haveI : Subsingleton (negSubgroup τ) := (Nat.card_eq_one_iff_unique.mp hNeg1).1
    have hFix27 : Nat.card (fixSubgroup τ) = 27 := by
      have h := hsplit
      rwa [hNeg1, mul_one] at h
    obtain ⟨eFix⟩ := order54_mulEquiv_c3c3c3_of_exp hFix27 expFix
    exact Or.inl ⟨eMain.trans (MulEquiv.prodCongr eFix semidirectUniqueLeft)⟩
  · have hNeg3 : Nat.card (negSubgroup τ) = 3 := by simpa using hi
    have hFix9 : Nat.card (fixSubgroup τ) = 9 := by
      have h := hsplit
      rw [hNeg3] at h
      have h' : Nat.card (fixSubgroup τ) * 3 = 9 * 3 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 3) h'
    obtain ⟨eFix⟩ := mulEquiv_elemAbelian_of_exp (p := 3) hFix9 expFix
    obtain ⟨eNeg⟩ := prime_classification (by norm_num : Nat.Prime 3) hNeg3
    exact Or.inr (Or.inl ⟨eMain.trans <|
      MulEquiv.prodCongr eFix ((genDihCongr eNeg).trans (genDihedralCyclicIso 3))⟩)
  · have hNeg9 : Nat.card (negSubgroup τ) = 9 := by simpa using hi
    have hFix3 : Nat.card (fixSubgroup τ) = 3 := by
      have h := hsplit
      rw [hNeg9] at h
      have h' : Nat.card (fixSubgroup τ) * 9 = 3 * 9 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 9) h'
    obtain ⟨eFix⟩ := prime_classification (by norm_num : Nat.Prime 3) hFix3
    obtain ⟨eNeg⟩ := mulEquiv_elemAbelian_of_exp (p := 3) hNeg9 expNeg
    exact Or.inr (Or.inr (Or.inl ⟨eMain.trans <|
      MulEquiv.prodCongr eFix (genDihCongr eNeg)⟩))
  · have hNeg27 : Nat.card (negSubgroup τ) = 27 := by simpa using hi
    have hFix1 : Nat.card (fixSubgroup τ) = 1 := by
      have h := hsplit
      rw [hNeg27] at h
      have h' : Nat.card (fixSubgroup τ) * 27 = 1 * 27 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 27) h'
    haveI : Subsingleton (fixSubgroup τ) := (Nat.card_eq_one_iff_unique.mp hFix1).1
    haveI : Unique (fixSubgroup τ) := uniqueOfSubsingleton 1
    obtain ⟨eNeg⟩ := order54_mulEquiv_c3c3c3_of_exp hNeg27 expNeg
    exact Or.inr (Or.inr (Or.inr ⟨eMain.trans <|
      MulEquiv.uniqueProd.trans (genDihCongr eNeg)⟩))

/-! ### First reductions for the mixed abelian kernel case `(C₉ × C₃) ⋊ C₂` -/

theorem order54_c9c3_pow_nine (x : order54_C9C3) : x ^ 9 = 1 := by
  obtain ⟨a, b⟩ := x
  have ha : a ^ 9 = 1 := by
    have h : a ^ Fintype.card (Multiplicative (ZMod 9)) = 1 := pow_card_eq_one
    rwa [Fintype.card_multiplicative, ZMod.card] at h
  have hb3 : b ^ 3 = 1 := by
    have h : b ^ Fintype.card (Multiplicative (ZMod 3)) = 1 := pow_card_eq_one
    rwa [Fintype.card_multiplicative, ZMod.card] at h
  have hb : b ^ 9 = 1 := by
    rw [show (9 : ℕ) = 3 * 3 by norm_num, pow_mul, hb3, one_pow]
  rw [Prod.pow_mk, ha, hb]
  rfl

theorem order54_c9c3_not_exp_three : ¬ ∀ x : order54_C9C3, x ^ 3 = 1 := by
  intro h
  let x : order54_C9C3 := (Multiplicative.ofAdd (1 : ZMod 9),
    (1 : Multiplicative (ZMod 3)))
  have hx := congrArg Prod.fst (h x)
  have hxpow : (Multiplicative.ofAdd (1 : ZMod 9)) ^ 3 = 1 := by
    simpa [x] using hx
  have hxord : orderOf (Multiplicative.ofAdd (1 : ZMod 9)) = 9 := by
    rw [orderOf_ofAdd_eq_addOrderOf, ZMod.addOrderOf_one]
  have hdvd : 9 ∣ 3 := by
    rw [← hxord]
    exact orderOf_dvd_of_pow_eq_one hxpow
  norm_num at hdvd

theorem order54_pow_three_of_mulEquiv_cyclic3 {H : Type*} [Group H]
    (e : H ≃* CyclicRep 3) (x : H) : x ^ 3 = 1 := by
  apply e.injective
  rw [map_pow, map_one]
  have h : (e x) ^ Fintype.card (Multiplicative (ZMod 3)) = 1 := pow_card_eq_one
  rwa [Fintype.card_multiplicative, ZMod.card] at h

theorem order54_pow_three_of_mulEquiv_elemAbelian3 {H : Type*} [Group H]
    (e : H ≃* ElemAbelianRep 3) (x : H) : x ^ 3 = 1 := by
  apply e.injective
  rw [map_pow, map_one]
  exact pow_p_elemAbelian (p := 3) (e x)

/-- The mixed abelian kernel case splits into fixed and inverted factors.  Since every element of
`C₉ × C₃` has ninth power equal to `1`, the same eigenspace construction used for exponent-`p`
elementary kernels works here with `p = 9` and `t = 5`. -/
noncomputable def order54_c9c3_decompIso (φ : order54_C2 →* MulAut order54_C9C3) :
    SemidirectProduct order54_C9C3 order54_C2 φ ≃*
      fixSubgroup (φ (Multiplicative.ofAdd 1)) ×
        SemidirectProduct (negSubgroup (φ (Multiplicative.ofAdd 1))) order54_C2
          (invActionHom (negSubgroup (φ (Multiplicative.ofAdd 1)))) := by
  set τ := φ (Multiplicative.ofAdd 1) with hτ
  have h2 : τ * τ = 1 := by
    rw [← sq, hτ, ← map_pow, show (Multiplicative.ofAdd (1 : ZMod 2)) ^ 2 = 1 from by decide,
      map_one]
  have hinv : ∀ x, τ (τ x) = x := fun x => by
    have hx := DFunLike.congr_fun h2 x
    rwa [MulAut.mul_apply, MulAut.one_apply] at hx
  have hexp : ∀ x : order54_C9C3, x ^ 9 = 1 := order54_c9c3_pow_nine
  have ht : 2 * 5 = 9 + 1 := by norm_num
  exact elem_decomp_semidirect hinv hexp ht φ rfl

theorem order54_c9c3_decomp_card (φ : order54_C2 →* MulAut order54_C9C3) :
    Nat.card (fixSubgroup (φ (Multiplicative.ofAdd 1))) *
      Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 27 := by
  set τ := φ (Multiplicative.ofAdd 1) with hτ
  have h2 : τ * τ = 1 := by
    rw [← sq, hτ, ← map_pow, show (Multiplicative.ofAdd (1 : ZMod 2)) ^ 2 = 1 from by decide,
      map_one]
  have hinv : ∀ x, τ (τ x) = x := fun x => by
    have hx := DFunLike.congr_fun h2 x
    rwa [MulAut.mul_apply, MulAut.one_apply] at hx
  have hexp : ∀ x : order54_C9C3, x ^ 9 = 1 := order54_c9c3_pow_nine
  have ht : 2 * 5 = 9 + 1 := by norm_num
  change Nat.card (fixSubgroup τ) * Nat.card (negSubgroup τ) = 27
  rw [← Nat.card_prod, ← Nat.card_congr (eigenEquiv hinv hexp ht).toEquiv]
  exact card_order54_C9C3

theorem order54_c9c3_neg_card_cases (φ : order54_C2 →* MulAut order54_C9C3) :
    Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 1 ∨
      Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 3 ∨
      Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 9 ∨
      Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 27 := by
  have hsplit := order54_c9c3_decomp_card φ
  have hdvd : Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) ∣ 3 ^ 3 :=
    ⟨Nat.card (fixSubgroup (φ (Multiplicative.ofAdd 1))), by
      rw [mul_comm]
      exact hsplit.symm⟩
  obtain ⟨i, hi_le, hi⟩ := (Nat.dvd_prime_pow (by norm_num : Nat.Prime 3)).mp hdvd
  interval_cases i
  · exact Or.inl (by simpa using hi)
  · exact Or.inr (Or.inl (by simpa using hi))
  · exact Or.inr (Or.inr (Or.inl (by simpa using hi)))
  · exact Or.inr (Or.inr (Or.inr (by simpa using hi)))

theorem order54_c9c3_endpoint_cases (φ : order54_C2 →* MulAut order54_C9C3) :
    (Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 1 →
      Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed0)) ∧
    (Nat.card (negSubgroup (φ (Multiplicative.ofAdd 1))) = 27 →
      Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed3)) := by
  set τ := φ (Multiplicative.ofAdd 1) with hτ
  have h2 : τ * τ = 1 := by
    rw [← sq, hτ, ← map_pow, show (Multiplicative.ofAdd (1 : ZMod 2)) ^ 2 = 1 from by decide,
      map_one]
  have hinv : ∀ x, τ (τ x) = x := fun x => by
    have hx := DFunLike.congr_fun h2 x
    rwa [MulAut.mul_apply, MulAut.one_apply] at hx
  have hexp : ∀ x : order54_C9C3, x ^ 9 = 1 := order54_c9c3_pow_nine
  have ht : 2 * 5 = 9 + 1 := by norm_num
  let eMain :
      SemidirectProduct order54_C9C3 order54_C2 φ ≃*
        fixSubgroup τ × SemidirectProduct (negSubgroup τ) order54_C2
          (invActionHom (negSubgroup τ)) :=
    elem_decomp_semidirect hinv hexp ht φ rfl
  have hsplit : Nat.card (fixSubgroup τ) * Nat.card (negSubgroup τ) = 27 := by
    rw [← Nat.card_prod, ← Nat.card_congr (eigenEquiv hinv hexp ht).toEquiv]
    exact card_order54_C9C3
  constructor
  · intro hNeg1
    change Nat.card (negSubgroup τ) = 1 at hNeg1
    haveI : Subsingleton (negSubgroup τ) := (Nat.card_eq_one_iff_unique.mp hNeg1).1
    haveI : Unique (negSubgroup τ) := uniqueOfSubsingleton 1
    let eFix : order54_C9C3 ≃* fixSubgroup τ :=
      (eigenEquiv hinv hexp ht).trans MulEquiv.prodUnique
    exact ⟨eMain.trans <|
      (MulEquiv.prodCongr eFix.symm semidirectUniqueLeft)⟩
  · intro hNeg27
    change Nat.card (negSubgroup τ) = 27 at hNeg27
    have hFix1 : Nat.card (fixSubgroup τ) = 1 := by
      have h := hsplit
      rw [hNeg27] at h
      have h' : Nat.card (fixSubgroup τ) * 27 = 1 * 27 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 27) h'
    haveI : Subsingleton (fixSubgroup τ) := (Nat.card_eq_one_iff_unique.mp hFix1).1
    haveI : Unique (fixSubgroup τ) := uniqueOfSubsingleton 1
    let eNeg : order54_C9C3 ≃* negSubgroup τ :=
      (eigenEquiv hinv hexp ht).trans MulEquiv.uniqueProd
    exact ⟨eMain.trans <|
      MulEquiv.uniqueProd.trans (genDihCongr eNeg.symm)⟩

theorem order54_c9c3_semidirect_cases (φ : order54_C2 →* MulAut order54_C9C3) :
    Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed0) ∨
      Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed1) ∨
      Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed2) ∨
      Nonempty (SemidirectProduct order54_C9C3 order54_C2 φ ≃* order54_Mixed3) := by
  set τ := φ (Multiplicative.ofAdd 1) with hτ
  have h2 : τ * τ = 1 := by
    rw [← sq, hτ, ← map_pow, show (Multiplicative.ofAdd (1 : ZMod 2)) ^ 2 = 1 from by decide,
      map_one]
  have hinv : ∀ x, τ (τ x) = x := fun x => by
    have hx := DFunLike.congr_fun h2 x
    rwa [MulAut.mul_apply, MulAut.one_apply] at hx
  have hexp : ∀ x : order54_C9C3, x ^ 9 = 1 := order54_c9c3_pow_nine
  have ht : 2 * 5 = 9 + 1 := by norm_num
  let eMain :
      SemidirectProduct order54_C9C3 order54_C2 φ ≃*
        fixSubgroup τ × SemidirectProduct (negSubgroup τ) order54_C2
          (invActionHom (negSubgroup τ)) :=
    elem_decomp_semidirect hinv hexp ht φ rfl
  let eSplit : order54_C9C3 ≃* fixSubgroup τ × negSubgroup τ := eigenEquiv hinv hexp ht
  have hsplit : Nat.card (fixSubgroup τ) * Nat.card (negSubgroup τ) = 27 := by
    rw [← Nat.card_prod, ← Nat.card_congr (eigenEquiv hinv hexp ht).toEquiv]
    exact card_order54_C9C3
  rcases order54_c9c3_neg_card_cases φ with hNeg1 | hNeg3 | hNeg9 | hNeg27
  · exact Or.inl ((order54_c9c3_endpoint_cases φ).1 hNeg1)
  · change Nat.card (negSubgroup τ) = 3 at hNeg3
    have hFix9 : Nat.card (fixSubgroup τ) = 9 := by
      have h := hsplit
      rw [hNeg3] at h
      have h' : Nat.card (fixSubgroup τ) * 3 = 9 * 3 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 3) h'
    obtain ⟨eNeg⟩ := prime_classification (by norm_num : Nat.Prime 3) hNeg3
    rcases prime_sq_classification (p := 3) hFix9 with hFixCyc | hFixElem
    · change Nonempty (fixSubgroup τ ≃* CyclicRep 9) at hFixCyc
      obtain ⟨eFix⟩ := hFixCyc
      exact Or.inr (Or.inl ⟨eMain.trans <|
        MulEquiv.prodCongr eFix ((genDihCongr eNeg).trans (genDihedralCyclicIso 3))⟩)
    · exfalso
      obtain ⟨eFix⟩ := hFixElem
      have hAexp : ∀ x : order54_C9C3, x ^ 3 = 1 := by
        intro x
        apply eSplit.injective
        rw [map_pow, map_one]
        apply Prod.ext
        · exact order54_pow_three_of_mulEquiv_elemAbelian3 eFix (eSplit x).1
        · exact order54_pow_three_of_mulEquiv_cyclic3 eNeg (eSplit x).2
      exact order54_c9c3_not_exp_three hAexp
  · change Nat.card (negSubgroup τ) = 9 at hNeg9
    have hFix3 : Nat.card (fixSubgroup τ) = 3 := by
      have h := hsplit
      rw [hNeg9] at h
      have h' : Nat.card (fixSubgroup τ) * 9 = 3 * 9 := by omega
      exact Nat.eq_of_mul_eq_mul_right (by norm_num : 0 < 9) h'
    obtain ⟨eFix⟩ := prime_classification (by norm_num : Nat.Prime 3) hFix3
    rcases prime_sq_classification (p := 3) hNeg9 with hNegCyc | hNegElem
    · change Nonempty (negSubgroup τ ≃* CyclicRep 9) at hNegCyc
      obtain ⟨eNeg⟩ := hNegCyc
      exact Or.inr (Or.inr (Or.inl ⟨eMain.trans <|
        MulEquiv.prodCongr eFix ((genDihCongr eNeg).trans (genDihedralCyclicIso 9))⟩))
    · exfalso
      obtain ⟨eNeg⟩ := hNegElem
      have hAexp : ∀ x : order54_C9C3, x ^ 3 = 1 := by
        intro x
        apply eSplit.injective
        rw [map_pow, map_one]
        apply Prod.ext
        · exact order54_pow_three_of_mulEquiv_cyclic3 eFix (eSplit x).1
        · exact order54_pow_three_of_mulEquiv_elemAbelian3 eNeg (eSplit x).2
      exact order54_c9c3_not_exp_three hAexp
  · exact Or.inr (Or.inr (Or.inr ((order54_c9c3_endpoint_cases φ).2 hNeg27)))

/-! ### Sylow-3 normality and semidirect-product reduction -/

/-- The Sylow `3`-subgroup is unique in a group of order `54`. -/
theorem card_sylow_3_eq_one_of_card_54 [Finite G] (hG : Nat.card G = 54) :
    Nat.card (Sylow 3 G) = 1 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 3 G))
  have hndvd_3 : ¬ 3 ∣ Nat.card (Sylow 3 G) := not_dvd_card_sylow 3 G
  have hdvd54 : Nat.card (Sylow 3 G) ∣ 54 := by
    rw [← hG]
    exact P0.card_dvd_index.trans (Subgroup.index_dvd_card _)
  have h54 : 54 = 2 * 3 ^ 3 := by norm_num
  have hdvd2_mul : Nat.card (Sylow 3 G) ∣ 2 * 3 ^ 3 := by
    simpa [h54] using hdvd54
  have hp3 : Nat.Prime 3 := by norm_num
  have hcop : Nat.Coprime (Nat.card (Sylow 3 G)) 3 :=
    (hp3.coprime_iff_not_dvd.mpr hndvd_3).symm
  have hcop_pow : Nat.Coprime (Nat.card (Sylow 3 G)) (3 ^ 3) :=
    hcop.pow_right 3
  have hdvd2 : Nat.card (Sylow 3 G) ∣ 2 := hcop_pow.dvd_of_dvd_mul_right hdvd2_mul
  have hmod := card_sylow_modEq_one 3 G
  have hle : Nat.card (Sylow 3 G) ≤ 2 := Nat.le_of_dvd (by norm_num) hdvd2
  have hpos : 0 < Nat.card (Sylow 3 G) := Nat.card_pos
  have hlt : Nat.card (Sylow 3 G) < 3 := by omega
  unfold Nat.ModEq at hmod
  rw [Nat.mod_eq_of_lt hlt, Nat.mod_eq_of_lt (by norm_num : 1 < 3)] at hmod
  exact hmod

/-- The Sylow `3`-subgroup of a group of order `54` is normal. -/
theorem sylow_3_normal_of_card_54 [Finite G] (hG : Nat.card G = 54) (P : Sylow 3 G) :
    (↑P : Subgroup G).Normal := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Subsingleton (Sylow 3 G) :=
    (Nat.card_eq_one_iff_unique.mp (card_sylow_3_eq_one_of_card_54 hG)).1
  exact normal_of_subsingleton P

/-- The Sylow `3`-subgroup of a group of order `54` has order `27`. -/
theorem card_sylow_3_subgroup_of_card_54 [Finite G] (hG : Nat.card G = 54)
    (P : Sylow 3 G) : Nat.card (↑P : Subgroup G) = 27 := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  have hfact : (54 : ℕ).factorization 3 = 3 := by
    rw [show (54 : ℕ) = 2 * 3 ^ 3 by norm_num,
      Nat.factorization_mul (by norm_num) (pow_ne_zero 3 (by norm_num : (3 : ℕ) ≠ 0)),
      Finsupp.add_apply, Nat.factorization_eq_zero_of_not_dvd (by norm_num : ¬ 3 ∣ 2),
      Nat.factorization_pow, Finsupp.smul_apply,
      Nat.Prime.factorization_self (by norm_num : Nat.Prime 3)]
    norm_num
  rw [Sylow.card_eq_multiplicity, hG]
  rw [hfact]
  norm_num

/-- **Schur-Zassenhaus reduction for order `54`.**
Every group of order `54` is a semidirect product `N ⋊[φ] H`, where
`N` has order `27` and `H` has order `2`. -/
theorem order54_semidirectProduct [Finite G] (hG : Nat.card G = 54) :
    ∃ (N H : Subgroup G) (φ : H →* MulAut N),
      N.Normal ∧ Nat.card N = 27 ∧ Nat.card H = 2 ∧
        Nonempty (G ≃* SemidirectProduct N H φ) := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  obtain ⟨P0⟩ := (Sylow.nonempty : Nonempty (Sylow 3 G))
  haveI hnorm : (↑P0 : Subgroup G).Normal := sylow_3_normal_of_card_54 hG P0
  have hcardN : Nat.card (↑P0 : Subgroup G) = 27 :=
    card_sylow_3_subgroup_of_card_54 hG P0
  haveI : (↑P0 : Subgroup G).FiniteIndex := ⟨Subgroup.index_ne_zero_of_finite⟩
  have hcop : Nat.Coprime (Nat.card (↑P0 : Subgroup G)) (↑P0 : Subgroup G).index := by
    rw [hcardN]
    have hnot : ¬ 3 ∣ (↑P0 : Subgroup G).index := P0.not_dvd_index
    have hcop3 : Nat.Coprime 3 (↑P0 : Subgroup G).index :=
      (show Nat.Prime 3 by norm_num).coprime_iff_not_dvd.mpr hnot
    simpa using hcop3.pow_left 3
  obtain ⟨H, φ, ⟨e⟩⟩ := schurZassenhaus_semidirectProduct (↑P0 : Subgroup G) hcop
  have hcardH : Nat.card H = 2 := by
    have h1 : Nat.card G = Nat.card (↑P0 : Subgroup G) * Nat.card H := by
      rw [Nat.card_congr e.toEquiv, Nat.card_congr SemidirectProduct.equivProd, Nat.card_prod]
    rw [hG, hcardN] at h1
    have h1' : 27 * Nat.card H = 27 * 2 := by omega
    exact Nat.eq_of_mul_eq_mul_left (by norm_num : 0 < 27) h1'
  exact ⟨↑P0, H, φ, hnorm, hcardN, hcardH, ⟨e⟩⟩

/-! ### Standard order-27 kernel cases -/

/-- The normal subgroup in an order-`54` semidirect product is one of the five groups of
order `27`. -/
theorem order54_kernel_cases {N : Type*} [Group N] [Fintype N] (hN : Nat.card N = 27) :
    P3Group.IsP3Group 3 N := by
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  exact P3Group.classification 3 N (hN.trans (by norm_num))

/-- Combined standard-case reduction: the normal subgroup in the Schur--Zassenhaus
decomposition is one of the five standard groups of order `27`. -/
theorem order54_semidirectProduct_kernel_cases [Finite G] (hG : Nat.card G = 54) :
    ∃ (N H : Subgroup G) (φ : H →* MulAut N),
      ∃ (_ : Fintype N),
      N.Normal ∧ Nat.card N = 27 ∧ Nat.card H = 2 ∧
        P3Group.IsP3Group 3 N ∧ Nonempty (G ≃* SemidirectProduct N H φ) := by
  rcases order54_semidirectProduct (G := G) hG with
    ⟨N, H, φ, hnorm, hcardN, hcardH, hiso⟩
  haveI : Fintype N := Fintype.ofFinite N
  exact ⟨N, H, φ, inferInstance, hnorm, hcardN, hcardH, order54_kernel_cases hcardN, hiso⟩

/-- Every group of order `54` is a semidirect product of `C₂` acting on one of the five
standard groups of order `27`.  The remaining work is to classify the possible actions in
each branch. -/
theorem order54_semidirectProduct_standard_cases [Finite G] (hG : Nat.card G = 54) :
    (∃ φ : order54_C2 →* MulAut order54_C27,
      Nonempty (G ≃* SemidirectProduct order54_C27 order54_C2 φ)) ∨
    (∃ φ : order54_C2 →* MulAut order54_C9C3,
      Nonempty (G ≃* SemidirectProduct order54_C9C3 order54_C2 φ)) ∨
    (∃ φ : order54_C2 →* MulAut order54_C3C3C3,
      Nonempty (G ≃* SemidirectProduct order54_C3C3C3 order54_C2 φ)) ∨
    (∃ φ : order54_C2 →* MulAut order54_Heisenberg,
      Nonempty (G ≃* SemidirectProduct order54_Heisenberg order54_C2 φ)) ∨
    (∃ φ : order54_C2 →* MulAut order54_SemidirectP2P,
      Nonempty (G ≃* SemidirectProduct order54_SemidirectP2P order54_C2 φ)) := by
  rcases order54_semidirectProduct (G := G) hG with
    ⟨N, H, φ, _, hcardN, hcardH, ⟨e⟩⟩
  haveI : Fact (Nat.Prime 3) := ⟨by norm_num⟩
  haveI : Fintype N := Fintype.ofFinite N
  obtain ⟨eH⟩ := prime_classification (by norm_num : Nat.Prime 2) hcardH
  rcases P3Group.classification 3 N (hcardN.trans (by norm_num)) with
    hN | hN | hN | hN | hN | hN | hN
  · change Nonempty (N ≃* order54_C27) at hN
    obtain ⟨eN⟩ := hN
    exact Or.inl ⟨_, ⟨e.trans (SemidirectProduct.congr' eN eH)⟩⟩
  · change Nonempty (N ≃* order54_C9C3) at hN
    obtain ⟨eN⟩ := hN
    exact Or.inr (Or.inl ⟨_, ⟨e.trans (SemidirectProduct.congr' eN eH)⟩⟩)
  · change Nonempty (N ≃* order54_C3C3C3) at hN
    obtain ⟨eN⟩ := hN
    exact Or.inr (Or.inr (Or.inl ⟨_, ⟨e.trans (SemidirectProduct.congr' eN eH)⟩⟩))
  · change 3 ≠ 2 ∧ Nonempty (N ≃* order54_Heisenberg) at hN
    obtain ⟨eN⟩ := hN.2
    exact Or.inr (Or.inr (Or.inr (Or.inl
      ⟨_, ⟨e.trans (SemidirectProduct.congr' eN eH)⟩⟩)))
  · change 3 ≠ 2 ∧ Nonempty (N ≃* order54_SemidirectP2P) at hN
    obtain ⟨eN⟩ := hN.2
    exact Or.inr (Or.inr (Or.inr (Or.inr
      ⟨_, ⟨e.trans (SemidirectProduct.congr' eN eH)⟩⟩)))
  · exfalso
    exact (by norm_num : ¬ (3 : ℕ) = 2) hN.1
  · exfalso
    exact (by norm_num : ¬ (3 : ℕ) = 2) hN.1

/-! ### Assembled abelian-kernel cases -/

/-- Once the Schur--Zassenhaus kernel is abelian, the order-`54` group is one of the
ten explicit representatives coming from the `C₂₇`, `C₉ × C₃`, and `C₃³` kernel
branches. -/
theorem order54_abelian_kernel_cases
    (h :
      (∃ φ : order54_C2 →* MulAut order54_C27,
        Nonempty (G ≃* SemidirectProduct order54_C27 order54_C2 φ)) ∨
      (∃ φ : order54_C2 →* MulAut order54_C9C3,
        Nonempty (G ≃* SemidirectProduct order54_C9C3 order54_C2 φ)) ∨
      (∃ φ : order54_C2 →* MulAut order54_C3C3C3,
        Nonempty (G ≃* SemidirectProduct order54_C3C3C3 order54_C2 φ))) :
    Nonempty (G ≃* order54_C54) ∨
      Nonempty (G ≃* order54_D27) ∨
      Nonempty (G ≃* order54_Mixed0) ∨
      Nonempty (G ≃* order54_Mixed1) ∨
      Nonempty (G ≃* order54_Mixed2) ∨
      Nonempty (G ≃* order54_Mixed3) ∨
      Nonempty (G ≃* order54_Elem0) ∨
      Nonempty (G ≃* order54_Elem1) ∨
      Nonempty (G ≃* order54_Elem2) ∨
      Nonempty (G ≃* order54_Elem3) := by
  rcases h with hC27 | h
  · rcases hC27 with ⟨φ, ⟨eG⟩⟩
    rcases order54_c27_semidirect_cases φ with hC54 | hD27
    · rcases hC54 with ⟨eC54⟩
      exact Or.inl ⟨eG.trans eC54⟩
    · rcases hD27 with ⟨eD27⟩
      exact Or.inr (Or.inl ⟨eG.trans eD27⟩)
  rcases h with hMixed | hElem
  · rcases hMixed with ⟨φ, ⟨eG⟩⟩
    rcases order54_c9c3_semidirect_cases φ with hMixed0 | hMixed1 | hMixed2 | hMixed3
    · rcases hMixed0 with ⟨eMixed0⟩
      exact Or.inr (Or.inr (Or.inl ⟨eG.trans eMixed0⟩))
    · rcases hMixed1 with ⟨eMixed1⟩
      exact Or.inr (Or.inr (Or.inr (Or.inl ⟨eG.trans eMixed1⟩)))
    · rcases hMixed2 with ⟨eMixed2⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl ⟨eG.trans eMixed2⟩))))
    · rcases hMixed3 with ⟨eMixed3⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl ⟨eG.trans eMixed3⟩)))))
  · rcases hElem with ⟨φ, ⟨eG⟩⟩
    rcases order54_c3c3c3_semidirect_cases φ with hElem0 | hElem1 | hElem2 | hElem3
    · rcases hElem0 with ⟨eElem0⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl ⟨eG.trans eElem0⟩))))))
    · rcases hElem1 with ⟨eElem1⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr
        (Or.inl ⟨eG.trans eElem1⟩)))))))
    · rcases hElem2 with ⟨eElem2⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr
        (Or.inl ⟨eG.trans eElem2⟩))))))))
    · rcases hElem3 with ⟨eElem3⟩
      exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr
        (Or.inr ⟨eG.trans eElem3⟩))))))))

/-- Current assembled reduction for order `54`: after the abelian-kernel work, an arbitrary
group of order `54` is either one of the ten abelian-kernel representatives, or it comes from
one of the two non-abelian order-`27` kernels. -/
theorem order54_cases_after_abelian_kernels [Finite G] (hG : Nat.card G = 54) :
    (Nonempty (G ≃* order54_C54) ∨
      Nonempty (G ≃* order54_D27) ∨
      Nonempty (G ≃* order54_Mixed0) ∨
      Nonempty (G ≃* order54_Mixed1) ∨
      Nonempty (G ≃* order54_Mixed2) ∨
      Nonempty (G ≃* order54_Mixed3) ∨
      Nonempty (G ≃* order54_Elem0) ∨
      Nonempty (G ≃* order54_Elem1) ∨
      Nonempty (G ≃* order54_Elem2) ∨
      Nonempty (G ≃* order54_Elem3)) ∨
    (∃ φ : order54_C2 →* MulAut order54_Heisenberg,
      Nonempty (G ≃* SemidirectProduct order54_Heisenberg order54_C2 φ)) ∨
    (∃ φ : order54_C2 →* MulAut order54_SemidirectP2P,
      Nonempty (G ≃* SemidirectProduct order54_SemidirectP2P order54_C2 φ)) := by
  rcases order54_semidirectProduct_standard_cases (G := G) hG with hC27 | h
  · exact Or.inl (order54_abelian_kernel_cases (Or.inl hC27))
  rcases h with hMixed | h
  · exact Or.inl (order54_abelian_kernel_cases (Or.inr (Or.inl hMixed)))
  rcases h with hElem | h
  · exact Or.inl (order54_abelian_kernel_cases (Or.inr (Or.inr hElem)))
  rcases h with hHeisenberg | hSemidirectP2P
  · exact Or.inr (Or.inl hHeisenberg)
  · exact Or.inr (Or.inr hSemidirectP2P)

end Smallgroups.UsefulTheorems
