/-
Copyright (c) 2026 Smallgroups contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Smallgroups contributors
-/
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import Mathlib.GroupTheory.OrderOfElement

/-!
# Groups of prime order are cyclic

This file proves the basic structural fact underpinning the classification of groups
of prime order: **a finite group whose order is a prime number is cyclic**.

Although Mathlib already provides `isCyclic_of_prime_card`, we give a short
self-contained proof here (via Lagrange's theorem on the order of an element) so that the
`Classifications` files can be built on a single, named entry point inside this project.

## Main results

* `Smallgroups.isCyclic_of_card_eq_prime` :
  if `Nat.card G = p` with `p` prime, then `G` is cyclic.
* `Smallgroups.orderOf_eq_card_of_card_eq_prime` :
  in such a group every non-identity element has order equal to the whole group.
-/

namespace Smallgroups

variable {G : Type*} [Group G]

/-- In a group of prime order `p`, any non-identity element has order exactly `p`.

This is the heart of the argument: by Lagrange's theorem the order of an element divides
`p`, and being prime it is either `1` or `p`; only the identity has order `1`. -/
theorem orderOf_eq_card_of_card_eq_prime {p : ℕ} (hp : p.Prime) (hcard : Nat.card G = p)
    {g : G} (hg : g ≠ 1) : orderOf g = p := by
  have hdvd : orderOf g ∣ p := hcard ▸ orderOf_dvd_natCard g
  rcases (Nat.dvd_prime hp).mp hdvd with h1 | hp'
  · exact absurd (orderOf_eq_one_iff.mp h1) hg
  · exact hp'

/-- **A finite group of prime order is cyclic.**

If `Nat.card G = p` for a prime `p`, then `G` is cyclic, generated by any of its
non-identity elements. -/
theorem isCyclic_of_card_eq_prime {p : ℕ} (hp : p.Prime) (hcard : Nat.card G = p) :
    IsCyclic G := by
  have : Finite G := Nat.finite_of_card_ne_zero (by rw [hcard]; exact hp.ne_zero)
  have : Nontrivial G :=
    Finite.one_lt_card_iff_nontrivial.mp (by rw [hcard]; exact hp.one_lt)
  obtain ⟨g, hg⟩ := exists_ne (1 : G)
  refine isCyclic_of_orderOf_eq_card g ?_
  rw [orderOf_eq_card_of_card_eq_prime hp hcard hg, hcard]

end Smallgroups
